ets-berkeley-edu/boac

- boac/models/manually_added_advisee.py
- scripts/db/drop_schema.sql
- scripts/db/migrate/20190829-BOAC-2589/pre_deploy_01_create_manually_added_advisees_table.sql
- scripts/db/schema.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2589
> BOAC-2589: Adds pending_advisees table

- src/components/note/NewNoteModal.vue
- src/components/note/NewNoteModalButtons.vue
- src/components/note/NewNotePageHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2658
> BOAC-2658, UX/accessibility tweaks in note/template modal

- boac/models/note_template.py
- scripts/db/migrate/20190830-BOAC-2662/pre_deploy_01_drop_and_recreate_note_templates_constraint.sql
- scripts/db/schema.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2662
> BOAC-2662, note_templates 'unique' constraint now includes deleted_at

- boac/api/admin_controller.py
- boac/models/manually_added_advisee.py
- tests/test_api/test_admin_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2589
> BOAC-2589: Adds API endpoint for getting manually added advisees

- boac/merged/student.py
- tests/test_api/test_curated_group_controller.py
- tests/test_api/test_search_controller.py
- tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2441
> BOAC-2441 Team memberships for all

- src/components/course/CourseStudents.vue
- src/components/search/SortableStudents.vue
- src/components/student/StudentRow.vue
- src/components/student/profile/StudentProfileHeader.vue
- src/mixins/StudentMetadata.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2597
> BOAC-2597 Distinguish ASC, CoE inactivity

- scripts/db/schema.sql
- src/components/note/NewNotePageHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2670
> BOAC-2670, title attribute for template options

- src/components/course/CourseStudents.vue
- src/components/student/StudentRow.vue
- src/components/student/profile/StudentProfileHeader.vue
- src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2441
> BOAC-2441 Unbold the teams

- boac/lib/berkeley.py
- fixtures/loch.sql
- tests/test_api/test_cache_utils.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2665
> BOAC-2665: Adds L&S minor advisors to the major advising pool

- boac/lib/berkeley.py
- src/components/note/CreateTemplateModal.vue
- src/components/note/NewNoteModal.vue
- src/components/note/NewNoteModalButtons.vue
- src/components/note/NewNotePageHeader.vue
- src/store/modules/note-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-2666
https://jira.ets.berkeley.edu/jira/browse/BOAC-2681
> BOAC-2666, better path to create template; well-behaved modal

- scripts/db/tools/add_admin_user.sql
- scripts/db/tools/add_advisor_per_dept.sql
- scripts/db/tools/delete_authorized_user.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2680
What have you done for DevOps today?
> BOAC-2680, our SQL scripts (devops!) maintain proper 'deleted_at' status

- boac/api/note_templates_controller.py
- boac/models/note_template.py
- tests/test_api/test_note_templates_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2651
> BOAC-2651, API to rename note template

- boac/merged/student.py
- fixtures/loch_student_profile_11667051.json
- fixtures/loch_student_profile_2345678901.json
- fixtures/loch_student_profile_3456789012.json
- fixtures/loch_student_profile_5678901234.json
- fixtures/loch_student_profile_7890123456.json
- fixtures/loch_student_profile_8901234567.json
- fixtures/loch_student_profile_890127492.json
- fixtures/loch_student_profile_9000000000.json
- fixtures/loch_student_profile_9100000000.json
- src/components/student/profile/StudentProfileHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2654
> BOAC-2654 Better display for inactive student plans

- src/components/curated/CuratedGroupBulkAdd.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2677
> BOAC-2677 Bulk SID input: allow any combination of commas, whitespace, newlines

- boac/api/note_templates_controller.py
- src/api/note-templates.ts
- src/components/note/create/BatchNoteAddCohort.vue
- src/components/note/create/BatchNoteAddStudent.vue
- src/components/note/create/BatchNoteFeatures.vue
- src/components/note/create/CreateNoteFooter.vue
- src/components/note/create/CreateNoteHeader.vue
- src/components/note/create/CreateNoteMinimized.vue
- src/components/note/create/CreateNoteModal.vue
- src/components/note/create/CreateTemplateModal.vue
- src/components/note/create/RenameTemplateModal.vue
- src/components/sidebar/Sidebar.vue
- src/components/student/profile/AcademicTimeline.vue
- src/mixins/NoteEditSession.vue
- src/store/modules/note-edit-session.ts
- tests/test_api/test_note_templates_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2651
And, moved rename/delete methods to Header component to reduce `props` complexity.
> BOAC-2651, front-end for rename template; moved create-note components to 'note/create' dir

- src/components/note/AdvisingNote.vue
- src/components/note/create/CreateNoteFooter.vue
- src/components/note/create/CreateNoteHeader.vue
- src/components/note/create/CreateTemplateModal.vue
- src/components/note/create/RenameTemplateModal.vue
- src/mixins/Validator.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2673
https://jira.ets.berkeley.edu/jira/browse/BOAC-2681
> BOAC-2673, improved markup in note templates feature

- src/components/cohort/FilterRow.vue
- src/components/curated/CuratedGroupSelector.vue
- src/components/student/profile/StudentGroupSelector.vue
For accessibility bug https://jira.ets.berkeley.edu/jira/browse/BOAC-2675.
> BOAC-2675 Use low-tech dropdown separators that don't render as fake list items

- src/components/note/create/CreateNoteModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2683
https://jira.ets.berkeley.edu/jira/browse/BOAC-2688
Hidden but not forgotten.
> BOAC-2683, in edit-template mode, use v-show (not v-if) on add-student/cohort section

- src/components/note/create/CreateNoteHeader.vue
- src/components/note/create/CreateNoteModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2685
> BOAC-2685, update template and properly list its attachments

- src/components/note/EditAdvisingNote.vue
- src/components/note/create/CreateNoteModal.vue
- src/components/student/profile/AcademicTimeline.vue
- src/components/student/profile/TimelineDate.vue
- src/mixins/NoteEditSession.vue
- src/store/modules/note-edit-session.ts
- src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2668
While note is being created, user sees small spinner + note subject + today's date at top of academic timeline. One fix required: the _Promise_ returned by `createAdvisingNote()` in vuex store needed to come from the `action`.
> BOAC-2668, progress on create-note is shown (spinner) at top of student timeline

- package-lock.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/BOAC-2663
> BOAC-2663, fix 'link' in rich-text editor (note body) by reverting to previous ckeditor

- src/components/course/CourseStudents.vue
- src/components/search/AdvisingNoteSnippet.vue
- src/components/search/SortableStudents.vue
- src/components/student/StudentRow.vue
- src/components/student/profile/StudentProfileHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2684
> BOAC-2684, UI deals with encoded apostrophe in student names

- boac/merged/student.py
- src/components/course/CourseStudents.vue
- src/components/search/SortableStudents.vue
- src/components/student/StudentRow.vue
- src/components/student/profile/StudentProfileHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2646
> BOAC-2646 Display modifications for inactive and completed academic careers

- .eslintrc.js
- src/components/note/AdvisingNote.vue
- src/components/note/AdvisingNoteAttachments.vue
- src/components/student/profile/AcademicTimeline.vue
- src/views/Course.vue
> NOJIRA, eslint rule enforces 'eqeqeq'

- src/components/student/profile/AcademicTimeline.vue
- src/mixins/Util.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2684
Follows PR #1874
> BOAC-2684, decode encoded entities in page title

- boac/api/curated_group_controller.py
- boac/api/search_controller.py
- boac/api/student_controller.py
- boac/externals/data_loch.py
- boac/merged/student.py
- boac/models/curated_group.py
- fixtures/loch.sql
- src/components/search/SortableStudents.vue
- src/components/student/profile/StudentProfileHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2647
Let the bugs begin. I apologize for tossing this much new and rearranged code into the works without corresponding test coverage; given our timeline, it seemed important to get this into shared code as soon as possible to avoid merge conflicts. I'll plan to follow up with some fleshed-out fixtures and new tests.
> BOAC-2647 Access to inactive students via SID search and curated groups

- boac/merged/student.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2692
> BOAC-2692: Adds SIDs to manually_added_advisees when searched or curated

- boac/models/curated_group.py
- fixtures/loch.sql
- fixtures/loch_student_enrollment_term_completed_2718281828_2058.json
- fixtures/loch_student_enrollment_term_completed_2718281828_2102.json
- fixtures/loch_student_enrollment_term_inactive_3141592653_2052.json
- fixtures/loch_student_profile_completed_2718281828.json
- fixtures/loch_student_profile_inactive_3141592653.json
- tests/test_api/test_curated_group_controller.py
- tests/test_api/test_search_controller.py
- tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2647
> BOAC-2647 Fixtures/tests for non-current students

- src/components/note/create/CreateNoteHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2693
> BOAC-2693, font-weight-normal on template dropdown items

- boac/merged/student.py
- src/components/student/profile/StudentClasses.vue
- src/views/Student.vue
- tests/test_api/test_curated_group_controller.py
- tests/test_api/test_search_controller.py
- tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2695
> BOAC-2695 Don't expand or link courses when full profile is pending

- src/components/student/profile/StudentClasses.vue
- src/components/student/profile/StudentWithdrawalCancel.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2696
> BOAC-2693, StudentWithdrawalCancel has optional prop: termId

- boac/externals/data_loch.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2746
QA version of #1890.
> [QA] BOAC-2746 Remove active-student restriction on note attachment download

- boac/externals/data_loch.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2746
> BOAC-2746 Remove active-student restriction on note attachment download

- boac/api/cache_utils.py
- boac/models/development_db.py
- boac/models/university_dept.py
- scripts/db/migrate/20190916-BOAC-2715/post_deploy_01_remove_per_dept_automated_memberships.sql
- scripts/db/schema.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2715
> BOAC-2715 Remove per-department automation flag

- src/components/curated/CuratedGroupBulkAdd.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2745
> [QA] BOAC-2745, bulk SIDs error msg: 'SIDs must be separated by...'

- src/components/curated/CuratedGroupBulkAdd.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2745
qa PR is #1895
> BOAC-2745, bulk SIDs error msg: 'SIDs must be separated by...'

- src/components/note/AdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2613
> BOAC-2613, link to directory if and only if note.author.uid

- scripts/db/tools/add_admin_user.sql
- scripts/db/tools/add_advisor_per_dept.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2616
> BOAC-2616 Manually added users get default Canvas data privileges and persist through nightly refresh

- requirements.txt
https://jira.ets.berkeley.edu/jira/browse/BOAC-2738
> BOAC-2738, upgrade to Flask 1.1

- scripts/db/tools/add_admin_user.sql
- scripts/db/tools/add_advisor_per_dept.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2616
QA version of #1900.
> [QA] BOAC-2616 Manually added users get default Canvas data privileges and persist through nightly refresh

- scripts/db/migrate/20190917-BOAC-2748/pre_deploy_01_alter_tool_settings_value_column.sql
- scripts/db/schema.sql
- tests/test_api/test_config_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2748
We are not Twitter. Verbosity is a choice.
> BOAC-2748, db column tool_settings::value type is now 'text'

- boac/api/cache_utils.py
- boac/api/user_controller.py
- boac/models/db_relationships.py
- boac/models/development_db.py
- boac/models/university_dept_member.py
- tests/test_api/test_cache_utils.py
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2709
> BOAC-2709: Adds API for add/delete dept memberships

- boac/api/curated_group_controller.py
- boac/models/curated_group.py
- src/api/curated.ts
- src/components/curated/CuratedGroupHeader.vue
- src/components/sidebar/Sidebar.vue
- src/components/student/StudentRow.vue
- src/router.ts
- src/views/AllGroups.vue
- src/views/CuratedGroup.vue
- tests/test_api/test_curated_group_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2650
Like it says on the tin. Note that the curated group view is modified to accommodate the previously impossible state of viewing a curated group you don't own, with editing functions disabled.
> BOAC-2650 Everyone's groups

- boac/api/user_controller.py
- boac/models/university_dept_member.py
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2709
> BOAC-2709: Adds API for update dept memberships

- fixtures/loch_student_profile_11667051.json
- src/components/student/StudentRow.vue
- src/components/student/profile/StudentClasses.vue
- tests/test_merged/test_student.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2753
https://jira-secure.berkeley.edu/browse/SISRP-48560
master PR is #1906
> [QA] BOAC-2753, suppress the unitsMin and unitsMax messaging in BOA

- boac/merged/student.py
QA-first PR for https://jira.ets.berkeley.edu/jira/browse/BOAC-2758.
BOA code runs this check in a couple of other places, but our code just has so many fun ways to retrieve a set of students.
> [QA] BOAC-2758 Plug one more leak of duplicate students from multiple tables

- boac/merged/student.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2758
Master-branch version of #1908.
> BOAC-2758 Plug one more leak of duplicate students from multiple tables

- src/api/curated.ts
- src/components/curated/CuratedGroupHeader.vue
- src/components/curated/CuratedGroupSelector.vue
- src/components/student/StudentRow.vue
- src/components/student/profile/StudentGroupSelector.vue
- src/mixins/CuratedEditSession.vue
- src/store/index.ts
- src/store/modules/curated-edit-session.ts
- src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2750
Follows the `edit-session` pattern we use for cohorts and advising notes. The page components are no longer responsible for keeping store in sync and maintaining a copy of the model object.
> BOAC-2750, curated group uses vuex store in a more reliable way

- src/components/curated/CuratedGroupHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2750
Follows #1911
> BOAC-2750, remove extraneous param from rename curated group call

- boac/api/cache_utils.py
- boac/models/authorized_user.py
- boac/models/development_db.py
- scripts/db/migrate/20190919-BOAC-2710/pre_deploy_01_add_column_authorized_users_created_by.sql
- scripts/db/schema.sql
- tests/test_api/test_cache_utils.py
- tests/test_models/test_authorized_user.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2710
> BOAC-2710: Adds created_by to authorized_users

- boac/api/cache_utils.py
- boac/models/db_relationships.py
- boac/models/development_db.py
- tests/test_api/test_cache_utils.py
QA-first PR for https://jira.ets.berkeley.edu/jira/browse/BOAC-2764.
> [QA] BOAC-2764 Resolve conflicts between non-automated and automated users

- boac/api/cache_utils.py
- boac/api/user_controller.py
- boac/models/development_db.py
- boac/models/university_dept_member.py
- tests/test_api/test_cache_utils.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2764
Master-branch version of #1913 (not just a cherry-pick since underlying code has changed in the meantime).
> BOAC-2764 Resolve conflicts between non-automated and automated users

- src/components/student/StudentGpaChart.vue
- src/components/student/StudentUnitsChart.vue
- src/components/student/profile/StudentProfileGPA.vue
- src/components/student/profile/StudentProfileUnits.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2698
> BOAC-2698 Reduce size of GPA/units on student page

- src/components/student/StudentRow.vue
- src/mixins/Berkeley.vue
- src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2766
> BOAC-2766 On summary pages, (W) is for waitlisted

- boac/api/cohort_controller.py
- boac/api/curated_group_controller.py
- tests/test_api/test_cohort_controller.py
- tests/test_api/test_curated_group_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2755
https://jira.ets.berkeley.edu/jira/browse/BOAC-2757
> BOAC-2755 BOAC-2757 Respect privacy of users without dept affiliations

- src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2619
> BOAC-2619 Note search: clear author filter on 'Posted by' toggle

- scripts/db/tools/add_admin_user.sql
- scripts/db/tools/add_advisor_per_dept.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2775
> BOAC-2775, add_user scripts need created_by value

- scripts/db/migrate/20190926-BOAC-2741/pre_deploy_01_add_topics.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2741
> BOAC-2741 Additional topics for new advising notes

- boac/models/curated_group.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2777
> BOAC-2777 Include zero-member curated groups in bulk query

- boac/api/cache_utils.py
- boac/models/authorized_user.py
- scripts/db/migrate/20190925-BOAC-2711/pre_deploy_01_add_column_authorized_users_is_blocked.sql
- scripts/db/schema.sql
- tests/test_api/test_cache_utils.py
- tests/test_models/test_authorized_user.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2711
> BOAC-2711: Allows user to be blocked from nightly refresh

- scripts/db/migrate/20190924-BOAC-2620/post_deploy_01_gpa_json_in_cohort_filter.sh
https://jira.ets.berkeley.edu/jira/browse/BOAC-2620
Follows #1924
> BOAC-2620, scripts/db/migrate: shell script pointed at wrong py

- boac/merged/cohort_filter_options.py
- src/components/cohort/FilterRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2779
> BOAC-2779, disable 'Update' in cohort-filter row if validation error

- src/components/cohort/FilterRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2780
> BOAC-2780, GPA Filter - 0.X vs .X

- src/components/cohort/FilterRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2629
> BOAC-2629, Teena friendly ids and class-names in FilterRow template

- src/components/cohort/FilterRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2784
> BOAC-2784, /cohort front-end: value=true when add boolean filter

- src/components/cohort/FilterRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2785
Tricky logic. Readable code, I hope. QA PR will follow.
> BOAC-2785, /cohort page: mo' better validation for add/update range filter

- src/components/cohort/FilterRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2785
The master PR is #1931
> [QA] BOAC-2785, /cohort page: mo' better validation for add/update range filter

- boac/externals/data_loch.py
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2788
See Jira desc. Master PR will follow.
> [QA] BOAC-2788, last_name_ranges SQL requires AND (...OR...)

- src/components/student/profile/StudentClasses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2786
A very quick and satisfying fix.
> BOAC-2786, margin and font weight/color fix on student profile

- boac/externals/data_loch.py
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2788
QA PR is #1933
> BOAC-2788, last_name_ranges SQL requires AND (...OR...)

- boac/lib/berkeley.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2800
> BOAC-2800 Guest is not Other, Other is not Guest

- boac/lib/berkeley.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2800
QA version of #1936.
> [QA] BOAC-2800 Guest is not Other, Other is not Guest

- src/components/cohort/FilterRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2802
> BOAC-2802, do not treat lastName as GPA when filter update

- src/components/cohort/FilterRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2802
master PR is #1938
> [QA] BOAC-2802, do not treat lastName as GPA when filter update

- src/components/cohort/FilterRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2798
> BOAC-2798, do not parseFloat(undefined) in GPA check

- src/components/cohort/FilterRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2798
master PR is #1940
> [QA] BOAC-2798, do not parseFloat(undefined) in GPA check

- .ebextensions/01_create_apache_conf.config
https://jira.ets.berkeley.edu/jira/browse/BOAC-2790
> BOAC-2790 Update BOA SSL certificate

- boac/externals/data_loch.py
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2797
QA version of #1943.
> [QA] BOAC-2797 Use correct column names when building intersections between schemas

- boac/externals/data_loch.py
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2797
> BOAC-2797 Use correct column names when building intersections between schemas

- src/components/admin/Users.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2714
> BOAC-2714: Displays user's dept membership data on admin page

- boac/externals/data_loch.py
- fixtures/loch.sql
- fixtures/loch_student_profile_11667051.json
- fixtures/loch_student_profile_2345678901.json
- fixtures/loch_student_profile_3456789012.json
- fixtures/loch_student_profile_5678901234.json
- fixtures/loch_student_profile_7890123456.json
- fixtures/loch_student_profile_8901234567.json
- fixtures/loch_student_profile_890127492.json
- fixtures/loch_student_profile_9000000000.json
- fixtures/loch_student_profile_9100000000.json
- src/components/sidebar/SearchForm.vue
- tests/test_api/test_cohort_controller.py
- tests/test_api/test_curated_group_controller.py
- tests/test_api/test_search_controller.py
- tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2467
> BOAC-2467 Student search by email address

- boac/models/development_db.py
- tests/test_api/test_cache_utils.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2855
> BOAC-2855 Fix discrepancies in authorized user test data

- boac/api/cohort_controller.py
- boac/api/curated_group_controller.py
- boac/api/note_templates_controller.py
- boac/api/notes_controller.py
- boac/api/util.py
- boac/lib/berkeley.py
- boac/merged/student.py
- boac/merged/user_session.py
- scripts/db/migrate/20191007-BOAC-2805/pre_deploy_01_add_column_is_scheduler.sql
- src/components/admin/Users.vue
- src/components/student/SortBy.vue
- src/mixins/UserMetadata.vue
- src/router.ts
- src/store/modules/context.ts
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2805
> BOAC-2805, correctly identify advisors and schedulers for proper routing

- src/components/admin/Users.vue
- src/store/modules/user.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-2718
> BOAC-2718: Adds user attribute filtering to admin page

- boac/externals/data_loch.py
- boac/merged/cohort_filter_options.py
- boac/merged/student.py
- boac/models/cohort_filter.py
- fixtures/loch.sql
- fixtures/loch_student_profile_11667051.json
- fixtures/loch_student_profile_3456789012.json
- fixtures/loch_student_profile_8901234567.json
- src/components/student/SortBy.vue
- src/components/student/StudentRow.vue
- src/components/student/profile/StudentProfileHeader.vue
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2744
https://jira.ets.berkeley.edu/jira/browse/BOAC-2765
> BOAC-2744 BOAC-2765 Cohort filter and sort on entering term aka matriculation

- boac/api/auth_controller.py
- package-lock.json
- package.json
- src/components/HeaderMenu.vue
- src/components/admin/Users.vue
- src/layouts/DropInDesk.vue
- src/layouts/StandardLayout.vue
- src/layouts/shared/ServiceAnnouncement.vue
- src/layouts/shared/StandardHeaderLayout.vue
- src/router.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-2849
Includes `vue-router` version bump: 3.0.7 -> 3.1.3
> BOAC-2849, '/appt/desk' view gets service alerts and other shared components

- boac/api/user_controller.py
- src/api/user.ts
- src/components/admin/Users.vue
- src/mixins/Util.vue
- src/store/modules/user.ts
- src/views/Admin.vue
- tests/test_api/test_user_controller.py
By extracting the departments from the users list, we prune the departments drop-down of irrelevant entries and avoid having to make a separate call to the server.
https://jira.ets.berkeley.edu/jira/browse/BOAC-2718
> BOAC-2718: Limits departments to those with members

- boac/api/appointments_controller.py
- boac/api/notes_controller.py
- boac/api/util.py
- boac/routes.py
- src/api/appointments.ts
- src/store/modules/user.ts
- tests/test_api/test_appointments_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2832
A little prep before real work begins.
> BOAC-2832, stub 'appointment' API endpoints as prep for /student profile page

- src/components/matrix/Matrix.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2372
> BOAC-2372, matrix view > consistent decimal precision for GPA

- boac/api/notes_controller.py
- boac/models/appointment_topic.py
- boac/models/development_db.py
- boac/models/topic.py
- scripts/db/drop_schema.sql
- scripts/db/migrate/20191009-BOAC-2810/pre_deploy_01_add_columns_to_topics.sql
- scripts/db/migrate/20191009-BOAC-2810/pre_deploy_02_create_appointment_topics_table.sql
- scripts/db/schema.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2810
> BOAC-2810: Adds support for appointment topics

- boac/externals/data_loch.py
- fixtures/loch.sql
- fixtures/loch_student_enrollment_term_5678901234_2178.json
- src/components/student/SortBy.vue
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2743
> BOAC-2743 Cohort/group sort on current-term enrolled units

- scripts/db/migrate/20191009-BOAC-2810/pre_deploy_01_add_columns_to_topics.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2810
> BOAC-2810: Switches existing topic 'Other' from insert to update

- src/components/HeaderMenu.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2862
> BOAC-2862, In header, if not user.firstName then UID:${user.uid}

- boac/merged/cohort_filter_options.py
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2747
Removing the tiniest bit of complexity.
> BOAC-2747 Everyone sees the same dept-specific inactive labels

- boac/api/appointments_controller.py
- src/api/appointments.ts
- src/api/notes.ts
- src/components/appointment/AdvisingAppointment.vue
- src/components/appointment/AppointmentCheckIn.vue
- src/components/student/profile/AcademicTimeline.vue
- src/mixins/UserMetadata.vue
- tests/test_api/test_appointments_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2832
> BOAC-2832, AdvisingAppointment component covers basics of display and mark-as-read

- src/components/matrix/Matrix.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2369
This looks like a lot of lines, but all we're doing is moving the matrix dots to render after the labels.
> BOAC-2369 Reorder matrix popups to display over surrounding elements

- src/components/search/SortableStudents.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2865
> BOAC-2685 Case-insensitive sort for student search results

- src/components/search/SortableStudents.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2865
> BOAC-2865 Fix sort normalizing

- boac/api/appointments_controller.py
- boac/api/util.py
- src/api/appointments.ts
- src/components/appointment/AdvisingAppointment.vue
- src/components/appointment/AppointmentDetailsModal.vue
- src/components/cohort/FilterRow.vue
- src/components/note/EditAdvisingNote.vue
- src/components/note/create/CreateNoteModal.vue
- src/components/student/profile/AcademicTimeline.vue
- src/views/CreateCuratedGroup.vue
- src/views/CuratedGroup.vue
- src/views/DropInWaitlist.vue
- tests/test_api/test_appointments_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2836
Also, both `isScheduler` and `isDropInAdvisor` can access the Intake Desk view.
> BOAC-2836, only user.isDropInAdvisor can check-in/cancel appointments on student profile page

- src/App.vue
- src/mixins/Context.vue
- src/store/modules/context.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-2737
> BOAC-2737, wanna dismiss BOA env alert? Click plane-departure!

- src/App.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2737
> BOAC-2737, id on dismiss-warning button; on dismiss, alert screen-reader

- boac/api/appointments_controller.py
- boac/models/appointment.py
- boac/models/development_db.py
- src/api/appointments.ts
- src/router.ts
- src/views/AppointmentWaitlist.vue
- tests/test_api/test_appointments_controller.py
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2872
See description in Jira above.
> BOAC-2872, URL of Intake Dashboard (appt waitlist) must include dept_code

- boac/models/appointment.py
- boac/models/development_db.py
- tests/test_api/test_appointments_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2872
> BOAC-2872, do the TODOs in test_appointments_controller

- src/components/matrix/Matrix.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1554
> BOAC-1554 Featured student starts out selected on matrix view

- boac/api/appointments_controller.py
- boac/merged/student.py
- boac/models/appointment.py
- src/components/appointment/AppointmentCancellationModal.vue
- src/components/appointment/AppointmentDetailsModal.vue
- src/mixins/Util.vue
- src/views/AppointmentWaitlist.vue
- tests/test_api/test_appointments_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2815
> BOAC-2814, student profile per appt on Intake Dashboard (waitlist)

- boac/api/appointments_controller.py
- src/api/appointments.ts
- src/assets/styles/boac-global.css
- src/components/appointment/AdvisingAppointment.vue
- src/components/appointment/AppointmentCancellationModal.vue
- src/components/appointment/AppointmentDetailsModal.vue
- src/components/student/profile/AcademicTimeline.vue
- src/mixins/UserMetadata.vue
- src/views/AppointmentWaitlist.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2866
> BOAC-2866, cancel appointment modal used on student profile and /appt/desk

- boac/models/appointment.py
- scripts/db/drop_schema.sql
- scripts/db/migrate/20191009-BOAC-2809/pre_deploy_05_create_appointments_search_index.sql
- scripts/db/schema.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2831
> BOAC-2831: Adds appointment search index

- boac/merged/user_session.py
- src/auth.ts
- src/components/appointment/AppointmentCancellationModal.vue
- src/router.ts
- src/views/DropInAdvisorHome.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2820
`router.ts` was cluttered with recent work so moved auth related functions to `auth.ts`.
> BOAC-2820, router: if is_drop_in_advisor=True then 'Drop-in Advisor' homepage

- src/components/admin/Users.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2858
> BOAC-2858: Hides become button and fixes filtering for role-less users

- boac/api/appointments_controller.py
- boac/api/student_controller.py
- src/api/appointments.ts
- src/views/AppointmentWaitlist.vue
- tests/test_api/test_appointments_controller.py
- tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2817
> BOAC-2817 Fixes to appointment creation workflow

- src/api/search.ts
- src/components/sidebar/Sidebar.vue
- src/components/student/profile/AcademicTimeline.vue
- src/views/Search.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2859
Existing search-timeline code handles notes and appointments.
> BOAC-2859, search notes/appointments in timeline (student profile page)

- src/components/admin/Users.vue
- src/components/appointment/DropInWaitlist.vue
- src/views/AppointmentWaitlist.vue
- src/views/DropInAdvisorHome.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2822
Not much new code – mostly reshuffling.
> BOAC-2822, drop-in advisor homepage shares DropInWaitlist component with /appt/desk

- boac/models/alert.py
- scripts/db/migrate/20191016-BOAC-2880/pre_deploy_01_update_phrase_in_withdrawal_alerts.sql
- tests/test_models/test_alert.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2880
> BOAC-2880, revise language of 'withdrawal' alerts

- boac/merged/student.py
- fixtures/loch_student_enrollment_term_11667051_2172.json
- tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2801
> BOAC-2801 Do not show obsolete waitlists

- boac/api/user_controller.py
- boac/models/university_dept_member.py
- src/api/user.ts
- src/components/appointment/CheckInModal.vue
- src/components/appointment/DropInWaitlist.vue
- src/router.ts
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2816
This code establishes the happy path from the scheduler's point of view.
> BOAC-2816 Appointment checkin from waitlist

- src/components/appointment/AppointmentCancellationModal.vue
- src/components/appointment/AppointmentDetailsModal.vue
- src/components/appointment/CheckInModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2816
Follow-up to #1994.
> BOAC-2816 Fix some button ids

- src/router.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-2885
> BOAC-2885, 404 and /settings routes for scheduler

- src/auth.ts
- src/components/HeaderMenu.vue
- src/components/admin/DemoModeToggle.vue
- src/components/admin/MyProfile.vue
- src/components/admin/Users.vue
- src/router.ts
- src/views/Admin.vue
- src/views/PassengerManifest.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2891
> BOAC-2891, split BOA /admin into (1) Flight Desk and (2) Passenger Manifest

- boac/models/appointment.py
- src/components/appointment/AdvisingAppointment.vue
- src/components/appointment/CheckInModal.vue
- src/components/student/profile/AcademicTimeline.vue
- src/mixins/UserMetadata.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2836
> BOAC-2836 Finish checkin/cancel workflow on student page

- src/components/appointment/AdvisingAppointment.vue
- src/components/appointment/AppointmentCancellationModal.vue
- src/components/appointment/DropInWaitlist.vue
- src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2866
https://jira.ets.berkeley.edu/jira/browse/BOAC-2884
> BOAC-2866 BOAC-2884 Give me one good reason to cancel this drop-in

- src/components/appointment/AppointmentCancellationModal.vue
- src/components/appointment/CheckInModal.vue
A couple more `b-form-select` with the https://jira.ets.berkeley.edu/jira/browse/BOAC-2843 bug
> BOAC-2843, avoid blank select menu (cancel/check-in modals)

- boac/api/search_controller.py
- boac/lib/util.py
- boac/merged/advising_note.py
- boac/models/appointment.py
- boac/models/development_db.py
- config/test.py
- fixtures/calnet_search_entries.json
- tests/conftest.py
- tests/test_api/test_appointments_controller.py
- tests/test_api/test_config_controller.py
- tests/test_api/test_search_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2840
Appointments will start appearing in search results, but display will look weird until the UI work is done.
> BOAC-2840: Includes appointments in note search

- src/components/appointment/AppointmentCancellationModal.vue
- src/components/appointment/AppointmentDetailsModal.vue
- src/components/appointment/AppointmentTopics.vue
- src/components/appointment/CreateAppointmentModal.vue
- src/components/appointment/DropInWaitlist.vue
- src/mixins/Util.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2830
https://jira.ets.berkeley.edu/jira/browse/BOAC-2881
> BOAC-2830 BOAC-2881 Styling, ids and such

- src/components/appointment/CreateAppointmentModal.vue
- src/components/search/SortableGroup.vue
- src/views/DropInAdvisorHome.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2898
> BOAC-2898, consistent styling of sortable-Alerts; responsive /home/dept_code

- boac/models/appointment.py
- scripts/db/migrate/20191009-BOAC-2809/pre_deploy_05_create_appointments_search_index.sql
- scripts/db/schema.sql
- tests/test_api/test_search_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2894
> BOAC-2894: Adds cancel reason (explained) to search index

- src/auth.ts
- src/router.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-2808
I also removed unnecessary `store.dispatch('user/loadUser')`
> BOAC-2808, every beforeEnter() in router must invoke a next()

- src/components/appointment/AppointmentCancellationModal.vue
- src/components/appointment/AppointmentDetailsModal.vue
- src/components/appointment/AppointmentTopics.vue
- src/components/appointment/CreateAppointmentModal.vue
- src/components/appointment/DropInWaitlist.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2879
The ids I changed are not being referenced by Teena. This PR includes a couple small fixes.
> BOAC-2879, accessibility-related work on Drop-in Appts homepage

- src/components/appointment/AppointmentCancellationModal.vue
- src/components/appointment/AppointmentDetailsModal.vue
- src/components/appointment/CreateAppointmentModal.vue
- src/components/appointment/DropInWaitlist.vue
- src/components/student/profile/AcademicTimeline.vue
- src/mixins/Util.vue
- src/views/AppointmentWaitlist.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2906
https://jira.ets.berkeley.edu/jira/browse/BOAC-2903
https://jira.ets.berkeley.edu/jira/browse/BOAC-2912
> BOAC-2903 / BOAC-2906, styling, aligning, sr-alerts, and ids

- boac/api/appointments_controller.py
- boac/models/appointment.py
- boac/models/development_db.py
- src/api/appointments.ts
- src/components/appointment/AdvisingAppointment.vue
- src/components/appointment/DropInWaitlist.vue
- src/views/DropInAdvisorHome.vue
- tests/test_api/test_appointments_controller.py
- tests/test_api/test_search_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2899
> BOAC-2899, drop-in advisor homepage shows today's checked-in and cancelled

- boac/api/search_controller.py
- boac/models/appointment.py
- src/api/search.ts
- src/components/search/AdvisingNoteSnippet.vue
- src/components/search/AppointmentSnippet.vue
- src/components/sidebar/SearchForm.vue
- src/views/Search.vue
- tests/test_api/test_search_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2904
> BOAC-2904: Displays appointments in search results

- src/components/appointment/AppointmentTopics.vue
- src/components/appointment/CreateAppointmentModal.vue
- src/components/appointment/DropInWaitlist.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2899
Review with `?w=1`. Includes ids and styles.
> BOAC-2899, Create appt: you get a do-over if you choose the wrong student

- boac/api/config_controller.py
- config/default.py
- src/mixins/Context.vue
- src/mixins/Util.vue
- src/store/modules/context.ts
- src/views/AppointmentWaitlist.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2877
> BOAC-2877 Periodic refresh for drop-in appt desk

- src/components/appointment/DropInWaitlist.vue
- src/components/search/AdvisingNoteSnippet.vue
- src/components/search/AppointmentSnippet.vue
- src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2911
Also, resolves https://jira.ets.berkeley.edu/jira/browse/BOAC-2910
@paulkerschen - You introduced that regex. Do you know if this change will impact beyond note and appointment links in search results?
> BOAC-2911, avoid permalink collisions on student profile page

- scripts/db/migrate/20191022-BOAC-2854/note-topics-per-ce3-request.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2854
> BOAC-2854, new topics per CE3; and modify 'Other'

- boac/api/appointments_controller.py
- src/components/appointment/DropInWaitlist.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2818
Unshift and not splice.
> BOAC-2818, new appts on top; cancel/check-in gets immediate update in waitlist

- src/components/util/Spinner.vue
- src/views/Admin.vue
- src/views/AllCohorts.vue
- src/views/AllGroups.vue
- src/views/AppointmentWaitlist.vue
- src/views/Cohort.vue
- src/views/Course.vue
- src/views/CuratedGroup.vue
- src/views/DropInAdvisorHome.vue
- src/views/Home.vue
- src/views/PassengerManifest.vue
- src/views/Search.vue
- src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2879
Meaningful `srAlert` when page is loading / has loaded.
> BOAC-2879, spinner component optional props for srAlert: prefix, is-plural

- src/components/appointment/AppointmentTopics.vue
- src/components/appointment/CreateAppointmentModal.vue
- src/components/appointment/DropInWaitlist.vue
- src/layouts/AppointmentDropIn.vue
- src/layouts/Login.vue
- src/layouts/StandardLayout.vue
- src/mixins/Context.vue
- src/store/modules/context.ts
- src/views/DropInAdvisorHome.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2879
https://jira.ets.berkeley.edu/jira/browse/BOAC-2924
And, the responsiveness  of drop-in advisor homepage needed help.
> BOAC-2879, additional accessibility work; BOAC-2924 responsive drop-in advisor home

- src/components/matrix/Matrix.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1554
> BOAC-1554 Clear old matrix tooltips on axis reselection

- boac/models/development_db.py
- boac/models/topic.py
- tests/test_api/test_appointments_controller.py
- tests/test_api/test_notes_controller.py
- tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2854
> BOAC-2854, topics with notes=true and appts=true must show for all

- src/components/appointment/DropInWaitlist.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2910
> BOAC-2910, use aria-hidden on Cancel Appt; sr-only for full phrase

- src/components/search/SortableStudents.vue
- src/mixins/Berkeley.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2926
> BOAC-2926, sort 'Alerts' section on home/search: last, first, sid

- src/components/appointment/DropInWaitlist.vue
- src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2913
> BOAC-2913 Appointment status indicator on academic timeline

- src/components/matrix/Matrix.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1554
> BOAC-1554 A more aggressive eraser for old tooltips

- src/components/matrix/Matrix.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1554
QA version of #2029.
> [QA] BOAC-1554 A more aggressive eraser for old tooltips

- src/components/student/SortBy.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2925
> BOAC-2925, width: auto for sort-by dropdown

- src/mixins/StudentMetadata.vue
- src/mixins/Validator.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2940
QA version of #2032.
> [QA] BOAC-2940 Remove references to old isAsc/isCoe user methods

- src/mixins/Validator.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2940
> BOAC-2940 Arrow functions and 'this', the old gotcha

- src/mixins/Validator.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2940
QA version of #2035.
> [QA] BOAC-2940 Arrow functions and 'this', the old gotcha

- boac/api/appointments_controller.py
- boac/api/search_controller.py
- boac/merged/advising_note.py
- boac/models/appointment.py
- src/api/appointments.ts
- src/components/sidebar/SearchForm.vue
- src/mixins/Util.vue
- src/views/Search.vue
- tests/test_api/test_appointments_controller.py
- tests/test_api/test_search_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2841
https://jira.ets.berkeley.edu/jira/browse/BOAC-2842
> BOAC-2841: Adapts sidebar search form for appointments

- scripts/db/migrate/20191009-BOAC-2809/pre_deploy_01_add_columns_to_topics.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2941
> BOAC-2941 Separate add/drop topics for appointments

- scripts/db/migrate/20191009-BOAC-2809/pre_deploy_01_add_columns_to_topics.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2941
QA version of #2037. While this feature isn't part of the release, we still need a QA PR since this migration will be run during prod deploy.
> [QA] BOAC-2941 Separate add/drop topics for appointments

- src/components/appointment/DropInWaitlist.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2942
> BOAC-2942, click check-in and the modal must close

- src/components/admin/Users.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2858
> BOAC-2858: Restores 'become' link for admin passengers

- src/components/student/profile/AcademicTimeline.vue
- src/components/student/profile/StudentProfileGPA.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2911
https://jira.ets.berkeley.edu/jira/browse/BOAC-2944
> BOAC-2911, fix permalink href; BOAC-2944: more/less GPA

- src/components/student/profile/AcademicTimeline.vue
- src/components/student/profile/StudentProfileGPA.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2911
https://jira.ets.berkeley.edu/jira/browse/BOAC-2944
master PR is #2042
> [QA] BOAC-2911, fix permalink href; BOAC-2944: more/less GPA

- src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2945
QA version of #2045.
> [QA] BOAC-2945 Match new options format when searching notes on student page

- src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2945
> BOAC-2945 Match new options format when searching notes on student page

- src/components/admin/Users.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2858
QA version of #2041
> [QA] BOAC-2858: Restores 'become' link for admin passengers

- src/store/modules/context.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-2957
> BOAC-2957, 'false' in .env file is not false until you test: === 'true'

- src/components/note/AdvisingNote.vue
> BOAC-2951: Removes logic preventing download of old attachments

- src/components/note/AdvisingNote.vue
> [QA] BOAC-2951: Removes logic preventing download of old attachments

- src/components/note/AdvisingNote.vue
Reverts ets-berkeley-edu/boac#2051
> Revert "[QA] BOAC-2951: Removes logic preventing download of old attachments"

- src/components/note/AdvisingNote.vue
Reverts ets-berkeley-edu/boac#2050
> Revert "BOAC-2951: Removes logic preventing download of old attachments"

- .eslintrc.js
- package-lock.json
- package.json
- src/assets/styles/bootstrap-overrides.css
- src/components/admin/Users.vue
- src/components/appointment/AppointmentTopics.vue
- src/components/appointment/CreateAppointmentModal.vue
- src/components/appointment/DropInWaitlist.vue
- src/components/cohort/ApplyAndSaveButtons.vue
- src/components/cohort/CreateCohortModal.vue
- src/components/cohort/FilterRow.vue
- src/components/course/CourseStudents.vue
- src/components/course/SortableCourseList.vue
- src/components/curated/CreateCuratedGroupModal.vue
- src/components/curated/CuratedGroupSelector.vue
- src/components/curated/CuratedStudentCheckbox.vue
- src/components/note/create/RenameTemplateModal.vue
- src/components/search/SortableStudents.vue
- src/components/sidebar/SearchForm.vue
- src/components/student/StudentRow.vue
- src/components/student/profile/AcademicTimeline.vue
- src/components/student/profile/StudentGroupSelector.vue
- src/components/student/profile/StudentProfileGPA.vue
- src/components/student/profile/StudentProfileHeader.vue
- src/components/util/Autocomplete.vue
- src/components/util/Spinner.vue
- src/mixins/Util.vue
- src/store/modules/cohort-edit-session.ts
- src/views/Cohort.vue
- src/views/Search.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2850
> BOAC-2850, Update bootstrap-vue: 2.0.0-rc.26 to 2.0.4

- .ebextensions/07_create_boa_cron.config
- scripts/db/tools/cancel_open_appointments.sh
- scripts/db/tools/cancel_open_appointments.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2895
The idea is that this gets run nightly at 10:00 UTC. Will it work?
> BOAC-2895 Script and cronjob for nightly appointments cleanup

- src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2947
> BOAC-2947: Fixes advisor autocomplete browser compatibility issue

- .eslintrc.js
- .travis.yml
https://jira.ets.berkeley.edu/jira/browse/BOAC-2970
See example of parallel "unit tests" in https://docs.travis-ci.com/user/build-stages/deploy-heroku  This PR uses slightly different syntax with equivalent function. 
Here is sample build on my BOAC fork: https://travis-ci.com/johncrossman/boac/builds/133912119 (3 min 38 sec). The most recently merged ets-berkeley-edu/boac PR took 6 min 42 sec.
> BOAC-2970, shave 2-3 minutes off Travis build with parallel jobs

- scripts/db/migrate/20191009-BOAC-2809/pre_deploy_05_create_appointments_search_index.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2894
> BOAC-2894: Fixes sql bug in appointments search index

- src/components/appointment/DropInWaitlist.vue
- src/components/search/SortableGroup.vue
- src/components/search/SortableStudents.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2974
https://jira.ets.berkeley.edu/jira/browse/BOAC-2952
> BOAC-2974, sort by alert-count on drop-in advisor home

- src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2958
> BOAC-2958: Fixes topics list ordering/duplication issue

- src/components/appointment/DropInWaitlist.vue
- src/router.ts
- src/views/DropInAdvisorHome.vue
- src/views/DropInDesk.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2973
Renamed `src/views/AppointmentWaitlist` to `DropInDesk` to get it side-by-side, in alpha order, with our other drop-in view.
> BOAC-2973, canceled appointments to bottom of waitlist

- src/components/sidebar/SearchForm.vue
- src/store/modules/context.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-2946
> BOAC-2946: Adds SR alerts for note/appt search filter toggle

- src/components/appointment/AppointmentDetailsModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2992
> BOAC-2992, say no to dupe ids

- boac/api/appointments_controller.py
- boac/api/cache_utils.py
- boac/api/user_controller.py
- boac/api/util.py
- boac/merged/user_session.py
- boac/models/authorized_user.py
- boac/models/development_db.py
- boac/models/drop_in_advisor.py
- boac/models/university_dept_member.py
- scripts/db/drop_schema.sql
- scripts/db/migrate/2019/20191031-BOAC-2985/post_deploy_01_drop_drop_in_advisor_column.sql
- scripts/db/migrate/2019/20191031-BOAC-2985/pre_deploy_01_add_drop_in_advisor_table.sql
- scripts/db/schema.sql
- src/auth.ts
- src/components/admin/MyProfile.vue
- src/components/admin/Users.vue
- src/components/appointment/AdvisingAppointment.vue
- src/components/appointment/DropInWaitlist.vue
- src/mixins/UserMetadata.vue
- src/router.ts
- tests/test_api/test_cache_utils.py
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2985
> BOAC-2985 Refactor drop-in advisor status into its own table and feed element

- boac/models/appointment.py
- boac/models/appointment_event.py
- boac/models/development_db.py
- scripts/db/migrate/2019/20191031-BOAC-2993/create_appointment_events_table.sql
- scripts/db/schema.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2993
The SQL script, with these fixes, has been run against boac-dev db. Front-end tweaks will follow.
> BOAC-2993, fixes on appointment_events related SQL/API

- boac/models/appointment.py
- tests/test_api/test_appointments_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2995
More tests, too.
> BOAC-2994, add 'reservedAt' and 'reservedBy' to API

- boac/api/user_controller.py
- boac/merged/user_session.py
- boac/models/drop_in_advisor.py
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2986
> BOAC-2986 API wiring for drop-in availability toggle

- boac/api/appointments_controller.py
- boac/models/appointment.py
- src/api/appointments.ts
- src/components/appointment/DropInWaitlist.vue
- src/mixins/DropInWaitlistContainer.vue
- src/views/DropInAdvisorHome.vue
- tests/test_api/test_appointments_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2995
> BOAC-2995, reserve and un-reserve API endpoints; front-end basics

- boac/api/cohort_controller.py
- boac/api/curated_group_controller.py
- boac/api/util.py
- src/api/cohort.ts
- src/api/curated.ts
- src/components/cohort/CohortPageHeader.vue
- src/components/curated/CuratedGroupHeader.vue
- src/components/util/ExportListModal.vue
- src/store/modules/cohort-edit-session.ts
- tests/test_api/test_cohort_controller.py
- tests/test_api/test_curated_group_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2893
> BOAC-2893: Allows custom columns in cohort and group CSV exports

- boac/api/user_controller.py
- src/api/user.ts
- src/components/appointment/DropInAvailabilityToggle.vue
- src/components/appointment/DropInWaitlist.vue
- src/store/modules/user.ts
- src/views/DropInAdvisorHome.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2990
> BOAC-2990 Drop-in availability toggle, front end

- boac/models/appointment_event.py
- src/components/appointment/DropInWaitlist.vue
- src/mixins/UserMetadata.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2996
> BOAC-2996, scheduler cannot reserve an appointment

- boac/api/user_controller.py
- src/components/appointment/CheckInModal.vue
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2987
> BOAC-2987 Scheduler may check in only available advisors

- src/components/appointment/DropInAppointmentDropdown.vue
- src/components/appointment/DropInWaitlist.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2996
> BOAC-2996, reusable appointment dropdown component for waitlist, student profile

- boac/models/appointment.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2959
With notes, the author's first and last name are stored in separate columns and are separately queryable.  User can search 'sa sm' and get Sam Smith.
Appointments have the entire name in one column, so in order to achieve the same search functionality we need to either split the name or do a full wildcard search.  I picked the latter but put in some benchmarking so I can monitor the query's performance as the appointments table grows in dev.
> BOAC-2959: Incrementally improves appointment advisor name autocomplete

- boac/api/appointments_controller.py
- src/api/appointments.ts
- src/components/appointment/AdvisingAppointment.vue
- src/components/appointment/DropInAppointmentDropdown.vue
- src/components/appointment/DropInWaitlist.vue
- src/components/student/profile/AcademicTimeline.vue
- tests/test_api/test_appointments_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2996
> BOAC-2996, reserve/unreserve from student profile page

- src/components/admin/MyProfile.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2976
For now, this page is only available in dev and qa.
> BOAC-2976, if drop-in advisor then show it on user profile page

- src/components/appointment/CheckInModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2983
If none on-duty then "Sorry, no advisors..."
> BOAC-2983, disable check-in btn until advisor selected

- boac/api/appointments_controller.py
- boac/models/appointment.py
- src/api/appointments.ts
- src/components/appointment/CreateAppointmentModal.vue
- src/components/appointment/DropInWaitlist.vue
- src/views/DropInDesk.vue
- tests/test_api/test_appointments_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3003
> BOAC-3003 Scheduler can assign appointment to advisor on creation

- scripts/db/migrate/2019/20191106-BOAC-3004/pre_deploy_01_revise_topics.sql
- src/components/appointment/DropInAvailabilityToggle.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3004
We decided to exclude:
* Degree Check, APR Update, EGT Update
* Probation, Dismissal
> BOAC-3004, add/update/delete topics per L&S feedback

- boac/externals/data_loch.py
- boac/merged/student.py
- fixtures/loch.sql
- fixtures/loch_student_enrollment_term_11667051_2162.json
- fixtures/loch_student_enrollment_term_11667051_2172.json
- fixtures/loch_student_enrollment_term_11667051_2178.json
- fixtures/loch_student_enrollment_term_11667051_2182.json
- fixtures/loch_student_enrollment_term_2345678901_2172.json
- fixtures/loch_student_enrollment_term_3456789012_2178.json
- fixtures/loch_student_enrollment_term_5678901234_2178.json
- src/components/student/SortBy.vue
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2025
> BOAC-2025 Sort cohorts by term GPA

- boac/api/search_controller.py
- src/components/appointment/DropInAvailabilityToggle.vue
- src/components/appointment/DropInWaitlist.vue
- src/views/Search.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2960
And mo' better `ids`
> BOAC-2960, notes/appt search results: 20 per resultset

- src/views/DropInDesk.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3005
> BOAC-3005, no 'Create Appt' if user.isAdmin

- src/components/appointment/DropInAvailabilityToggle.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2960
PR #2089 was too hasty.
> BOAC-2960, uid when advisor is nil in DropInAvailabilityToggle

- boac/models/authorized_user.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3007
> BOAC-3007 Respect deleted_at in user/drop-in dept join

- boac/models/alert.py
- scripts/db/migrate/2019/20191107-BOAC-2975/post_deploy_01_update_midpoint_grade_alerts.sql
- tests/test_api/test_cache_utils.py
- tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2975
> BOAC-2975 Revise midpoint deficient grade alert text

- src/auth.ts
- src/router.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-2969
Shared router logic for drop-in advisor and scheduler.
> BOAC-2969, clean up Vue router w.r.t drop-in auth

- boac/models/appointment_event.py
- boac/models/development_db.py
- tests/test_api/test_appointments_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3008
> BOAC-3008, most recent appointment event: order by created_at, desc

- src/components/appointment/DropInAppointmentDropdown.vue
- src/components/appointment/DropInWaitlist.vue
- src/components/student/profile/AcademicTimeline.vue
- src/views/DropInAdvisorHome.vue
- src/views/DropInDesk.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2971
Next up: conflict resolution.
> BOAC-2971 Spinners for appointment actions in progress

- boac/api/admin_controller.py
- boac/api/cache_utils.py
- run.py
- scripts/refresh_current_term_cache.sh
- tests/test_models/test_job_progress.py
> NOJIRA Remove some obsolete admin endpoints

- boac/api/appointments_controller.py
- boac/models/appointment.py
- tests/test_api/test_appointments_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2961
https://jira.ets.berkeley.edu/jira/browse/BOAC-2971
Next step: client code to handle all these new 400s.
> BOAC-2961 BOAC-2971 Server-side conflict handling for drop-in appts

- boac/api/user_controller.py
- boac/api/util.py
- boac/models/authorized_user.py
- boac/models/university_dept.py
- boac/models/user_login.py
- src/api/user.ts
- src/components/admin/Users.vue
- src/store/modules/user.ts
- src/views/PassengerManifest.vue
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2874
Just cuz
> BOAC-2874, /admin page: filter controls are dropdowns, not checkboxes

- src/api/appointments.ts
- src/components/appointment/AppointmentUpdateModal.vue
- src/components/appointment/DropInAppointmentDropdown.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2961
> BOAC-2961 BOAC-2971 Error handlin' modals

- boac/api/user_controller.py
- boac/api/util.py
- boac/models/authorized_user.py
- src/api/user.ts
- src/components/admin/EditUserProfileModal.vue
- src/components/admin/Users.vue
- tests/test_api/test_student_controller.py
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2874
> BOAC-2874, fixes to /admin users view

- src/components/appointment/AdvisingAppointment.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3012
> BOAC-3012 Advisor details for checked in appointments only

- boac/api/appointments_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3015
> BOAC-3015, Admin user gets Drop-in advisor UX on /home/{deptCode}

- boac/api/util.py
- src/components/admin/EditUserProfileModal.vue
- src/components/admin/Users.vue
- src/components/appointment/AppointmentDetailsModal.vue
- src/components/appointment/DropInAppointmentDropdown.vue
- src/components/appointment/DropInAvailabilityToggle.vue
- src/components/appointment/DropInWaitlist.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3014
Admins cannot:
* toggle advisor status
* check-in appointments
Admins can see appt details and cancel appts.
> BOAC-3014, limit Admin on Drop-in Appt views; small fixes to /admin

- boac/api/user_controller.py
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3026
> BOAC-3026, Pasenger Manifest user search: ignore case

- boac/api/user_controller.py
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3026
master PR is #2110
> [QA] BOAC-3026, Pasenger Manifest user search: ignore case

- src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2949
QA PR:  #2113
> BOAC-2949: Labelizes search form inputs

- src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2949
master PR:  #2112
> [QA] BOAC-2949: Labelizes search form inputs

- src/components/admin/Users.vue
- src/components/appointment/CreateAppointmentModal.vue
- src/components/appointment/DropInWaitlist.vue
- src/mixins/UserMetadata.vue
- src/views/DropInAdvisorHome.vue
- src/views/DropInDesk.vue
- tests/test_api/test_appointments_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3010
> BOAC-3010, specify advisor when create appt and BOA captures dept roles, etc.

- src/components/admin/Users.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2935
The tests for this page are failing since the redesign, so I think I'm going to end up rewriting most of them (including CSV export).
> BOAC-2935: Tweaks ids on passenger manifest

- boac/externals/data_loch.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3032
QA version of #2117.
> [QA] BOAC-3032 Avoid SQL alias conflict on enrollment term joins

- boac/api/cache_utils.py
- boac/api/user_controller.py
- boac/api/util.py
- boac/merged/user_session.py
- boac/models/authorized_user.py
- boac/models/development_db.py
- boac/models/drop_in_advisor.py
- boac/models/university_dept_member.py
- src/api/user.ts
- src/components/admin/EditUserProfileModal.vue
- src/components/admin/Users.vue
- src/components/util/Autocomplete.vue
- tests/test_api/test_cache_utils.py
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2844
The API supports `create_or_update_user` but for now, the front-end is only wired for `update`. I had to finesse `db.relationships` a bit.  Nothing too controversial, I hope.
> BOAC-2713, update user profile and dept memberships from Passenger Manifest page

- boac/externals/data_loch.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3032
> BOAC-3032 Avoid SQL alias conflict on enrollment term joins

- boac/api/user_controller.py
- src/api/user.ts
- src/components/admin/EditUserProfileModal.vue
- src/components/admin/Users.vue
- src/views/PassengerManifest.vue
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2713
> BOAC-2713, add user to BOA with UID via Passenger Manifest

- src/components/appointment/CreateAppointmentModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3027
> BOAC-3027, in create-appt modal, allow user to un-select advisor

- boac/api/user_controller.py
- boac/models/authorized_user.py
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2887
Last bit of work, in this sprint, on Passenger Manifest.
> BOAC-2887, added fields to users CSV download

- requirements.txt
- tox.ini
https://jira.ets.berkeley.edu/jira/browse/BOAC-2979
Docs:
* https://docs.sqlalchemy.org/en/13/changelog/changelog_13.html#change-1.3.10
* https://palletsprojects.com/blog/flask-1-1-released/
> BOAC-2979, upgrade Flask, Werkzeug and SQLAlchemy

- boac/api/user_controller.py
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3040
> BOAC-3040, Passenger Manifest > regex fix for search by last name

- boac/api/user_controller.py
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3040
master PR is #2124
> [QA] BOAC-3040, Passenger Manifest > regex fix for search by last name

- src/components/student/profile/StudentGroupSelector.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3043
> BOAC-3043 Restore title to curated group creation modal

- src/components/student/profile/StudentGroupSelector.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3043
QA version of #2125.
> [QA] BOAC-3043 Restore title to curated group creation modal

- boac/api/user_controller.py
- src/components/note/AdvisingNote.vue
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3041
master PR is #2128
> [QA] BOAC-3041, Student profile > note author not found > graceful 404 server-side

- boac/api/appointments_controller.py
- boac/models/appointment.py
- boac/models/appointment_event.py
- boac/models/development_db.py
- scripts/db/migrate/2019/20191118-BOAC-3029/pre_deploy_01_update_appointment_events_enum.sql
- scripts/db/schema.sql
- scripts/db/tools/cancel_open_appointments.sql
- src/api/appointments.ts
- src/components/appointment/AdvisingAppointment.vue
- src/components/appointment/AppointmentCancellationModal.vue
- src/components/appointment/DropInAppointmentDropdown.vue
- src/components/appointment/DropInWaitlist.vue
- src/components/cohort/ApplyAndSaveButtons.vue
- src/components/cohort/FilterRow.vue
- src/components/note/EditAdvisingNote.vue
- src/components/note/create/CreateNoteModal.vue
- src/components/student/profile/AcademicTimeline.vue
- src/views/CreateCuratedGroup.vue
- src/views/CuratedGroup.vue
- tests/test_api/test_appointments_controller.py
- tests/test_api/test_search_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3029
Double-L is cooler.
> BOAC-3029, 'canceled' has been cancelled, in favor of 'cancelled'

- .eslintrc.js
- src/components/matrix/Matrix.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3046
> BOAC-3046 Revert well-intentioned vue-a11y @blur mandate

- src/components/search/SortableGroup.vue
- src/mixins/Berkeley.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3038
> BOAC-3038 Default sort by alert count for all homepage cohorts/groups

- .eslintrc.js
- src/components/matrix/Matrix.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3046
QA version of #2132.
> [QA] BOAC-3046 Revert well-intentioned vue-a11y @blur mandate

- src/components/note/AdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3051 describes two issues to resolve. This PR resolves one; a Teena PR will follow. 
I also removed a couple unnecessary ids.
> BOAC-3051, consistent note-subject id naming in student profile > timeline

- src/components/admin/Users.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2935
> BOAC-2935: IDs passenger manifest user detail section

- src/components/appointment/DropInWaitlist.vue
- src/views/DropInAdvisorHome.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3037
> BOAC-3037, reduce padding in Drop-in Waitlist

- src/components/curated/CuratedGroupSelector.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3059
> BOAC-3059, restore b-modal id to restore 'Create new group' feature

- src/components/appointment/CreateAppointmentModal.vue
- src/components/cohort/ApplyAndSaveButtons.vue
- src/components/curated/CuratedGroupSelector.vue
- src/components/note/create/CreateTemplateModal.vue
- src/components/note/create/RenameTemplateModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3052
Turns out we had a handful of these.
> BOAC-3052 Restore missing titles, ids to b-modal elements

- src/components/curated/CuratedGroupSelector.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3059
master PR is #2139
> [QA] BOAC-3059, restore b-modal id to restore 'Create new group' feature

- src/components/appointment/CreateAppointmentModal.vue
- src/components/cohort/ApplyAndSaveButtons.vue
- src/components/curated/CuratedGroupSelector.vue
- src/components/note/create/CreateTemplateModal.vue
- src/components/note/create/RenameTemplateModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3052
QA version of #2141 (NB: not a cherry pick because of attribute ordering differences between master and qa).
> [QA] BOAC-3052 Restore missing titles, ids to b-modal elements

- package-lock.json
- package.json
- src/filters.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-3060
> BOAC-3060: Installs numeral.js as explicit numFormat dependency

- boac/api/appointments_controller.py
- boac/models/appointment.py
- src/api/appointments.ts
- src/components/appointment/CheckInModal.vue
- src/components/appointment/DropInAppointmentDropdown.vue
- src/components/appointment/DropInWaitlist.vue
- src/components/appointment/DropInWaitlistAppointment.vue
- tests/test_api/test_appointments_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3028
> BOAC-3028 Advisors get confirmation modal and undo for checkin/cancel

- src/components/appointment/AdvisingAppointment.vue
- src/components/appointment/DropInAppointmentDropdown.vue
- src/components/appointment/DropInWaitlistAppointment.vue
- src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3021
> BOAC-3021 Relabel reserve/unreserve as assign/unassign

- boac/api/user_controller.py
- boac/models/authorized_user.py
- src/api/user.ts
- src/components/admin/EditUserProfileModal.vue
- src/components/admin/Users.vue
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3063
> BOAC-3063, Passenger Manifest > Delete and un-delete users

- src/components/note/AdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3061
Cause of regression: PR #2128 
> BOAC-3061, if author.uid or author.csid then lazy-load calnet profile

- src/components/note/AdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3061
master PR is #2150
> [QA] BOAC-3061, if author.uid or author.csid then lazy-load calnet profile

- src/components/note/AdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3061
`qa` PR is #2153
> BOAC-3061, AdvisingNote > fix note author title/dept formatting

- src/components/note/AdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3061
For example:
> [QA] BOAC-3061, AdvisingNote > fix note author title/dept formatting

- src/components/admin/DevAuth.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2972
Explanation: https://github.com/vuejs/vue-router/issues/2881#issuecomment-520554378
> BOAC-2972, DevAuth: silence benign 'router.push' error

- boac/api/appointments_controller.py
- boac/models/appointment.py
- src/api/appointments.ts
- src/components/appointment/AppointmentDetailsModal.vue
- src/components/appointment/AppointmentTopics.vue
- src/components/appointment/DropInAppointmentDropdown.vue
- tests/test_api/test_appointments_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3021
> BOAC-3021 Make appointment details modal editable

- src/components/appointment/AppointmentDetailsModal.vue
- src/components/util/Autocomplete.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3065
> BOAC-3065, Autocomplete dropdown should not bully other form elements

- boac/models/appointment.py
- src/views/Search.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3067
> BOAC-3067, if /search has no params then go /home

- boac/api/user_controller.py
- src/components/note/AdvisingNote.vue
- tests/test_api/test_user_controller.py
> BOAC-3068, no 404 when advisor not found; nil tolerant front-end

- src/components/note/AdvisingNote.vue
> [QA] BOAC-3068, 'Advisor profile not found' when API returns nil

- src/components/note/AdvisingNote.vue
> BOAC-3068, 'Advisor profile not found' when API returns nil

- src/components/HeaderMenu.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2972
No more `NavigationDuplicated error: Navigating to current location ("/admin/passengers") is not allowed`
> BOAC-2972, header nav menu > reset Passenger view; no console errors

- boac/api/user_controller.py
- src/api/user.ts
- src/components/note/AdvisingNote.vue
- src/store/modules/user.ts
- tests/test_api/test_user_controller.py
> BOAC-3068, get-advisor-info is strictly CalNet-based, no authorized_user dependency

- boac/api/config_controller.py
- config/default.py
- src/components/admin/Users.vue
- src/mixins/Context.vue
- src/store/modules/context.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-3071
boa-dev will need `FEATURE_FLAG_PASSENGER_EDIT = True`
> BOAC-3071, feature flag on EditUserProfileModal (Passenger Manifest)

- boac/__init__.py
> NOJIRA, BOA is now v4 on master branch

- src/components/admin/DevAuth.vue
- src/layouts/Login.vue
- src/main.ts
- src/mixins/Context.vue
- src/router.ts
- src/store/modules/context.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-3076
https://jira.ets.berkeley.edu/jira/browse/BOAC-3044
Our `axios.interceptor` logic causes trouble and it's hard to override. E.g., recent "unexpected 404" bug in prod: https://jira.ets.berkeley.edu/jira/browse/BOAC-3068.  Now, explicit error handling is required. 
This PR also removes our unused 'errors' list in vuex store. In the process, simplifying error messaging on `/login` page.
> BOAC-3076, remove axios.interceptor fallback and vuex-managed list o' errors

- boac/models/appointment_event.py
- scripts/db/migrate/2019/20191202-BOAC-3073/pre_deploy_01_appointment_events_user_drop_not_null.sql
- scripts/db/schema.sql
- scripts/db/tools/cancel_open_appointments.sh
- scripts/db/tools/cancel_open_appointments.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-3073
> BOAC-3073 Update nightly appt cancellation script to new schema

- src/components/appointment/CheckInModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3075
> BOAC-3075 Check-in modal: fix advisor initialization

- boac/api/appointments_controller.py
- src/api/appointments.ts
- src/components/appointment/AppointmentAssignModal.vue
- src/components/appointment/DropInAppointmentDropdown.vue
- tests/test_api/test_appointments_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3072
> BOAC-3072 Assign/unassign for appointment schedulers too

- src/components/student/profile/AcademicTimeline.vue
- src/components/util/ExportListModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3048
https://jira.ets.berkeley.edu/jira/browse/BOAC-2978
> BOAC-2978, Accessibility: sr-only in collapsed appt; BOAC-3048, disable CSV export button

- boac/api/util.py
- src/components/appointment/AppointmentAssignModal.vue
- src/components/appointment/CheckInModal.vue
- src/components/appointment/CreateAppointmentModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3080
https://jira.ets.berkeley.edu/jira/browse/BOAC-3079
See comments in Jiras above.
> BOAC-3080, advisor dropdown fixes for ApptAssignModal, CheckInModal, etc.

- src/components/admin/Users.vue
- src/components/appointment/CheckInModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3081
> BOAC-3081, if self-check-in then CheckInModal need not wait for advisor list

- src/components/appointment/DropInWaitlist.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3088
> BOAC-3088, scheduler waitlist count is waitlist.unresolved.length

- src/components/appointment/DropInWaitlist.vue
- src/components/appointment/DropInWaitlistAppointment.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3083
> BOAC-3083, Drop-in Advisor homepage shows advisor name when checked-in and cancelled

- src/components/appointment/AppointmentAssignModal.vue
- src/components/appointment/AppointmentCancellationModal.vue
- src/components/appointment/AppointmentTopics.vue
- src/components/appointment/CheckInModal.vue
- src/components/appointment/CreateAppointmentModal.vue
- src/views/PassengerManifest.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3027
https://jira.ets.berkeley.edu/jira/browse/BOAC-3090
QA PR is #2183
> BOAC-3027, allow de-select of advisor when create appt and similar modals

- src/components/appointment/AppointmentAssignModal.vue
- src/components/appointment/AppointmentCancellationModal.vue
- src/components/appointment/AppointmentTopics.vue
- src/components/appointment/CheckInModal.vue
- src/components/appointment/CreateAppointmentModal.vue
- src/views/PassengerManifest.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3027
https://jira.ets.berkeley.edu/jira/browse/BOAC-3090
> [QA] BOAC-3027, allow de-select of advisor when create appt and similar modals

- src/components/appointment/CheckInModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3091
> BOAC-3901 Fix advisor dept code mapping on checkin

- src/components/appointment/CheckInModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3091
QA version of #2187.
> [QA] BOAC-3901 Fix advisor dept code mapping on checkin

- src/auth.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-3089
I can reproduce on boa-dev but not locally. Nonetheless, I have a hunch on infinite loop. This is a no-risk change.
> [QA] BOAC-3089, remove 'config' dependency from auth.ts; no more scheduler freeze

- src/auth.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-3089
QA PR is #2189
> BOAC-3089, remove 'config' dependency from auth.ts; no more scheduler  freeze

- src/api/student.ts
- src/views/DropInAdvisorHome.vue
- src/views/DropInDesk.vue
QA-first PR for https://jira.ets.berkeley.edu/jira/browse/BOAC-3099.
Let's see what it does.
> [QA] BOAC-3099 Simple request throttling for drop-in poller, student autocomplete

- src/views/DropInAdvisorHome.vue
- src/views/DropInDesk.vue
See http://bonsaiden.github.io/JavaScript-Garden/#other.timeouts - `setInterval` bad, nested `setTimeout` good.
> BOAC-3099 Adjust drop-in poller timing

- src/api/student.ts
- src/views/DropInAdvisorHome.vue
- src/views/DropInDesk.vue
Master version of QA PRs #2192, #2193.
>  BOAC-3099 Simple request throttling for drop-in poller, student autocomplete

- src/components/appointment/DropInAppointmentDropdown.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3094
Corresponding `qa` PR is #2191. The master branch will get one more PR to resolve the Jira.
> BOAC-3094, drop-in advisor sees 'Assign to me' rather than 'Assign'

- .ebextensions/06_create_cloudwatch_conf.config
https://jira.ets.berkeley.edu/jira/browse/BOAC-3073
> BOAC-3073 Add cron logs to CloudWatch

- .ebextensions/06_create_cloudwatch_conf.config
https://jira.ets.berkeley.edu/jira/browse/BOAC-3073
QA version of #2196.
> [QA] BOAC-3073 Add cron logs to CloudWatch

- boac/api/cache_utils.py
- boac/models/drop_in_advisor.py
- tests/test_api/test_cache_utils.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3070
> BOAC-3070: Deletes orphan dropin advisors on dept refresh

- boac/api/cache_utils.py
- boac/models/drop_in_advisor.py
- tests/test_api/test_cache_utils.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3070
master PR #2198
> [QA] BOAC-3070: Deletes orphan dropin advisors on dept refresh

- src/api/appointments.ts
- src/api/notes.ts
> [QA] BOAC-3099 More throttling for autocomplete-triggered requests

- src/api/appointments.ts
- src/api/notes.ts
> BOAC-3099 More throttling for autocomplete-triggered requests

- boac/api/util.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3080
master PR is #2202
> [QA] BOAC-3080, drop-in advisors alphabetically by first name

- boac/api/util.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3080
> BOAC-3080, drop-in advisors alphabetically by first name

- src/components/util/Autocomplete.vue
> [QA] BOAC-3099 Limit input length in autocomplete

- src/components/util/Autocomplete.vue
> BOAC-3099 Limit input length in autocomplete

- src/components/appointment/DropInWaitlistAppointment.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3105
> BOAC-3105, checked-in appts: display advisor who saw the student

- src/components/appointment/DropInWaitlistAppointment.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3105
master PR is #2206
> [QA] BOAC-3105, waiting list car battery for advisor who saw the student

- src/components/appointment/CreateAppointmentModal.vue
- src/components/appointment/DropInAppointmentDropdown.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3091
> BOAC-3091 Consistent use of LDAP title for appointments

- src/views/DropInAdvisorHome.vue
- src/views/DropInDesk.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3102
master PR is #2209
> [QA] BOAC-3102, do not set apptDeskRefreshInterval on user-initiated appt update

- boac/models/appointment.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3074
> BOAC-3074 Timezone adjustments in appointment waitlist query

- src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2978
See latest comment in Jira.
> BOAC-2978, sr speaks 'Appointment date' when type=appt

- src/components/student/profile/StudentPersonalDetails.vue
- src/components/student/profile/StudentProfileHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3113
UX: https://jira.ets.berkeley.edu/jira/browse/BOAC-2799
Use `?w=1` to get slightly simpler diff.
> BOAC-3113, expand/collapse UX for student details

- src/components/admin/Users.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3128
> BOAC-3128, Passenger Manifest: Quick links to drop-in advisors, L&S advisors, and schedulers

- src/components/student/profile/StudentPersonalDetails.vue
- src/components/student/profile/StudentProfileHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3115
> BOAC-3115 Intended and discontinued majors in details panel

- src/components/student/profile/StudentPersonalDetails.vue
- src/components/student/profile/StudentProfileHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3111
https://jira.ets.berkeley.edu/jira/browse/BOAC-3127
> BOAC-3111 BOAC-3127 Add minors to profile, move other elements around

- src/components/student/profile/StudentPersonalDetails.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3118
> BOAC-3118 Show alternate email address if available

- boac/api/appointments_controller.py
- boac/api/config_controller.py
- boac/api/search_controller.py
- boac/api/topic_controller.py
- boac/api/util.py
- config/default.py
- config/development.py
- config/test.py
- src/api/search.ts
- src/components/sidebar/SearchForm.vue
- src/components/student/profile/AcademicTimeline.vue
- src/mixins/Context.vue
- src/store/modules/context.ts
- src/views/Search.vue
- tests/test_api/test_appointments_controller.py
- tests/test_api/test_config_controller.py
- tests/test_api/test_search_controller.py
- tests/test_api/test_student_controller.py
- tests/test_api/test_topic_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3129
A lot of clean up in `test_search_controller`, too.
> BOAC-3129, remove appointments feature flag and includeAppointments param in search

- src/components/student/profile/StudentPersonalDetails.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2921
> BOAC-2921 Display international status in profile details

- src/components/student/profile/StudentPersonalDetails.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2921
> BOAC-2921 Fix _.get goof

- src/components/appointment/CreateAppointmentModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3130
> BOAC-3130, null-safe attempt to get advisor title

- src/components/student/profile/StudentPersonalDetails.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2921
> BOAC-2921 Update international status wording

- src/components/admin/EditUserProfileModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3135
> BOAC-3135, id on passenger edit button

- src/components/admin/EditUserProfileModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3132
Simpler diff with `?w=1`
> BOAC-3132, Pax manifest: report error when saving dept without role

- src/components/admin/EditUserProfileModal.vue
- src/components/admin/Users.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3133
> BOAC-3133, Pax manifest: save a user in search mode and the user remains in view

- src/components/admin/EditUserProfileModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3135
> BOAC-3135, uid of passenger, not current-user

- boac/externals/data_loch.py
- fixtures/loch.sql
- tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3108
I chatted with Steven about this and we agreed to try it out in dev. If it makes for a confusing UX we'll look at alternatives.
> BOAC-3108: Allows non-current students to turn up in auto-suggest by SID only

- src/components/student/profile/StudentPersonalDetails.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3109
> BOAC-3109 Show assigned advisors in student profile details

- src/components/student/profile/StudentPersonalDetails.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3115
> BOAC-3115 Link intended majors if degree program URL present

- boac/merged/student.py
- src/components/appointment/DropInWaitlistAppointment.vue
- tests/test_merged/test_student.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3110
> BOAC-3110: Denotes non-current students in waitlist with an icon

- boac/api/user_controller.py
- src/api/user.ts
- src/components/appointment/DropInAdvisorList.vue
- src/components/appointment/DropInAvailabilityToggle.vue
- src/components/appointment/DropInWaitlist.vue
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3141
Tweak on props of `DropInAvailabilityToggle`.
> BOAC-3141, DropInAvailabilityToggle keeps 'watch' on advisor availability

- boac/api/user_controller.py
- boac/models/authorized_user.py
- src/components/admin/EditUserProfileModal.vue
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3134
> BOAC-3134, Pax manifest: deny add user when UID is in BOA db

- src/components/HeaderMenu.vue
- src/components/admin/Users.vue
- src/components/appointment/AdvisingAppointment.vue
- src/components/student/SortBy.vue
- src/mixins/Berkeley.vue
- src/mixins/StudentMetadata.vue
- src/mixins/UserMetadata.vue
- src/mixins/Validator.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3146
Review with `?w=1`.
> BOAC-3146, dismantle the UserMetadata mixin

- boac/api/search_controller.py
- boac/models/appointment.py
- src/api/search.ts
- src/views/Search.vue
- tests/test_api/test_search_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3139
> BOAC-3139: Disentangles notes and appointments search

- src/mixins/Util.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3149
> BOAC-3149 Add _.upperCase to Util mixin

- src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3150
> BOAC-3150 Sort appts in academic timeline by creation time

- src/components/student/profile/StudentPersonalDetails.vue
- src/components/student/profile/StudentProfileHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3148
> BOAC-3148 Discontinued minors below the fold

- boac/models/appointment.py
- src/components/appointment/AppointmentTopics.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3117
> BOAC-3117 Alphabetize appointment topics

- boac/externals/data_loch.py
- boac/merged/cohort_filter_options.py
- boac/merged/student.py
- boac/models/cohort_filter.py
- fixtures/loch.sql
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1459
> BOAC-1459: Adds new cohort filter for visa type

- src/components/appointment/AppointmentDetailsModal.vue
- src/components/appointment/AppointmentTopics.vue
- src/components/appointment/CreateAppointmentModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3114
> BOAC-3114 Focus back to topic list after adding topics

- src/components/appointment/CreateAppointmentModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3112
> BOAC-3112: Changes label on appt detail field

- src/components/appointment/CreateAppointmentModal.vue
- src/components/appointment/DropInWaitlist.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3116
> BOAC-3116 No double-booking the Drop-In Waitlist

- config/default.py
- src/App.vue
- src/api/appointments.ts
- src/api/auth.ts
- src/api/curated.ts
- src/api/note-templates.ts
- src/api/notes.ts
- src/api/search.ts
- src/components/cohort/ApplyAndSaveButtons.vue
- src/components/cohort/CohortPageHeader.vue
- src/components/cohort/FilterRow.vue
- src/components/curated/CuratedGroupSelector.vue
- src/components/search/SortableGroup.vue
- src/components/sidebar/SearchForm.vue
- src/components/student/profile/AcademicTimeline.vue
- src/components/student/profile/StudentGroupSelector.vue
- src/core.ts
- src/main.ts
- src/mixins/UserMetadata.vue
- src/store/modules/cohort.ts
- src/store/modules/context.ts
- src/store/modules/curated.ts
- src/store/modules/user.ts
- src/views/Cohort.vue
- src/views/Course.vue
- src/views/CreateCuratedGroup.vue
- src/views/CuratedGroup.vue
- src/views/Search.vue
- tests/test_api/test_config_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3146
In `main.ts`, two async calls to init user and ga:
```
$core.initializeCurrentUser();
$core.mountGoogleAnalytics();
```
`$core` is where we keep low-level utilities that initialize prototype objects. These are invoked again when user logs in via dev-auth.
> BOAC-3146, move Google Analytics out of vuex store and UserMetadata mixin

- src/App.vue
- src/api/api-utils.ts
- src/api/appointments.ts
- src/api/notes.ts
- src/components/Footer.vue
- src/components/HeaderMenu.vue
- src/components/appointment/AdvisingAppointment.vue
- src/components/course/CourseStudents.vue
- src/components/matrix/Matrix.vue
- src/components/matrix/MatrixUtil.vue
- src/components/note/AdvisingNote.vue
- src/components/note/AdvisingNoteAttachments.vue
- src/components/search/AdvisingNoteSnippet.vue
- src/components/search/AppointmentSnippet.vue
- src/components/student/SortBy.vue
- src/components/student/StudentRow.vue
- src/components/student/profile/StudentClasses.vue
- src/components/student/profile/StudentProfileUnits.vue
- src/components/student/profile/TimelineDate.vue
- src/core.ts
- src/layouts/Login.vue
- src/main.ts
- src/mixins/Context.vue
- src/store/modules/context.ts
- src/views/PassengerManifest.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3146
A "store" (vuex) should not maintain static configs. This PR reduces `context.ts` to state variables that might actually mutate.
> BOAC-3146, process.env variables put to $config and removed from 'store'

- src/components/appointment/AdvisingAppointment.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3159
> BOAC-3159 Show appointment arrival times in Academic Timeline

- src/components/appointment/DropInAppointmentDropdown.vue
- src/components/appointment/DropInWaitlist.vue
- src/components/appointment/DropInWaitlistAppointment.vue
- src/components/note/AdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3146
> BOAC-3146, this.user is now this.$currentUser (I missed a few)

- boac/models/drop_in_advisor.py
- scripts/db/migrate/2019/20191219-BOAC-3160/pre_deploy_01_add_drop_in_supervisor_column.sql
- scripts/db/schema.sql
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3167
> BOAC-3167: Adds supervisor on call flag to drop_in_advisors

- boac/api/user_controller.py
- src/components/admin/EditUserProfileModal.vue
- src/components/admin/Users.vue
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3170
> BOAC-3170: Allows admin to assign supervisor on-call role to users

- src/components/appointment/AppointmentAssignModal.vue
- src/components/appointment/CreateAppointmentModal.vue
- src/components/appointment/DropInAdvisorList.vue
- src/mixins/Berkeley.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3169
> BOAC-3169: Adds visual indicator for supervisor on call

- src/components/student/profile/StudentPersonalDetails.vue
http://localhost:8080/student/1577017
> BOAC-3175, student profile > show details > null-safe check on 'student.advisors'

- boac/api/cache_utils.py
- boac/api/user_controller.py
- boac/models/development_db.py
- src/api/user.ts
- src/components/admin/EditMyRolesModal.vue
- src/components/admin/EditUserProfileModal.vue
- src/components/admin/MyProfile.vue
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3168
> BOAC-3168: Allows user to change drop-in roles on Settings page

- src/components/student/profile/StudentPersonalDetails.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3175
master PR is #2263
> [QA] BOAC-3175, student profile > show details > null-safe check on student.advisors

- boac/merged/student.py
- tests/test_merged/test_student.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3174
> BOAC-3174: Puts placeholder avatar on non-current student appointments

- src/components/student/profile/StudentClasses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3173
Also, relevantTerms does not need to be "computed" value.
> BOAC-3173, Student page > no 'more semesters' button if enrollmentTerms.length <= size(relevantTerms)

- boac/merged/student.py
- tests/test_merged/test_student.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3174
master PR is #2266
> [QA] BOAC-3174: Puts placeholder avatar on non-current student appointments

- src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3177
> BOAC-3177: Applies demo mode logic to Academic Timeline search result summary

- src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3177
master PR is #2271
> [QA] BOAC-3177: Applies demo mode logic to Academic Timeline search result summary

- boac/api/config_controller.py
- config/default.py
- src/components/admin/Users.vue
- src/views/PassengerManifest.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3188
> BOAC-3188, remove FEATURE_FLAG_PASSENGER_EDIT

- boac/api/appointments_controller.py
- src/components/appointment/AdvisingAppointment.vue
- src/components/appointment/AppointmentDetailsModal.vue
- src/components/appointment/CreateAppointmentModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3082
> BOAC-3082, edit appointment details > rich-text editor

- boac/api/search_controller.py
- boac/models/authorized_user.py
- boac/models/development_db.py
- config/default.py
- tests/test_api/test_search_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3190
> BOAC-3190, search history server-side, with USER_SEARCH_HISTORY_MAX_SIZE config

- src/components/student/profile/StudentPersonalDetails.vue
- src/components/student/profile/StudentProfileHeader.vue
- src/components/student/profile/StudentProfilePlan.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3153
> BOAC-3153 Show discontinued plans above the fold if no active majors

- src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2705
Autocomplete appends the `-input` for us.
> BOAC-2705, Teena wants id='search-students-input' on form element

- src/components/appointment/DropInWaitlistAppointment.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3180
> BOAC-3180, highlight appointments assigned to me

- boac/externals/data_loch.py
- boac/merged/student.py
- src/components/student/SortBy.vue
- tests/test_api/test_cohort_controller.py
- tests/test_api/test_curated_group_controller.py
- tests/test_externals/test_data_loch.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2023
> BOAC-2023: Adds descending sort for cohorts and groups

- src/assets/styles/ckeditor-custom.css
- src/components/appointment/AppointmentDetailsModal.vue
- src/components/appointment/CreateAppointmentModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3200
> BOAC-3200, appointment-details RichTextEditor gets height: 180px

- src/components/util/Autocomplete.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3204
> BOAC-3204, search history: set isOpen false when clickAway

- boac/models/appointment.py
- src/components/search/AppointmentSnippet.vue
- src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3206
https://jira.ets.berkeley.edu/jira/browse/BOAC-3208
Includes BOAC-3208 fix: When search, scroll to top.
> BOAC-3206, if no student in AppointmentSnippet (search) then show SID

- boac/api/notes_controller.py
- boac/api/util.py
- boac/merged/advising_note.py
- requirements.txt
- src/components/student/profile/AcademicTimeline.vue
- src/mixins/Berkeley.vue
- tests/test_api/test_notes_controller.py
- tests/test_merged/test_advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2339
> BOAC-2339 Admins, directors can download zipped notes+attachments

- boac/merged/advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2339
Follow-up to #2290. Notes imported from SIS identify author by CSID only.
> BOAC-2339 Supplemental Calnet advisor info for legacy note download

- boac/externals/data_loch.py
- boac/merged/student.py
- fixtures/loch.sql
- fixtures/loch_student_profile_11667051.json
- fixtures/loch_student_profile_2345678901.json
- fixtures/loch_student_profile_7890123456.json
- src/components/student/SortBy.vue
- tests/test_api/test_cohort_controller.py
- tests/test_api/test_curated_group_controller.py
- tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3054
> BOAC-3054: Adds sort by terms completed for cohorts and groups

- src/components/sidebar/SearchForm.vue
- src/components/util/Autocomplete.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3209
> BOAC-3209, suggestion.label style (optional) allows search history to wrap nicely in dropdown

- src/components/matrix/Matrix.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3097
> BOAC-3097 Clear matrix tooltips on zoom

- boac/api/notes_controller.py
- boac/api/util.py
- boac/merged/advising_note.py
- src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3158
> BOAC-3158 Prefer full Calnet names for advisors where feasible

- src/components/HeaderMenu.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3213
> BOAC-3213, simplified markup in BOA's top nav menu

- src/components/student/SortBy.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3211
> BOAC-3211, css padding tweaks on sort-by dropdown

- src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3217
> BOAC-3217, Sidebar search: if validation error then alert the user

- src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3217
> BOAC-3217, if 'search input required' then scrollToTop, put focus

- src/auth.ts
- src/components/HeaderMenu.vue
- src/router.ts
- src/views/Analytics.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3195
Design Jira: https://jira.ets.berkeley.edu/jira/browse/BOAC-2792
> BOAC-3195, /analytics page for 'directors' has stats per dept

- boac/api/reports_controller.py
- boac/models/development_db.py
- boac/routes.py
- src/api/reports.ts
- src/router.ts
- src/views/Analytics.vue
- tests/test_api/test_reports_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3196
Designs: https://jira.ets.berkeley.edu/jira/browse/BOAC-2792
> BOAC-3196, server-side /api/reports will serve front-end /analytics/:deptCode

- boac/api/user_controller.py
- boac/api/util.py
- boac/models/development_db.py
- boac/models/drop_in_advisor.py
- scripts/db/drop_schema.sql
- scripts/db/migrate/2020/20200113-BOAC-3221/pre_deploy_01_add_drop_in_availability_enum.sql
- scripts/db/schema.sql
- src/api/user.ts
- src/components/appointment/AppointmentAssignModal.vue
- src/components/appointment/CheckInModal.vue
- src/components/appointment/CreateAppointmentModal.vue
- src/components/appointment/DropInAdvisorList.vue
- src/components/appointment/DropInAvailabilityToggle.vue
- src/components/appointment/DropInWaitlist.vue
- src/store/modules/current-user-extras.ts
- src/views/DropInAdvisorHome.vue
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3221
No functional change as yet, but we quietly move our four-valued enum into place behind the scenes.
> BOAC-3221 Expand drop-in advisor status types

- boac/api/reports_controller.py
- boac/models/development_db.py
- boac/models/university_dept_member.py
- src/api/reports.ts
- src/views/Analytics.vue
- tests/test_api/test_cache_utils.py
- tests/test_api/test_reports_controller.py
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3196
Tweak in test data meant updates for `test_cache_utils` and `test_user_controller`
> BOAC-3196, if director of multiple depts or admin then dept dropdown on /analytics page

- boac/api/util.py
- boac/merged/user_session.py
- config/default.py
- tests/test_api/test_appointments_controller.py
- tests/test_api/test_student_controller.py
- tests/test_api/test_topic_controller.py
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3181
> BOAC-3181: Adds setting to enable drop-in advising by department

- boac/api/reports_controller.py
- boac/externals/data_loch.py
- boac/models/note.py
- src/components/HeaderMenu.vue
- src/views/Analytics.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3196
> BOAC-3196, /analytics page: total note count (SIS and BOA), total author count (BOA)

- boac/api/admin_controller.py
- boac/api/reports_controller.py
- boac/merged/reports.py
- boac/models/note.py
- src/components/HeaderMenu.vue
- src/components/admin/Users.vue
- src/views/Analytics.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3196
> BOAC-3196, /analytics page: percentage of notes with attachments, etc.

- boac/api/user_controller.py
- src/api/user.ts
- src/components/appointment/DropInAvailabilityToggle.vue
- src/store/modules/current-user-extras.ts
- src/views/DropInAdvisorHome.vue
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3222
> BOAC-3222 Allow off-duty advisors to toggle waitlist visibility

- boac/api/auth_controller.py
- boac/api/reports_controller.py
- boac/externals/data_loch.py
- boac/merged/reports.py
- src/api/reports.ts
- src/components/admin/Users.vue
- src/components/reports/NotesReport.vue
- src/components/reports/UserReport.vue
- src/mixins/Berkeley.vue
- src/views/Analytics.vue
- tests/test_api/test_reports_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3106
* report on notes created in BOA 
* note count from various note-import jobs
* users report use b-table similar to Pax Manifest
> BOAC-3106, /analytics page has user metrics per dept

- src/components/matrix/MatrixUtil.vue
- src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3228
> BOAC-3228, exceedsMatrixThresholdMessage fix

- src/components/appointment/DropInAdvisorList.vue
- src/components/appointment/DropInAvailabilityToggle.vue
- src/components/appointment/DropInWaitlist.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3223
Design revision in https://jira.ets.berkeley.edu/jira/browse/BOAC-3227.
> BOAC-3223 Revise appearance of drop-in status toggle

- src/views/DropInAdvisorHome.vue
- src/views/DropInDesk.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3226
The job is also cleared when `hideDropInWaitlist`.
> BOAC-3226, clear loadDropInWaitlist job on-destory of view component

- fixtures/loch.sql
- fixtures/loch_student_profile_5678901234.json
- fixtures/loch_student_profile_8901234567.json
- fixtures/loch_student_profile_890127492.json
- fixtures/loch_student_profile_9000000000.json
- fixtures/loch_student_profile_9100000000.json
- src/components/student/SortBy.vue
- src/components/student/StudentRow.vue
- tests/test_api/test_cohort_controller.py
- tests/test_api/test_curated_group_controller.py
Plus a DESC sort option.
https://jira.ets.berkeley.edu/jira/browse/BOAC-3054
> BOAC-3054: Adds terms in attendance to list views

- boac/merged/student.py
- tests/test_api/test_cohort_controller.py
- tests/test_api/test_curated_group_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2023
> BOAC-2023: Sorts null term GPAs last regardless of sort direction

- boac/merged/student.py
- boac/models/appointment.py
- boac/models/development_db.py
- tests/test_api/test_search_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3176
> BOAC-3176: Makes search work on inactive student appointments

- boac/api/appointments_controller.py
- boac/models/appointment.py
- boac/models/appointment_event.py
- boac/models/development_db.py
- scripts/db/drop_schema.sql
- scripts/db/migrate/2020/20200116-BOAC-3238/pre_deploy_01_add_appointment_event_advisor_id.sql
- scripts/db/schema.sql
- src/api/appointments.ts
- src/components/appointment/AdvisingAppointment.vue
- src/components/appointment/CheckInModal.vue
- src/components/appointment/CreateAppointmentModal.vue
- src/components/appointment/DropInAppointmentDropdown.vue
- src/components/appointment/DropInWaitlist.vue
- src/components/appointment/DropInWaitlistAppointment.vue
- tests/test_api/test_appointments_controller.py
- tests/test_api/test_search_controller.py
- tests/util.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3238
> BOAC-3238 Standardize representation of appointment status and events

- boac/api/user_controller.py
- boac/models/appointment.py
- src/components/appointment/DropInAdvisorList.vue
- src/components/appointment/DropInAvailabilityToggle.vue
- src/components/appointment/DropInWaitlist.vue
- src/mixins/Util.vue
- src/views/DropInDesk.vue
- tests/test_api/test_appointments_controller.py
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3154
> BOAC-3154 Unreserve appointments when advisor goes off duty

- boac/merged/advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3236
> BOAC-3236 Adjust dates in CSV export to app timezone

- boac/merged/advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3235
> BOAC-3235 Add numeric suffixes to dupe attachment filenames

- src/components/course/CourseStudents.vue
- src/components/student/StudentRow.vue
- src/components/student/profile/StudentProfileHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3122
> BOAC-3122: Adds graduation indicator on class, cohort, group, student

- boac/api/util.py
- fixtures/loch_student_profile_11667051.json
- fixtures/loch_student_profile_2345678901.json
- fixtures/loch_student_profile_3456789012.json
- fixtures/loch_student_profile_5678901234.json
- fixtures/loch_student_profile_7890123456.json
- fixtures/loch_student_profile_8901234567.json
- fixtures/loch_student_profile_890127492.json
- fixtures/loch_student_profile_9000000000.json
- fixtures/loch_student_profile_9100000000.json
- tests/test_api/test_cohort_controller.py
- tests/test_api/test_curated_group_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3183
> BOAC-3183: Replaces career status with plan status in CSV

- boac/merged/student.py
- fixtures/loch.sql
- tests/test_api/test_cohort_controller.py
- tests/test_api/test_curated_group_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3054
> BOAC-3054: Sorts out null handling when sorting cohorts, groups

- src/main.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-3145
> BOAC-3145 Handle server 401s by redirecting to login page

- src/components/admin/MyProfile.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3256
More work to come on these roles, but this display fix can go in separately.
> BOAC-3256 Rework drop-in status toggle on settings page

- boac/externals/data_loch.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3098
> BOAC-3098, get_sis_note_attachments: priority given to is_historical=FALSE (per SID, note_id)

- src/components/reports/NotesReport.vue
- src/components/reports/UserReport.vue
- src/views/Analytics.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3281
https://jira.ets.berkeley.edu/jira/browse/BOAC-3286
> BOAC-3281, clean up 'Flight Data Recorder' layout and header structure

- src/views/Analytics.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3287
> BOAC-3287, FDR gives 404 if you're unauth to view requested dept

- boac/merged/reports.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3288
> BOAC-3288, fix note_count_per_user query (FDR view)

- boac/api/user_controller.py
- boac/api/util.py
- boac/merged/user_session.py
- boac/models/authorized_user.py
- boac/models/drop_in_advisor.py
- scripts/db/migrate/2020/20200124-BOAC-3255/pre_deploy_01_drop_drop_in_deleted_at.sql
- scripts/db/schema.sql
- src/api/user.ts
- src/auth.ts
- src/components/admin/DropInAdvisingToggle.vue
- src/components/admin/MyProfile.vue
- src/router.ts
- src/store/modules/current-user-extras.ts
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3268
> BOAC-3268: Switches drop-in advisor soft delete to a hard delete

- boac/models/curated_group.py
- src/api/curated.ts
- src/core.ts
- src/store/modules/current-user-extras.ts
- tests/test_api/api_test_utils.py
- tests/test_api/test_cohort_controller.py
- tests/test_api/test_curated_group_controller.py
- tests/test_api/test_search_controller.py
- tests/test_merged/test_student.py
- tests/test_models/test_cohort_filter.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3252
Some "entropy reduction" in tests, too.
> BOAC-3252, If curated group modified then update student-count and SIDs of referencing cohorts

- boac/models/authorized_user.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3300
> BOAC-3300 Remove stray refs to drop-in soft delete

- boac/api/curated_group_controller.py
- boac/models/curated_group.py
- src/components/curated/CuratedGroupHeader.vue
- src/main.ts
- src/mixins/CuratedEditSession.vue
- src/store/modules/curated-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-3248
> BOAC-3248, do not allow curated group deletion until user has detached the referencing cohorts

- boac/merged/reports.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3299
> BOAC-3299, /reports: attachment % is based on DISTINCT a.note_id

- boac/models/authorized_user.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3265
> BOAC-3265: Updates user query per new roles

- src/components/curated/CuratedGroupHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3248
> BOAC-3248, tweak wording in delete curated group modal

- src/components/appointment/CreateAppointmentModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3297
> BOAC-3297 Fix reference to available advisors list

- src/components/cohort/FilterRow.vue
- src/components/curated/CuratedGroupHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3305
https://jira.ets.berkeley.edu/jira/browse/BOAC-3304
> BOAC-3305, informational text on /curated page: '...used as a filter in cohort...'

- boac/api/util.py
- src/api/user.ts
- src/components/appointment/DropInAdvisorList.vue
- src/components/appointment/DropInAvailabilityToggle.vue
- src/components/appointment/DropInWaitlist.vue
- src/store/modules/current-user-extras.ts
- src/views/DropInAdvisorHome.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3270
> BOAC-3270 Drop-in status: front end

- boac/api/user_controller.py
- src/api/user.ts
- src/components/admin/EditUserProfileModal.vue
- src/components/cohort/FilterRow.vue
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3303
> BOAC-3303, remove the 'Advisor + Drop In' option; remove drop_in_advisor if role='scheduler'

- src/components/appointment/CreateAppointmentModal.vue
- src/components/appointment/DropInWaitlist.vue
- src/views/DropInAdvisorHome.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3094
If current-user is an advisor and on-duty then his/her name will show up in the (optional) advisor dropdown.
> BOAC-3094, drop-in home: assign appointment at creation-time

- boac/api/user_controller.py
- boac/models/appointment.py
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3254
> BOAC-3254: Unreserve appointments when advisor stops doing drop-ins

- boac/api/appointments_controller.py
- boac/models/appointment.py
- src/assets/styles/bootstrap-overrides.css
- src/assets/styles/ckeditor-custom.css
- src/components/appointment/AdvisingAppointment.vue
- src/components/appointment/AppointmentStudentPill.vue
- src/components/appointment/DropInWaitlist.vue
- src/components/appointment/LogResolvedIssueModal.vue
- src/views/DropInDesk.vue
- tests/test_api/test_appointments_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3298
> BOAC-3298 Scheduler can Log Resolved Issue

- boac/externals/data_loch.py
- boac/merged/cohort_filter_options.py
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3201
Also, if user selects "All" then the top-level filter menu is immediately disabled.
> BOAC-3201, cohort filter: 'All' option for visaTypes

- src/components/appointment/DropInWaitlist.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3308
Sample screenshots are in the Jira. Review with `?w=1`
> BOAC-3308, tidy up drop-in-waitlist UX on advisor homepage

- boac/merged/cohort_filter_options.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3310
> BOAC-3310, cohort with curated-group filter viewable by others

- package-lock.json
- src/auth.ts
- src/router.ts
- src/views/AdmitStudent.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3234
> BOAC-3234, limit access to /admit/student/:id (requires admin or CE3)

- boac/api/cache_utils.py
- boac/api/cohort_controller.py
- boac/models/cohort_filter.py
- boac/models/curated_group.py
- tests/test_api/api_test_utils.py
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3276
https://jira.ets.berkeley.edu/jira/browse/BOAC-3277
> BOAC-3276 BOAC-3277 Cohort membership diff and history API

- src/components/appointment/DropInWaitlist.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3320
> BOAC-3320 CSS fixes for drop-in status

- boac/api/cohort_controller.py
- boac/api/config_controller.py
- boac/api/util.py
- boac/merged/cohort_filter_options.py
- boac/models/cohort_filter.py
- boac/models/development_db.py
- config/default.py
- requirements.txt
- scripts/db/drop_schema.sql
- scripts/db/migrate/2020/20200204-BOAC-3325/pre_deploy_01_cohort_types_enum.sql
- scripts/db/schema.sql
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3321
Also added config `FEATURE_FLAG_ADMITTED_STUDENTS`.
> BOAC-3321, add 'domain' property to cohort object; filter-options per domain

- boac/models/cohort_filter.py
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3337
> BOAC-3337 Track membership changes on cohort filter updates

- boac/api/cohort_controller.py
- src/api/cohort.ts
- src/components/sidebar/MyAdmitCohorts.vue
- src/components/sidebar/Sidebar.vue
- src/components/util/NavLink.vue
- src/mixins/CurrentUserExtras.vue
- src/store/modules/cohort-edit-session.ts
- src/store/modules/current-user-extras.ts
- src/views/AllCohorts.vue
- src/views/Cohort.vue
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3326
https://jira.ets.berkeley.edu/jira/browse/BOAC-3338
> BOAC-3326, front-end > cohort API and store are cohort.domain-sensitive

- boac/models/cohort_filter.py
- src/components/cohort/AdmitStudentRow.vue
- src/components/cohort/CohortPageHeader.vue
- src/components/sidebar/MyAdmitCohorts.vue
- src/components/util/NavLink.vue
- src/mixins/CohortEditSession.vue
- src/store/modules/cohort-edit-session.ts
- src/store/modules/current-user-extras.ts
- src/views/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3326
> BOAC-3326, /cohort UX varies per domain type; vuex store is domain-sensitive

- boac/merged/cohort_filter_option_utils.py
- boac/merged/cohort_filter_options.py
- boac/models/cohort_filter.py
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3321
The `dict` in `cohort_filter_options.py` finally hit the tipping point.
> BOAC-3321, additional CE3 filter options; less code duplication in cohort_filter_options.py

- boac/api/cohort_controller.py
- boac/models/cohort_filter_event.py
- src/api/cohort.ts
- src/components/cohort/CohortHistory.vue
- src/components/cohort/CohortPageHeader.vue
- src/mixins/Scrollable.vue
- src/views/Cohort.vue
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3278
https://jira.ets.berkeley.edu/jira/browse/BOAC-3279
> BOAC-3278 BOAC-3279 Cohort history front end

- boac/api/cohort_controller.py
- src/components/cohort/CohortHistory.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3341
> BOAC-3341 Cohort history: include historical students, handle gaps

- src/components/student/profile/StudentProfileHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3350
> BOAC-3350 Student profile: fix degree heading CSS

- boac/api/cohort_controller.py
- boac/models/cohort_filter.py
- src/components/cohort/CohortPageHeader.vue
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3343
> BOAC-3343, 'admitted_students' cohorts live in the present, no history

- boac/api/cohort_controller.py
- boac/merged/cohort_filter_options.py
- src/components/cohort/CohortPageHeader.vue
- src/components/curated/CuratedGroupHeader.vue
- src/components/util/ExportListModal.vue
- src/mixins/Berkeley.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3344
Answers to my reqts questions in https://jira.ets.berkeley.edu/jira/browse/BOAC-3351  will lead to a bit more tweaking.
> BOAC-3344, cohort-export feature is sensitive to 'domain' (eg, admitted_students)

- src/views/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3336
> BOAC-3336 Ensure unique keys for cohort filter rows

- src/components/appointment/DropInWaitlist.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3320
> BOAC-3320 CSS fix: drop-in status clear button

- boac/api/admit_controller.py
- boac/api/util.py
- boac/externals/data_loch.py
- boac/merged/admitted_student.py
- boac/models/development_db.py
- boac/routes.py
- config/default.py
- fixtures/loch.sql
- tests/test_api/test_admit_controller.py
- tests/test_externals/test_data_loch.py
- tests/test_merged/test_admitted_student.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3331
> BOAC-3331: Provides admit data by SID to UI

- boac/__init__.py
> NOJIRA Bump BOA to 4.3

- boac/merged/cohort_filter_options.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3353
> BOAC-3353 Allow 'all types' cohort filters to be edited

- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3355
> BOAC-3355 Fix intermittent test failure

- src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3339
> BOAC-3339 Don't let curated group edit modes loiter around the store

- src/components/admin/MyProfile.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3371
> BOAC-3371: Hides drop-in toggle from schedulers

- src/components/admin/MyProfile.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3371
master PR: #2385
> [QA] BOAC-3371: Hides drop-in toggle from schedulers

- src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3376
> BOAC-3376: Prevents competing event listeners on Curated Groups

- src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3376
master PR #2390
> [QA] BOAC-3376: Prevents competing event listeners on Curated Groups

- src/components/appointment/AppointmentAssignModal.vue
- src/components/appointment/CheckInModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3393
QA version of #2392.
> [QA] BOAC-3393 Demo-mode blur on drop-in advising modals

- src/components/appointment/AppointmentAssignModal.vue
- src/components/appointment/CheckInModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3393
> BOAC-3393 Demo-mode blur on drop-in advising modals

- boac/api/user_controller.py
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3388
https://jira.ets.berkeley.edu/jira/browse/BOAC-3390
> BOAC-3388 BOAC-3390 Back end for drop-in scheduler management

- boac/api/search_controller.py
- boac/externals/data_loch.py
- boac/merged/admitted_student.py
- tests/test_api/test_search_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3349
> BOAC-3349: API for searching admits

- boac/api/user_controller.py
- src/api/user.ts
- src/components/admin/DemoModeToggle.vue
- src/components/admin/DropInSchedulerManagement.vue
- src/components/admin/RemoveDropInSchedulerModal.vue
- src/components/util/Autocomplete.vue
- src/views/Admin.vue
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3389
https://jira.ets.berkeley.edu/jira/browse/BOAC-3391
https://jira.ets.berkeley.edu/jira/browse/BOAC-3392
Designs in https://jira.ets.berkeley.edu/jira/browse/BOAC-3274.
> BOAC-3389 BOAC-3391 BOAC-3392 Scheduler management: front end

- src/components/admin/DropInSchedulerManagement.vue
- src/components/admin/RemoveDropInSchedulerModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3389
Follow-up to #2396.
> BOAC-3389 Follow-up blurring for demo mode

- src/components/cohort/CohortHistory.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3398
> BOAC-3398 Blur cohort history SIDs in demo mode

- src/components/admin/DropInSchedulerManagement.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3389
> BOAC-3389 Get rando attribute out of the scheduler management template

- boac/externals/data_loch.py
- boac/merged/admitted_student.py
- fixtures/loch.sql
- src/views/AdmitStudent.vue
- tests/test_api/test_search_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3349
> BOAC-3349: adds/updates admit data elements

- src/components/appointment/DropInWaitlist.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3264
> BOAC-3264 Available advisor list on drop-in advisor homepage

- boac/merged/admitted_student.py
- src/api/search.ts
- src/components/sidebar/SearchForm.vue
- src/components/sidebar/Sidebar.vue
- src/core.ts
- src/mixins/Util.vue
- src/views/Search.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3346
> BOAC-3349: Adds option to search admits

- boac/api/search_controller.py
- boac/merged/admitted_student.py
- src/api/search.ts
- src/components/search/SortableAdmits.vue
- src/views/Search.vue
- tests/test_api/test_search_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3347
> BOAC-3347: Displays first 50 admit search results

- package-lock.json
- package.json
- src/main.ts
- src/views/AdmitStudent.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3403
> BOAC-3403: Removes icons on admit profile

- boac/api/cohort_controller.py
- boac/externals/data_loch.py
- boac/lib/cohort_utils.py
- boac/merged/admitted_student.py
- boac/merged/cohort_filter_options.py
- boac/merged/student.py
- boac/models/cohort_filter.py
- fixtures/loch.sql
- tests/test_models/test_cohort_filter.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3409
> BOAC-3409: Adapts admit cohort filters to real data

- boac/api/user_controller.py
- boac/models/authorized_user.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3411
> BOAC-3411 Don't block removed schedulers

- src/views/AdmitStudent.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3404
Also, table stripes for readability.
> BOAC-3404: Adds int'l status, etc to admit page

- boac/models/alert.py
- tests/test_models/test_alert.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3100
> BOAC-3100 Alerts with static messaging shouldn't record daily updates

- src/components/admit/AdmitStudentRow.vue
- src/views/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3374
> BOAC-3374: Puts first name first when sorting by first_name

- boac/api/cache_utils.py
- boac/api/cohort_controller.py
- boac/merged/advising_note.py
- boac/models/authorized_user.py
- boac/models/cohort_filter.py
- boac/models/curated_group.py
- boac/models/db_relationships.py
- boac/models/development_db.py
- scripts/db/drop_schema.sql
- scripts/db/migrate/2020/20200227-BOAC-3334/post_deploy_01_drop_cohort_filter_owners.sql
- scripts/db/migrate/2020/20200227-BOAC-3334/pre_deploy_01_add_cohort_filters_owner_id.sql
- scripts/db/schema.sql
- src/store/modules/cohort-edit-session.ts
- tests/test_api/api_test_utils.py
- tests/test_api/test_cohort_controller.py
- tests/test_models/test_authorized_user.py
- tests/test_models/test_cohort_filter.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3334
> BOAC-3334 So long, cohort_filter_owners

- boac/externals/data_loch.py
- boac/merged/admitted_student.py
- src/components/admit/AdmitDataWarning.vue
- src/views/AdmitStudent.vue
- src/views/Cohort.vue
- tests/test_merged/test_admitted_student.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3395
> BOAC-3395: Displays warning when admit data is stale

- boac/models/cohort_filter.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3419
> BOAC-3419 Fix UREM cohort filter

- boac/merged/admitted_student.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3420
> BOAC-3420 Admit cohorts: ensure student count returned even when no results

- boac/externals/data_loch.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3423
> BOAC-3423 Admit cohorts: adjust first_generation_college query

- src/views/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3425
> BOAC-3425 Back button from admit page preserves cohort filters

- src/auth.ts
- src/components/sidebar/Sidebar.vue
- src/core.ts
- src/mixins/CurrentUserExtras.vue
- src/store/modules/current-user-extras.ts
- src/views/Cohort.vue
PR:  https://jira.ets.berkeley.edu/jira/browse/BOAC-3408
> BOAC-3408: Prevents admit cohort API call when not authorized

- boac/api/cohort_controller.py
- boac/api/util.py
- boac/externals/data_loch.py
- src/components/cohort/CohortPageHeader.vue
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3424
> BOAC-3424 CSV export for admit cohorts

- src/views/AdmitStudent.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3417
> BOAC-3417: Solves Y2K bug in CE3 data

- src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3432
> BOAC-3432 Keep search checkboxes checked by default

- boac/merged/admitted_student.py
- src/components/admit/AdmitStudentRow.vue
- src/components/admit/SortableAdmits.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3433
https://jira.ets.berkeley.edu/jira/browse/BOAC-3434
> BOAC-3433 BOAC-3434 Residency category in admit cohorts and search results

- src/components/cohort/CohortPageHeader.vue
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3441
> BOAC-3441 Exclude email addresses from admit cohort CSV export

- src/components/cohort/FilterRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3430
> BOAC-3430: Validates against non-integer dependents

- boac/merged/admitted_student.py
- src/components/admit/SortableAdmits.vue
- tests/test_api/test_search_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3436
> BOAC-3436 Fix first generation college field in admit search results

- boac/merged/admitted_student.py
- src/views/Search.vue
PR:  https://jira.ets.berkeley.edu/jira/browse/BOAC-3435
> BOAC-3435: Adds last updated warning to admit search results

- src/components/admit/AdmitStudentRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3443
> BOAC-3443: Fixes demo mode bug on CE3 cohorts

- boac/api/search_controller.py
- boac/externals/data_loch.py
- boac/merged/admitted_student.py
- src/components/admit/AdmitStudentRow.vue
- src/components/admit/SortableAdmits.vue
- tests/test_api/test_search_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3438
> BOAC-3438: Improves admit name search

- src/views/AdmitStudent.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3443
> BOAC-3443: Blurs admit name in student profile link

- boac/api/admit_controller.py
- src/api/admit.ts
- src/components/sidebar/MyAdmitCohorts.vue
- src/router.ts
- src/views/AdmitStudent.vue
- src/views/AdmitStudents.vue
- tests/test_api/test_admit_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3426
> BOAC-3426: Allows user to view unfiltered list of admits

- src/components/admit/AdmitStudentRow.vue
- src/components/cohort/ApplyAndSaveButtons.vue
- src/components/cohort/CohortPageHeader.vue
- src/store/modules/cohort-edit-session.ts
- src/views/AdmitStudents.vue
- src/views/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3450
> BOAC-3450: Improves SR text on CE3 pages

- src/views/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3487
> BOAC-3487 SectionSpinner, get out of that div, it's not your home

- src/views/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3487
QA version of #2442.
> [QA] BOAC-3487 SectionSpinner, get out of that div, it's not your home

- src/mixins/Util.vue
- src/views/Search.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3488
> BOAC-3488 Fix handling of boolean search params

- src/mixins/Util.vue
- src/views/Search.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3488
QA version of #2444.
> [QA] BOAC-3488 Fix handling of boolean search params

- src/components/student/profile/StudentPersonalDetails.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3493
> BOAC-3493 Blur alternate email in demo mode

- src/components/student/profile/StudentPersonalDetails.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3493
QA version of #2446.
> [QA] BOAC-3493 Blur alternate email in demo mode

- boac/api/appointments_controller.py
- boac/models/appointment.py
- scripts/db/drop_schema.sql
- scripts/db/migrate/2020/20200319-BOAC-3477/pre_deploy_01_update_appointments.sql
- scripts/db/schema.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-3477
> BOAC-3477 Expand appointments model/table to cover scheduled appts

- boac/merged/student.py
- fixtures/loch_student_profile_7890123456.json
- src/components/student/profile/StudentPersonalDetails.vue
- tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3452
> BOAC-3452: Displays name and email for generic Haas advisor

- requirements.txt
https://jira.ets.berkeley.edu/jira/browse/NS-808
Nothing urgent, just housekeeping.
> NS-808 Update database libraries

- boac/api/user_controller.py
- boac/models/appointment_availability.py
- scripts/db/drop_schema.sql
- scripts/db/migrate/2020/20200320-BOAC-3479/pre_deploy_01_add_same_day_tables.sql
- scripts/db/migrate/2020/20200323-BOAC-3482/pre_deploy_01_rds_add_appointment_availability.sql
- scripts/db/schema.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-3482
Logic in progress; also some fixes to the SameDayAdvisor entity. Validation, tests, etcetera to follow.
> BOAC-3482 Appointment availability table, model

- scripts/db/migrate/2020/20200320-BOAC-3479/pre_deploy_01_add_same_day_tables.sql
- scripts/db/migrate/2020/20200323-BOAC-3482/pre_deploy_01_add_appointment_availability.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-3482
It's app_boa's world now.
> BOAC-3482 Update ownership in migration scripts

- boac/models/appointment_availability.py
- tests/test_models/test_appointment_availability.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3482
> BOAC-3482 Appointment availability: validation and tests

- boac/merged/student.py
- fixtures/loch_student_profile_7890123456.json
- src/components/student/profile/StudentPersonalDetails.vue
- tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3452
> BOAC-3452: Displays plan and title for generic Haas advisor

- boac/api/appointments_controller.py
- boac/models/appointment_availability.py
- config/default.py
- tests/test_api/test_appointments_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3483
> BOAC-3483 API feed for appointment openings

- boac/api/util.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3496
All this course and enrollment parsing has been happening in Nessie-land for quite a while now.
> BOAC-3496 Remove dead code

- requirements.txt
https://jira.ets.berkeley.edu/jira/browse/NS-808
Reverts #2454.
> NS-808 Revert database library upgrades

- boac/api/util.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3510
> BOAC-3510 Don't blow up sorting missing names

- boac/api/util.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3510
QA version of #2463.
> [QA] BOAC-3510 Don't blow up sorting missing names

- src/components/util/NavLink.vue
- src/views/AdmitStudents.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3472
> BOAC-3472 Allow NavLink to receive URL counter from parent component

- boac/api/cache_utils.py
- boac/api/user_controller.py
- boac/externals/data_loch.py
- boac/models/authorized_user.py
- boac/models/development_db.py
- boac/models/university_dept.py
- fixtures/loch.sql
- scripts/db/migrate/2020/20200407-BOAC-3442/pre_deploy_01_alter_authorized_users_add_can_access_advising_data.sql
- scripts/db/schema.sql
- tests/test_api/test_cache_utils.py
- tests/test_externals/test_data_loch.py
- tests/test_models/test_authorized_user.py
- tests/test_models/test_university_dept.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3512
> BOAC-3512: Identifies and flags users for a notes-free experience

- src/components/util/NavLink.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3522
> BOAC-3522 Vue prop with default should not be required

- boac/api/appointments_controller.py
- boac/api/note_templates_controller.py
- boac/api/notes_controller.py
- boac/api/topic_controller.py
- boac/api/user_controller.py
- boac/api/util.py
- boac/merged/advising_appointment.py
- boac/merged/advising_note.py
- boac/merged/user_session.py
- boac/models/development_db.py
- fixtures/loch.sql
- tests/test_api/test_appointments_controller.py
- tests/test_api/test_cache_utils.py
- tests/test_api/test_note_templates_controller.py
- tests/test_api/test_notes_controller.py
- tests/test_api/test_topic_controller.py
- tests/test_api/test_user_controller.py
- tests/test_externals/test_data_loch.py
- tests/test_models/test_university_dept.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3514
Another PR for blocking requests from the UI is forthcoming.
> BOAC-3514: Secures endpoints against user without advising data access

- .ebextensions/00_ami.config
- .ebextensions/10_upgrade_pip.config
- requirements.txt
https://jira.ets.berkeley.edu/jira/browse/BOAC-3523
> BOAC-3523 Upgrade database dependencies

- src/views/AdmitStudent.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3494
> BOAC-3494 Scroll to top on admit page load

- boac/api/user_controller.py
- boac/models/authorized_user.py
- fixtures/calnet_search_entries.json
- package-lock.json
- package.json
- src/components/admin/EditUserProfileModal.vue
- src/components/admin/MyProfile.vue
- src/components/admin/Users.vue
- src/main.ts
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3514
> BOAC-3514: Updates pax manifest to manage user without advising data access

- boac/api/search_controller.py
- boac/api/util.py
- src/components/admin/MyProfile.vue
- src/components/sidebar/SearchForm.vue
- src/components/sidebar/Sidebar.vue
- src/components/student/profile/AcademicTimeline.vue
- src/views/Admin.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3514
> BOAC-3514: Hides note & appt features from user without advising data access

- boac/externals/data_loch.py
- tests/test_api/test_cache_utils.py
- tests/test_externals/test_data_loch.py
- tests/test_models/test_university_dept.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3514
> BOAC-3514: Ensures user without note/appt access also sees no Canvas data

- boac/api/appointments_controller.py
- boac/models/appointment_read.py
- scripts/db/migrate/2020/20200407-BOAC-3442/pre_deploy_02_alter_appointment_read_set_appointments_id_type.sql
- scripts/db/schema.sql
- tests/test_api/test_appointments_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3505
`AppointmentRead` will work for both BOA appointments and imported SIS appointments, similar to how `NoteRead` does.
> BOAC-3505: Preps AppointmentRead to handle SIS appointments with string IDs

- package.json
https://jira.ets.berkeley.edu/jira/browse/BOAC-3527
> BOAC-3527: Locks down @apollographql/apollo-tools version

- buildspec.yml
https://jira.ets.berkeley.edu/jira/browse/BOAC-3521
Reverting PR #2482
> Revert --> BOAC-3521, force AWS CodeBuild failure to test Slack integration

- boac/api/notes_controller.py
- boac/merged/advising_note.py
- boac/models/note.py
- tests/conftest.py
- tests/test_api/test_appointments_controller.py
- tests/test_api/test_notes_controller.py
- tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3498
> BOAC-3498: Includes BOA note authors in advisor search filter autocomplete

- babel.config.js
- package-lock.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/BOAC-3515
> BOAC-3515: Upgrades @vue/cli, forces safe version of minimist

- boac/externals/data_loch.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3537
> BOAC-3537 Friends don't let friends surface blank options in cohort filter menus

- boac/api/user_controller.py
- fixtures/loch.sql
- tests/test_api/test_curated_group_controller.py
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3057
> BOAC-3057: Reduces redundancy in pax manifest export

- boac/externals/data_loch.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3537
QA version of #2488.
> [QA] BOAC-3537 Friends don't let friends surface blank options in cohort filter menus

- boac/api/appointments_controller.py
- boac/api/notes_controller.py
- boac/api/search_controller.py
- boac/merged/advising_appointment.py
- boac/merged/advising_note.py
- boac/models/appointment.py
- boac/models/note.py
- scripts/db/drop_schema.sql
- scripts/db/migrate/2020/20200427-BOAC-3540/pre_deploy_01_create_note_appointment_advisor_index.sql
- scripts/db/schema.sql
- src/api/appointments.ts
- src/api/notes.ts
- src/api/search.ts
- src/components/sidebar/SearchForm.vue
- src/components/util/Autocomplete.vue
- tests/test_api/test_appointments_controller.py
- tests/test_api/test_notes_controller.py
- tests/test_api/test_search_controller.py
- tests/test_merged/test_advising_appointment.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3542
> BOAC-3542: Adds advisor index view, refactors advisor autocomplete

- boac/api/appointments_controller.py
- boac/api/notes_controller.py
- boac/api/search_controller.py
- boac/merged/advising_appointment.py
- boac/merged/advising_note.py
- boac/models/appointment.py
- boac/models/note.py
- scripts/db/drop_schema.sql
- scripts/db/migrate/2020/20200427-BOAC-3540/pre_deploy_01_create_note_appointment_advisor_index.sql
- scripts/db/schema.sql
- src/api/appointments.ts
- src/api/notes.ts
- src/api/search.ts
- src/components/sidebar/SearchForm.vue
- src/components/util/Autocomplete.vue
- tests/test_api/test_appointments_controller.py
- tests/test_api/test_notes_controller.py
- tests/test_api/test_search_controller.py
- tests/test_merged/test_advising_appointment.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3542
master PR is #2493
> [QA] BOAC-3542: Adds advisor index view, refactors advisor autocomplete

- boac/api/search_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3545
> [QA] BOAC-3545: Includes SID in advisors feed when available

- boac/api/search_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3545
QA PR is #2495
> BOAC-3545: Includes SID in advisors feed when available

- boac/api/cache_utils.py
- boac/api/cohort_controller.py
- boac/api/note_templates_controller.py
- boac/api/student_controller.py
- boac/api/user_controller.py
- boac/externals/data_loch.py
- boac/merged/admitted_student.py
- boac/merged/advising_note.py
- boac/merged/student.py
- boac/models/appointment.py
- boac/models/authorized_user.py
- boac/models/cohort_filter.py
- boac/models/curated_group.py
- requirements.txt
- scripts/db/migrate/2018/20180809-BOAC-1147/create_my_students_cohort_per_uid.py
- tests/conftest.py
- tests/test_api/test_admin_controller.py
- tests/test_api/test_appointments_controller.py
- tests/test_api/test_note_templates_controller.py
- tests/test_api/test_notes_controller.py
- tests/test_api/test_reports_controller.py
- tests/test_api/test_user_controller.py
- tox.ini
> NOJIRA, flake8 upgrade; fix various F541 f-string violations

- .ebextensions/01_create_apache_conf.config
https://jira.ets.berkeley.edu/jira/browse/BOAC-3558
Ops asked for this change; see Jira for details.
> BOAC-3558: Updates apache SSL settings

- .ebextensions/00_ami.config
https://jira.ets.berkeley.edu/jira/browse/BOAC-3567
> [QA] BOAC-3567: Updates SSL cert

- .ebextensions/00_ami.config
https://jira.ets.berkeley.edu/jira/browse/BOAC-3567
QA PR is #2500
> BOAC-3567: Updates SSL cert

- buildspec.yml
https://jira.ets.berkeley.edu/jira/browse/BOAC-3571
> BOAC-3571 Update buildspec runtime

- package-lock.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/BOAC-3518
https://jira.ets.berkeley.edu/jira/browse/BOAC-3584
> BOAC-3518 BOAC-3584 Upgrade Node dependecies

- boac/externals/data_loch.py
- fixtures/loch.sql
- tests/test_api/test_search_controller.py
- tests/test_externals/test_data_loch.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3578
> BOAC-3578: Includes Data Science notes in search results

- .ebextensions/00_ami.config
https://jira.ets.berkeley.edu/jira/browse/BOAC-3581
> BOAC-3581 Restrict ALB listener to TLS 1.2

- boac/merged/advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3582
> BOAC-3582: Suppresses empty topics on Data Science notes

- boac/merged/advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3582
master PR #2512
> [QA] BOAC-3582: Suppresses empty topics on Data Science notes

- package-lock.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/BOAC-3573
> BOAC-3573 Update vue-cli

- src/components/note/AdvisingNoteAttachments.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3583
> BOAC-3583: Changes text to reflect limitations of file upload widget

- boac/models/appointment.py
- tests/test_merged/test_advising_appointment.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3588
Travis points to the sky, like, none shall pass.
> BOAC-3588 Fix test failure; nail down appts order in feed

- boac/externals/calnet.py
- boac/merged/calnet.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3580
> BOAC-3580 Remove fallback to deprecated CalNet attributes

- boac/models/alert.py
- scripts/db/drop_schema.sql
- scripts/db/migrate/2020/20200714-BOAC-3594/pre_deploy_01_alert_alerts_unique_constraint.sql
- scripts/db/schema.sql
- tests/test_models/test_alert.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3594
https://jira.ets.berkeley.edu/jira/browse/BOAC-3595
> BOAC-3594 BOAC-3595 Updates to alert refresh logic

- boac/externals/data_loch.py
- fixtures/loch.sql
- tests/test_api/test_search_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3544
> BOAC-3544 Switch note/appointment search queries to unified profile index

- src/components/student/profile/StudentProfileHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3592
> BOAC-3592 Show subplans in student profile header

- src/components/note/AdvisingNote.vue
- src/components/note/AdvisingNoteAttachments.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3606
> BOAC-3606: Fixes attachment upload error/infinite loop

- src/components/student/profile/StudentProfileHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3592
> BOAC-3592 No subplan header if no subplans

- boac/api/util.py
- boac/externals/data_loch.py
- boac/merged/student.py
- fixtures/loch.sql
- src/components/student/StudentRow.vue
- src/components/student/profile/StudentAcademicStanding.vue
- src/components/student/profile/StudentClasses.vue
- src/components/student/profile/StudentProfileHeader.vue
- src/mixins/Berkeley.vue
- tests/test_api/test_cohort_controller.py
- tests/test_api/test_course_controller.py
- tests/test_api/test_curated_group_controller.py
- tests/test_api/test_search_controller.py
- tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3607
> BOAC-3607 Display academic standing in cohorts and profiles

- src/components/note/AdvisingNoteAttachments.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3612
> BOAC-3612: Just kidding; this time actully fixes attachment upload bug

- src/components/note/AdvisingNoteAttachments.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3612
Master PR #2533
> [QA] BOAC-3612: Just kidding; this time actully fixes attachment upload bug

- boac/api/notes_controller.py
- boac/models/note.py
- src/api/notes.ts
- src/components/note/create/CreateNoteModal.vue
- src/mixins/NoteEditSession.vue
- src/store/modules/note-edit-session.ts
- tests/test_api/test_notes_controller.py
- tests/test_api/test_search_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3614
A single endpoint for both single and batch note creation. Less code and faster create.
> BOAC-3614, improve create-note perf by using bulk-create for all

- boac/api/search_controller.py
- boac/externals/data_loch.py
- boac/merged/sis_sections.py
- fixtures/loch_sis_section_2168_18309.csv
- fixtures/loch_sis_section_2178_90100.csv
- fixtures/loch_sis_section_2178_90200.csv
- requirements.txt
- src/views/Course.vue
- tests/test_api/test_course_controller.py
- tests/test_api/test_search_controller.py
- tests/test_merged/test_sis_sections.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3605
Follows Nessie work: https://github.com/ets-berkeley-edu/nessie/pull/729
> BOAC-3605, surface instruction-mode in BOA

- boac/api/config_controller.py
- boac/externals/data_loch.py
- boac/lib/berkeley.py
- boac/lib/cohort_utils.py
- boac/merged/cohort_filter_options.py
- boac/merged/student.py
- boac/models/cohort_filter.py
- src/components/student/profile/StudentAcademicStanding.vue
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3315
> BOAC-3315, cohort filter: Academic Status

- boac/models/alert.py
- tests/test_api/test_alerts_controller.py
- tests/test_api/test_cache_utils.py
- tests/test_api/test_cohort_controller.py
- tests/test_api/test_course_controller.py
- tests/test_api/test_curated_group_controller.py
- tests/test_api/test_search_controller.py
- tests/test_api/test_student_controller.py
- tests/test_models/test_alert.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1097
Blasé alert wording, per usual.
> BOAC-1097, new alert type: academic_standing

- boac/externals/data_loch.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3315
Negative is a positive.
> BOAC-3315, null Academic Standing is a good standing

- src/components/student/profile/StudentAcademicStanding.vue
- src/components/student/profile/StudentPersonalDetails.vue
- src/components/student/profile/StudentProfileHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3556
Also, avoid `StudentAcademicStanding` console error if `standing` prop is undefined.
> BOAC-3556, moved athlete info on student page

- .ebextensions/01_create_apache_conf.config
BOAC-3555 - Adding X-Forwarded-For to logging
> Adding new 01_create_apache_conf.config for BOAC-3555

- src/components/appointment/DropInAvailabilityToggle.vue
- src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3629
> BOAC-3629, 'pluralize' is in mixin, not options.filters

- src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3631
> BOAC-3631, no location, no em-dash

- src/components/note/create/CreateNoteModal.vue
- src/components/sidebar/Sidebar.vue
- src/components/student/profile/AcademicTimeline.vue
- src/mixins/Context.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3614
Running Teena locally tells me that things are "faster".
> BOAC-3614, speed up modal actions to, in eyes of Teena/user, end transaction more quickly

- .eslintrc.js
- package.json
- src/components/admin/EditUserProfileModal.vue
- src/components/appointment/AppointmentCancellationModal.vue
- src/components/appointment/AppointmentDetailsModal.vue
- src/components/appointment/AppointmentStudentPill.vue
- src/components/appointment/DropInWaitlistAppointment.vue
- src/components/matrix/Matrix.vue
- src/components/reports/UserReport.vue
- src/components/student/StudentRow.vue
- src/components/util/Autocomplete.vue
- src/views/Cohort.vue
- src/views/CuratedGroup.vue
- tox.ini
> NOJIRA, more eslint rules and a few style fixes

- boac/externals/data_loch.py
- boac/lib/cohort_utils.py
- boac/merged/cohort_filter_options.py
- boac/merged/student.py
- src/components/cohort/FilterRow.vue
- src/components/student/profile/StudentAcademicStanding.vue
- src/mixins/Util.vue
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3315
Also:
- Academic Standing term info in list view and on student profile
- "grouped options" is new to the cohort options paradigm
> BOAC-3315, 'Academic Standing' cohort filter grouped by term

- boac/externals/data_loch.py
- boac/lib/cohort_utils.py
- boac/merged/cohort_filter_options.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3627
> BOAC-3627, academic_standing options min_term: 'Fall {current_year - 5}'

- boac/api/notes_controller.py
- boac/api/topic_controller.py
- boac/models/note.py
- boac/models/topic.py
- src/components/appointment/AppointmentTopics.vue
- src/components/note/AdvisingNoteTopics.vue
- src/components/sidebar/SearchForm.vue
- src/components/sidebar/Sidebar.vue
- tests/test_api/test_topic_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3016
The 'Manage' feature will need all `topics` data.
> BOAC-3016, topic.to_api_json gets standard treatment, front-end adjusts

- src/components/topics/ManageTopics.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3642
> BOAC-3642, fix alignment in 'Manaage Topics'; add 'Deleted' column

- src/components/topics/ManageTopics.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3643
> BOAC-3643, when topic is deleted, show em-dash in place of 'available_in_notes' and 'available_in_appointments'

- boac/models/cohort_filter.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3641
See Jira comments for details.
> BOAC-3641, initialize '__transient_sids' outside of init method

- src/assets/styles/bootstrap-overrides.css
- src/components/topics/ManageTopics.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3642
> BOAC-3642, final CSS tweak on Manage Topics widget

- boac/api/util.py
- src/components/student/profile/StudentProfileHeader.vue
- src/mixins/Berkeley.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3620
https://jira.ets.berkeley.edu/jira/browse/BOAC-3645
Plus, graduated students are included in CSV export.
> BOAC-3620, Academic Subplan in CSV export

- src/components/topics/ManageTopics.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3643
The `availableIn` values are ignored (and hidden from user) when topic is deleted.
> BOAC-3643, if deleted topic then, when sorting, treat 'availableIn' as if null

- src/components/topics/EditTopicModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3651
> BOAC-3651, topic has max length 50

- src/components/topics/ManageTopics.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3654
`qa` PR is #2579
> BOAC-3654, end CSS color invasion of Topics table column

- src/components/topics/ManageTopics.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3654
master PR coming soon.
> [QA] BOAC-3654, end CSS color invasion of Topics table column

- .eslintrc.js
- babel.config.js
- package.json
- postcss.config.js
- tox.ini
- vue.config.js
https://jira.ets.berkeley.edu/jira/browse/BOAC-3657
Guidance from https://github.com/babel/babel/issues/9849
> BOAC-3657, babel plugin/config to get regeneratorRuntime

- src/components/topics/EditTopicModal.vue
- src/views/FlightDeck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3020
UX is shown in recent Jira comments.
> BOAC-3020, lable is read-only when edit existing topic

- src/components/topics/EditTopicModal.vue
- src/views/FlightDeck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3020
master PR is #2584
> [QA] BOAC-3020, lable is read-only when edit existing topic

- boac/externals/data_loch.py
- boac/merged/student.py
- boac/models/alert.py
- tests/test_api/test_alerts_controller.py
- tests/test_api/test_cohort_controller.py
- tests/test_api/test_curated_group_controller.py
- tests/test_api/test_student_controller.py
- tests/test_models/test_alert.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3630
The master PR is #2587
> [QA] BOAC-3630, academic_standing alerts: use action_date for created_at and preserve

- boac/models/note.py
- tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3663
> [QA] BOAC-3663, create/update note: neither titleize nor vacuum_whitespace topics

- boac/models/note.py
- tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3663
`qa` PR is #2590
> BOAC-3663, create/update note: neither titleize nor vacuum_whitespace topics

- boac/models/note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3660
> BOAC-3660, benchmark the performance of note creation

- boac/models/note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3660
master PR is #2592
> [QA] BOAC-3660, benchmark the performance of note creation

- package-lock.json
Hoping to avoid intermittent vue-cli failures similar to #2593
> NOJIRA, package-lock wants to be updated (missed in older commit?)

- boac/models/note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3668
> [QA] BOAC-3668, benchmarking note creation: log topic and attachment counts

- boac/models/note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3668
The `qa` PR is #2595
> BOAC-3668, benchmarking note creation: log topic and attachment counts

- boac/api/search_controller.py
- package-lock.json
- src/views/Search.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3666
> BOAC-3666: Skips admit search when search phrase not provided

- src/api/cohort.ts
- src/store/modules/cohort-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-3723
> BOAC-3723, when cohort viewed by non-owner, always query with owner_id

- boac/api/cohort_controller.py
- src/api/cohort.ts
- src/store/modules/cohort-edit-session.ts
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3723
> BOAC-3723, CSV is same for owner and observer when criteria has 'My'

- boac/__init__.py
We will soon branch for a patch release.
> NOJIRA, v4.9.1 for BOA master

- package-lock.json
- src/api/user.ts
- src/components/note/EditAdvisingNote.vue
- src/components/note/create/CreateNoteModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3656
Fyi, I did `npm install` and package-local was modified, so it's included in this PR.
> BOAC-3656, check user session status when 'Save' click (notes, templates)

- package-lock.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/BOAC-3729
> BOAC-3729: Updates node-forge (via selfsigned)

- package-lock.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/BOAC-3673
> BOAC-3673: Updates bl (buffer list)

- boac/merged/advising_appointment.py
- boac/merged/advising_note.py
- src/components/appointment/AdvisingAppointment.vue
- src/components/note/AdvisingNote.vue
- src/components/student/profile/AcademicTimeline.vue
- tests/test_api/test_student_controller.py
- tests/test_merged/test_advising_appointment.py
- tests/test_merged/test_advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3717
> BOAC-3717: Shows source on imported notes

- fixtures/loch/student_profile_7890123456.json
- src/components/student/profile/StudentPersonalDetails.vue
- src/mixins/Berkeley.vue
- tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3730
> BOAC-3730: Puts 'director' last in the advisors list

- src/components/curated/CuratedGroupSelector.vue
- src/components/sidebar/SearchForm.vue
- src/components/student/profile/StudentGroupSelector.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1736
> BOAC-1736, keyboard-only use of curated group widget on student, cohort and class pages

- src/components/student/StudentRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3687
> BOAC-3687 Better voicing for student course data headings

- src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3689
> BOAC-3689 Voicing for show/hide search options

- src/components/student/StudentRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3708
> BOAC-3708 W is for Waitlisted

- src/components/note/AdvisingNoteAttachments.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3699
https://jira.ets.berkeley.edu/jira/browse/BOAC-3701
> BOAC-3699 BOAC-3701 Voicing for note attachment selector

- src/views/Search.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1575
> BOAC-1575, sr-only h1 for search results view

- src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3696
> BOAC-3696: Fixes 'show previous messages' SR alert

- src/views/Search.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3688
> BOAC-3688 Refocus on completed search

- src/components/util/SectionSpinner.vue
- src/views/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3685
> BOAC-3685 Optional announcement suppressor for SectionSpinner

- src/components/student/StudentRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3707
> BOAC-3707 Remove student from curated group: screenreader voicing

- src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3706
> BOAC-3706: SR voices results of searching Academic Timeline

- src/components/util/Pagination.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3710
> BOAC-3710 Aria navigation label for pagination widget

- src/components/cohort/FilterRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3711
> BOAC-3711 Screenreader prominence for filter range validation errors

- src/components/cohort/FilterRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3712
> BOAC-3712 Voice term name in academic standing filter dropdown

- src/components/note/create/BatchNoteAddStudent.vue
- src/components/sidebar/Sidebar.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3682
Also fixes spacing in SR text.
> BOAC-3682: Associates label with correct element on create note modal

- src/views/Profile.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3683
> BOAC-3683 Focus profile header on page load

- src/layouts/shared/StandardHeaderLayout.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3684
> BOAC-3684 Move skip-to-content link after Home

- src/components/appointment/DropInWaitlistAppointment.vue
- src/components/search/SortableStudents.vue
- src/components/sidebar/SearchForm.vue
- src/components/student/StudentAvatar.vue
- src/components/student/profile/StudentProfileHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3692
> BOAC-3692 Clarify note/appointment search filter toggle

- src/components/appointment/DropInWaitlistAppointment.vue
- src/components/search/SortableStudents.vue
- src/components/student/StudentAvatar.vue
- src/components/student/profile/StudentProfileHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3694
> BOAC-3694 Voice graduated and inactive icons when not obvious from context

- src/components/student/SortBy.vue
- src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1740
> BOAC-1740, sort-by with optgroups, accessibility

- buildspec.yml
- package-lock.json
- Reverts `--unsafe-perm` attempt
- is an outdated `package-lock` file causing fail on first build?
> NOJIRA, move `npm install` to build>commands; package-lock updates

- src/components/student/profile/StudentClasses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1743
> BOAC-1743, differentiate class-related links and buttons on student page

- src/components/student/StudentAvatar.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1421
> BOAC-1421, accessible alert counts on student bobbleheads

- buildspec.yml
If CodeBuild fails, review npm log.
> NOJIRA, cat npm log in case of error

- src/components/admin/EditServiceAnnouncement.vue
- src/components/appointment/AppointmentDetailsModal.vue
- src/components/appointment/CreateAppointmentModal.vue
- src/components/appointment/LogResolvedIssueModal.vue
- src/components/note/EditAdvisingNote.vue
- src/components/note/create/CreateNoteModal.vue
- src/components/util/RichTextEditor.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3703
> BOAC-3703: associates form labels with rich text editors

- boac/api/util.py
- src/mixins/Berkeley.vue
JIRA: https://jira.ets.berkeley.edu/jira/browse/BOAC-3546
> Added Transfer status to the CSV Export

- buildspec.yml
- src/components/util/Spinner.vue
- src/store/modules/cohort-edit-session.ts
- src/views/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1740
- more info about cohort when page loads
- no redundant alerts in `Spinner`
- lessen the noise w.r.t sr-alerts in `/cohort` view
> BOAC-1740, clean up screenreader alerts in /cohort view

- src/components/note/create/CreateNoteModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3702
Also changes order on some of the post-save activities for better SR UX.
> BOAC-3702: Shows alert while creating note, regardless of attachments

- src/components/admin/DropInSchedulerManagement.vue
- src/components/admin/Users.vue
- src/components/appointment/CreateAppointmentModal.vue
- src/components/appointment/LogResolvedIssueModal.vue
- src/components/curated/CuratedGroupSelector.vue
- src/components/note/create/BatchNoteAddStudent.vue
- src/components/sidebar/SearchForm.vue
- src/components/util/Autocomplete.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3686
> BOAC-3686, auto-suggest component requires labelled-by; properly voice suggestions list

- src/components/student/profile/AcademicTimeline.vue
- src/components/util/SectionSpinner.vue
- src/components/util/Spinner.vue
- src/views/Search.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1575
> BOAC-1575, do not put aria-live on h1, h2, etc. NVDA will not recognize them as headers

- src/components/student/SortBy.vue
- src/views/Cohort.vue
- src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3713
I'm done trying to shoe-horn accessibility into `b-form-select'`. This is a better approach, methinks.
> BOAC-3713, replace 'b-form-select' with more accessible 'b-dropdown', styled

- src/components/student/StudentAvatar.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1421
> BOAC-1421, aria-hidden on alerts tooltip (img aria-label has info)

- src/components/student/profile/StudentClasses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1743
> BOAC-1743, clearer sr-only for show/hide course details on /student

- boac/__init__.py
- boac/lib/background.py
- boac/models/appointment.py
- boac/models/note.py
- config/default.py
- config/test.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3669
Advisory lock code adapted from Nessie.
> BOAC-3669 Move search index refreshes to background thread

- src/components/note/create/BatchNoteFeatures.vue
- src/mixins/NoteEditSession.vue
- src/store/modules/note-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-3704
> BOAC-3704: waits for recalculation to finish before displaying new student count on batch note

- src/components/student/profile/AcademicTimeline.vue
- src/components/student/profile/StudentClasses.vue
- src/components/student/profile/StudentGroupSelector.vue
- src/components/student/profile/StudentProfileGPA.vue
- src/components/student/profile/StudentProfileHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3718
> BOAC-3718: Adds context to student page buttons

- src/components/curated/CuratedGroupHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3760
> BOAC-3760, remove 'Loading' from non-view component

- src/components/search/SortableGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3759
> BOAC-3759, bootstrap collapse: v-b-toggle or v-model, not both

- src/components/cohort/ApplyAndSaveButtons.vue
- src/components/cohort/CreateCohortModal.vue
- src/components/cohort/FilterRow.vue
- src/components/curated/CreateCuratedGroupModal.vue
- src/components/curated/CuratedGroupSelector.vue
- src/components/student/profile/StudentGroupSelector.vue
> BOAC-1481, sr-alerts and focus for create cohort and curated modals

- .eslintrc.js
- buildspec.yml
- src/components/search/SortableGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3473
I sneaking in a change to buildspec to revert the explicit vue-cli install.
> BOAC-3473, sortable-groups component (cleaner and more accessible)

- src/components/curated/CuratedGroupSelector.vue
- src/components/curated/CuratedStudentCheckbox.vue
- src/components/curated/CuratedStudentSelector.vue
- src/components/student/StudentRow.vue
- src/views/Cohort.vue
> BOAC-1481, first step towards accessible add-to-curated-from-list workflow

- src/mixins/CurrentUserExtras.vue
- src/views/Cohort.vue
- src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3754
> BOAC-3754 Translate sort options for screenreader

- src/components/curated/dropdown/ManageStudent.vue
- src/components/curated/dropdown/SelectAll.vue
- src/components/curated/dropdown/StudentCheckbox.vue
- src/store/modules/current-user-extras.ts
> BOAC-1481, refresh curated/ManageStudent on any change to myCurated

- src/views/AllCohorts.vue
- src/views/AllGroups.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1482
> BOAC-1482 Everyone's Cohorts/Groups: focus header on load

- src/components/note/AdvisingNoteTopics.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3720
> BOAC-3720 Reorder announcements when removing note topic

- src/components/note/AdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3751
> BOAC-3751: Clears up note author JS error and Vue warnings

- src/assets/styles/boac-global.css
- src/components/admin/DevAuth.vue
- src/components/cohort/CohortHistory.vue
- src/components/course/CourseStudents.vue
- src/components/matrix/Matrix.vue
- src/components/search/SortableStudents.vue
- src/components/student/StudentRow.vue
- src/components/util/SectionSpinner.vue
- src/mixins/Util.vue
- src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1463
This PR also benefits sighted users with a cleaner UI.
> BOAC-1463, Course page: toggle tabs or page-size and expect proper sr alerts

- src/components/course/CourseStudents.vue
- src/components/search/SortableStudents.vue
> BOAC-1481, /course page gets manage-groups-of-student dropdown per row
