- src/components/curated/dropdown/ManageStudent.vue
- src/components/search/SortableStudents.vue
And a bit of `aria-label` improvement.
> BOAC-1481, manage-curated-per-student is always sr-only in search results

- src/components/cohort/CohortPageHeader.vue
- src/components/curated/CuratedGroupHeader.vue
- src/views/Cohort.vue
- src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1478
There's a lot (too much?) going on.
> BOAC-1478, tidy up top sections of /cohort and /curated views

- src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1478
CSS tidying, too.
> BOAC-1478, toggle tabs on /course page, good focus follows

- src/assets/styles/boac-global.css
- src/components/curated/CuratedGroupHeader.vue
- src/components/note/create/CreateNoteModal.vue
- src/components/search/SortableGroup.vue
- src/views/Cohort.vue
- src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3721
> BOAC-3721, create note > focus at start of new note row

- src/components/util/DismissibleFooterAlert.vue
- src/layouts/shared/ServiceAnnouncement.vue
- src/mixins/Context.vue
- src/store/modules/context.ts
- src/views/AdmitStudents.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3678
This button is sr-only but it's in the tab-order. Savvy sighted users can get at it.
> BOAC-3678, screen-reader users can dismiss/restore BOA service announcement

- src/components/student/profile/StudentProfileHeader.vue
Some  things to note:
- The data  for minors owners is  not there, so I can't  display it. How would this work  for dual degrees  + minors since they would be different colleges?
- Hyperlinks don't seem to be there for graduated students
- Had to hard code the "UG"
- I added some logic in  case people have multiple  minors
> BOAC-3619: Student page now displays graduated minors

- package-lock.json
- package.json
- src/components/course/CourseStudents.vue
- src/components/student/StudentBoxplot.vue
- src/components/student/StudentGpaChart.vue
- src/components/student/StudentRow.vue
- src/components/student/StudentUnitsChart.vue
- src/components/student/profile/StudentClasses.vue
- src/components/student/profile/StudentProfileGPA.vue
- src/components/student/profile/StudentProfileUnits.vue
- src/main.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-3589
https://jira.ets.berkeley.edu/jira/browse/BOAC-1420
We can't upgrade to highcharts 8.1.2 because it's incompatible with `vue-highcharts`. (We'll upgrade vue-highcharts when we upgrade to Vue 3.) Fortunately, highcharts 7.2.2 was patched w.r.t security vulnerability: https://www.highcharts.com/blog/changelog/#highcharts-v7.2.2
I've added 'accessibility' configs to options passed to highcharts component.
> BOAC-3589, highcharts 7.2.2; enable highcharts-accessibility; refactor

- src/components/curated/dropdown/ManageStudent.vue
> [QA] BOAC-1482, proper focus after add/remove to curated from student row

- src/components/curated/dropdown/ManageStudent.vue
> BOAC-1482, proper focus after add/remove to curated from student row

- src/components/student/profile/StudentPersonalDetails.vue
- src/components/student/profile/StudentProfileHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3772
> BOAC-3772, student profile > phone and email have proper sr-only prefix

- src/components/student/profile/StudentPersonalDetails.vue
- src/components/student/profile/StudentProfileHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3772
master PR is #2699
> [QA] BOAC-3772, student profile > phone and email have proper sr-only prefix

- src/components/note/create/CreateNoteModal.vue
- src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3777
https://jira.ets.berkeley.edu/jira/browse/BOAC-3721
QA PR will follow.
> BOAC-3777/BOAC-3721, no dupe note when keyboard-only; proper focus on create

- src/components/note/create/CreateNoteModal.vue
- src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3777
https://jira.ets.berkeley.edu/jira/browse/BOAC-3721
master PR is #2701
> [QA] BOAC-3777/BOAC-3721, no dupe note when keyboard-only; proper focus on  create

- src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1480
> BOAC-1480, fix wording of pagination sr-alert

- src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1480
master PR is #2703
> [QA] BOAC-1480, fix wording of pagination sr-alert

- package-lock.json
- package.json
- src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3784
> BOAC-3784, fix calendar popup in search form

- package-lock.json
- package.json
- src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3784
master PR is #2705
> [QA] BOAC-3784, fix calendar popup in search form

- src/components/student/profile/StudentPersonalDetails.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3772
> BOAC-3772, aria-label for student phone num

- src/components/student/profile/StudentPersonalDetails.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3772
master PR is #2710
> [QA] BOAC-3772, aria-label for student phone num

- src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3757
> BOAC-3757, informative sr-alert when course page loads

- src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3757
master PR is #2711
> [QA] BOAC-3756, informative sr-alert when course page loads

- src/components/student/profile/StudentProfileHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3791
> BOAC-3791 Header focus for student profile page

- src/components/student/profile/StudentProfileHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3791
QA version of #2713.
> [QA] BOAC-3791 Header focus for student profile page

- src/components/search/SortableGroup.vue
- src/views/Home.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3794
> BOAC-3794 Fix homepage heading structure

- src/components/search/SortableGroup.vue
- src/views/Home.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3794
QA version of #2715.
> [QA] BOAC-3794 Fix homepage heading structure

- src/components/note/AdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3799
Master-branch version of #2718.
> BOAC-3799 Fix unwanted in-component caching of note authors

- src/components/curated/dropdown/ManageStudent.vue
- src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3795
https://jira.ets.berkeley.edu/jira/browse/BOAC-3797
Saner screen reader voicing.
> BOAC-3795, remove needless aria-owns; aria-label for student-to-group  checkbox

- src/components/curated/dropdown/ManageStudent.vue
- src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3795
https://jira.ets.berkeley.edu/jira/browse/BOAC-3797
master PR is #2720
> [QA] BOAC-3795, remove needless aria-owns; aria-label for student-to-group  checkbox

- boac/externals/data_loch.py
- boac/merged/cohort_filter_options.py
- boac/merged/student.py
- boac/models/cohort_filter.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2909
> BOAC-2909: Added cohort filter for students with holds

- boac/lib/berkeley.py
- boac/merged/student.py
- tests/test_api/test_student_controller.py
- tests/test_lib/test_berkeley.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3827
> BOAC-3827: Attaches academic year label to each enrollment term

- src/components/student/profile/StudentClasses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3827
> BOAC-3827: Divides student enrl terms into expandable sections by year

- boac/api/reports_controller.py
- boac/models/alert.py
- src/api/reports.ts
- src/components/admin/AlertsLogExport.vue
- src/views/FlightDeck.vue
- tests/test_api/test_reports_controller.py
The CSV contents may evolve, based on open requirement questions. Front-end work will follow.
> BOAC-3596, Flight Deck > download alerts CSV per dates (backend)

- package-lock.json
- package.json
- src/components/admin/AlertsLogExport.vue
- src/components/sidebar/SearchForm.vue
Date picker with smart min/max logic for date range.
> BOAC-3596, UX of alerts export, with v-calendar update

- boac/api/reports_controller.py
- boac/lib/util.py
- src/api/reports.ts
- src/components/admin/AlertsLogExport.vue
- tests/test_api/test_reports_controller.py
> BOAC-3596, wire AlertsLogExport to /api/reports/download_alerts_csv

- boac/api/reports_controller.py
- src/components/admin/AlertsLogExport.vue
- tests/test_api/test_reports_controller.py
> BOAC-3596, alerts CSV download: cleanup, new columns

- src/components/HeaderMenu.vue
- src/layouts/shared/StandardHeaderLayout.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3801
See screenshot in Jira. Incorporates Flint feedback.
> BOAC-3801, accessibility: if home then no link to home; href label change

- src/components/sidebar/Sidebar.vue
- src/components/student/profile/AcademicTimeline.vue
- src/components/util/Pagination.vue
- src/layouts/StandardLayout.vue
- src/layouts/shared/StandardHeaderLayout.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3814
The navigation role in sidebar excludes search input and create-note button.
> BOAC-3814, nav role for sidebar; tablist role in AcademicTimeline

- src/components/admit/SortableAdmits.vue
- src/components/cohort/CohortHistory.vue
- src/components/course/SortableCourseList.vue
- src/components/search/SortableStudents.vue
- src/components/student/StudentRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3804
> BOAC-3804, no 'Go to profile page of' aria-label prefix

- src/components/appointment/AppointmentTopics.vue
- src/components/cohort/CohortPageHeader.vue
- src/components/cohort/FilterRow.vue
- src/components/course/SortableCourseList.vue
- src/components/curated/CuratedGroupHeader.vue
- src/components/note/AdvisingNoteTopics.vue
- src/components/note/create/CreateNoteHeader.vue
- src/components/search/SortableStudents.vue
- src/components/sidebar/SearchForm.vue
- src/components/student/StudentAvatar.vue
- src/components/student/profile/AcademicTimeline.vue
- src/components/student/profile/StudentClasses.vue
- src/components/student/profile/StudentPersonalDetails.vue
- src/components/student/profile/StudentProfileGPA.vue
- src/components/student/profile/StudentProfileHeader.vue
- src/layouts/Login.vue
- src/layouts/shared/StandardHeaderLayout.vue
- src/mixins/Loading.vue
- src/store/modules/context.ts
- src/views/AdmitStudent.vue
- src/views/AdmitStudents.vue
- src/views/AllCohorts.vue
- src/views/AllGroups.vue
- src/views/Course.vue
- src/views/Profile.vue
- src/views/Search.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3805
https://jira.ets.berkeley.edu/jira/browse/BOAC-3807
https://jira.ets.berkeley.edu/jira/browse/BOAC-3813
> BOAC-3805, remove tabindex of non-interactive; aria-expanded added on  student profile

- src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3808
> BOAC-3808, Academic Timeline accessibility: sr-only h3 after filter-by buttons

- src/components/admit/SortableAdmits.vue
- src/components/cohort/CohortPageHeader.vue
- src/components/curated/CuratedGroupHeader.vue
- src/components/search/SortableGroup.vue
- src/components/search/SortableStudents.vue
- src/components/student/StudentRow.vue
- src/components/student/profile/StudentClasses.vue
- src/views/AdmitStudent.vue
- src/views/AdmitStudents.vue
- src/views/Home.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3815
The Jira has specifics.
> BOAC-3815, /home accessibility: cohort accordion, aria-expanded, keyboard nav

- src/components/student/profile/StudentProfileGPA.vue
- src/components/student/profile/StudentProfileUnits.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3806
> BOAC-3806, h4 headers above highcharts widgets

- src/components/student/profile/StudentClasses.vue
JIRA: https://jira.ets.berkeley.edu/jira/browse/BOAC-3831
Design: https://jira.ets.berkeley.edu/jira/browse/BOAC-3734
> BOAC-3831: Added sort academic year functionality to student classes ui

- .eslintrc.js
- src/auth.ts
- src/components/appointment/AdvisingAppointment.vue
- src/components/appointment/AppointmentTopics.vue
- src/components/appointment/DropInAppointmentDropdown.vue
- src/components/course/SortableCourseList.vue
- src/components/note/create/BatchNoteAddCohort.vue
- src/components/sidebar/SearchForm.vue
- src/components/sidebar/Sidebar.vue
- src/components/student/StudentBoxplot.vue
- src/components/student/StudentGpaChart.vue
- src/components/student/profile/AcademicTimeline.vue
- src/components/student/profile/StudentClasses.vue
- src/components/student/profile/StudentProfileHeader.vue
- src/components/topics/EditTopicModal.vue
- src/components/util/Autocomplete.vue
- src/main.ts
- src/store/modules/cohort-edit-session.ts
- src/store/modules/current-user-extras.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-3840
https://jira.ets.berkeley.edu/jira/browse/BOAC-3811
> BOAC-3596 / BOAC-3840, close date-picker when date selected; code cleanup

- src/components/note/create/CreateNoteHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3813
> BOAC-3813, screen-reader alerts for note template related actions

- src/components/note/create/CreateNoteHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2674
> BOAC-2674, tabindex needed on modal header if we want putFocus

- src/components/student/profile/StudentProfileHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3807
> BOAC-3807, show/hide student details: aria-expanded and alertSr

- src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3788
Teena PR will follow.
> BOAC-3788, proper focus after dismissing delete-note popover

- src/components/student/StudentUnitsChart.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3793
> BOAC-3793: Fixes unit chart tooltip, scales to accommodate extra units

- src/components/student/profile/StudentProfileHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3619
> CC-3619: Graduated student minors are now bolded

- src/components/student/StudentUnitsChart.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3793
> BOAC-3793: updates units chart default upper limit

- package-lock.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/BOAC-3845
> BOAC-3845, bump axios version (SSRF vulnerability)

- src/components/student/profile/StudentClasses.vue
- src/components/student/profile/StudentEnrollmentTerm.vue
This component is still a WIP and doesn't include the expandable class details.
https://jira.ets.berkeley.edu/jira/browse/BOAC-3828
> BOAC-3828: Adds enrollment term component to student profile

- src/components/admin/AlertsLogExport.vue
- src/components/admin/DevAuth.vue
- src/components/admin/Users.vue
- src/components/curated/CuratedGroupHeader.vue
- src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3756
> BOAC-3756, avoid 'navigation guard' error after curated group delete

- src/components/student/profile/StudentCourse.vue
- src/components/student/profile/StudentEnrollmentTerm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3830
> BOAC-3830: Adds class detail section to new classes view

- boac/api/cohort_controller.py
- boac/lib/cohort_utils.py
- boac/merged/cohort_filter_options.py
- boac/models/cohort_filter.py
- src/components/cohort/FilterRow.vue
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3852
> BOAC-3852, reorganize cohort filter categories

- src/components/student/profile/StudentClasses.vue
- src/components/student/profile/StudentCourse.vue
- src/components/student/profile/StudentEnrollmentTerm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3828
> BOAC-3828: arranges terms horizontal; cleans up old code

- boac/lib/cohort_utils.py
- boac/merged/cohort_filter_options.py
- src/components/cohort/FilterRow.vue
- src/components/cohort/FilterSelect.vue
- src/mixins/Util.vue
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3852
* Consistent JSON structure for opt_groups used in select menu.
* Slim down FilterRow component
> BOAC-3852, new FilterSelect component for primary and secondary cohort menu

- src/components/cohort/FilterRow.vue
- src/components/cohort/FilterSelect.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3852
See recent comments in da Jira.
> BOAC-3852, if only one filter-option-group then flatten to simple array of options

- boac/merged/cohort_filter_options.py
- src/components/cohort/FilterRow.vue
- src/components/cohort/FilterSelect.vue
- src/views/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3854
> BOAC-3854, cohort filters cleanup after dropdown-to-select refactor

- src/components/cohort/FilterSelect.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3743
> BOAC-3743, sensible and legit ids for filter select options

- src/components/cohort/FilterSelect.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3852
> BOAC-3852, use option.value as id suffix in secondary filter options

- src/components/sidebar/SearchForm.vue
- src/components/util/Autocomplete.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3839
See recent comments in the Jira.  Use `?w=1` for simpler diff.
> BOAC-3839, order sections of search form (sidebar) for sensible tab sequence

- src/components/cohort/FilterRow.vue
- src/store/modules/cohort-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-3861
Includes a bit of cleanup to slim down the bloated `FilterRow` component.
> BOAC-3861, when edit cohort filter, flatten opt-groups to find selected option

- src/components/cohort/ApplyAndSaveButtons.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3773
> BOAC-3773, sr-alert when apply updated cohort filters

- src/assets/styles/boac-global.css
- src/components/admin/DropInSchedulerManagement.vue
- src/components/admin/EditUserProfileModal.vue
- src/components/admin/RemoveDropInSchedulerModal.vue
- src/components/appointment/AppointmentAssignModal.vue
- src/components/appointment/AppointmentCancellationModal.vue
- src/components/appointment/AppointmentDetailsModal.vue
- src/components/appointment/AppointmentUpdateModal.vue
- src/components/appointment/CheckInModal.vue
- src/components/appointment/CreateAppointmentModal.vue
- src/components/appointment/LogResolvedIssueModal.vue
- src/components/cohort/ApplyAndSaveButtons.vue
- src/components/cohort/CohortPageHeader.vue
- src/components/cohort/CreateCohortModal.vue
- src/components/cohort/DeleteCohortModal.vue
- src/components/curated/CreateCuratedGroupModal.vue
- src/components/curated/CuratedGroupHeader.vue
- src/components/curated/dropdown/ManageStudent.vue
- src/components/curated/dropdown/SelectAll.vue
- src/components/note/create/CreateNoteHeader.vue
- src/components/note/create/CreateNoteModal.vue
- src/components/note/create/CreateTemplateModal.vue
- src/components/note/create/RenameTemplateModal.vue
- src/components/topics/EditTopicModal.vue
- src/components/util/AreYouSureModal.vue
- src/components/util/ExportListModal.vue
- src/components/util/ModalHeader.vue
- src/mixins/Util.vue
- src/views/CreateCuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3774
Consistency in style and focus of modal h3s.
> BOAC-3774, ModalHeader component to standardize putFocus when open modal

- src/components/curated/CuratedGroupHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3774
> BOAC-3774, hide-header on two modals, we use ModalHeader

- src/components/student/profile/StudentClasses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3841
> BOAC-3841: flips the academic year sort-by icon

- src/components/curated/CuratedGroupHeader.vue
- src/components/note/create/CreateNoteHeader.vue
- src/components/util/ModalHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3881
E.g., if you don't want bottom-border.
> BOAC-3881, ModalHeader gets optional container-class prop

- src/components/note/create/CreateNoteHeader.vue
- src/components/util/ModalHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3881
@paulkerschen was right. See comments on PR #2779
> BOAC-3881, class attribute on Vue component is applied to container therein

- src/components/student/profile/StudentCourse.vue
- src/components/student/profile/StudentEnrollmentTerm.vue
- src/main.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-3843
> BOAC-3843: Fixes leaky grade values; adds IDs

- package-lock.json
- package.json
- src/components/search/InputAutocomplete.vue
- src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3838
Docs: https://autocomplete.trevoreyre.com/#/vue-component
A lot of code in `SearchForm` will be obsolete if this is a viable fix but I've left in place, for now. Makes for a simpler PR diff.
> BOAC-3838, sidebar search with new package: autocomplete-vue

- package-lock.json
- package.json
- src/components/search/InputAutocomplete.vue
- src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3884
Because the _autocomplete-vue_ component has `inheritAttrs: false` we must be explicit in setting props (eg, 'id' attribute).
> BOAC-3884, sidebar search 'Go' button onSubmit

- src/assets/styles/boac-global.css
- src/components/search/InputAutocomplete.vue
- src/components/sidebar/SearchForm.vue
- src/components/student/profile/StudentPersonalDetails.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3885
Disabled search input gets custom bg-color, as in previous impl.
> BOAC-3885, search-input re-uses StudentPersonalDetails transition CSS

- boac/api/reports_controller.py
- boac/merged/reports.py
- tests/test_api/test_reports_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3894
> BOAC-3894, advising notes metadata CSV download (server-side)

- boac/api/reports_controller.py
- boac/merged/reports.py
- src/api/reports.ts
- src/components/reports/NotesReport.vue
- tests/test_api/test_reports_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3894
> BOAC-3894, front-end for notes-by-month report

- src/components/curated/CuratedGroupBulkAdd.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3771
> BOAC-3771, screen-reader speaks error when create curated group w/ bulk SIDs

- src/assets/styles/boac-global.css
- src/components/student/profile/AcademicTimeline.vue
- src/components/student/profile/AcademicTimelineHeader.vue
- src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3809
`AcademicTimeline.vue` was nearing 1000 lines, surpassing maintainability. Let's break it up into logical chunks.
> BOAC-3809, break up AcademicTimeline component prior to accessibility  fix

- src/components/student/profile/AcademicTimeline.vue
- src/components/student/profile/AcademicTimelineTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3809
> BOAC-3809, break up AcademicTimeline component for readability

- src/components/student/profile/StudentClasses.vue
- src/components/student/profile/StudentCourse.vue
- src/components/student/profile/StudentEnrollmentTerm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3830
> BOAC-3830: Responsive class details

- src/components/student/profile/AcademicTimelineHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3903
> BOAC-3903, `import Util` if you want to putFocusNextTick

- src/components/student/profile/AcademicTimelineHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3903
master PR is #2794
> [QA] BOAC-3903,  `import Util` if you want to putFocusNextTick

- src/components/student/profile/StudentClasses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3857
> BOAC-3857: Removed sort button if student has less than 2 terms

- src/components/student/profile/AcademicTimeline.vue
- src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3904
> BOAC-3904, import Context to use alertScreenReader

- boac/externals/data_loch.py
- boac/merged/cohort_filter_options.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3889
> BOAC-3889: Added CPN to EPN filter

- src/components/student/profile/AcademicTimeline.vue
- src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3904
master PR is #2798
> [QA] BOAC-3904, import Context to use alertScreenReader

- src/components/student/profile/StudentCourse.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3830
> BOAC-3830: Tweaks class detail styles

- src/components/student/profile/StudentClasses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3900
> BOAC-3900: Preserves academic year collapse state on sort

- src/components/student/profile/StudentClasses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3900
master PR is #2801
> [QA] BOAC-3900: Preserves academic year collapse state on sort

- boac/api/util.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3899
> (QA) BOAC-3899: CSV export now checks for students without intended majors

- src/mixins/Berkeley.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3902
> BOAC-3902: fixes academic standing Y2K bug

- src/mixins/Berkeley.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3902
master PR is #2806
> [QA] BOAC-3902: fixes academic standing Y2K bug

- src/components/student/profile/AcademicTimeline.vue
- src/components/student/profile/AcademicTimelineTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3905
> [QA] BOAC-3905, note creation spinner must stop

- src/components/student/profile/AcademicTimeline.vue
- src/components/student/profile/AcademicTimelineTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3905
QA PR is #2808
> BOAC-3905, note creation spinner must stop

- src/components/search/InputAutocomplete.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3912
master PR is #2810
> [QA] BOAC-3912, keypress.enter.prevent=noop for input-autocomplete widget

- boac/api/reports_controller.py
- tests/test_api/test_reports_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3914
> BOAC-3914, FDR is for admins _and_ directors 

- boac/api/reports_controller.py
- tests/test_api/test_reports_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3914
master PR is #2812
> [QA] BOAC-3914, director deserves FDR

- src/components/student/profile/StudentCourse.vue
- src/components/student/profile/StudentEnrollmentTerm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3907
> BOAC-3907: Prevents course detail section from covering courses in neighboring terms

- src/components/student/profile/StudentCourse.vue
- src/components/student/profile/StudentEnrollmentTerm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3907
Master PR is #2814
> [QA] BOAC-3907: Prevents course detail section from covering courses in neighboring terms

- src/components/note/AdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3906
> [QA] BOAC-3906, note.author post-processing should happen in Promise callback

- src/components/note/AdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3906
The QA PR is #2816
> BOAC-3906, note.author post-processing should happen in Promise callback

- src/components/student/profile/StudentEnrollmentTerm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3908
> [QA] BOAC-3908: Student page now displays GPA/Units as mdash instead of 0

- src/components/note/AdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3915
master PR is #2818
> [QA] BOAC-3915, tweaks to note component > loadAuthorDetails

- src/components/note/AdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3915
Made a boo-boo in previous PR.
> BOAC-3915, tweaks to note component > loadAuthorDetails

- src/components/student/profile/StudentCourse.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3911
master PR is #2821
> [QA] BOAC-3911: Visually limits long course names

- src/components/student/profile/StudentCourse.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3911
> BOAC-3911: Visually limits long course names

- src/components/student/profile/StudentCourse.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3907
> BOAC-3907: Fixes detail expand for narrow screen and waitlisted course

- src/components/student/profile/StudentCourse.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3907
Master PR is #2823
> [QA] BOAC-3907: Fixes detail expand for narrow screen and waitlisted course

- src/components/note/AdvisingNote.vue
- src/mixins/Util.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3906
QA PR is #2825
> BOAC-3906, show role of first dept; oxfordJoin on length zero is blank

- src/components/note/AdvisingNote.vue
- src/mixins/Util.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3906
> [QA] BOAC-3906, show role of first dept; oxfordJoin on length zero is blank

- src/store/modules/context.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-3901
> BOAC-3901: Fixed Curated Group pagination widget

- boac/merged/student.py
- src/components/student/profile/StudentAcademicStanding.vue
- src/components/student/profile/StudentClasses.vue
- src/components/student/profile/StudentEnrollmentTerm.vue
- src/components/student/profile/StudentWithdrawalCancel.vue
- src/mixins/Berkeley.vue
- tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3916
master PR is #2829
> [QA] BOAC-3916: Always shows current term/year

- boac/merged/student.py
- src/components/student/profile/StudentAcademicStanding.vue
- src/components/student/profile/StudentClasses.vue
- src/components/student/profile/StudentEnrollmentTerm.vue
- src/components/student/profile/StudentWithdrawalCancel.vue
- src/mixins/Berkeley.vue
- tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3916
> BOAC-3916: Always shows current term/year

- src/auth.ts
- src/components/HeaderMenu.vue
- src/core.ts
- src/mixins/CurrentUserExtras.vue
- src/store/modules/current-user-extras.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-3931
> BOAC-3931: Adds Degree Checks link to header menu

- src/views/DegreeChecks.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3932
> BOAC-3932: Adds degree checks list, populated with fake data

- src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3818
> BOAC-3818: Notes are now sorted by created date

- package-lock.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/BOAC-3939
https://jira.ets.berkeley.edu/jira/browse/BOAC-3949
> BOAC-3939 BOAC-3949 npm package updates

- src/views/AdmitStudent.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3943
> BOAC-3943: Adjusted header font sizes + padding of cells

- src/router.ts
- src/views/CreateDegree.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3934
Design: https://jira.ets.berkeley.edu/jira/browse/BOAC-3864
> BOAC-3943: Added create degree page

- src/views/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3946
> BOAC-3946: Removed extraneous separator when cohort has 1 result

- src/views/AdmitStudent.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3969
> BOAC-3969: Fixed wrong label above GPA info

- src/mixins/StudentMetadata.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3983
> BOAC-3983 Include new RD mark in grades with alert display

- boac/merged/student.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3957
> BOAC-3957 Don't suppress dropped sections in previous terms

- .eslintrc.js
- boac/api/user_controller.py
- boac/models/authorized_user.py
- boac/models/development_db.py
- requirements.txt
- src/layouts/shared/ServiceAnnouncement.vue
- tests/test_api/test_user_controller.py
- tests/test_models/test_authorized_user.py
- tox.ini
https://jira.ets.berkeley.edu/jira/browse/BOAC-3923
With a small bit of tidying.
> BOAC-3923, 'deleted' doesn't need to be 'deleted and blocked'

- boac/models/degree_progress_template.py
- tests/test_models/test_degree_progress_template.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3954
> BOAC-3954: Adds query returning a list of degree prog templates

- src/assets/styles/boac-global.css
- src/components/degree-progress/UnitRequirements.vue
- src/mixins/DegreeProgressEditSession.vue
- src/router.ts
- src/store/index.ts
- src/store/modules/degree-progress-edit-session.ts
- src/views/CreateDegree.vue
- src/views/DegreeProgressTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3962
> BOAC-3962: Stubs unit reqts list view, adds vuex component

- boac/externals/data_loch.py
- boac/merged/cohort_filter_options.py
- src/components/cohort/FilterRow.vue
- tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3982
In SQL query and in UI, the last-name range comparison is case-insensitive.
> BOAC-3982, last_name cohort filter allows 2 letters per range entry

- src/components/cohort/FilterRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3982
Do not up-case a float.
> BOAC-3982, change to cohort filter range logic must be float friendly

- boac/api/degree_progress_controller.py
- boac/models/degree_progress_template.py
- boac/models/degree_progress_unit_requirement.py
- boac/routes.py
- src/api/degree.ts
- src/components/degree-progress/StartDegree.vue
- src/mixins/Validator.vue
- src/router.ts
- src/views/CreateDegreeTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3935
> BOAC-3935: Added API for initializing degree

- boac/api/util.py
- boac/merged/user_session.py
- src/auth.ts
- src/components/HeaderMenu.vue
- src/components/degree-progress/StartDegree.vue
- src/core.ts
- src/mixins/CurrentUserExtras.vue
- src/router.ts
- src/store/modules/current-user-extras.ts
- src/views/DegreeChecks.vue
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3966
With reliable server-side auth logic we can simplify client-side.
> BOAC-3966, protect degree-progress features per user.canEdit / user.canRead

- boac/api/user_controller.py
- boac/api/util.py
- boac/lib/berkeley.py
- boac/merged/user_session.py
- src/api/user.ts
- src/components/admin/EditUserProfileModal.vue
- src/components/degree-progress/StartDegree.vue
- src/mixins/Berkeley.vue
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3967
I kept feature-flag out of the mix on Passenger Manifest so admin can _always_ review perms.
> BOAC-3967, Passenger Manifest > admin can view/toggle degree-progress permission

- boac/api/cohort_controller.py
- boac/api/curated_group_controller.py
- boac/merged/student.py
- boac/models/cohort_filter.py
- src/api/cohort.ts
- src/api/curated.ts
- src/components/cohort/ApplyAndSaveButtons.vue
- src/components/student/StudentRow.vue
- src/components/student/TermSelector.vue
- src/main.ts
- src/mixins/Berkeley.vue
- src/store/modules/cohort-edit-session.ts
- src/store/modules/curated-edit-session.ts
- src/store/modules/current-user-extras.ts
- src/views/Cohort.vue
- src/views/CuratedGroup.vue
- tests/test_api/test_cohort_controller.py
- tests/test_api/test_curated_group_controller.py
- tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3767
> BOAC-3767 User-selectable term in cohort and group list views

- src/components/student/TermSelector.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3767
Follow-up to #2867.
> BOAC-3767 Term selector options in descending order

- boac/api/degree_progress_controller.py
- boac/models/degree_progress_unit_requirement.py
- src/components/degree/UnitRequirements.vue
- tests/test_api/test_degree_progress_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3964
> BOAC-3964: API for creating a unit requirement

- boac/api/degree_progress_controller.py
- src/api/degree.ts
- src/components/HeaderMenu.vue
- src/views/degree/DegreeChecks.vue
- tests/test_api/test_degree_progress_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4013
> BOAC-4013, delete template (with confirmation modal) from /degrees page

- src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4015
> BOAC-4015 Adjust spacing in curated group header

- src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4015
QA version of #2875.
> [QA] BOAC-4015 Adjust spacing in curated group header

- src/views/Cohort.vue
- src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4016
> BOAC-4016 Preserve pagination when changing term selection

- src/views/Cohort.vue
- src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4016
QA version of #2877.
> [QA] BOAC-4016 Preserve pagination when changing term selection

- boac/api/degree_progress_controller.py
- boac/models/degree_progress_template.py
- src/api/degree.ts
- src/views/degree/DegreeChecks.vue
- tests/test_api/test_degree_progress_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4012
Design Jira is linked to BOAC-4012
> BOAC-4012, rename degree on /degrees page (list view)

- boac/api/degree_progress_controller.py
- boac/models/degree_progress_template.py
- src/api/degree.ts
- src/components/degree/CloneDegreeTemplateModal.vue
- src/views/degree/DegreeChecks.vue
- tests/test_api/test_degree_progress_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4014
Good artists copy, great artists clone.
> BOAC-4014, click 'Copy' to clone degree template, refresh list view

- boac/merged/user_session.py
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4017
> BOAC-4017, degree_progress off if feature_flag false, and applies to admins

- boac/merged/user_session.py
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4017
master PR is #2881
> [QA] BOAC-4017, degree_progress off if feature_flag false, and applies to admins

- boac/api/degree_progress_controller.py
- boac/models/degree_progress_template.py
- tests/test_api/test_degree_progress_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4018
This is back-end piece. Front-end in next PR.
> BOAC-4018, names must be unique (ignore case) across non-deleted degree templates

- src/main.ts
- src/router.ts
- src/views/Error.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3727
500s are not 404s.
> BOAC-3727, if 404 then /404 else if 400+ then /error

- boac/api/degree_progress_controller.py
- boac/models/degree_progress_unit_requirement.py
- src/api/degree.ts
- src/components/degree/EditUnitRequirement.vue
- src/components/degree/RequirementCategories.vue
- src/components/degree/UnitRequirements.vue
- src/mixins/DegreeEditSession.vue
- src/store/modules/degree-edit-session.ts
- src/views/degree/DegreeProgressTemplate.vue
- tests/test_api/test_degree_progress_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3963
New `get_degree_template` endpoint returns a template with all of its contents (unit requirements, etc).
> BOAC-3963: Adds create/update unit requirement form

- src/assets/styles/boac-global.css
- src/components/degree/CloneDegreeTemplateModal.vue
- src/views/degree/CreateDegreeTemplate.vue
- src/views/degree/DegreeChecks.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4018
> BOAC-4018, degree template  names must be unique (front-end)

- boac/api/degree_progress_controller.py
- src/components/degree/CloneDegreeTemplateModal.vue
- src/views/degree/DegreeChecks.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4018
And removed an extraneous `getTemplate` on server-side.
> BOAC-4018, proper putFocus after CRUD operatoins on /degrees

- boac/api/degree_progress_controller.py
- boac/models/degree_progress_unit_requirement.py
- tests/test_api/test_degree_progress_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4019
This is the back end work; front end to follow.
> BOAC-4019: API for editing a unit requirement

- src/api/degree.ts
- src/components/degree/EditUnitRequirement.vue
- src/components/degree/UnitRequirements.vue
- src/mixins/DegreeEditSession.vue
- src/store/modules/degree-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4019
> BOAC-4019: Makes unit requirements editable

- boac/api/config_controller.py
- boac/api/degree_progress_category_controller.py
- src/api/degree.ts
- src/components/admin/MyProfile.vue
- src/components/admin/Users.vue
- src/components/degree/AddDegreeCategory.vue
- src/components/degree/DegreeTemplateCategory.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/components/degree/UnitRequirements.vue
- src/mixins/Berkeley.vue
- src/mixins/DegreeEditSession.vue
- src/store/modules/degree-edit-session.ts
- src/views/PassengerManifest.vue
- src/views/degree/DegreeTemplate.vue
- tests/test_api/test_degree_progress_category_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3999
The `disableButtons` variable in `degree-edit-session` (store) is used to disable all buttons on the page when a create/edit transaction begins.
> BOAC-3999, add category UI and corresponding API

- boac/api/degree_progress_category_controller.py
- src/components/degree/AddDegreeCategory.vue
- src/components/degree/TemplateCategoryColumn.vue
- tests/test_api/test_degree_progress_category_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4024
> BOAC-4024, UI and API for /delete/category; deleting parent causes deletion of its descendants

- src/components/degree/AddDegreeCategory.vue
- src/mixins/DegreeEditSession.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4023
Placeholder for requirement-fulfillment options: Larry, Curly, Moe.
> BOAC-4023, enforce category/sub/course hierarchy; custom 'create new' form for type=course

- boac/api/degree_progress_controller.py
- boac/models/degree_progress_unit_requirement.py
- tests/test_api/test_degree_progress_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4019
> BOAC-4019: API for deleting a unit requirement

- boac/api/degree_progress_category_controller.py
- boac/api/note_templates_controller.py
- boac/api/notes_controller.py
- boac/api/util.py
- boac/models/degree_progress_category.py
- src/api/degree.ts
- src/components/degree/AddDegreeCategory.vue
- src/store/modules/degree-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4027
> BOAC-4027, degree progress: input 'units' and 'reqt fulfillments' when creating a course

- boac/api/degree_progress_category_controller.py
- boac/api/note_templates_controller.py
- boac/api/notes_controller.py
- boac/api/util.py
- boac/models/degree_progress_category.py
- boac/models/degree_progress_course_unit_requirement.py
- boac/models/degree_progress_unit_requirement.py
- scripts/db/drop_schema.sql
- scripts/db/migrate/2021/20210416-BOAC-4029/pre_deploy_01_degree_progress_course_unit_requirements.sql
- scripts/db/schema.sql
- src/components/degree/AddDegreeCategory.vue
- src/components/degree/DebugDegreeTemplate.vue
- src/components/degree/DegreeTemplateCategory.vue
- src/components/degree/DegreeTemplateCoursesTable.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/mixins/DegreeEditSession.vue
- src/store/modules/degree-edit-session.ts
- src/views/degree/DegreeTemplate.vue
- tests/test_api/test_degree_progress_category_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4029
Schema doc: https://docs.google.com/drawings/d/1PVCrQdontQj2zGFV_i9iD8TL51v9rdJhR92tWODHdH8/edit
Note: I switched notes-related code back to its original `get_note_topics_from_http_post`.
> BOAC-4029, 'degree_progress_course_unit_requirements' (db mapping table) to capture course metadata

- boac/api/degree_progress_category_controller.py
- boac/models/degree_progress_category.py
- boac/models/degree_progress_course_unit_requirement.py
- src/components/degree/DegreeTemplateCategory.vue
- src/components/degree/TemplateCategoryColumn.vue
- tests/test_api/test_degree_progress_category_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4023
IMO, more intuitive and cleaner.
> BOAC-4023, categories.to_api_json struct suitable to front-end rendering needs

- boac/api/degree_progress_category_controller.py
- boac/models/degree_progress_category.py
- src/api/degree.ts
- src/components/degree/DegreeTemplateCategory.vue
- src/components/degree/EditDegreeCategory.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/mixins/DegreeEditSession.vue
- src/store/modules/degree-edit-session.ts
- tests/test_api/test_degree_progress_category_controller.py
> BOAC-4025, API and UI to edit categories; UI for edit course is in-progress

- src/components/degree/Category.vue
- src/components/degree/CloneTemplateModal.vue
- src/components/degree/CoursesTable.vue
- src/components/degree/DebugTemplate.vue
- src/components/degree/EditCategory.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/views/degree/DegreeChecks.vue
- src/views/degree/DegreeTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4022
Not every Vue file needs 'Degree' in the name.  These filenames make it easier to identify purpose.
> BOAC-4022, simply renaming some front-end degree/ files

- src/components/degree/CoursesTable.vue
- src/components/degree/EditCategory.vue
- src/mixins/DegreeEditSession.vue
> BOAC-4025, front-end of edit course, in categories section of /degree/:id

- boac/models/degree_progress_template.py
- src/api/degree.ts
- src/components/degree/EditUnitRequirement.vue
- src/components/degree/UnitRequirements.vue
- src/mixins/DegreeEditSession.vue
- src/store/modules/degree-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4019
> BOAC-4019: Makes unit requirements deletable

- src/components/degree/CoursesTable.vue
- src/mixins/Util.vue
See https://stackoverflow.com/questions/9789723/css-text-overflow-in-a-table-cell
> BOAC-4025, table.td need its own flavor of truncate-with-ellipsis

- src/components/degree/EditUnitRequirement.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4030
> BOAC-4030: Fixes element id on unit reqt cancel button

- src/components/degree/Category.vue
- src/components/degree/EditCategory.vue
- src/components/degree/TemplateCategoryColumn.vue
> BOAC-4025, some UI tidying in category-column section of /degree/:id

- boac/externals/data_loch.py
- fixtures/loch/loch.sql
- tests/test_externals/test_data_loch.py
- tests/test_merged/test_advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3994
> BOAC-3994 Add ASC subject/body to notes API feed where available

- boac/api/degree_progress_category_controller.py
- src/components/degree/EditCategory.vue
- src/views/degree/DegreeTemplate.vue
And do not allow 'Course' creation when parent is nil.
> BOAC-4025, more UI touchup; disable submit via keypress.enter when not ready

- src/components/degree/EditCategory.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/mixins/DegreeEditSession.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4022
> BOAC-4022, more UI cleanup; bug fix on edit subcategory -> course

- boac/api/student_controller.py
- boac/api/util.py
- src/assets/styles/boac-global.css
- src/assets/styles/bootstrap-overrides.css
- src/components/student/profile/StudentClasses.vue
- src/components/student/profile/StudentProfileHeader.vue
- src/router.ts
- src/views/Student.vue
- src/views/degree/StudentDegreeCheck.vue
- src/views/degree/StudentDegreeCreate.vue
- tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4034
This new page uses same StudentPageHeader component, with `compact=true`.
> BOAC-4034, initial routes and page layout of /student/:uid/degree/create

- src/components/degree/EditUnitRequirement.vue
- src/components/degree/UnitRequirements.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4041
> BOAC-4041, disable column reqt actions while actioning a unit reqt

- src/components/degree/TemplateCategoryColumn.vue
- src/components/degree/UnitRequirements.vue
- src/views/degree/DegreeTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4038
Also, a tiny bit of CSS refactoring.
> BOAC-4038: Suppresses empty table headings; restores btn style

- boac/api/degree_progress_student_controller.py
- boac/api/student_controller.py
- boac/api/util.py
- boac/models/degree_progress_template.py
- boac/routes.py
- src/api/degree.ts
- src/assets/styles/boac-global.css
- src/components/degree/Category.vue
- src/components/degree/CoursesTable.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/components/student/profile/StudentClasses.vue
- src/components/student/profile/StudentProfileHeader.vue
- src/layouts/shared/ServiceAnnouncement.vue
- src/views/degree/StudentDegreeCheck.vue
- src/views/degree/StudentDegreeCreate.vue
- tests/test_api/test_degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4034
Design: https://jira.ets.berkeley.edu/jira/browse/BOAC-3870
> BOAC-4034, click 'save degree check' and route to /student/:uid/degree/:id

- src/components/degree/Category.vue
- src/components/degree/CoursesTable.vue
- src/components/degree/EditUnitRequirement.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/components/degree/UnitRequirements.vue
- src/views/degree/DegreeTemplate.vue
- src/views/degree/ManageDegreeChecks.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4040
Also, edit and delete icon buttons will have the same size and spacing across the board. Items within the template will have standard padding/alignment. See design Jira BOAC-3898.
> BOAC-4040: Validates unit reqt input; standardizes button styles

- src/mixins/DegreeEditSession.vue
- src/router.ts
- src/store/modules/degree-edit-session.ts
- src/views/degree/StudentDegreeCheck.vue
- src/views/degree/StudentDegreeHistory.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4035
> BOAC-4035, '/student/:uid/degree/:id' with current degree check highlighted

- boac/api/degree_progress_controller.py
- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_template.py
- tests/test_api/test_degree_progress_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4032
> BOAC-4032, if cloning degree template then be sure to clone template.unit_reqts, too

- src/components/degree/student/StudentDegreeCheckHeader.vue
- src/components/student/profile/StudentProfileHeader.vue
- src/components/student/profile/StudentProfileHeaderAcademics.vue
- src/components/student/profile/StudentProfileHeaderBio.vue
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4036
A cleaning was overdue for the header.
> BOAC-4036, tame the StudentProfileHeader component and tidy up formatting

- src/components/degree/Category.vue
- src/components/degree/CoursesTable.vue
- src/components/degree/EditCategory.vue
- src/components/degree/EditUnitRequirement.vue
- src/components/degree/UnitRequirements.vue
- src/views/degree/DegreeTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4039
Also, some CSS and responsiveness tweaks.
> BOAC-4039: Adds char counter to text inputs

- src/assets/styles/boac-global.css
- src/components/degree/student/StudentDegreeCheckHeader.vue
- src/components/student/profile/StudentPersonalDetails.vue
- src/components/student/profile/StudentProfileHeader.vue
- src/components/student/profile/StudentProfileHeaderAcademics.vue
- src/main.ts
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3870
And bug fixes:
* https://jira.ets.berkeley.edu/jira/browse/BOAC-4048
* https://jira.ets.berkeley.edu/jira/browse/BOAC-4047
> BOAC-3870 / BOAC-4048, UI work on sub-header component of /student/:uid/degree/:id and bug fixes

- boac/api/degree_progress_api_utils.py
- boac/api/degree_progress_controller.py
- boac/api/degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4046
> BOAC-4046, 'copy template' and 'create per student' use same clone-template code

- src/router.ts
- src/views/degree/ManageDegreeChecks.vue
- src/views/degree/PrintableDegreeTemplate.vue
Design: https://jira.ets.berkeley.edu/jira/browse/BOAC-3880
JIRA: https://jira.ets.berkeley.edu/jira/browse/BOAC-4011
> BOAC-4011: Initial version of printable degree

- src/components/appointment/DropInWaitlistAppointment.vue
- src/components/course/CourseStudents.vue
- src/components/matrix/Matrix.vue
- src/components/search/SortableStudents.vue
- src/components/student/StudentAvatar.vue
- src/components/student/StudentRow.vue
- src/components/student/profile/StudentProfileHeader.vue
- src/components/student/profile/StudentProfileHeaderBio.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4045
Standard header matches what it has been. The 'compact' version gives more room for degree-check content.
> BOAC-4045, student-profile-header 'compact' mode tweaks

- src/views/degree/ManageDegreeChecks.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4060
> BOAC-4060, flex-wrap and align-center for /manage degree-template actions

- boac/api/degree_progress_student_controller.py
- src/views/degree/StudentDegreeHistory.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4061
And minor front-end fix in `/degree/history`  promise.resolve.
> BOAC-4061, include sid when clone degree-template for student

- src/assets/styles/boac-global.css
- src/components/degree/Category.vue
- src/components/degree/CoursesTable.vue
- src/components/degree/EditCategory.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/components/degree/UnitRequirements.vue
- src/views/degree/DegreeTemplate.vue
- src/views/degree/ManageDegreeChecks.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4085
And, CSS tweaks to get `Create ... [+]` buttons aligned.
> BOAC-4085, disable Subcategory as child-of option when creating Subcategory

- boac/api/degree_progress_api_utils.py
- src/components/degree/student/EditUnassignedCourse.vue
- src/components/degree/student/UnassignedCourses.vue
- src/components/student/profile/StudentClasses.vue
- src/views/Error.vue
- src/views/degree/StudentDegreeCheck.vue
- src/views/degree/StudentDegreeHistory.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4087
> BOAC-4087 / BOAC-4085, cloned categories are mapped to clone.id, not template.id. Plus, initial UnassignedCourses component

- boac/models/degree_progress_category.py
- scripts/db/migrate/2021/20210416-BOAC-4033/pre_deploy_01_degree_progress_alter_category_course_units.sql
- scripts/db/schema.sql
- src/components/degree/EditCategory.vue
- tests/test_api/test_degree_progress_category_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4033
I opted not to add validation to ensure the 'min' is less than the 'max' - if a user decides to input '4-3', for example, that's on them.
> BOAC-4033: Allows category course units to be a numerical range

- boac/api/degree_progress_api_utils.py
- boac/api/degree_progress_student_controller.py
- boac/merged/student.py
- src/api/degree.ts
- src/components/degree/CoursesTable.vue
- src/components/degree/student/StudentDegreeCheckHeader.vue
- src/components/degree/student/UnassignedCourses.vue
- src/components/student/profile/StudentEnrollmentTerm.vue
- src/mixins/DegreeEditSession.vue
- src/store/modules/degree-edit-session.ts
- src/views/degree/DegreeTemplate.vue
- src/views/degree/StudentDegreeCheck.vue
- tests/test_api/test_degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4077
The `degree_progress_courses` db table is coming soon. See https://docs.google.com/drawings/d/1PVCrQdontQj2zGFV_i9iD8TL51v9rdJhR92tWODHdH8/edit
> BOAC-4077, /unassigned/courses API is a work-in-progress; includes UI touch-ups, too

- boac/api/degree_progress_api_utils.py
- src/components/degree/student/UnassignedCourses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4077
> BOAC-4077, UI tweaks to work-in-progress /unassigned/courses

- boac/api/degree_progress_api_utils.py
- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_course.py
- scripts/db/drop_schema.sql
- scripts/db/migrate/2021/20210420-BOAC-4065/pre_deploy_01_create_degree_progress_courses.sql
- scripts/db/schema.sql
- src/views/degree/CreateDegreeTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4065
Test coverage will follow.
> BOAC-4065, db script to create 'degree_progress_courses'; lazy load unassigned courses per degree-check id

- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_course.py
- scripts/db/migrate/2021/20210420-BOAC-4065/pre_deploy_01_create_degree_progress_courses.sql
- src/api/degree.ts
- src/components/degree/student/EditUnassignedCourse.vue
- src/components/degree/student/StudentDegreeCheckHeader.vue
- src/components/degree/student/UnassignedCourses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4066
> BOAC-4066, Degree Progress: edit course in 'Unassigned Courses'

- boac/api/degree_progress_category_controller.py
- boac/models/degree_progress_category.py
- src/api/degree.ts
- src/components/degree/EditCategory.vue
- src/store/modules/degree-edit-session.ts
- tests/test_api/test_degree_progress_category_controller.py
- tests/test_api/test_degree_progress_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4092
> BOAC-4092, bug fix: user can change parent of subcategory or course

- boac/api/user_controller.py
- boac/models/authorized_user.py
- src/api/user.ts
- src/views/degree/StudentDegreeHistory.vue
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4064
`updatedBy` is user.id, not user.uid.
> BOAC-4064, getCalnetProfileByUserId for /degree/history page

- src/assets/styles/boac-global.css
- src/components/degree/Category.vue
- src/components/degree/CoursesTable.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/components/degree/UnitRequirements.vue
- src/components/degree/student/UnassignedCourses.vue
- src/views/degree/DegreeTemplate.vue
- src/views/degree/PrintableDegreeTemplate.vue
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4086
Designs: https://jira.ets.berkeley.edu/jira/browse/BOAC-3898
> BOAC-4086, /degree/template styling to match designs

- src/components/degree/Category.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4094
> BOAC-4094, delete modal needs 'categoryType' in header

- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_note.py
- boac/models/degree_progress_template.py
- scripts/db/drop_schema.sql
- scripts/db/migrate/2021/20210420-BOAC-4042/pre_deploy_01_degree_progress_notes.sql
- scripts/db/schema.sql
- tests/test_api/test_degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4042
> BOAC-4042: Degree note table, model, and API

- src/components/degree/student/CourseAssignmentMenu.vue
- src/components/degree/student/UnassignedCourses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4073
This initial pass will allow us to verify content of the dropdown. The UI is not styled.
> BOAC-4073, initial dropdown to assign course to degree requirement

- src/components/degree/CoursesTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4096
> BOAC-4096, Degree Progress: better use of space in courses-table of column/category section

- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_course.py
- src/api/degree.ts
- src/components/degree/student/CourseAssignmentMenu.vue
- tests/test_api/test_degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4070
> BOAC-4070, API to assign a course to a degree-check requirement

- boac/models/degree_progress_category.py
- src/assets/styles/boac-global.css
- src/components/degree/CoursesTable.vue
- src/components/degree/student/CourseAssignmentMenu.vue
- src/views/degree/DegreeTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4067
> BOAC-4067, category and subcategory must be selectable in dropdown to assign course to reqt

- boac/models/degree_progress_category.py
- boac/models/degree_progress_course.py
- src/components/degree/CoursesTable.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/components/degree/student/CourseAssignmentMenu.vue
- src/components/degree/student/UnassignedCourses.vue
- tests/test_api/test_degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4099
> BOAC-4099, advisor drag/drop an unassigned course to an empty category or subcategory

- boac/api/degree_progress_controller.py
- boac/models/degree_progress_note.py
- boac/models/degree_progress_template.py
- src/api/degree.ts
- src/components/degree/student/StudentDegreeCheckHeader.vue
- src/mixins/DegreeEditSession.vue
- src/store/modules/degree-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4079
> BOAC-4079: Surfaces degree notes on the student page

- src/components/degree/CoursesTable.vue
- src/components/degree/student/StudentDegreeCheckHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4091
> BOAC-4091, if course/category satisfies 2+ reqts then badge-with-count, after ellipsis

- src/components/degree/student/CourseAssignmentMenu.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4103
> BOAC-4103, assign-course-to-category menu option is disabled if category reqt is fulfilled

- src/components/degree/CoursesTable.vue
- src/components/degree/student/CourseAssignmentMenu.vue
- src/components/degree/student/UnassignedCourses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4104
The Jira has more info.
> BOAC-4104, remove 'responsive' from b-table so assign-course dropdown can overflow

- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_category.py
- boac/models/degree_progress_course.py
- src/components/degree/CoursesTable.vue
- src/components/degree/student/CourseAssignmentMenu.vue
- src/store/modules/degree-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4069
> BOAC-4069, offer 'Unassign' option if course is assigned to category

- src/components/degree/CoursesTable.vue
- src/components/degree/EditCategory.vue
- src/components/degree/UnitRequirements.vue
- src/views/degree/ManageDegreeChecks.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4090
> BOAC-4090, properly disable unit-reqt options; UI fix on /create/degree_check page

- boac/api/reports_controller.py
- boac/merged/reports.py
- boac/models/note_topic.py
- tests/test_api/test_reports_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3918
> BOAC-3918, include topics in the notes-metadata download CSV

- boac/api/degree_progress_api_utils.py
- boac/api/degree_progress_category_controller.py
- boac/models/degree_progress_category.py
- src/api/degree.ts
- src/components/degree/CoursesTable.vue
- src/components/degree/EditCategory.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/store/modules/degree-edit-session.ts
- tests/test_api/test_degree_progress_category_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4115
https://jira.ets.berkeley.edu/jira/browse/BOAC-4101
https://jira.ets.berkeley.edu/jira/browse/BOAC-4116
Plus, element id fix.
> BOAC-4115 / BOAC-4101, in degree progress templates API, 'courseUnits' is now 'units'

- boac/api/degree_progress_api_utils.py
- boac/api/degree_progress_category_controller.py
- boac/models/degree_progress_category.py
- scripts/db/migrate/2021/20210426-BOAC-4117/pre_deploy_01_change_degree_progress_category_types.sql
- scripts/db/schema.sql
- src/components/degree/EditCategory.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/components/degree/student/CourseAssignmentMenu.vue
- src/mixins/DegreeEditSession.vue
- tests/test_api/test_degree_progress_category_controller.py
- tests/test_api/test_degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4117
Postgres 10+ offers an easier way to rename enum label:  https://stackoverflow.com/questions/12627830/rename-enum-item-in-postgresql
> BOAC-4117, in degree_progress_category_type (db enum) rename 'Course' to 'Course Requirement'

- src/components/degree/student/StudentDegreeCheckHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4105
> BOAC-4105: Refreshes advisor name after note edit

- src/components/degree/Category.vue
- src/components/degree/CoursesTable.vue
- src/views/degree/ManageDegreeChecks.vue
- src/views/degree/PrintableDegreeTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4058
> BOAC-4058: Added categories, subcategories, courses to print view

- boac/api/degree_progress_api_utils.py
- boac/api/degree_progress_category_controller.py
- boac/models/degree_progress_category.py
- scripts/db/migrate/2021/20210426-BOAC-4117/pre_deploy_01_change_degree_progress_category_types.sql
- scripts/db/schema.sql
- src/components/degree/EditCategory.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/components/degree/student/CourseAssignmentMenu.vue
- src/mixins/DegreeEditSession.vue
- tests/test_api/test_degree_progress_category_controller.py
- tests/test_api/test_degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4117
This reverts #2959
We want a more traditional approach to modifying db enum (type).
> BOAC-4117, Revert commit: degree_progress_category_type (db enum) rename 'Course' to 'CourseRequirement'

- boac/api/degree_progress_api_utils.py
- boac/api/degree_progress_category_controller.py
- boac/models/degree_progress_category.py
- scripts/db/migrate/2021/20210426-BOAC-4117/pre_deploy_01_change_degree_progress_category_types.sql
- scripts/db/schema.sql
- src/components/degree/EditCategory.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/components/degree/student/CourseAssignmentMenu.vue
- src/mixins/DegreeEditSession.vue
- tests/test_api/test_degree_progress_category_controller.py
- tests/test_api/test_degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4117
A safer and simpler way to modify db enum:
https://blog.yo1.dog/updating-enum-values-in-postgresql-the-safe-and-easy-way/
> BOAC-4117, alter degree_progress_category_types, rename 'Course' TO 'Course Requirement'

- boac/api/degree_progress_controller.py
- boac/models/degree_progress_category.py
- boac/models/degree_progress_template.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4102
> BOAC-4102, predictable order in unit_requirements list (templates, categories)

- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_course.py
- scripts/db/drop_schema.sql
- scripts/db/migrate/2021/20210427-BOAC-4053/pre_deploy_01_alter_degree_progress_course_pk.sql
- scripts/db/schema.sql
- src/api/degree.ts
- src/components/degree/CoursesTable.vue
- src/components/degree/student/EditUnassignedCourse.vue
- src/store/modules/degree-edit-session.ts
- tests/test_api/test_degree_progress_student_controller.py
This change is based on feedback in PR #2955 (cc: @pauline2k)
> BOAC-4053, degree_progress_courses table gets 'id' column, the new primary-key

- boac/api/degree_progress_api_utils.py
- boac/models/degree_progress_category.py
- boac/models/degree_progress_course.py
- scripts/db/drop_schema.sql
- scripts/db/migrate/2021/20210427-BOAC-4124/pre_deploy_01_degree_progress_course_add_degree_check_id.sql
- scripts/db/schema.sql
- src/components/degree/CoursesTable.vue
- src/components/degree/student/CourseAssignmentMenu.vue
- src/components/degree/student/UnassignedCourses.vue
- tests/test_api/test_degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4124
I recommend reading the BOAC-4124 description.
> BOAC-4124, add non-nullable degree_check_id to degree_progress_courses table

- src/router.ts
- src/views/degree/BatchDegreeCheck.vue
- src/views/degree/ManageDegreeChecks.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4107
https://jira.ets.berkeley.edu/jira/browse/BOAC-4108
> BOAC-4107, BOAC-4108: Adds batch degree check link+view

- src/components/degree/CoursesTable.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/components/degree/student/AddCourseToCategory.vue
- src/components/degree/student/UnassignedCourses.vue
Gives Teena a preview of form element ids.
> BOAC-4053, AddCourseToCategory component with mocked up select

- boac/models/degree_progress_category.py
- src/components/degree/CoursesTable.vue
- src/components/degree/student/AddCourseToCategory.vue
- src/mixins/DegreeEditSession.vue
- src/store/modules/degree-edit-session.ts
> BOAC-4053, use 'Add Course' menu and we must create placeholder 'Course Requirement'

- src/router.ts
- src/views/degree/PrintableDegreeTemplate.vue
& cleaned up some unnecessary CSS 
https://jira.ets.berkeley.edu/jira/browse/BOAC-4057
> BOAC-4057: Removed sidebar, header, edit/remove buttons from degree prnt

- src/store/modules/degree-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4088
> BOAC-4088, state.disableButtons = false when reset() in degree-edit-session

- boac/api/degree_progress_api_utils.py
- boac/api/degree_progress_controller.py
- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_category.py
- boac/models/degree_progress_course.py
- boac/models/degree_progress_template.py
- src/api/degree.ts
- src/components/degree/CoursesTable.vue
- src/components/degree/EditUnitRequirement.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/components/degree/UnitRequirements.vue
- src/components/degree/student/AddCourseToCategory.vue
- src/components/degree/student/StudentDegreeCheckHeader.vue
- src/components/degree/student/UnassignedCourses.vue
- src/mixins/DegreeEditSession.vue
- src/store/modules/degree-edit-session.ts
- src/views/degree/DegreeTemplate.vue
- src/views/degree/PrintableDegreeTemplate.vue
- src/views/degree/StudentDegreeCheck.vue
- tests/test_api/test_degree_progress_student_controller.py
PR includes:
* 'Add Course' menu populated
* simplify the degree-edit-session store a bit
* removed dedicated `/unassigned` endpoint
> BOAC-4053, /api/degree response packages assigned and unassigned courses

- boac/api/degree_progress_category_controller.py
- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_category.py
- boac/models/degree_progress_course.py
- src/components/degree/CoursesTable.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/components/degree/student/AddCourseToCategory.vue
- src/components/degree/student/CourseAssignmentMenu.vue
- src/mixins/DegreeEditSession.vue
- src/views/degree/PrintableDegreeTemplate.vue
- tests/test_api/test_degree_progress_student_controller.py
> BOAC-4053, category.courseIds order determines primary and secondary assignments

- src/components/degree/EditUnitRequirement.vue
- src/components/degree/UnitRequirements.vue
- src/views/degree/DegreeTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4128
Regression caused by my refactor of `editMode`.
> BOAC-4128, fix edit-unit-reqts component, with additional focus and sr-alerts

- src/views/degree/PrintableDegreeTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4142
> BOAC-4142: Print: unit reqs table now renders only if they exist

- src/components/degree/CoursesTable.vue
- src/components/degree/UnitRequirements.vue
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4080
Use `?w=1`
> BOAC-4080, in /degree/student view, do not offer 'add/edit reqt'

- boac/api/degree_progress_category_controller.py
- boac/api/degree_progress_student_controller.py
- boac/lib/util.py
- boac/models/degree_progress_category.py
- boac/models/degree_progress_course.py
- src/api/degree.ts
- src/components/degree/CoursesTable.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/components/degree/student/AddCourseToCategory.vue
- src/mixins/DegreeEditSession.vue
- src/store/modules/degree-edit-session.ts
- tests/test_api/test_degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4061
Elaborate rules verified in test coverage.
> BOAC-4061, /course/copy with test coverage

- boac/lib/cohort_utils.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3981
> BOAC-3981, 'Future' terms first in EGT cohort filter options

- boac/api/degree_progress_api_utils.py
- boac/api/degree_progress_controller.py
- boac/api/student_controller.py
- boac/api/util.py
- boac/models/degree_progress_category.py
- boac/models/degree_progress_template.py
- src/components/degree/CoursesTable.vue
- src/components/degree/TemplateCategoryColumn.vue
- tests/test_api/test_degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4147
`isCopy` decides edit/delete options per course.
> BOAC-4147, courses in /degree/:id feed have isCopy flag

- src/components/note/create/CreateNoteModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4125
> BOAC-4125, bump up z-index of CreateNote modal

- src/components/degree/student/EditUnassignedCourse.vue
- src/components/degree/student/UnassignedCourses.vue
- src/mixins/DegreeEditSession.vue
- src/store/modules/degree-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4150
> BOAC-4150, refresh /degree/:id view after updateCourse

- src/components/degree/CoursesTable.vue
- src/components/degree/student/AddCourseToCategory.vue
- src/components/degree/student/EditCourse.vue
- src/components/degree/student/UnassignedCourses.vue
- src/store/modules/degree-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4080
https://jira.ets.berkeley.edu/jira/browse/BOAC-4154
> BOAC-4080, use EditCourse component when editing (un)assigned courses

- src/components/degree/CoursesTable.vue
- src/components/degree/student/EditCourse.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4145
https://jira.ets.berkeley.edu/jira/browse/BOAC-4156
And no 'Add Course' in `/degree/template` view.
> BOAC-4145, if copied-course units differ from original then show appropriate icon

- src/assets/styles/boac-global.css
- src/components/degree/Category.vue
- src/components/degree/CoursesTable.vue
- src/components/degree/EditCategory.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/components/degree/student/AddCourseToCategory.vue
- src/components/degree/student/CourseAssignmentMenu.vue
- src/components/degree/student/EditCourse.vue
- src/components/degree/student/StudentDegreeCheckHeader.vue
- src/views/degree/StudentDegreeCreate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4140
Designs: https://jira.ets.berkeley.edu/jira/browse/BOAC-3896
> BOAC-3896, /degree/:id UX cleanup, table alignment

- src/components/degree/UnitRequirements.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3862
The 'Completed' column now needs data.
> BOAC-4140, if student then 'Completed' column in UnitRequirements else allow no actions/edits

- boac/api/degree_progress_student_controller.py
- src/api/degree.ts
- src/components/degree/CoursesTable.vue
- src/components/degree/EditCategory.vue
- src/components/degree/SelectUnitFulfillment.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/components/degree/student/EditCourse.vue
- src/components/degree/student/UnassignedCourses.vue
- src/store/modules/degree-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4158
https://jira.ets.berkeley.edu/jira/browse/BOAC-4151
> BOAC-4158, no Add-Course-to-category if has SubCat; reusable select-units component

- src/components/degree/CoursesTable.vue
- src/components/degree/student/AddCourseToCategory.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4159
> BOAC-4159, 'Copy Course' dropdown has only assigned; disable btn if that list is empty

- src/components/degree/CoursesTable.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/components/degree/student/CourseAssignmentMenu.vue
- src/components/degree/student/EditCourse.vue
- src/mixins/DegreeEditSession.vue
- src/views/degree/StudentDegreeCreate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4153
> BOAC-4153, (sub)categories get a single CoursesTable, which concats courses and course-reqts

- src/components/degree/CoursesTable.vue
- src/components/degree/student/StudentDegreeCheckHeader.vue
- src/views/degree/PrintableDegreeTemplate.vue
Notes, Course requirements: https://jira.ets.berkeley.edu/jira/browse/BOAC-4084 
Notes toggle: https://jira.ets.berkeley.edu/jira/browse/BOAC-4141
> BOAC-4084: Added notes, notes toggle, style changes to print view

- boac/api/student_controller.py
- boac/externals/data_loch.py
- src/api/student.ts
- src/mixins/Validator.vue
- src/views/degree/BatchDegreeCheck.vue
- tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4108
> BOAC-4108: Batch degree check form accepts list of SIDs

- src/components/degree/EditCategory.vue
- src/components/degree/student/CourseAssignmentMenu.vue
- src/mixins/DegreeEditSession.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4140
> BOAC-4140, improved disable-select-option logic in CourseAssignmentMenu

- scripts/db/migrate/2021/20210416-BOAC-4033/pre_deploy_01_degree_progress_alter_category_course_units.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-4033
> BOAC-4033: Removes failing UPDATE from SQL migration

- scripts/db/migrate/2021/20210416-BOAC-4033/pre_deploy_01_degree_progress_alter_category_course_units.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-4033
master PR is #2994
> [QA] BOAC-4033: Removes failing UPDATE from SQL migration

- boac/models/degree_progress_category.py
- boac/models/degree_progress_course.py
- scripts/db/migrate/2021/20210505-BOAC-4146/pre_deploy_01_degree_progress_units_decimal_type.sql
- scripts/db/schema.sql
- src/components/degree/CoursesTable.vue
- src/components/degree/UnitRequirements.vue
- src/components/degree/student/UnassignedCourses.vue
- src/components/student/profile/StudentClasses.vue
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4149
https://jira.ets.berkeley.edu/jira/browse/BOAC-4148
Release instructions: https://docs.google.com/document/d/18rEK9PGCo43OujXHhbuKhAdwxuh4BsQe2rrS_WsN-14
I snuck in a few minor UI fixes.
> BOAC-4149, type 'decimal' for units column in degree_progress_courses; convert int4range to numrange in categories

- boac/models/degree_progress_category.py
- boac/models/degree_progress_category_unit_requirement.py
- boac/models/degree_progress_unit_requirement.py
- scripts/db/drop_schema.sql
- scripts/db/migrate/2021/20210506-BOAC-4146/pre_deploy_create_course_unit_requirements_table.sql
- scripts/db/schema.sql
- src/components/degree/Category.vue
- src/components/degree/CoursesTable.vue
- src/components/degree/UnitRequirements.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4146
Also, we reuse the name `degree_progress_course_unit_requirement` for a new mapping table to match reqts in the Jira. I will create the model class in next PR.
Release instructions updated: https://docs.google.com/document/d/18rEK9PGCo43OujXHhbuKhAdwxuh4BsQe2rrS_WsN-14
> BOAC-4146, rename 'degree_progress_course_unit_requirement' table per category_id fkey

- boac/api/degree_progress_category_controller.py
- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_course.py
- boac/models/degree_progress_course_unit_requirement.py
- boac/models/degree_progress_unit_requirement.py
- scripts/db/migrate/2021/20210506-BOAC-4146/pre_deploy_create_course_unit_requirements_table.sql
- src/api/degree.ts
- src/components/degree/EditCategory.vue
- src/components/degree/UnitsInput.vue
- src/components/degree/student/EditCourse.vue
- src/store/modules/degree-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4146
> BOAC-4146, py models, API and UI for course-to-unit-requirement mapping

- src/components/degree/CoursesTable.vue
- src/components/degree/student/EditCourse.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4146
Designs: https://jira.ets.berkeley.edu/jira/browse/BOAC-3872
> BOAC-4146, if course fulfills some or all category unit-requirements then show alert

- boac/api/degree_progress_student_controller.py
- boac/api/student_controller.py
- boac/externals/data_loch.py
- src/api/degree.ts
- src/api/student.ts
- src/views/degree/PrintableDegreeTemplate.vue
- src/views/degree/StudentDegreeCheck.vue
- src/views/degree/StudentDegreeCreate.vue
- src/views/degree/StudentDegreeHistory.vue
- tests/test_api/test_degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4164
> BOAC-4164, /degree/student performance bump by fetching lightweight student profile

- boac/api/degree_progress_category_controller.py
- boac/api/degree_progress_controller.py
- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_template.py
- boac/models/degree_progress_unit_requirement.py
- tests/test_api/test_degree_progress_category_controller.py
- tests/test_api/test_degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4123
> BOAC-4123, certain updates will update the updated_at of top-level record

- src/api/degree.ts
- src/components/degree/CoursesTable.vue
- src/components/degree/UnitsInput.vue
- src/components/degree/student/UnassignedCourses.vue
- src/mixins/DegreeEditSession.vue
- src/store/modules/degree-edit-session.ts
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4055
Because this page is complex, using native drag-and-drop API – instead of a third-party Vue.js lib – will keep our code cleaner and give us more control.
> BOAC-4055, drag assigned course to 'Unassigned' to unassign using native Drag API

- src/components/degree/DegreeTemplatesMenu.vue
- src/components/util/BatchAddStudentSet.vue
- src/views/degree/BatchDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4110
> BOAC-4110: Populates degree templates for batch create

- src/components/degree/CoursesTable.vue
- src/components/degree/student/StudentDegreeCheckHeader.vue
- src/components/degree/student/UnassignedCourses.vue
- src/store/modules/degree-edit-session.ts
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4170
The 'context' var has been split into dragContext (the initial grab) and dropContext (the endpoint).
> BOAC-4170, drag unassigned to empty course-requirements will assign to parent-category

- src/components/degree/CoursesTable.vue
- src/components/degree/student/CourseAssignmentMenu.vue
- src/mixins/DegreeEditSession.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4174
> BOAC-4174, drop unassigned on course-requirement; reuse logic of CourseAssignMenu

- src/components/degree/CoursesTable.vue
- src/components/degree/student/CourseAssignmentMenu.vue
- src/components/degree/student/UnassignedCourses.vue
- src/mixins/DegreeEditSession.vue
- src/store/modules/degree-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4172
The styles-during-drag are a work in progress. Also, console debug logging in local-dev env only.
> BOAC-4172, drag assigned course to a course requirement elsewhere in degree check

- src/assets/styles/boac-global.css
- src/components/degree/CoursesTable.vue
- src/components/degree/UnitRequirements.vue
- src/components/degree/student/CourseAssignmentMenu.vue
- src/components/degree/student/UnassignedCourses.vue
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4172
https://jira.ets.berkeley.edu/jira/browse/BOAC-4181
Also, more style tweaks. E.g., more real estate for course names.
> BOAC-4172, drag a tr and it becomes rounded, dark blue, and ready for fun

- boac/models/degree_progress_template.py
- src/assets/styles/boac-global.css
- src/components/degree/CoursesTable.vue
- src/components/degree/student/UnassignedCourses.vue
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4183
And a `tr` width fix.
> BOAC-4183, use postgres builtin  instead of passing in date arg

- boac/lib/util.py
- boac/models/degree_progress_category.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4183
> BOAC-4183, verify valid float before putting numeric-range in db

- boac/api/degree_progress_api_utils.py
- boac/api/degree_progress_student_controller.py
- src/api/degree.ts
- src/views/degree/BatchDegreeCheck.vue
- tests/test_api/test_degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4111
More work is needed to improve performance. I'm planning to switch the `clone` function to bulk SQL inserts, similar to how batch note creation works.
> BOAC-4111: Degree check batch creation

- src/assets/styles/boac-global.css
- src/components/degree/CoursesTable.vue
- src/store/modules/degree-edit-session.ts
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4173
> BOAC-4173, drag events need preventDefault() to drop effectively

- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_template.py
- src/api/degree.ts
- src/components/degree/DegreeTemplatesMenu.vue
- src/components/util/BatchAddStudentSet.vue
- src/views/degree/BatchDegreeCheck.vue
- tests/test_api/test_degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4112
> BOAC-4112: Alerts user to students already assigned degree check

- src/components/degree/Category.vue
- src/components/degree/CoursesTable.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/components/degree/UnitRequirements.vue
- src/components/degree/student/AddCourseToCategory.vue
- src/components/degree/student/CourseAssignmentMenu.vue
- src/components/degree/student/UnassignedCourses.vue
- src/views/degree/DegreeTemplate.vue
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4132
> BOAC-4132, degree progress: 'student' prop not necessary cuz 'sid' is in vuex session

- boac/api/degree_progress_api_utils.py
- boac/models/degree_progress_template.py
- scripts/db/drop_schema.sql
- scripts/db/migrate/2021/20210517-BOAC-4138/pre_deploy_01_add_parent_template_id.sql
- scripts/db/schema.sql
- tests/test_api/test_degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4138
> BOAC-4138: Adds parent_template_id to templates table

- boac/api/degree_progress_controller.py
- src/components/degree/student/StudentDegreeCheckHeader.vue
- src/mixins/DegreeEditSession.vue
- src/store/modules/degree-edit-session.ts
- tests/test_api/test_degree_progress_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4139
> BOAC-4139: Adds revision indicator to student degree check

- src/components/student/TermSelector.vue
- src/views/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4186
> BOAC-4186: Hides term selector on admit cohorts

- boac/api/degree_progress_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4190
> BOAC-4190, degree-check with deleted parent (template) is legit

- src/assets/styles/boac-global.css
- src/components/degree/CoursesTable.vue
- src/components/degree/UnitRequirements.vue
- src/components/degree/student/UnassignedCourses.vue
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4181
I'll apply the same improvements to `UnassignedCourses` in next PR.
> BOAC-4181, improved CSS for /degree/check courses table (during drag, etc.)

- src/components/degree/CoursesTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4181
> BOAC-4181, do not reference course.id if course is nil

- src/components/degree/CoursesTable.vue
- src/components/degree/student/UnassignedCourses.vue
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4181
> BOAC-4181, CSS cleanup applied to UnassignedCourses component

- package-lock.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/BOAC-4161
> BOAC-4161: Updates highcharts to v9.1

- src/components/degree/CoursesTable.vue
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4200
> BOAC-4200: in some cases, event.stopPropagation() is needed for drag-and-drop

- src/components/degree/CoursesTable.vue
- src/store/modules/degree-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4200
> BOAC-4200, drag from 'assigned' to empty (sub)category

- src/components/degree/CoursesTable.vue
- src/components/degree/EditCategory.vue
- src/components/degree/EditUnitRequirement.vue
- src/components/degree/UnitsInput.vue
- src/components/degree/student/EditCourse.vue
- src/mixins/DegreeEditSession.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4183
> BOAC-4183, more intuitive shared UnitsInput component

- src/components/degree/EditCategory.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4208
> BOAC-4208, units validation iff 'Course Requirement' selected

- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_course.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4212
> BOAC-4212, no Boom! when copy course with unit fulfillment

- src/main.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4162
> BOAC-4162: Skips error page when error should be displayed inline

- src/components/degree/EditCategory.vue
- src/components/degree/UnitsInput.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4209
https://jira.ets.berkeley.edu/jira/browse/BOAC-4210
> BOAC-4209, no units validation for 'Course Reqt'

- boac/models/degree_progress_template.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4207
> BOAC-4207, order /degrees page by degree_name

- src/components/degree/CoursesTable.vue
- src/mixins/DegreeEditSession.vue
- src/store/modules/degree-edit-session.ts
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4189
https://jira.ets.berkeley.edu/jira/browse/BOAC-4214
Scrolling is paused when you hover a droppable div.
> BOAC-4189, smooth scroll when dragging course

- src/views/degree/PrintableDegreeTemplate.vue
It wasn't until I was about to submit this that I realized it was my external monitor's settings that made the text basically invisible 🤦‍♂️
> BOAC-4126: Added support for blur mode on print view

- boac/models/degree_progress_template.py
- src/components/degree/CoursesTable.vue
- src/components/degree/student/UnassignedCourses.vue
- src/mixins/DegreeEditSession.vue
- tests/test_api/test_degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4213
Our has-units-diff calculation has nothing to do with units value of the course-requirement to which course is assigned.
> BOAC-4213, units diff indicator for assigned and unassigned courses

- boac/models/degree_progress_template.py
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4189
And, sort unassigned courses by name.
> BOAC-4189, only trigger scroll when dragging from unassigned courses

- src/components/degree/student/StudentDegreeCheckHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4223
> BOAC-4223, offer edit note iff currentUser.canEditDegreeProgress

- src/components/degree/student/EditCourse.vue
- src/components/degree/student/StudentDegreeCheckHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4192
And, edit-unit-requirements should only be available for assigned courses.
> BOAC-4192, open new tab for /printable degree check

- src/components/degree/student/UnassignedCourses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4203
> BOAC-4203, fix formatting on read-only unassigned courses table

- src/components/degree/Category.vue
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4195
And, improve scroll-when-dragging.  cc: @pfarestveit
> BOAC-4195, drop to category/subcategory header to assign as additional (phantom) reqt

- boac/models/degree_progress_course.py
- boac/models/degree_progress_template.py
- scripts/db/migrate/2021/20210602-BOAC-4229/pre_deploy_add_column_ignore_to_degree_progress_courses.sql
- scripts/db/schema.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-4230
> BOAC-4230, add column 'ignore' to degree_progress_courses table

- boac/api/degree_progress_student_controller.py
- src/api/degree.ts
- src/components/degree/student/UnassignedCourses.vue
- src/layouts/shared/ServiceAnnouncement.vue
- src/store/modules/degree-edit-session.ts
- src/views/degree/StudentDegreeCheck.vue
- tests/test_api/test_degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4231
https://jira.ets.berkeley.edu/jira/browse/BOAC-4232
We pay attention to the 'ignore' param iff categoryId is null.
> BOAC-4231 / BOAC-4232, API gets 'ignore' option; reuse UnassignedCourses for Ignored

- src/components/degree/student/CourseAssignmentMenu.vue
- src/components/degree/student/UnassignedCourses.vue
- src/store/modules/degree-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4238
https://jira.ets.berkeley.edu/jira/browse/BOAC-4237
The snarky "Junk" label is a placeholder.
> BOAC-4238, 'junk drawer' option in CourseAssignmentMenu

- src/assets/styles/boac-global.css
- src/components/degree/Category.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4232
> BOAC-4232, UI cleanup on Unassigned and Ignored sections

- src/components/degree/Category.vue
- src/components/degree/student/StudentDegreeCheckHeader.vue
- src/mixins/DegreeEditSession.vue
- src/store/modules/degree-edit-session.ts
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4235
The quest for smooth scrolling continues.
> BOAC-4235, smooth drag-n-drop for unassigned courses and other junk

- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_course_unit_requirement.py
- src/components/degree/UnitRequirements.vue
- src/mixins/DegreeEditSession.vue
- src/store/modules/degree-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4134
> BOAC-4134, calculate completed unit requirements based on unit values of assigned courses

- src/components/degree/student/UnassignedCourses.vue
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4229
> BOAC-4229, put 'responsive' attribute on unassigned/junk tables

- src/components/degree/Category.vue
- src/store/modules/degree-edit-session.ts
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4235
> BOAC-4235, another attempt at smooth scrolling during drag

- boac/api/student_controller.py
- src/components/student/profile/StudentClasses.vue
- tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4241
> BOAC-4241, show 'Degree Checks' link if (1) is CoE student or (2) non-CoE with degree check(s)

- boac/api/util.py
- src/mixins/Berkeley.vue
- tests/test_api/test_cohort_controller.py
- tests/test_api/test_curated_group_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4206
> BOAC-4206 Per-term GPA for CSV download

- src/components/HeaderMenu.vue
- src/components/student/profile/StudentClasses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4239
> BOAC-4239, CoE advisor can view/create degree-checks for any student

- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_course.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4227
And, un-assign course -> remove unit_requirements
> BOAC-4227, assign course to category -> inherit unit_requirements

- src/components/degree/Category.vue
- src/components/degree/CoursesTable.vue
- src/views/degree/PrintableDegreeTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4193
> BOAC-4193, Degree Progress: /printable view should have neither edit, delete, nor assign options

- boac/api/cache_utils.py
- boac/externals/data_loch.py
- boac/models/development_db.py
- boac/models/university_dept.py
- fixtures/loch/loch.sql
- tests/test_api/test_cache_utils.py
- tests/test_externals/test_data_loch.py
- tests/test_models/test_university_dept.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-3975
> BOAC-3975: Uses loch data for degree progress auto-permissioning

- src/components/degree/student/StudentDegreeCheckHeader.vue
- src/views/degree/PrintableDegreeTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4194
> BOAC-4194, respect include-note-in-print flag when open /printable in new tab

- src/components/degree/CoursesTable.vue
- src/components/degree/UnitRequirements.vue
- src/views/degree/PrintableDegreeTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4194
Includes indentation tweaks, use `?w=1` to see actual diff.
> BOAC-4194, no icons/alerts on /printable; CSS styles per reqts

- src/assets/styles/boac-global.css
- src/components/degree/Category.vue
- src/components/degree/CoursesTable.vue
- src/components/degree/UnitRequirements.vue
- src/views/degree/PrintableDegreeTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4194
Designs: https://jira.ets.berkeley.edu/jira/browse/BOAC-3880
> BOAC-4194, finishing touches on styles of /printable

- src/components/degree/UnitRequirements.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4244
> BOAC-4244, a bit of whitespace between 'Min' and 'Completed'

- src/components/degree/DebugTemplate.vue
- src/views/degree/StudentDegreeCheck.vue
A bit more attractive and a little less obtrusive.
> NOJIRA, tidy up the DebugDegreeTemplate component

- src/components/degree/UnitRequirements.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4247
> BOAC-4247, calculate unit totals on course unit-fulfillments (ignore categories)

- src/components/student/profile/StudentCourse.vue
- src/components/student/profile/StudentEnrollmentTerm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4020
> BOAC-4020 Reposition grade alert icons on student profile

- src/components/degree/EditCategory.vue
- src/components/degree/UnitRequirements.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4196
Also fixes a bug with creating/updating unit requirements in the template builder:
https://jira.ets.berkeley.edu/jira/browse/BOAC-4250
> BOAC-4196: Allows cats, subcats to be linked to unit reqts; BOAC-4250

- src/components/degree/UnitRequirements.vue
- src/store/modules/degree-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4196
> BOAC-4196: Refreshes template when unit requirements change

- src/components/degree/UnitRequirements.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4250
> BOAC-4250: Hides unit reqts table footer in template builder

- boac/models/degree_progress_category_unit_requirement.py
- boac/models/degree_progress_unit_requirement.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4249
> BOAC-4249, delete category_to_unit_requirement mappings before delete of unit_requirement

- src/components/degree/CoursesTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4252
> BOAC-4252, if category has course X then deny copies of course X to be dropped on that category

- src/components/degree/CoursesTable.vue
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4253
> BOAC-4253, courses in category w/o reqts: fix logic of isEditing(...) to open proper edit form

- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_course.py
- src/components/degree/student/AddCourseToCategory.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4196
> BOAC-4196: Copied course inherits unit reqts of its parent category

- src/components/degree/student/CourseAssignmentMenu.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4256
> BOAC-4256, CourseAssignmentMenu accounts for new "placeholder" category type

- src/components/degree/CoursesTable.vue
- src/mixins/Util.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4255
> BOAC-4255: Shows indicator only when course fulfillments are edited

- src/components/degree/CoursesTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4258
> BOAC-4258: Puts unique IDs on course edit, delete buttons

- boac/models/degree_progress_category.py
- src/components/degree/CoursesTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4263
> BOAC-4263: Gives course/category rows a contextual ID

- src/components/degree/DebugTemplate.vue
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4235
Event listeners track drag and scroll. Auto-scroll only if the drag is in lower region (< 100) of viewport.
> BOAC-4235, tamer scroll when dragging degree-check courses

- src/components/util/Autocomplete.vue
- src/views/degree/BatchDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4240
> BOAC-4240: Removes autocomplete functionality from batch degree check

- src/components/degree/student/CourseAssignmentMenu.vue
- src/components/degree/student/UnassignedCourses.vue
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4260
> BOAC-4260, if course.isCopy then unassigned & junk are not droppable

- boac/api/curated_group_controller.py
- boac/api/degree_progress_category_controller.py
- boac/api/degree_progress_controller.py
- boac/api/degree_progress_student_controller.py
- requirements.txt
- src/components/degree/Category.vue
- src/components/degree/CoursesTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4261
https://jira.ets.berkeley.edu/jira/browse/BOAC-4272
And:
* remove flask-cors
* drop-zone for category includes description `<div>`
Much simpler diff with `?w`
> BOAC-4261, course on placeholder category can be dragged to adjacent course-reqt

- requirements.txt
Changes: https://flask.palletsprojects.com/en/2.0.x/changes/#version-2-0-1
> NOJIRA, upgrade Flask/Werkzeug from 2.0 to 2.0.1

- src/assets/styles/boac-global.css
- src/components/degree/CoursesTable.vue
- src/components/degree/DebugTemplate.vue
- src/components/degree/student/StudentDegreeCheckHeader.vue
- src/components/degree/student/UnassignedCourses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4262
Debug component now includes link to source degree-template.
> BOAC-4262, alert icon if fulfillments removed from course; CSS tweaks

- src/components/degree/CoursesTable.vue
- src/components/degree/student/UnassignedCourses.vue
- src/components/util/DismissibleFooterAlert.vue
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4235
Scroll up/down when dragged object enters top/bottom region, defined by "magicNumber".
> BOAC-4235, Firefox scrolls per drag w/o our help; CSS compatible across browser types

- src/components/degree/CoursesTable.vue
- src/components/degree/student/UnassignedCourses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4270
> BOAC-4270, tr-when-dragging style: cross-browser compatible CSS

- src/components/degree/CoursesTable.vue
- src/components/degree/student/UnassignedCourses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4270
Safari is not my friend.
> BOAC-4270, Safari requires set-opacity for visible ghost div during drag

- src/components/student/profile/AcademicTimelineTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2426
> BOAC-2426: Requirements are no longer clickable in the Academic timeline

- src/components/degree/CoursesTable.vue
- src/mixins/DegreeEditSession.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4275
And vice versa.
> BOAC-4275, do not allow course-copy to be dropped on category containing the course

- src/assets/styles/boac-global.css
- src/components/degree/Category.vue
- src/components/degree/CoursesTable.vue
- src/components/degree/UnitRequirements.vue
- src/views/degree/PrintableDegreeTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4278
> BOAC-4278, PrintableDegreeTemplate tweaks: CSS, concise course name

- src/components/degree/CoursesTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4278
> BOAC-4278, do not let course.note disrupt layout of /print view

- src/components/degree/Category.vue
- src/components/degree/UnitRequirements.vue
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4279
> BOAC-4279, /degree accessibility: get the heading structure right

- boac/api/degree_progress_api_utils.py
- boac/lib/background.py
- boac/models/degree_progress_category.py
- boac/models/degree_progress_category_unit_requirement.py
- boac/models/degree_progress_template.py
- boac/models/degree_progress_unit_requirement.py
- src/views/degree/BatchDegreeCheck.vue
- tests/test_api/test_degree_progress_student_controller.py
> BOAC-4243: Runs batch degree check process in bg thread

- src/views/degree/ManageDegreeChecks.vue
- src/views/degree/PrintableDegreeTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4290
> BOAC-4290, /print degree page must tolerate null student

- src/components/degree/EditUnitRequirement.vue
- src/components/degree/UnitRequirements.vue
- src/store/modules/degree-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4293
> BOAC-4293, simplify EditUnitRequirement code and fix 'Delete undefined?' bug

- src/components/degree/SelectUnitFulfillment.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/components/degree/student/AddCourseToCategory.vue
- src/components/degree/student/StudentDegreeCheckHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4285
https://jira.ets.berkeley.edu/jira/browse/BOAC-4287
https://jira.ets.berkeley.edu/jira/browse/BOAC-4295
And fixes focus problem when click to edit category.
> BOAC-4285, <label ../> for show notes in print toggle (checkbox)

- src/components/degree/student/CourseAssignmentMenu.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4286
> BOAC-4286, CourseAssignmentMenu options include sr-only lineage description

- src/views/degree/ManageDegreeChecks.vue
- src/views/degree/StudentDegreeCreate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4289
https://jira.ets.berkeley.edu/jira/browse/BOAC-4297
> BOAC-4289, Managing Degree Checks: sr text for buttons print, rename, etc.

- src/components/degree/UnitRequirements.vue
- src/components/degree/student/EditCourse.vue
- src/components/student/profile/StudentClasses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4288
https://jira.ets.berkeley.edu/jira/browse/BOAC-4294
> BOAC-4288, Degree Progress: labels for inputs of edit-course form

- src/components/degree/CoursesTable.vue
- src/components/degree/TemplateCategoryColumn.vue
- src/mixins/DegreeEditSession.vue
- src/views/degree/PrintableDegreeTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4252
I renamed `getCourses()` to describe its actual purpose.
> BOAC-4252, course cannot share category w/ copy but it can move within its own category

- src/components/degree/EditUnitRequirement.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4299
> BOAC-4299, Unit Requirement names must be unique

- src/components/degree/EditCategory.vue
- src/components/degree/TemplateCategoryColumn.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4300
https://jira.ets.berkeley.edu/jira/browse/BOAC-4301
The `create()` and `update()` functions are consolidated in `onSubmit()`.
> BOAC-4300/BOAC-4301: after save/update category, put focus based on action type

- src/components/degree/Category.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4302
> BOAC-4302, after delete category, put focus on create btn per position value

- src/components/degree/CoursesTable.vue
- src/components/degree/student/AddCourseToCategory.vue
- src/components/degree/student/CourseAssignmentMenu.vue
- src/components/degree/student/StudentDegreeCheckHeader.vue
- src/components/degree/student/UnassignedCourses.vue
- src/store/modules/degree-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4304
> BOAC-4304, put focus after buttons are enabled; use CSS selector in putFocus()

- boac/api/degree_progress_student_controller.py
- src/components/degree/CoursesTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4306
> BOAC-4306, Unassign course: if course-copy then delete category if exists

- src/components/degree/CloneTemplateModal.vue
- src/components/degree/EditCategory.vue
- src/views/degree/ManageDegreeChecks.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4307
> BOAC-4307, do not offer save/rename if name.trim() is empty

- boac/api/degree_progress_api_utils.py
- boac/api/degree_progress_student_controller.py
- boac/factory.py
- boac/lib/cache_utils.py
- config/default.py
- src/api/degree.ts
- src/main.ts
- src/views/degree/BatchDegreeCheck.vue
- tests/conftest.py
- tests/test_api/test_degree_progress_student_controller.py
> BOAC-4243: Tracks batch create progress via caching

- src/components/degree/EditCategory.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4308
> BOAC-4308, if degree entry of type 'Category' has course-requirements then it cannot have a Subcategory

- src/components/util/ProgressBar.vue
- src/views/degree/BatchDegreeCheck.vue
> BOAC-4243: Adds progress bar to batch degree check

- src/components/degree/DegreeTemplatesMenu.vue
- src/mixins/DegreeEditSession.vue
- src/store/modules/degree-edit-session.ts
- src/views/degree/BatchDegreeCheck.vue
- src/views/degree/ManageDegreeChecks.vue
> BOAC-4243: Adds batch degree check confirmation message

- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_template.py
- tests/test_api/test_degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4309
> BOAC-4309: Updates batch degree check validation to consider current degree checks only

- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_template.py
- tests/test_api/test_degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4309
master PR #3137
> [QA] BOAC-4309: Updates batch degree check validation to consider current degree checks only

- boac/externals/data_loch.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4269
> BOAC-4269: Ensures no duplicates in batch SIDs validation query

- boac/externals/data_loch.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4269
master PR #3139
> [QA] BOAC-4269: Ensures no duplicates in batch SIDs validation query

- boac/models/authorized_user.py
QA version of #3141. 
I don't know for a fact that this will fix https://jira.ets.berkeley.edu/jira/browse/BOAC-4313 but I have suspicions.
> [QA] BOAC-4313 Ensure db session picks up refresh updates for existing users

- boac/models/authorized_user.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4313
> BOAC-4313 Ensure db session picks up refresh updates for existing users

- src/components/degree/DegreeTemplatesMenu.vue
- src/views/degree/BatchDegreeCheck.vue
- src/views/degree/ManageDegreeChecks.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4291
Also, show added students even if they have already been added via cohort or group (aligning with how the batch note form works).
> BOAC-4291: SR announces name when single student added to batch

- src/components/degree/DegreeTemplatesMenu.vue
- src/views/degree/BatchDegreeCheck.vue
- src/views/degree/ManageDegreeChecks.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4291
Also, show added students even if they have already been added via cohort or group (aligning with how the batch note form works).
master PR #3143
> [QA] BOAC-4291: SR announces name when single student added to batch

- src/components/util/ProgressBar.vue
- src/views/degree/BatchDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4312
> BOAC-4312: SR announces progress bar updates

- boac/api/degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4316
> BOAC-4316 Delete course copies when parent unassigned

- boac/api/degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4316
QA version of #3146.
> [QA] BOAC-4316 Delete course copies when parent unassigned

- src/store/modules/degree-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4315
> BOAC-4315: Prevents dragging course copies to unassigned or junk

- src/store/modules/degree-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4315
master PR #3148
> [QA] BOAC-4315: Prevents dragging course copies to unassigned or junk

- src/views/degree/PrintableDegreeTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4319
> BOAC-4319: Saves space and shows true colors on printed degree check

- src/views/degree/PrintableDegreeTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4319
master PR #3152
> [QA] BOAC-4319: Saves space and shows true colors on printed degree check

- src/components/degree/CoursesTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4317
> BOAC-4317 No unauthorized drops, please

- src/components/degree/CoursesTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4317
QA version of #3150.
> [QA] BOAC-4317 No unauthorized drops, please

- src/components/degree/Category.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4275
> BOAC-4275 No, for real, no unauthorized category drops

- src/components/degree/Category.vue
https://github.com/ets-berkeley-edu/boac/pull/3154
QA version of #3154.
> [QA] BOAC-4275 No, for real, no unauthorized category drops

- src/views/degree/ManageDegreeChecks.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4318
> BOAC-4318 Better messaging for degree checks overview

- src/views/degree/ManageDegreeChecks.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4318
QA version of #3156.
> [QA] BOAC-4318 Better messaging for degree checks overview

- src/assets/styles/boac-global.css
- src/views/degree/PrintableDegreeTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4320
> BOAC-4320: Fixes height issue using print-only style

- src/assets/styles/boac-global.css
- src/views/degree/PrintableDegreeTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4320
master PR #3158
> [QA] BOAC-4320: Fixes height issue using print-only style

- package-lock.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/BOAC-4311
> BOAC-4311: Upgrades prismjs to 1.24

- boac/externals/data_loch.py
- fixtures/loch/loch.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-4330
> BOAC-4330 Add new fields to E&I notes query

- boac/merged/student.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4331
QA version of #3164.
> [QA] BOAC-4331 Put guardrails on sids-for-cohort query

- boac/merged/student.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4331
> BOAC-4331 Put guardrails on sids-for-cohort query

- src/views/degree/PrintableDegreeTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4333
QA version of #3166.
> [QA] BOAC-4333 Handle missing data in printable degree check

- src/views/degree/PrintableDegreeTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4333
> BOAC-4333 Handle missing data in printable degree check

- src/components/degree/DegreeTemplatesMenu.vue
- src/components/util/BatchAddStudentSet.vue
- src/views/degree/BatchDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4292
> BOAC-4292, CSS tweaks on /degree/batch

- boac/api/degree_progress_api_utils.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4332
master PR #3169
> [QA] BOAC-4332: Adds benchmark logging to batch create

- boac/api/degree_progress_api_utils.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4332
> BOAC-4332: Adds benchmark logging to batch create

- src/views/degree/BatchDegreeCheck.vue
> BOAC-4243: Restores mistakenly reverted batch confirmation message

- src/views/degree/BatchDegreeCheck.vue
> [QA] BOAC-4243: Restores mistakenly reverted batch confirmation message

- src/components/degree/CoursesTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4305
See latest comment in the Jira above.
> BOAC-4305, after delete course-copy, put focus on 'Add Course' button

- src/components/degree/student/CourseAssignmentMenu.vue
- src/store/modules/degree-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4303
> BOAC-4303, after assigning a course, put focus on course-assignment-menu in its assigned location

- boac/api/errors.py
- src/views/degree/ManageDegreeChecks.vue
- tox.ini
https://jira.ets.berkeley.edu/jira/browse/BOAC-4336
> BOAC-4336, if zero templates then no link to 'Batch degree checks'

- boac/models/authorized_user.py
- tests/test_api/test_search_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4340
Not a regression. See the Jira for details.
> BOAC-4340, case-insensitive delete from search_history

- boac/models/appointment.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4341
> BOAC-4341, if appointment's SID is not found in the loch then appt.to_api_json() returns student profile = {}

- boac/merged/student.py
- tests/test_api/test_cohort_controller.py
- tests/test_api/test_curated_group_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4325
> BOAC-4325, nulls last if order by units, descending

- config/default.py
- config/test.py
- requirements.txt
- tests/conftest.py
- tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4342
Release instructions updated. Devs will need to update local configs.
> BOAC-4342, upgrade to SQLAlchemy 1.4.20 plus necessary tweaks

- src/assets/styles/boac-global.css
- src/components/degree/UnitRequirements.vue
- src/components/student/profile/AcademicTimelineTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4280
Faint is not a good look.
Includes fix on element-id uniqueness in AcademicTimeline. (No Teena change needed.)
> BOAC-4280, accessibility: fix low contrast on b-table headers

- src/mixins/DegreeEditSession.vue
- src/store/modules/degree-edit-session.ts
- src/views/degree/BatchDegreeCheck.vue
- src/views/degree/ManageDegreeChecks.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4284
This minor fix has been lingering in my git stash. A simplification worth keeping.
> BOAC-4284, aria-live=polite on bulk create confirmation; vuex store not necessary

- src/components/admin/Users.vue
- src/components/student/profile/AcademicTimelineTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3897
Much faster, too.
> BOAC-3897, AcademicTimeline search: client-side index for filter-as-you-type

- src/components/student/profile/AcademicTimelineTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3897
Freshness matters.
> BOAC-3897, refresh in-page search index when create/edit/delete note

- src/components/degree/Category.vue
- src/views/degree/PrintableDegreeTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4345
> BOAC-4345, line breaks in degree notes and category description are properly rendered

- boac/api/notes_controller.py
- src/api/api-utils.ts
- src/main.ts
> BOAC-4352, benchmark logging to debug error during PDF attachment upload

- tsconfig.json
Experiment in PR #3193 taught us very little.
> BOAC-4352, bring back strict=true in tsconfig

- boac/api/config_controller.py
- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_course.py
- src/api/degree.ts
- src/components/degree/student/CreateCourseModal.vue
- src/mixins/DegreeEditSession.vue
- src/store/modules/degree-edit-session.ts
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3937
> BOAC-3937, accent_color_codes as static list; introducing CreateCourseModal.vue

- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_template.py
- src/components/degree/UnitsInput.vue
- src/components/degree/student/CreateCourseModal.vue
- src/components/util/ModalHeader.vue
- src/store/modules/degree-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4359
> BOAC-4359, CreateCourseModal validation; adjust logic of course.isCopy

- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_course.py
- src/api/degree.ts
- src/assets/styles/boac-global.css
- src/components/degree/CoursesTable.vue
- src/components/degree/student/CreateCourseModal.vue
- src/components/degree/student/EditCourse.vue
- src/components/degree/student/UnassignedCourses.vue
- src/mixins/DegreeEditSession.vue
- src/store/modules/degree-edit-session.ts
- tests/test_api/test_degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4359
> BOAC-4359, extend EditCourse component to accomodate manually-created courses

- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_course.py
- src/api/degree.ts
- src/components/degree/student/AddCourseToCategory.vue
- src/components/degree/student/CreateCourseModal.vue
- src/mixins/DegreeEditSession.vue
- src/store/modules/degree-edit-session.ts
- tests/test_api/test_degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4366
> BOAC-4366, manually-created courses can be deleted; /course/copy per course_id

- boac/models/alert.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4176
> BOAC-4176: Updates alerts to use auto terms

- src/components/degree/CoursesTable.vue
- src/components/degree/student/AccentColorSelect.vue
- src/components/degree/student/CourseAssignmentMenu.vue
- src/components/degree/student/CreateCourseModal.vue
- src/components/degree/student/EditCourse.vue
- src/components/degree/student/UnassignedCourses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3937
> BOAC-3937, color-coded select; b-tr text respects course.accentColor

- src/components/degree/student/UnassignedCourses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4368
> BOAC-4368, Degree Progress: use course.id for element ids

- src/components/degree/CoursesTable.vue
- src/components/degree/student/UnassignedCourses.vue
- src/mixins/DegreeEditSession.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4371
https://jira.ets.berkeley.edu/jira/browse/BOAC-4370
> BOAC-4371, front-end adjusts to latest course uniqueness constraint

- src/components/degree/student/EditCourse.vue
- src/components/degree/student/UnassignedCourses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4372
> BOAC-4372, manual unassigned course unit fulfillment should be editable

- src/components/degree/student/UnassignedCourses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4368
@pfarestveit can review this one, on behalf of Teena.
> BOAC-4368, ids vary per course.manuallyCreatedBy value

- boac/api/degree_progress_student_controller.py
- boac/lib/util.py
- boac/models/degree_progress_course.py
- src/components/degree/CoursesTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4378
And a couple CSS tweaks.
> BOAC-4378, create course with 0.5 units, save as 0.5 units

- boac/api/degree_progress_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4379
> BOAC-4379, grade is optional param – if None then ignore

- src/store/modules/degree-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4371
> BOAC-4371, getCourseKey function must incorporate manuallyCreated[At | By]

- boac/merged/student.py
- tests/test_api/test_cohort_controller.py
- tests/test_api/test_curated_group_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4325
> BOAC-4325, nulls last for sort-by units, both DESC and ASC

- src/components/degree/CoursesTable.vue
- src/components/degree/EditCategory.vue
- src/components/degree/student/EditCourse.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4199
If course was manually-created then we want focus on name-input.
> BOAC-4199, accessibility fix now that EditCourse sometimes starts with name-input

- boac/__init__.py
> NOJIRA, BOA is now v4.18 on master branch

- src/components/degree/student/EditCourse.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4381
QA PR coming soon.
> BOAC-4381, name required when edit manually created course

- src/components/degree/student/EditCourse.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4381
master PR is #3215
> [QA] BOAC-4381, name required when edit manually created course

- boac/externals/data_loch.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4380
> BOAC-4380: Resolves alias conflict in students query

- boac/externals/data_loch.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4380
master PR #3217
> [QA] BOAC-4380: Resolves alias conflict in students query

- src/components/student/profile/AcademicTimelineTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4382
> BOAC-4382: Fixes error in Academic Timeline appointment filter

- src/components/student/profile/AcademicTimelineTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4382
master PR #3219
> [QA] BOAC-4382: Fixes error in Academic Timeline appointment filter

- src/components/degree/CoursesTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4383
> BOAC-4383, do not highlight region as droppable when it's not

- src/components/degree/CoursesTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4383
master PR is #3222
> [QA] BOAC-4383, do not highlight region as droppable when it's not

- src/components/appointment/DropInAvailabilityToggle.vue
- src/components/degree/Category.vue
- src/components/degree/CoursesTable.vue
- src/components/degree/UnitRequirements.vue
- src/components/degree/student/UnassignedCourses.vue
- src/components/note/AdvisingNote.vue
- src/components/note/EditAdvisingNote.vue
- src/components/note/create/CreateNoteHeader.vue
- src/components/student/profile/AcademicTimelineTable.vue
- src/components/topics/ManageTopics.vue
- src/components/util/AreYouSureModal.vue
- src/views/Student.vue
- src/views/degree/ManageDegreeChecks.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4384
Most usages of this component were already dealing in Promises. I just needed to add the `return`.
> BOAC-4384, on click confirm in generic AreYouSureModal will wait, if given Promise

- requirements.txt
https://jira.ets.berkeley.edu/jira/browse/BOAC-4385
> BOAC-4385, minor py dependency updates (following qa branch cut)

- boac/models/degree_progress_template.py
- src/views/degree/StudentDegreeHistory.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4346
Alert icon (with mouseover message) when parent updated_at > degree.updated_at.
> BOAC-4346, show parent template updated_at on /degree/history

- boac/models/degree_progress_template.py
- src/views/degree/StudentDegreeHistory.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4346
This is a simple change, per CoE request. The QA dept (cc: @pfarestveit) can comment if the calendar doesn't have room for this verification. Worst case, we put it in following release.
The master PR is #3225
> [QA] BOAC-4346, show parent template updated_at on /degree/history

- boac/api/admin_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4387
> BOAC-4387: Starts cache job with the freshest of term values

- boac/api/admin_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4387
master PR #3227
> [QA] BOAC-4387: Starts cache job with the freshest of term values

- src/components/student/profile/StudentEnrollmentTerm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4266
> BOAC-4266: Shows date on dropped classes

- boac/merged/advising_appointment.py
- src/components/appointment/AdvisingAppointment.vue
- tests/test_merged/test_advising_appointment.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4338
> BOAC-4338 SIS appts: supply advisor SID for lazy load if needed

- src/components/degree/Category.vue
- src/views/degree/DegreeTemplate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4395
> BOAC-4395, fix header structure on degree template builder

- boac/api/degree_progress_category_controller.py
- boac/api/degree_progress_controller.py
- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_category.py
- boac/models/degree_progress_template.py
- scripts/db/migrate/2021/20210809-BOAC-4396/pre_deploy_01_add_column_recommended.sql
- scripts/db/schema.sql
- tests/test_api/test_degree_progress_category_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4396
v4.18 release instructions updated.
> BOAC-4396, backend work for 'recommended' indicator per course-requirement

- src/components/degree/CoursesTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4396
> BOAC-4396, course.isRecommended indicator (orange icon)

- src/components/degree/CoursesTable.vue
- src/components/degree/student/EditCourseRequirement.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4396
> BOAC-4396, EditCourseRequirement gets its form and formatting

- boac/api/degree_progress_category_controller.py
- boac/models/degree_progress_category.py
- scripts/db/migrate/2021/20210810-BOAC-4394/pre_deploy_01_add_column_category_note.sql
- scripts/db/schema.sql
- src/api/degree.ts
- src/components/degree/CoursesTable.vue
- src/components/degree/student/EditCourseRequirement.vue
- src/store/modules/degree-edit-session.ts
- tests/test_api/test_degree_progress_category_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4394
> BOAC-4394, add column 'note' to category table; front-end allows note per course-requirement

- boac/models/degree_progress_template.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4405
> BOAC-4405, degree progress fix: free variable referenced before assignment in enclosing scope

- src/components/degree/UnitsInput.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4399
> BOAC-4399, four character limit for units input (degree progress)

- boac/externals/data_loch.py
- boac/merged/advising_appointment.py
- config/default.py
- fixtures/loch/loch.sql
- tests/test_merged/test_advising_appointment.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4363
> BOAC-4363: Added methods to fetch and transform YCBM data to json

- boac/merged/advising_appointment.py
- src/components/appointment/AdvisingAppointment.vue
- src/components/student/profile/AcademicTimelineTable.vue
- tests/test_merged/test_advising_appointment.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4363
> BOAC-4363: YCBM data now correctly displayed in UI (advisor, cancellation)

- src/components/appointment/AdvisingAppointment.vue
- src/components/student/profile/AcademicTimelineTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4416
> BOAC-4416: Fixing YCBM canceled appointments display

- boac/merged/advising_appointment.py
- src/components/appointment/AdvisingAppointment.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4418
> BOAC-4418: YCBM appointment title now appearing correctly

- boac/merged/advising_appointment.py
- src/components/student/profile/AcademicTimelineTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4417
> BOAC-4417: YCBM appointments now show start and end time of appt

- package-lock.json
- package.json
Hoping to at least rule these out as the cause of the issue.
> BOAC-4352: Updates a few front-end devDependencies

- src/components/appointment/AdvisingAppointment.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4426
> BOAC-4426 Summary title for untitled appointments

- src/components/degree/CoursesTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4394
> BOAC-4394, if course.note is blank and category.note has text then 'blank' wins

- package-lock.json
- package.json
- src/components/degree/CoursesTable.vue
- src/components/degree/student/StudentDegreeCheckHeader.vue
- src/components/degree/student/UnassignedCourses.vue
- src/main.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4392
> BOAC-4392, Degree progress: URLs in notes are linked in non-printable view

- src/components/degree/Category.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4392
> BOAC-4392, URLs in category.description are linked in non-printable view

- src/components/degree/UnitRequirements.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4388
https://jira.ets.berkeley.edu/jira/browse/BOAC-4281 (accessibility bug) is now a non-issue.
> BOAC-4388, remove 'Total Units' from student degree check

- src/components/degree/student/CourseAssignmentMenu.vue
- src/views/degree/StudentDegreeCheck.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4389
> BOAC-4389, 'Junk Drawer' is now 'Free Electives'

- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_course.py
- scripts/db/migrate/2021/20210823-BOAC-4391/pre_deploy_01_degree_course_units_nullable.sql
- scripts/db/schema.sql
- src/components/degree/student/CreateCourseModal.vue
- src/components/degree/student/EditCourse.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4391
Release instructions have been updated.
> BOAC-4391, units is now nullable in degree_progress_courses table

- boac/models/degree_progress_template.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4411
> BOAC-4411, Degree Progress: concise course labels

- src/components/degree/student/AddCourseToCategory.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4410
> BOAC-4410, 'Add Course' is now 'Duplicate Course'

- boac/api/degree_progress_category_controller.py
- boac/models/degree_progress_category.py
- fixtures/loch/loch.sql
- src/api/degree.ts
- src/components/degree/student/EditCourseRequirement.vue
- src/store/modules/degree-edit-session.ts
- tests/test_api/test_degree_progress_category_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4415
> BOAC-4415, on /student/degree page, edit 'course requirements' form includes unit range

- boac/api/degree_progress_category_controller.py
- boac/models/degree_progress_category.py
- boac/models/degree_progress_course.py
- scripts/db/migrate/2021/20210823-BOAC-4415/pre_deploy_01_degree_category_add_grade_column.sql
- scripts/db/schema.sql
- tests/test_api/test_degree_progress_category_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4415
The server-side bits.
> BOAC-4415, add grade column to degree_category table

- src/api/degree.ts
- src/components/degree/CoursesTable.vue
- src/components/degree/student/EditCourse.vue
- src/components/degree/student/EditCourseRequirement.vue
- src/store/modules/degree-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4415
> BOAC-4415, uncompleted course requirements get editable grade property

- src/api/appointments.ts
- src/components/appointment/AppointmentCancellationModal.vue
- src/components/appointment/DropInAppointmentDropdown.vue
- src/components/appointment/DropInWaitlist.vue
- src/components/appointment/DropInWaitlistAppointment.vue
- src/components/cohort/ApplyAndSaveButtons.vue
- src/components/cohort/FilterRow.vue
- src/components/curated/dropdown/ManageStudent.vue
- src/components/curated/dropdown/SelectAll.vue
- src/components/degree/CoursesTable.vue
- src/components/degree/student/AddCourseToCategory.vue
- src/components/degree/student/UnassignedCourses.vue
- src/components/note/EditAdvisingNote.vue
- src/components/note/create/CreateNoteHeader.vue
- src/components/note/create/CreateNoteModal.vue
- src/components/student/profile/AcademicTimelineTable.vue
- src/components/topics/ManageTopics.vue
- src/views/CreateCuratedGroup.vue
- src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4429
Only changed what the customer sees.
> BOAC-4429, you say canceled, I say cancelled, let's call the whole thing off

- boac/merged/advising_note.py
- src/components/note/AdvisingNote.vue
- tests/test_merged/test_advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4434
> BOAC-4434: Adds detail to eForm and includes in notes CSV

- boac/api/degree_progress_category_controller.py
- boac/api/degree_progress_student_controller.py
- boac/api/util.py
- boac/models/degree_progress_category.py
- scripts/db/migrate/2021/20210909-BOAC-4440/pre_deploy_01_add_accent_color_to_categories.sql
- scripts/db/schema.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-4452
https://jira.ets.berkeley.edu/jira/browse/BOAC-4453
Following pattern of `degree_progress_courses`. Release instructions updated.
> BOAC-4452, add accent_color to degree_progress_categories

- src/api/degree.ts
- src/components/degree/CoursesTable.vue
- src/components/degree/student/AccentColorSelect.vue
- src/components/degree/student/EditCourseRequirement.vue
- src/store/modules/degree-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-4454
> BOAC-4454, category.accentColor axios wiring; extend EditCourseReqt component

- boac/externals/data_loch.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4458
> BOAC-4458 Predictable ordering for multiple academic standings

- src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4436
> BOAC-4436 Add class number to course heading display

- src/components/degree/student/CourseAssignmentMenu.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4461
> BOAC-4461, omit satisfied course-requirements from CourseAssignmentMenu

- src/components/note/AdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4462
https://jira.ets.berkeley.edu/jira/browse/BOAC-4463
> BOAC-4462, BOAC-4463: changes eForm header and order of fields

- boac/externals/data_loch.py
- src/components/note/AdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4472
> BOAC-4472: Hides grading basis details on non grading basis change eForms

- src/components/curated/CuratedGroupBulkAdd.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4423
> BOAC-4423, offer link to drop invalid SIDs in curated group 'bulk' textarea

- src/components/curated/CuratedGroupBulkAdd.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4423
Auto-fix is only available if SIDs.length > magic.
> BOAC-4423, curated bulk SIDs: if invalid.length <= magic then list 'em out

- boac/merged/advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-4474
> BOAC-4474: no 'eform' on non-eForm notes

- src/components/student/profile/StudentProfileGPA.vue
- src/components/student/profile/StudentProfileUnits.vue
- src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-3909
> BOAC-3909: sizes units and GPA charts to fit width

- package-lock.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/BOAC-4445
https://github.com/ets-berkeley-edu/boac/security/dependabot/package-lock.json/axios/open
> BOAC-4445, fix: axios is vulnerable to 'Inefficient Regular Expression Complexity'

- src/components/note/AdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4477
> BOAC-4477: Adds eForm subject element ID

- .ebextensions/00_ami.config
- .platform/hooks/predeploy/00_load_mpm_worker_module.sh
https://jira.ets.berkeley.edu/jira/browse/BOAC-4374
> BOAC-4374 Remove mpm configs, adjust Cloudwatch

- src/components/degree/Category.vue
- src/components/degree/CoursesTable.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4449
> BOAC-4449: Makes Campus Requirements undroppable

- src/components/degree/Category.vue
- src/components/degree/CoursesTable.vue
- src/components/degree/student/EditCourseRequirement.vue
- src/mixins/DegreeEditSession.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4450
> BOAC-4450: hides irrelevant fields on Campus Requirement edit form

- src/components/degree/EditCategory.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-4494
> [QA] BOAC-4494: Hides description field on edit Course Requirement

- src/components/course/CourseStudents.vue
- src/components/matrix/Matrix.vue
- src/components/search/AdvisingNoteSnippet.vue
- src/components/search/AppointmentSnippet.vue
- src/components/search/SortableStudents.vue
- src/components/student/StudentRow.vue
- tox.ini
https://jira-secure.berkeley.edu/browse/BOAC-4509
> BOAC-4509, if student has no UID then do not offer link to profile page

- .ebextensions/00_ami.config
- .ebextensions/01_create_apache_conf.config
First try. Some part of this is surely not right yet.
> BOAC-4487 Update Apache configs for end-to-end encryption

- .ebextensions/00_ami.config
> BOAC-4487 Update hardcoded security group id

- .ebextensions/01_create_apache_conf.config
- .platform/hooks/predeploy/03_download_private_key.sh
> BOAC-4487 Move private key installation to platform hook

- boac/api/notes_controller.py
- boac/merged/advising_note.py
- boac/models/note.py
- tests/test_api/test_notes_controller.py
https://jira-secure.berkeley.edu/browse/BOAC-4515
> BOAC-4515, attachments of a private note must also be private

- .ebextensions/01_create_apache_conf.config
> BOAC-4487 Adjust custom ssl conf

- .ebextensions/01_create_apache_conf.config
> BOAC-4487 For want of a pipe character the deploy was lost

- .ebextensions/01_create_apache_conf.config
- .platform/hooks/postdeploy/01_update_apache_config.sh
> BOAC-4487 Apache config mods apparently need to be post-deploy

- .ebextensions/00_ami.config
https://jira-secure.berkeley.edu/browse/BOAC-4517
> BOAC-4517 Set security group from environment properties

- .ebextensions/00_ami.config
https://jira-secure.berkeley.edu/browse/BOAC-4517
> BOAC-4517 Alternate syntax to pull environment properties

- .ebextensions/00_ami.config
https://jira-secure.berkeley.edu/browse/BOAC-4517
> BOAC-4517 Ongoing .ebextension formatting experiments

- boac/api/notes_controller.py
- boac/models/note.py
- scripts/db/migrate/2021/20211102-BOAC-4471/notes_fts_index_must_respect_privacy.sql
- scripts/db/schema.sql
https://jira-secure.berkeley.edu/browse/BOAC-4471
> BOAC-4471, do not put body text of private note in search index

- boac/models/alert.py
- fixtures/loch/student_profile_2345678901.json
https://jira-secure.berkeley.edu/browse/BOAC-4519
> BOAC-4519 Create withdrawal alerts for current term only

- src/components/util/RichTextEditor.vue
https://jira-secure.berkeley.edu/browse/BOAC-4523
> BOAC-4523, ckeditor5 wysiwyg: disable fraction oriented text transforms

- boac/__init__.py
> NOJIRA, BOA is now v5.3 on dev branch

- src/api/notes.ts
- src/components/note/AdvisingNoteTopics.vue
- src/components/note/EditAdvisingNote.vue
- src/components/note/create/CreateNoteModal.vue
- src/components/note/create/PrivacyPermissions.vue
- src/components/student/profile/AcademicTimelineTable.vue
- src/mixins/NoteEditSession.vue
- src/store/modules/note-edit-session.ts
https://jira-secure.berkeley.edu/browse/BOAC-4469
https://jira-secure.berkeley.edu/browse/BOAC-4470
https://jira-secure.berkeley.edu/browse/BOAC-4512
> BOAC-4469, private notes, front-end UI

- boac/api/config_controller.py
- src/components/student/StudentRow.vue
- src/components/student/profile/StudentEnrollmentTerm.vue
https://jira-secure.berkeley.edu/browse/BOAC-4485
> BOAC-4485, show min/max unit approval if value is non-standard

- .ebextensions/00_ami.config
> BOAC-4524, fix log-file path in 00_ami.config

- src/components/degree/CoursesTable.vue
- src/components/degree/student/CampusRequirementCheckbox.vue
https://jira-secure.berkeley.edu/browse/BOAC-4498
> BOAC-4498: visually differentiates satisfied Campus Reqt from unsatisfied

- src/components/degree/CoursesTable.vue
- src/components/degree/student/CampusRequirementCheckbox.vue
https://jira-secure.berkeley.edu/browse/BOAC-4498
dev PR #3348
> [QA] BOAC-4498: visually differentiates satisfied Campus Reqt from unsatisfied

- .ebextensions/00_ami.config
- README.md
- application.py
- config/default.py
- requirements.txt
https://jira-secure.berkeley.edu/browse/BOAC-4522
> BOAC-4522, routine update of py deps; another boac.log path fix

- src/components/student/profile/StudentProfileHeaderAcademics.vue
https://jira-secure.berkeley.edu/browse/BOAC-4526
> BOAC-4526, student.sisProfile.degrees can be nil

- src/components/student/profile/StudentProfileHeaderAcademics.vue
https://jira-secure.berkeley.edu/browse/BOAC-4526
dev PR is #3351
> [QA] BOAC-4526, student.sisProfile.degrees can be nil

- boac/api/notes_controller.py
https://jira-secure.berkeley.edu/browse/BOAC-4527
> BOAC-4527, if attachment has no associated note then skip private check

- boac/api/notes_controller.py
https://jira-secure.berkeley.edu/browse/BOAC-4527
dev PR is #3354
> [QA] BOAC-4527, if attachment has no associated note then skip private check

- src/components/course/CourseStudents.vue
- src/components/student/StudentRow.vue
- src/components/student/profile/StudentProfileHeaderAcademics.vue
> BOAC-4529, BOA gets all degrees of student, list views and profile page accommodate

- src/components/course/CourseStudents.vue
- src/components/student/StudentRow.vue
- src/components/student/profile/StudentProfileHeaderAcademics.vue
> [QA] BOAC-4529, BOA gets all degrees of student, list views and profile page accommodate

- src/router.ts
- src/views/FlightDataRecorder.vue
https://jira-secure.berkeley.edu/browse/BOAC-4528
> BOAC-4528, will this playful tweak wake up the boa-dev pipeline?

- src/components/course/CourseStudents.vue
- src/components/student/DegreesAwarded.vue
- src/components/student/StudentRow.vue
> BOAC-4529, group by dateAwarded when rendering degrees

- src/components/course/CourseStudents.vue
- src/components/student/DegreesAwarded.vue
- src/components/student/StudentRow.vue
> [QA] BOAC-4529, group by dateAwarded when rendering degrees

- src/components/student/DegreesAwarded.vue
https://jira-secure.berkeley.edu/browse/BOAC-4533
> BOAC-4533, list o' degrees-awarded: type='major' only

- src/components/student/DegreesAwarded.vue
https://jira-secure.berkeley.edu/browse/BOAC-4533
dev PR is #3367
> [QA] BOAC-4533, list o' degrees-awarded: type='major' only

- src/components/admin/Users.vue
- src/components/note/create/CreateNoteHeader.vue
- src/components/note/create/CreateNoteModal.vue
- src/store/modules/note-edit-session.ts
- tests/test_api/test_notes_controller.py
https://jira-secure.berkeley.edu/browse/BOAC-4537
Also, removed useless quick links (eg, Schedulers) from Passenger Manifest.
> BOAC-4537, private notes: apply a template and privacy selector remains

- boac/api/notes_controller.py
- boac/merged/advising_note.py
- tests/test_merged/test_advising_note.py
https://jira-secure.berkeley.edu/browse/BOAC-4520
See recommended usage, with Flask: https://github.com/arjan-s/python-zipstream .  (Simplify the diff with `?w=1`.)
> BOAC-4520, zipstream.ZipFile using stream_with_context + generator

- src/components/student/StudentRow.vue
https://jira-secure.berkeley.edu/browse/BOAC-4516
> BOAC-4516, max/min units in list view and improved formatting

- requirements.txt
A few nice bug fixes: https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html
> NOJIRA, SQLAlchemy bump from 1.4.26 to 1.4.27

- boac/externals/data_loch.py
- boac/merged/advising_appointment.py
- boac/merged/advising_note.py
- boac/models/appointment.py
- tox.ini
https://jira-secure.berkeley.edu/browse/BOAC-4542
> BOAC-4542, de-dupe words list of search phrase to avoid complex SQL

- boac/models/degree_progress_category.py
- boac/models/degree_progress_course.py
- src/components/degree/CoursesTable.vue
- src/components/degree/student/UnassignedCourses.vue
No more cramming course/category note into a wee table cell.
> BOAC-4535, degree progress: show/hide note in dedicated tr

- src/components/degree/CoursesTable.vue
- src/components/degree/student/UnassignedCourses.vue
> BOAC-4535, correct usage of _.remove for show/hide util

- src/router.ts
https://jira-secure.berkeley.edu/browse/BOAC-3670
See https://router.vuejs.org/guide/advanced/lazy-loading.html#grouping-components-in-the-same-chunk
> BOAC-3670, lazy-load Vue components that define routes

- src/components/degree/CoursesTable.vue
- src/components/degree/student/UnassignedCourses.vue
- src/main.ts
- src/store/modules/context.ts
Revisions per CoE feedback. Plus, `console.log('Page load in seconds...')` when not prod.
> BOAC-4535, degree progress: tweak strategy on preview/show/hide notes

- src/components/degree/CoursesTable.vue
- src/components/degree/student/UnassignedCourses.vue
> BOAC-4535, keep note column steady during show/hide

- boac/api/course_controller.py
- boac/api/curated_group_controller.py
- boac/api/search_controller.py
- boac/api/util.py
- boac/models/alert.py
- boac/models/cohort_filter.py
- boac/models/curated_group.py
https://jira-secure.berkeley.edu/browse/BOAC-4544
> BOAC-4544: Adds benchmark logging to alerts+student profiles query

- src/components/student/StudentRow.vue
- src/components/student/profile/StudentCourse.vue
- src/components/student/profile/StudentEnrollmentTerm.vue
https://jira-secure.berkeley.edu/browse/BOAC-4547
And some `:id` fixing.
> BOAC-4547, consistent numFormat on min/max units display

- boac/api/note_templates_controller.py
- boac/models/note_template.py
- scripts/db/migrate/2021/20211129-BOAC-4548/alter_note_templates_add_column_is_private.sql
- scripts/db/schema.sql
https://jira-secure.berkeley.edu/browse/BOAC-4548
BOA release instructions updated.
> BOAC-4548, schema change to support private note_templates

- requirements.txt
- tests/util.py
https://jira-secure.berkeley.edu/browse/BOAC-4543
`LocationConstraint` must be specified to avoid this error: https://forums.aws.amazon.com/thread.jspa?threadID=308363
> BOAC-4543: Upgrades boto3 and moto

- boac/models/note_template.py
- src/api/note-templates.ts
- src/components/note/create/CreateNoteHeader.vue
- src/components/note/create/CreateNoteModal.vue
- tests/test_api/test_note_templates_controller.py
https://jira-secure.berkeley.edu/browse/BOAC-4548
> BOAC-4548, UX for is_private option in advising note templates

- src/components/degree/student/CreateCourseModal.vue
- src/components/degree/student/EditCourse.vue
https://jira-secure.berkeley.edu/browse/BOAC-4532
> BOAC-4532, remove SelectUnitFulfillment from create/edit-course components

- boac/models/degree_progress_course.py
- boac/models/degree_progress_template.py
- tests/test_api/test_degree_progress_student_controller.py
https://jira-secure.berkeley.edu/browse/BOAC-4545
> BOAC-4545, degree progress: grade changes reflected in assigned/unassigned courses

- src/components/student/DegreesAwarded.vue
https://jira-secure.berkeley.edu/browse/BOAC-4514
> BOAC-4514, show awarded degree if planType in 'CRT', 'HS', 'MAJ', etc.

- src/components/student/StudentRow.vue
https://jira-secure.berkeley.edu/browse/BOAC-4549
> BOAC-4549, display min/max units per term dropdown of list view

- src/components/degree/CoursesTable.vue
https://jira-secure.berkeley.edu/browse/BOAC-4552
> BOAC-4552, sensible width for course reqt column (degree progress)

- src/components/degree/student/EditCourse.vue
https://jira-secure.berkeley.edu/browse/BOAC-4532
> BOAC-4532, unit fulfillment(s) can be added to a course iff it is assigned

- Procfile
- buildspec.yml
https://jira-secure.berkeley.edu/browse/BOAC-4554
> BOAC-4554 Add Procfile for multi-worker gunicorn configuration

- boac/externals/data_loch.py
https://jira-secure.berkeley.edu/browse/BOAC-4546
> BOAC-4546: Uses new grading option column instead of slow string compare

- scripts/db/migrate/2021/20211203-BOAC-4555/pre_deploy_01_add_indexes_on_notes_and_alerts.sql
https://jira-secure.berkeley.edu/browse/BOAC-4555
> BOAC-4555: Fixes SQL syntax error

- boac/api/curated_group_controller.py
- boac/api/util.py
- boac/models/curated_group.py
- boac/models/development_db.py
- tests/test_api/api_test_utils.py
- tests/test_api/test_curated_group_controller.py
https://jira-secure.berkeley.edu/browse/BOAC-4563
> BOAC-4563, add 'domain' to curated_group related APIs

- src/components/degree/CoursesTable.vue
- src/components/degree/student/UnassignedCourses.vue
- src/views/degree/StudentDegreeCheck.vue
> BOAC-4535, fixed width on notes column (degree progress)

- src/components/degree/CoursesTable.vue
https://jira-secure.berkeley.edu/browse/BOAC-4377
> BOAC-4377, padding for 'satisfied note'

- src/main.ts
- src/router.ts
- src/views/Error.vue
https://jira-secure.berkeley.edu/browse/BOAC-4561
`error.statusCode` is shown in non-prod env only.
> BOAC-4561, actual error message (and statusCode) on /error

- src/components/degree/CoursesTable.vue
- src/components/degree/UnitRequirements.vue
- src/components/util/DismissibleFooterAlert.vue
- src/router.ts
- src/views/degree/PrintableDegreeTemplate.vue
https://jira-secure.berkeley.edu/browse/BOAC-4377
> BOAC-4377, printable degree check: no faint text, landscape, improved sizing

- boac/externals/data_loch.py
- boac/merged/student.py
- fixtures/loch/loch.sql
- tests/test_api/test_search_controller.py
- tests/test_externals/test_data_loch.py
https://jira-secure.berkeley.edu/browse/NS-1435
Best done before the BOA 5.3 branch cut so that we can safely remove the tables in Nessie 5.4.
> NS-1435 Remove BOA-side references to deprecated Nessie tables

- src/views/AllCohorts.vue
- src/views/AllGroups.vue
https://jira-secure.berkeley.edu/browse/BOAC-4573
> BOAC-4573, 'Everyone's Cohorts|Groups' omits advisors with zero cohorts|groups

- boac/externals/data_loch.py
- boac/merged/admitted_student.py
- fixtures/loch/loch.sql
https://jira-secure.berkeley.edu/browse/BOAC-4570
> BOAC-4570: Uses new name index in admits search query

- boac/externals/data_loch.py
- boac/merged/admitted_student.py
- fixtures/loch/loch.sql
This reverts commit 4fe7c23d38a5ac9c8a78b9cabbc17a313088316a.
PR #3411 was meant for the dev branch only.
https://jira-secure.berkeley.edu/browse/BOAC-4570
> [QA] Revert "BOAC-4570: Uses new name index in admits search query"

- boac/api/curated_group_controller.py
- boac/api/user_controller.py
- boac/api/util.py
- boac/merged/user_session.py
- boac/models/curated_group.py
- src/api/cohort.ts
- src/api/curated.ts
- src/components/curated/dropdown/ManageStudent.vue
- src/components/sidebar/CuratedGroups.vue
- src/components/sidebar/Sidebar.vue
- src/core.ts
- src/store/modules/current-user-extras.ts
- src/views/CreateCuratedGroup.vue
- tests/test_api/test_cohort_controller.py
- tests/test_api/test_curated_group_controller.py
- tests/test_api/test_notes_controller.py
- tests/test_api/test_user_controller.py
https://jira-secure.berkeley.edu/browse/BOAC-4564
Again, hoping for performance improvements and less complexity.
> BOAC-4564, add curated groups to /api/profile/my and remove /api/curated/my

- src/api/curated.ts
- src/components/sidebar/CuratedGroups.vue
- src/components/sidebar/Sidebar.vue
- src/views/CreateCuratedGroup.vue
https://jira-secure.berkeley.edu/browse/BOAC-4564
> BOAC-4564, CreateCuratedGroup component handles all domain types

- src/api/auth.ts
- src/api/curated.ts
- src/components/course/CourseStudents.vue
- src/components/curated/dropdown/ManageStudent.vue
- src/components/curated/dropdown/SelectAll.vue
- src/components/search/SortableStudents.vue
- src/components/sidebar/CuratedGroups.vue
- src/components/sidebar/Sidebar.vue
- src/components/student/StudentRow.vue
- src/components/student/profile/StudentProfileHeader.vue
- src/main.ts
- src/views/Cohort.vue
- src/views/Course.vue
- src/views/Error.vue
- src/views/Search.vue
https://jira-secure.berkeley.edu/browse/BOAC-4568
Valid domains: 'default' and 'admitted_students'.
> BOAC-4568, components used to create/update curated groups must be domain-aware

- boac/api/cohort_controller.py
- boac/api/curated_group_controller.py
- boac/merged/admitted_student.py
- boac/merged/cohort_filter_options.py
- src/api/curated.ts
- src/components/admit/AdmitDataWarning.vue
- src/components/admit/AdmitStudentsTable.vue
- src/components/util/NavLink.vue
- src/store/modules/cohort-edit-session.ts
- src/store/modules/curated-edit-session.ts
- src/views/Cohort.vue
- src/views/CuratedGroup.vue
- tests/test_api/test_curated_group_controller.py
https://jira-secure.berkeley.edu/browse/BOAC-4565
> BOAC-4565, /curated page uses AdmitStudentsTable if domain 'admitted_students'

- boac/api/cohort_controller.py
- boac/api/curated_group_controller.py
- boac/models/cohort_filter.py
- boac/models/curated_group.py
- src/api/cohort.ts
- src/api/curated.ts
- src/components/sidebar/Cohorts.vue
- src/components/sidebar/CuratedGroups.vue
- src/components/sidebar/MyAdmitCohorts.vue
- src/components/sidebar/Sidebar.vue
- src/views/AllCohorts.vue
- src/views/AllGroups.vue
- tests/test_api/test_cohort_controller.py
https://jira-secure.berkeley.edu/browse/BOAC-4565
> BOAC-4565, cleaner sidebar; '/groups/all' pages denote domain=admitted_students

- boac/api/curated_group_controller.py
- boac/models/curated_group.py
- src/assets/styles/bootstrap-overrides.css
- src/components/curated/dropdown/ManageStudent.vue
- src/components/student/profile/StudentProfileHeader.vue
- src/views/AdmitStudent.vue
- src/views/AllCohorts.vue
- tests/test_api/test_curated_group_controller.py
https://jira-secure.berkeley.edu/browse/BOAC-4567
> BOAC-4567, on /admit/student page we use existing component to add/remove from curated groups

- src/components/curated/dropdown/SelectAll.vue
- src/components/note/create/BatchNoteAddCohort.vue
- src/components/note/create/BatchNoteFeatures.vue
- src/components/util/BatchAddStudentSet.vue
- src/views/DropInAdvisorHome.vue
- src/views/Home.vue
- src/views/degree/BatchDegreeCheck.vue
https://jira-secure.berkeley.edu/browse/BOAC-4567
> BOAC-4567, modal to create a batch o' notes includes CE3 curated groups

- src/api/curated.ts
- src/components/admit/AdmitStudentRow.vue
- src/components/admit/SortableAdmits.vue
- src/components/course/CourseStudents.vue
- src/components/curated/CuratedGroupHeader.vue
- src/components/curated/dropdown/ManageStudent.vue
- src/components/curated/dropdown/SelectAll.vue
- src/components/curated/dropdown/StudentCheckbox.vue
- src/components/search/SortableGroup.vue
- src/components/search/SortableStudents.vue
- src/components/student/StudentRow.vue
- src/views/Search.vue
https://jira-secure.berkeley.edu/browse/BOAC-4566
> BOAC-4566, 'admitted students' in search results come with curated-group selector/checkboxes

- boac/externals/data_loch.py
https://jira-secure.berkeley.edu/browse/NS-1431
> NS-1431 Remove hist_enr restriction on section enrollments feed

- boac/externals/data_loch.py
https://jira-secure.berkeley.edu/browse/NS-1431
A matched set with #3425.
> NS-1431 Remove hist_enr restriction in section enrollments count query

- src/api/curated.ts
- src/assets/styles/boac-global.css
- src/components/admit/AdmitDataWarning.vue
- src/components/admit/AdmitStudentRow.vue
- src/components/admit/AdmitStudentsTable.vue
- src/components/admit/SortableAdmits.vue
- src/components/cohort/CohortPageHeader.vue
- src/components/course/CourseStudents.vue
- src/components/curated/CuratedGroupHeader.vue
- src/components/curated/dropdown/ManageStudent.vue
- src/components/curated/dropdown/StudentCheckbox.vue
- src/components/matrix/Matrix.vue
- src/components/search/SortableStudents.vue
- src/components/student/SortBy.vue
- src/components/student/StudentRow.vue
- src/components/student/TermSelector.vue
- src/mixins/Util.vue
- src/views/AdmitStudents.vue
- src/views/Cohort.vue
- src/views/CuratedGroup.vue
- src/views/Search.vue
https://jira-secure.berkeley.edu/browse/BOAC-4565
> BOAC-4565, UI cleanup on /cohort and /curated; AdmitStudentRow gets 'curate' controls

- boac/api/student_controller.py
- boac/api/user_controller.py
- boac/lib/cohort_utils.py
- boac/merged/cohort_filter_options.py
- src/api/cohort.ts
- src/api/curated.ts
- src/api/student.ts
- src/components/curated/CuratedGroupBulkAdd.vue
- src/components/sidebar/CuratedGroups.vue
- src/main.ts
- src/mixins/CuratedEditSession.vue
- src/store/modules/curated-edit-session.ts
- src/views/CreateCuratedGroup.vue
- src/views/CuratedGroup.vue
https://jira-secure.berkeley.edu/browse/BOAC-4425
Final cleanup.
> BOAC-4425, create 'admitted_students' group with bulk SIDs

- boac/api/config_controller.py
- boac/api/util.py
- boac/merged/user_session.py
- config/default.py
- config/test.py
- src/components/student/profile/StudentClasses.vue
- tests/test_api/test_degree_progress_controller.py
- tests/test_api/test_user_controller.py
https://jira-secure.berkeley.edu/browse/BOAC-4571
> BOAC-4571, remove FEATURE_FLAG_DEGREE_CHECK

- src/components/admit/AdmitStudentRow.vue
- src/components/admit/AdmitStudentsTable.vue
- src/views/AdmitStudents.vue
- src/views/CuratedGroup.vue
https://jira-secure.berkeley.edu/browse/BOAC-4579
> BOAC-4579, curated admits: remove buttons appearing on master list and cohorts

- boac/externals/data_loch.py
- tests/test_api/test_search_controller.py
https://jira-secure.berkeley.edu/browse/BOAC-3319
> BOAC-3319 Switch from hist_enr to academic_career_status as active-student criterion

- src/api/curated.ts
- src/components/admit/AdmitStudentsTable.vue
- src/components/admit/SortableAdmits.vue
- src/components/course/CourseStudents.vue
- src/components/curated/dropdown/CuratedGroupSelector.vue
- src/components/curated/dropdown/CuratedStudentCheckbox.vue
- src/components/search/SortableStudents.vue
- src/components/student/StudentRow.vue
- src/views/AdmitStudents.vue
- src/views/Cohort.vue
- src/views/Course.vue
- src/views/CuratedGroup.vue
- src/views/Search.vue
https://jira-secure.berkeley.edu/browse/BOAC-4580
> BOAC-4580, admit-cohort and admits-all pages get CuratedGroupSelector + checkboxes

- src/assets/styles/boac-global.css
- src/components/curated/CreateCuratedGroupModal.vue
- src/components/curated/CuratedGroupHeader.vue
- src/components/curated/dropdown/CuratedGroupSelector.vue
- src/components/curated/dropdown/CuratedStudentCheckbox.vue
- src/components/curated/dropdown/ManageStudent.vue
- src/components/note/create/BatchNoteFeatures.vue
- src/components/search/SortableGroup.vue
- src/components/sidebar/CuratedGroups.vue
- src/components/sidebar/Sidebar.vue
- src/components/student/SortBy.vue
- src/components/util/BatchAddStudentSet.vue
- src/mixins/Util.vue
- src/views/AdmitStudent.vue
- src/views/CreateCuratedGroup.vue
- src/views/CuratedGroup.vue
- src/views/Home.vue
- src/views/degree/BatchDegreeCheck.vue
https://jira-secure.berkeley.edu/browse/BOAC-4581
> BOAC-4581, use proper label per curated_group.domain

- boac/api/cohort_controller.py
- boac/api/curated_group_controller.py
- boac/api/student_controller.py
- boac/externals/data_loch.py
- boac/lib/cohort_utils.py
- boac/merged/cohort_filter_options.py
- boac/merged/student.py
- boac/models/cohort_filter.py
- boac/models/curated_group.py
- fixtures/loch/loch.sql
- tests/test_api/test_cohort_controller.py
https://jira-secure.berkeley.edu/browse/BOAC-3471
> BOAC-3471 Cohort filter for active/inactive academic career status

- boac/lib/cohort_utils.py
https://jira-secure.berkeley.edu/browse/BOAC-3471
Follow-up to #3436.
> BOAC-3471 Inactivate a typo

- src/components/curated/CreateCuratedGroupModal.vue
- src/components/curated/CuratedGroupBulkAdd.vue
- src/components/curated/CuratedGroupHeader.vue
- src/components/curated/dropdown/CuratedGroupSelector.vue
- src/views/CuratedGroup.vue
- src/views/Home.vue
https://jira-secure.berkeley.edu/browse/BOAC-4582
> BOAC-4582, curated admits: consistent verbiage

- src/components/curated/CuratedGroupHeader.vue
- src/components/curated/dropdown/CuratedGroupSelector.vue
- src/components/curated/dropdown/ManageStudent.vue
- src/components/sidebar/CuratedGroups.vue
https://jira-secure.berkeley.edu/browse/BOAC-4586
https://jira-secure.berkeley.edu/browse/BOAC-4588
> BOAC-4586, appropriate element ids per curated_group domain

- boac/api/student_controller.py
- boac/api/util.py
- boac/externals/data_loch.py
- boac/merged/admitted_student.py
- boac/models/curated_group.py
- src/components/student/SortBy.vue
- src/views/CuratedGroup.vue
- src/views/Home.vue
https://jira-secure.berkeley.edu/browse/BOAC-4583
> BOAC-4583, proper admits query for /curated view; proper sortBy options

- src/api/appointments.ts
- src/api/cohort.ts
- src/api/curated.ts
- src/api/degree.ts
- src/api/note-templates.ts
- src/api/notes.ts
- src/api/search.ts
- src/api/student.ts
- src/assets/styles/boac-global.css
- src/components/cohort/ApplyAndSaveButtons.vue
- src/components/cohort/CohortPageHeader.vue
- src/components/cohort/FilterRow.vue
- src/components/curated/dropdown/CuratedGroupSelector.vue
- src/components/curated/dropdown/ManageStudent.vue
- src/components/note/create/CreateNoteModal.vue
- src/components/search/SortableGroup.vue
- src/components/student/profile/AcademicTimelineTable.vue
- src/core.ts
- src/store/modules/cohort-edit-session.ts
- src/views/AdmitStudents.vue
- src/views/Cohort.vue
- src/views/Course.vue
- src/views/CreateCuratedGroup.vue
- src/views/CuratedGroup.vue
- src/views/Home.vue
- src/views/Search.vue
https://jira-secure.berkeley.edu/browse/BOAC-1872
Having `ga.track` calls in components is too messy. Keep it simply by keeping it certain `src/api` calls.
> BOAC-1872, more Google Analytics cleanup; track events in 'src/api' calls

- boac/api/curated_group_controller.py
- package-lock.json
- package.json
- src/views/AdmitStudents.vue
- src/views/CuratedGroup.vue
https://jira-secure.berkeley.edu/browse/BOAC-4583
Plus, `mitt` upgrade which we use for emitting and listening on events.
> BOAC-4583, admissions group: sortBy fix and no term selector

- src/api/admit.ts
- src/api/cohort.ts
- src/api/curated.ts
- src/api/notes.ts
- src/api/search.ts
- src/api/student.ts
- src/auth.ts
- src/core.ts
- src/main.ts
- src/router.ts
https://jira-secure.berkeley.edu/browse/BOAC-1872
All vue routes now have 'name' attribute, pulled from `meta.title` which was subsequently dropped. Less code and plays nice with gtag page-view tracking.
> BOAC-1872, Google Analytics: track page views and additional src/api events

- boac/api/auth_controller.py
- boac/api/user_controller.py
- boac/api/util.py
https://jira-secure.berkeley.edu/browse/BOAC-4589
> BOAC-4589, fetch complete user_profile when /dev_auth

- src/components/curated/CuratedGroupHeader.vue
- src/components/curated/dropdown/ManageStudent.vue
- src/views/CuratedGroup.vue
https://jira-secure.berkeley.edu/browse/BOAC-4590
https://jira-secure.berkeley.edu/browse/BOAC-4581
> BOAC-4590, minor fixes in labeling of admit groups

- src/components/sidebar/SearchForm.vue
https://jira-secure.berkeley.edu/browse/BOAC-4584
A bug which predates curated-admits work.
> BOAC-4584, do not disable search input when only 'admits' checked

- src/components/curated/dropdown/CuratedStudentCheckbox.vue
https://jira-secure.berkeley.edu/browse/BOAC-4585
See Jira for info.
> BOAC-4585, dupe ids across bootstrap checkboxes cause problems

- src/components/curated/dropdown/CuratedGroupSelector.vue
- src/components/curated/dropdown/CuratedStudentCheckbox.vue
- src/components/curated/dropdown/ManageStudent.vue
- src/components/sidebar/CuratedGroups.vue
https://jira-secure.berkeley.edu/browse/BOAC-4591
> BOAC-4591, curated admits: element ids per 'domain'

- src/components/curated/dropdown/ManageStudent.vue
https://jira-secure.berkeley.edu/browse/BOAC-4591
> BOAC-4591, remove dupe group from id

- src/api/curated.ts
https://jira-secure.berkeley.edu/browse/BOAC-4592
> BOAC-4592, defunct google analytics refs

- boac/api/curated_group_controller.py
https://jira-secure.berkeley.edu/browse/BOAC-4593
> BOAC-4593, wrong offset value when get_admitted_students_by_sids()

- boac/externals/data_loch.py
- boac/merged/cohort_filter_options.py
https://jira-secure.berkeley.edu/browse/BOAC-3470
> BOAC-3470 Degree cohort filters: relabel 'Degree Awarded,' reverse sort terms

- boac/api/cohort_controller.py
- boac/api/curated_group_controller.py
- boac/api/util.py
- src/components/cohort/CohortPageHeader.vue
- src/components/curated/CuratedGroupHeader.vue
- src/mixins/Berkeley.vue
- tests/test_api/test_curated_group_controller.py
- tests/test_api/test_user_controller.py
https://jira-secure.berkeley.edu/browse/BOAC-4596
> BOAC-4596, reuse the /cohort (domain-aware) CSV download logic for /curated

- .ebextensions/00_ami.config
> BOAC-4524, 00_ami.config changes per Ops' sleuthing on Cloudwatch

- boac/externals/data_loch.py
- boac/merged/admitted_student.py
- boac/merged/student.py
- requirements.txt
https://jira-secure.berkeley.edu/browse/BOAC-4558
We can't update to psycopg3 yet, it seems, because SQLAlchemy doesn't yet know how to adapt certain object types.
> BOAC-4558 Drop SQLAlchemy abstraction layer from loch queries

- boac/api/util.py
- boac/merged/student.py
https://jira-secure.berkeley.edu/browse/BOAC-2216
> BOAC-2216: Removes unused academic standing from cohort/group CSV export

- src/components/student/TermSelector.vue
https://jira-secure.berkeley.edu/browse/BOAC-4602
> BOAC-4602 Do not omit to emit on cohort/group term change

- src/views/Cohort.vue
https://jira-secure.berkeley.edu/browse/BOAC-4602
> BOAC-4602 Fix CSS, page structure in cohort header

- src/components/student/profile/TimelineDate.vue
https://jira-secure.berkeley.edu/browse/BOAC-4534
> BOAC-4534 Once again, computed properties are better than watchers

- src/views/Cohort.vue
https://jira-secure.berkeley.edu/browse/BOAC-4603
> BOAC-4603 Update cohort sort listener based on cohort type

- boac/merged/student.py
https://jira-secure.berkeley.edu/browse/BOAC-4600
> BOAC-4600 Guard against missing elements in profile distillation

- boac/externals/data_loch.py
- config/default.py
https://jira-secure.berkeley.edu/browse/BOAC-4558
> BOAC-4558 Simple threaded pooling for loch connections

- src/components/note/create/BatchNoteFeatures.vue
- src/views/AdmitStudent.vue
- src/views/Cohort.vue
- src/views/Home.vue
https://jira-secure.berkeley.edu/browse/BOAC-4567
Plus, padding tweaks in the UI.
> BOAC-4567, batch-create-notes form: omit CE3 groups from the dropdown

- .ebextensions/00_ami.config
See latest comments in the Jira.
> BOAC-4524, awslogs/awscli.conf > remove quotes on region config value

- boac/externals/data_loch.py
- fixtures/loch/loch.sql
- tests/test_externals/test_data_loch.py
https://jira-secure.berkeley.edu/browse/NS-1436
> NS-1436 History is bunk for advising note attachments

- boac/api/util.py
- boac/merged/student.py
- fixtures/loch/student_profile_11667051.json
- fixtures/loch/student_profile_2345678901.json
- fixtures/loch/student_profile_3456789012.json
- fixtures/loch/student_profile_5678901234.json
- fixtures/loch/student_profile_7890123456.json
- fixtures/loch/student_profile_8901234567.json
- fixtures/loch/student_profile_890127492.json
- fixtures/loch/student_profile_9000000000.json
- fixtures/loch/student_profile_9100000000.json
- fixtures/loch/student_profile_completed_2718281828.json
- fixtures/loch/student_profile_inactive_3141592653.json
- fixtures/loch/student_profile_summary_11667051.json
- fixtures/loch/student_profile_summary_2345678901.json
- fixtures/loch/student_profile_summary_3456789012.json
- fixtures/loch/student_profile_summary_5678901234.json
- fixtures/loch/student_profile_summary_7890123456.json
- fixtures/loch/student_profile_summary_8901234567.json
- fixtures/loch/student_profile_summary_890127492.json
- fixtures/loch/student_profile_summary_9000000000.json
- fixtures/loch/student_profile_summary_9100000000.json
- fixtures/loch/student_profile_summary_completed_2718281828.json
- fixtures/loch/student_profile_summary_inactive_3141592653.json
- src/components/student/StudentRow.vue
- src/components/student/profile/StudentProfileHeaderBio.vue
- tests/test_api/test_cohort_controller.py
- tests/test_api/test_curated_group_controller.py
- tests/test_api/test_search_controller.py
- tests/test_api/test_student_controller.py
https://jira-secure.berkeley.edu/browse/BOAC-2216
> BOAC-2216: Sources academic standing, term GPA from student profile feed

- config/default.py
- fixtures/loch/loch.sql
- tests/test_api/test_search_controller.py
https://jira-secure.berkeley.edu/browse/BOAC-4605
> BOAC-4605, history dept notes: BOA config and loch.sql setup

- boac/externals/data_loch.py
- boac/merged/advising_note.py
- fixtures/loch/loch.sql
https://jira-secure.berkeley.edu/browse/BOAC-4605
The 'TODO' will be dealt with in an upcoming PR.
> BOAC-4605, include History dept notes in student's Academic Timeline

- src/components/student/profile/StudentAcademicStanding.vue
- src/components/student/profile/StudentEnrollmentTerm.vue
https://jira-secure.berkeley.edu/browse/BOAC-2216
> BOAC-2216: Accounts for unresolved conflict between flavors of student profile

- src/components/student/profile/StudentPersonalDetails.vue
https://jira-secure.berkeley.edu/browse/BOAC-4609
> BOAC-4609, null safe check on enrollment.sections.length

- boac/merged/advising_note.py
https://jira-secure.berkeley.edu/browse/BOAC-4610
> BOAC-4610, imported history notes need 'legacySource' marker in BOA

- scripts/db/migrate/2022/20220106-BOAC-4314/add_column_automate_degree_progress_permission.sql
https://jira-secure.berkeley.edu/browse/BOAC-4314
> BOAC-4314, authorized_users table gets automate_degree_progress_permission flag

- boac/api/cache_utils.py
- boac/api/user_controller.py
- boac/api/util.py
- boac/models/authorized_user.py
- scripts/db/schema.sql
- src/components/admin/EditUserProfileModal.vue
- tests/test_api/test_user_controller.py
https://jira-secure.berkeley.edu/browse/BOAC-4314
> BOAC-4314, wire BOA up to authorized_user.automate_degree_progress_permission

- .ebextensions/00_ami.config
- .platform/hooks/postdeploy/02_start_awslogsd.sh
Darlene has given us the green light. This PR is ready for review/merge. cc: @sandeepmjay @pauline2k @lyttam
> BOAC-4524, add postdeploy hook 02_start_awslogsd.sh for Cloudwatch connect

- .platform/hooks/postdeploy/02_start_awslogsd.sh
>  BOAC-4524, BOA codePipeline hit permissions error on this step; remove sudo

- .platform/hooks/postdeploy/02_start_awslogsd.sh
As a reference: [.platform/hooks/postdeploy/01_update_apache_config.sh](https://github.com/ets-berkeley-edu/boac/blob/dev/.platform/hooks/postdeploy/01_update_apache_config.sh)
> BOAC-4524, awslogsd postdeploy is bash script, not ami config

- boac/api/user_controller.py
- boac/merged/user_session.py
- src/components/admin/MyProfile.vue
https://jira-secure.berkeley.edu/browse/BOAC-4314
And helpful UI change in /profile view.
> BOAC-4314, flush user_session json when update user profile

- boac/api/student_controller.py
- boac/externals/data_loch.py
- boac/lib/cohort_utils.py
- boac/models/curated_group.py
- fixtures/loch/loch.sql
- fixtures/loch/student_profile_inactive_9191919191.json
- fixtures/loch/student_profile_summary_inactive_9191919191.json
- tests/test_api/test_cohort_controller.py
https://jira-secure.berkeley.edu/browse/BOAC-4598
> BOAC-4598 Revise behavior of career status, degree cohort filters

- boac/externals/data_loch.py
https://jira-secure.berkeley.edu/browse/BOAC-4605
> BOAC-4605, BOA renders actual created_at date of history dept notes

- fixtures/loch/loch.sql
https://jira-secure.berkeley.edu/browse/NS-1448
> NS-1448 Remove hist_enr column from fixtures

- boac/api/degree_progress_student_controller.py
- boac/models/degree_progress_template.py
- src/components/admin/Users.vue
- src/views/degree/StudentDegreeHistory.vue
- tests/test_api/test_degree_progress_student_controller.py
https://jira-secure.berkeley.edu/browse/BOAC-4576
Heavy-lifting moved to server-side.
> BOAC-4576, bug fix: Degree check history advisor column sometimes coming up blank

- scripts/db/migrate/2022/20220106-BOAC-4314/add_column_automate_degree_progress_permission.sql
https://jira-secure.berkeley.edu/browse/BOAC-4618
> BOAC-4618, Degree Progress permissions: automate=TRUE is default for CoE

- src/components/admin/Users.vue
- src/mixins/Berkeley.vue
https://jira-secure.berkeley.edu/browse/BOAC-4619
> BOAC-4619, Passenger Manifest: show DP perms and automated flag

- boac/api/cache_utils.py
- src/components/admin/Users.vue
- tests/conftest.py
- tests/test_api/test_cache_utils.py
- tests/test_externals/test_data_loch.py
https://jira-secure.berkeley.edu/browse/BOAC-4617
> BOAC-4617, do not de-automate DP perms when cachejob/refresh

- src/api/user.ts
https://jira-secure.berkeley.edu/browse/BOAC-4623
> BOAC-4623, fix order of function args in setDropInStatus

- boac/api/cohort_controller.py
- boac/merged/user_session.py
- boac/models/cohort_filter.py
- src/views/AllCohorts.vue
https://jira-secure.berkeley.edu/browse/BOAC-4624
> BOAC-4624, do not show admit cohorts in /all view if user does not have perm

- boac/api/cohort_controller.py
- boac/merged/user_session.py
- boac/models/cohort_filter.py
- src/views/AllCohorts.vue
https://jira-secure.berkeley.edu/browse/BOAC-4624
dev PR is #3496
> [QA] BOAC-4624, do not show admit cohorts in /all view if user does not have perm

- src/components/admin/EditUserProfileModal.vue
- src/components/admin/Users.vue
https://jira-secure.berkeley.edu/browse/BOAC-4626
> [QA] BOAC-4626, pax manifest: auto_dp_perm is false when create non-COENG user

- src/components/admin/EditUserProfileModal.vue
- src/components/admin/Users.vue
https://jira-secure.berkeley.edu/browse/BOAC-4626
> BOAC-4626, pax manifest: auto_dp_perm is false when create non-COENG user

- boac/externals/data_loch.py
- boac/models/alert.py
https://jira-secure.berkeley.edu/browse/BOAC-4631
> BOAC-4631 Limit alert refresh to active students

- boac/externals/data_loch.py
- boac/models/alert.py
https://jira-secure.berkeley.edu/browse/BOAC-4631
QA version of #3500.
> [QA] BOAC-4631 Limit alert refresh to active students

- boac/api/cache_utils.py
- tests/conftest.py
- tests/test_api/test_cache_utils.py
https://jira-secure.berkeley.edu/browse/BOAC-4629
> BOAC-4629, user with 2+ depts gets DP access if at least one dept_membership qualifies

- src/components/student/profile/StudentClasses.vue
https://jira-secure.berkeley.edu/browse/BOAC-4634
> BOAC-4636 Open degree checks with link, not button

- src/components/student/profile/StudentPersonalDetails.vue
https://jira-secure.berkeley.edu/browse/BOAC-4627
> BOAC-4627: Added Perceptive Content document link
