boac/api/status_controller.py
boac/static/templates/landing.html
tests/conftest.py
tests/test_api/test_status_controller.py

Also includes some style fixes (courtesy of PyCharm's PEP 8 checks) and a test helper.

Validate our one current Canvas external

---

boac/api/errors.py
boac/api/status_controller.py
boac/auth/cas_auth.py
boac/auth/dev_auth.py
boac/externals/canvas.py
boac/factory.py
boac/lib/http.py
boac/lib/mockingbird.py
boac/models/authorized_user.py
boac/routes.py
tox.ini

https://jira.ets.berkeley.edu/jira/browse/BOAC-35
Code style fixes and removed corresponding codes from `flake8 --ignore` list.
A question for the team: Where do we stand on [trailing commas in Python data structures](https://coderwall.com/p/4fvcaa/trailing-comma-in-python-data-structures) (as enforced by `flake8-commas`)? 
Also: https://wiki.python.org/moin/TupleSyntax (see "...essential element here is the trailing comma...")

BOAC-35, code style fixes: import order, etc.

---

README.md

https://jira.ets.berkeley.edu/jira/browse/BOAC-35
Preview of README addition:
https://github.com/johncrossman/boac/tree/NOJIRA_readme

BOAC-35, README > how to run tests and lint the code

---

boac/lib/http.py
tox.ini

Three second build-time seemed wrong.

NOJIRA, envlist must match updated target names

---

boac/api/status_controller.py
boac/api/user_controller.py
boac/routes.py
boac/static/templates/landing.html
tests/test_api/test_status_controller.py
tests/test_api/test_user_controller.py

@johncrossman This was the last decent thing I did before falling into AngularJS perplexity...

NOJIRA Decouple authentication from Canvas API calls

---

boac/externals/canvas.py
boac/lib/mockingbird.py
fixtures/canvas_student_summaries_for_course_7654321_page_1.json
fixtures/canvas_student_summaries_for_course_7654321_page_2.json
fixtures/canvas_student_summaries_for_course_7654321_page_3.json
fixtures/canvas_student_summaries_for_course_7654321_page_4.json
fixtures/canvas_student_summaries_for_course_7654321_page_5.json
fixtures/canvas_student_summaries_for_course_7654321_page_6.json
fixtures/canvas_student_summaries_for_course_7654321_page_7.json
fixtures/canvas_student_summaries_for_course_7654321_page_8.json
requirements.txt
tests/test_externals/test_canvas.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-36
Most of the mass here is test/demo support. BIG data means BIG fixtures, adding up to a real Canvas data distribution with 730 obfuscated IDs.

BOAC-36 Client and tests for Canvas student summaries API

---

boac/db.py
boac/factory.py
boac/logger.py
boac/models/authorized_user.py
boac/models/development_db.py
run.py
tests/conftest.py
tests/test_api/test_api_errors.py
tests/test_api/test_user_controller.py
tests/test_auth/test_dev_auth.py
tests/test_models/test_authorized_user.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-42

BOAC-42 Add authorized users DB table & seed data

---

boac/models/authorized_user.py
run.py

Two follow-ups for https://github.com/ets-berkeley-edu/boac/pull/15

BOAC-42 In "UID", "U" is for "User" & "U" is for "Unique"

---

boac/externals/canvas.py
boac/lib/http.py
config/default.py
fixtures/canvas_user_courses_61889.json
tests/test_externals/test_canvas.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-43

BOAC-43 External API client for Canvas course site memberships

---

boac/externals/canvas.py
boac/lib/mockingbird.py

Per comments in https://github.com/ets-berkeley-edu/boac/pull/16.

NOJIRA An app is an app is an app

---

boac/static/js/app.js
boac/static/js/controllers/landingController.js
boac/static/js/factories/authFactory.js
boac/static/templates/landing.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-45
Eventually, `authFactory.refreshStatus` might move to an event-listener. The next PR will have CAS linkage.

BOAC-45, 'config' constant available in templates; module value 'me' refreshed on logOut

---

boac/lib/http.py

The dreaded `KeyError` strikes again!

NOJIRA Don't explode on non-Canvas APIs

---

boac/static/css/main.css
boac/static/js/app.js
boac/static/js/controllers/authController.js
boac/static/js/controllers/landingController.js
boac/static/js/routes.js
boac/static/templates/footer.html
boac/static/templates/header.html
boac/static/templates/landing.html
boac/templates/index.html
bower.json

https://jira.ets.berkeley.edu/jira/browse/BOAC-47
Make way for students & cohorts. Screenshot of footer:

BOAC-47, header and footer with compact login/logout; switch to angular-ui-router

---

boac/static/js/app.js
boac/static/js/controllers/studentController.js
boac/static/js/factories/analyticsFactory.js
boac/static/js/factories/authFactory.js
boac/static/js/routes.js
boac/static/templates/student.html
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-47
`student.html` iterates through sample data as a proof of concept. It is not an intended page design. Plus, the `me` object lives solely in `$rootScope` and is managed by authFactory only.

BOAC-47, draft version of '/student/:uid' view

---

boac/static/js/controllers/cohortController.js
boac/static/js/controllers/landingController.js
boac/static/js/factories/cohortFactory.js
boac/static/js/routes.js
boac/static/templates/cohort.html
boac/static/templates/landing.html
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-51
Front-end boilerplate corresponding to #33, making it possible to at least click around in advance of cohort-level visualizations.

BOAC-51 Simple front end for cohort data

---

.eslintrc.yml
boac/api/user_controller.py
boac/static/css/boxplot.css
boac/static/js/controllers/studentController.js
boac/static/templates/cohort.html
boac/static/templates/footer.html
boac/static/templates/landing.html
boac/static/templates/student.html
boac/templates/index.html
bower.json

https://jira.ets.berkeley.edu/jira/browse/BOAC-38
A first pass that will win no beauty contests in the console or the browser. Boxplot code was swiped from SuiteC and modified enough to get it working, but there's been no attempt to tidy things up with directives and such.

BOAC-38 Per-student boxplot visualization

---

boac/static/js/controllers/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-56
Because outlier dots are important too.

BOAC-56 Pad boxplot ever so slightly

---

boac/api/cohort_controller.py
boac/api/user_controller.py
boac/lib/analytics.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-9
Per-user analytics fetching is moved to `boac.lib.analytics.course_analytics_for_user` to make that logic accessible from other points in the app, including scripts.

BOAC-9 Factor course analytics out of controller

---

boac/static/app/auth/authFactory.js
boac/static/app/landing/landing.html
boac/static/app/landing/landingController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-61
Simple `$rootScope.$emit('authenticationSuccess')` for any controller that wants it.

BOAC-61, upon user auth, emit authenticationSuccess event

---

boac/static/app/auth/authFactory.js
boac/static/app/auth/authService.js
boac/static/app/bootstrap.js
boac/static/app/landing/landing.html
boac/static/app/landing/landingController.js
boac/static/app/routes.js
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-63
See Jira description.

BOAC-63, cohortFactory.getCohorts() is called when user is not authenticated

---

README.md
boac/static/app/student/studentController.js
config/default.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-68
Plus a couple of NOJIRA fixes.

BOAC-68 Whisker graph shown when "Assignments on time: No data"

---

boac/api/cohort_controller.py
boac/api/user_controller.py
boac/factory.py
config/default.py
config/demo.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-70

BOAC-70 Add basic cache for cohort summary

---

scripts/cohort_fixtures.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-66
When generating fixtures for a large student set, we get a lot of repeat courses.

BOAC-66 Cohort fixtures script: don't duplicate per-course API calls

---

boac/static/app/auth/authService.js
boac/static/app/cohort/cohortController.js
boac/static/app/landing/landingController.js
boac/static/app/student/student.css
boac/static/app/student/studentController.js
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-69
https://jira.ets.berkeley.edu/jira/browse/BOAC-71
A couple of pre-demo front-end fixes.

BOAC-69 BOAC-71 Fix authn state & avatar display size

---

.gitignore
boac/static/app/shared/footer.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-72
Also added ".DS_Store" to gitignore.

BOAC-72 Only display Dev Auth login if enabled

---

boac/externals/canvas.py
boac/lib/berkeley.py
fixtures/canvas_user_courses_61889.json
tests/test_externals/test_canvas.py
tests/test_lib/test_berkeley.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-73
First step in the grand old game of matching official sections to bCourses sites.

BOAC-73 Include Canvas term in user courses query; translate term name to SIS id

---

boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-76
Switch statements!

BOAC-76 Fix percentile ordinal logic

---

boac/externals/sis_enrollments_api.py
config/default.py
fixtures/sis_enrollments_api_11667051_2178.json
tests/test_externals/test_sis_enrollments_api.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-74
We include a realistic, exhaustively obfuscated Hub API payload (verbosity, empty objects and all).

BOAC-74 Client code, fixture, tests for SIS enrollments API

---

boac/externals/canvas.py
fixtures/canvas_course_sections_7654320.json
fixtures/canvas_course_sections_7654321.json
fixtures/canvas_course_sections_7654323.json
tests/test_externals/test_canvas.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-75
We continue to color inside the lines.

BOAC-75 Client, fixtures, tests for Canvas course sections API

---

boac/static/app/student/student.css
boac/static/app/student/student.html

Last step in https://jira.ets.berkeley.edu/jira/browse/BOAC-75.

BOAC-75 Crude front-end templating for enrollment and grade data

---

boac/externals/calnet.py
config/default.py
requirements.txt

https://jira.ets.berkeley.edu/jira/browse/BOAC-49
Yes, we have no test fixtures yet...

BOAC-49 Add CalNet LDAP support

---

boac/externals/sis_student_api.py
config/default.py
fixtures/sis_student_api_11667051.json
tests/test_externals/test_sis_student_api.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-81
The fixture is largely borrowed from https://github.com/ets-berkeley-edu/calcentral/blob/master/fixtures/json/hub_student.json, with some updates to reflect athlete status and apparent changes in Hub behavior over the last year.

BOAC-81 External client, fixture, tests for SIS Student API

---

scripts/student_api_fixtures.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-81
Following on #67, a script to pull down fixtures for speedier demo-mode development.

BOAC-81 Script to generate SIS student API fixtures

---

boac/api/cohort_controller.py
boac/api/user_controller.py
boac/configs.py
boac/externals/canvas.py
boac/externals/sis_athlete_api.py
boac/externals/sis_enrollments_api.py
boac/externals/sis_student_api.py
boac/lib/analytics.py
boac/lib/http.py
config/default.py
config/test.py
scripts/cohort_fixtures.py
scripts/example_generate_fixtures.py
tests/test_externals/test_canvas.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-103
Just simplifying some API support code before adding more complexity...
Also adds Athlete Descriptors API.

BOAC-103 Standardize external API configuration

---

README.md

I'm unsure why PR #70  is failing. This PR will rule out weirdness in Travis env.

NOJIRA, pip3 is pippier than pip

---

buildspec.yml

https://jira.ets.berkeley.edu/jira/browse/BOAC-97
Get the regex right.

BOAC-97, regex to get all files in subdir

---

buildspec.yml

https://jira.ets.berkeley.edu/jira/browse/BOAC-97
A couple more artifacts needed for deploy step.

BOAC-91, eb deploy step needs 'bower install'

---

boac/api/user_controller.py
boac/lib/merged.py
fixtures/sis_student_api_11667051.json
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-101

BOAC-101 Merge SIS profile data into per-user API feed

---

boac/lib/merged.py
boac/static/app/student/student.css
boac/static/app/student/student.html
boac/templates/index.html
bower.json
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-99
https://jira.ets.berkeley.edu/jira/browse/BOAC-100
Compare sample screenshot (below) to mockups at https://jira.ets.berkeley.edu/jira/browse/BOAC-11.

BOAC-99 BOAC-100 Student page front end

---

boac/externals/sis_enrollments_api.py
scripts/refresh_external_data_for_term.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-103
Noticed this on my first run against Spring 2017.

BOAC-103 Cache the absence of SIS Enrollment data for a term

---

run.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-109
An adaptation of the solution posted in https://blog.writelab.com/blog/2015/5/20/django-elastic-beanstalk-apache-config-and-environmental-variables.

BOAC-109 Special handling for environment variables under WSGI

---

boac/lib/merged.py
fixtures/canvas_course_sections_7654320.json
tests/test_externals/test_canvas.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-110

BOAC-110 Handle manually added site sections

---

run.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-109
Follow-up to https://github.com/ets-berkeley-edu/boac/pull/85.

BOAC-109 Bash brackets, my foot!

---

.ebextensions/01_create_apache_conf.config

As seen on https://jira.ets.berkeley.edu/jira/browse/BOAC-111.

BOAC-111 WSGI needs secret sauce or numpy will destroy it

---

.ebextensions/04_create_cloudwatch_conf.config
.ebextensions/99_delayed_script.config
boac/externals/calnet.py
boac/logger.py
boac/models/json_cache.py
boac/routes.py
run.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-108

BOAC-108 Effective logging under Elastic Beanstalk/WSGI

---

boac/lib/analytics.py
boac/routes.py
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-112
Fix the observed error. Also log error API responses at a higher level, and handle those responses on the cohort front end (`w=1` is recommended to review this last).

BOAC-112 Fix KeyError in analytics lib; better error handling generally

---

boac/lib/merged.py
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-113

BOAC-113 Fix Canvas munge error, front-end student view error handling

---

boac/lib/merged.py
fixtures/canvas_course_sections_7654321.json
tests/test_externals/test_canvas.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-114
Observed in the wild in PHYSICS 10.

BOAC-114 Allow for weird suffixes in SIS section ids

---

boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/shared/scatterplot.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-90
Following in-progress designs.

BOAC-90 List/matrix toggle for cohort view

---

boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-89
This frontend-only PR approximates current designs using the info our cohort API currently provides: name, avatar, UID. Filling in the rest of the details will require substantial API fortification.

BOAC-89 Restyled, sortable cohort list view

---

boac/api/cohort_controller.py
boac/api/user_controller.py
boac/externals/asc_cohorts.py
boac/lib/merged.py
boac/models/development_db.py
boac/models/team_member.py
scripts/db/migrate/20171107-BOAC-92/rename_cohorts_table.sql
scripts/load_cohorts_csv.py
scripts/obfuscate_cohort_fixtures.py
scripts/refresh_external_data_for_term.py
tests/fixtures/cohorts.py
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-92
First try was PR #94 
db modify script is `scripts/db/migrate/20171107-BOAC-92/rename_cohorts_table.sql`

BOAC-92, rename 'cohorts' to 'team_members' (w/ db modify script)

---

boac/api/cohort_controller.py
boac/models/authorized_user.py
boac/models/development_db.py
tests/fixtures/cohorts.py
tests/test_api/test_cohort_controller.py
tests/test_models/test_authorized_user.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-93
Custom cohort CRUD with tests.

BOAC-93, /api/cohort/create and /api/cohort/delete/<code> with test coverage

---

boac/api/user_controller.py
boac/static/app/auth/authFactory.js
boac/static/app/auth/authService.js
boac/static/app/bootstrap.js
boac/static/app/main.css
boac/static/app/routes.js
boac/static/app/shared/header.css
boac/static/app/shared/header.html
boac/static/app/student/search.html
boac/static/app/student/searchController.js
boac/templates/index.html
bower.json
tests/test_api/test_user_controller.py
tests/test_models/test_authorized_user.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-94
* Page header with search/custom-cohort placeholders
* User profile added to `me`
* search page with initial controller

BOAC-94, prep page header for cohort search

---

boac/static/app/cohort/cohort.html
boac/static/app/landing/landing.html
boac/static/app/student/search.html
boac/static/app/student/searchController.js
boac/static/app/student/student.html
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-94
* My tidying of `index.html` in PR #100 moved bootstrap out of pole position. Warnings added.
* Header/footer in `div:container` for UX alignment

BOAC-94, order matters in index.html; move header/footer inside div:container

---

boac/static/app/auth/authService.js
boac/static/app/routes.js
boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-140
None (without auth) shall pass!

BOAC-140, if not state.isPublic then force location.path to '/'

---

boac/lib/merged.py
fixtures/sis_student_api_11667051.json
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-139

BOAC-139 Include transfer credits in student's total units

---

boac/api/cohort_controller.py
boac/api/user_controller.py
boac/models/authorized_user.py
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortFactory.js
boac/static/app/cohort/manage.html
boac/static/app/cohort/manageCohortsController.js
boac/static/app/landing/landingController.js
boac/static/app/routes.js
boac/static/app/student/searchController.js
boac/templates/index.html
tests/test_api/test_cohort_controller.py
tests/test_models/test_authorized_user.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-141
* Wire front-end to update and delete ops
* Some minor tidying
* design for manage page: https://jira.ets.berkeley.edu/jira/browse/BOAC-12

BOAC-141, initial manage cohorts page (rename and delete)

---

boac/api/cohort_controller.py
boac/api/user_controller.py
boac/factory.py
boac/models/authorized_user.py
boac/models/cohort_filter.py
boac/models/development_db.py
boac/models/team_member.py
boac/routes.py
boac/static/app/bootstrap.js
boac/static/app/cohort/all.html
boac/static/app/cohort/allCohortsController.js
boac/static/app/cohort/cohortFactory.js
boac/static/app/cohort/manage.html
boac/static/app/cohort/manageCohortsController.js
boac/static/app/landing/landing.html
boac/static/app/landing/landingController.js
boac/static/app/routes.js
boac/static/app/shared/header.html
boac/static/app/student/search.html
boac/static/app/student/searchController.js
boac/templates/index.html
bower.json
tests/fixtures/cohorts.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_user_controller.py
tests/test_models/test_authorized_user.py
tests/test_models/test_cohort_filter.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-141
* CohortFilter gets dedicated file
* [per modified design](https://jira.ets.berkeley.edu/jira/browse/BOAC-12), user will have access to view all saved cohorts
* new routes
* landing page has Teams and My Cohorts
* 'Everyone's Cohorts' page added

BOAC-141, class CohortFilter gets dedicated file; landing page gets cohort lists

---

boac/models/team_member.py
boac/static/app/shared/header.css
boac/static/app/shared/header.html
boac/static/app/student/searchBox.html
boac/static/app/student/searchDirective.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-94
Follow up to PR #107. (A padding tweaks, too.)

BOAC-94, choose a student and kablooey! Student profile page

---

boac/api/cohort_controller.py
boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohortFactory.js
boac/static/app/cohort/cohortsDropdownDirective.js
boac/static/app/cohort/deleteCohortController.js
boac/static/app/cohort/deleteCohortModal.html
boac/static/app/cohort/manage.html
boac/static/app/cohort/manageCohortsController.js
boac/static/app/landing/landing.html
boac/static/app/main.css
boac/static/app/shared/header.css
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-141
UX: https://jira.ets.berkeley.edu/jira/browse/BOAC-12
* broadcast when `myCohortsUpdated` to keep header menu updated
* angular bootstrap for confirm-delete modal
* manage cohorts per BOAC-12

BOAC-141, manage cohorts UX per BOAC-12 designs

---

boac/api/cohort_controller.py
boac/models/cohort_filter.py
boac/models/development_db.py
boac/models/team_member.py
boac/static/app/cohort/all.html
boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortFactory.js
boac/static/app/cohort/dropdownNav.html
boac/static/app/cohort/manage.html
boac/static/app/landing/landing.html
boac/static/app/main.css
tests/test_api/test_cohort_controller.py
tests/test_models/test_cohort_filter.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-95
Backend/front-end support for sorting and paging of cohort member lists (and search results). Includes initial formatting on front-end.

BOAC-95, cohort member listing gets order_by, offset and limit params

---

boac/static/app/cohort/cohort.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-158

BOAC-158, use data-ng-show so #scatterplot is reachable by d3

---

tests/conftest.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-157
The particular breakage here addressed was caused by upgrading pytest from to 3.2.5 to 3.3.0. It may have something to do with changes to the `pytest_fixture_post_finalizer` hook, but that's getting pretty deep: https://docs.pytest.org/en/latest/changelog.html#pytest-3-3-0-2017-11-23
Note that explicit use of transactions seems not to be necessary, as nowadays an SQLAlchemy session behaves transactionally by default.

BOAC-157 Fix db session handling in tests

---

boac/api/cohort_controller.py
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortFactory.js
boac/static/app/cohort/createCohortController.js
boac/static/app/cohort/createCohortModal.html
boac/static/app/main.css
boac/templates/index.html
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-158
https://jira.ets.berkeley.edu/jira/browse/BOAC-94
Notes:
* lazy load of ALL cohort members in matrix view because it's not paginated
* create cohort popup
* step towards [version 1.C UX](https://confluence.ets.berkeley.edu/confluence/display/LRSASC/Cohort+View+Page)

BOAC-158, create cohort (modal); no pagination for teams; lazy load matrix

---

boac/lib/analytics.py
boac/static/app/student/student.html
boac/static/app/student/studentController.js
config/default.py
tests/test_lib/test_analytics.py

And don't show any percentiles if the data is meaningless.
https://jira.ets.berkeley.edu/jira/browse/BOAC-146
https://jira.ets.berkeley.edu/jira/browse/BOAC-161

BOAC-146 BOAC-161 Do show zero percentiles if meaningful range of data

---

boac/models/team_member.py
boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/createCohortController.js
boac/static/app/cohort/createCohortModal.html
boac/static/app/main.css
boac/static/app/shared/header.css
boac/static/app/shared/header.html
requirements.txt

https://jira.ets.berkeley.edu/jira/browse/BOAC-119
UX: https://confluence.ets.berkeley.edu/confluence/display/LRSASC/Cohort+View+Page
Note: pytest-catchlog has been merged to pytest.

BOAC-119, UX for cohort/search filters and create modal

---

boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/myCohortsDropdown.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-119
Follow up (fixes) on PR #124

BOAC-119, play nice when isCreateCohortMode becomes save search mode

---

boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-170

BOAC-170, limited tools in Cohort 'matrix' view; fix watch on orderBy

---

boac/lib/analytics.py
tests/test_api/test_user_controller.py
tests/test_lib/test_analytics.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-151

BOAC-151 Round all percentile figures to whole numbers

---

boac/api/config_controller.py
boac/static/app/cohort/cohortFactory.js
boac/static/app/shared/googleAnalyticsService.js
boac/templates/index.html
config/default.py
tests/test_api/test_config_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-169
More info: https://developers.google.com/analytics

BOAC-169, track user/browser events with Google Analytics

---

boac/lib/analytics.py
tests/test_lib/test_analytics.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-177

BOAC-177 Stop trying to calculate NaN stats on unvaried datasets

---

boac/lib/merged.py
fixtures/sis_enrollments_api_11667051_2178.json
tests/test_api/test_user_controller.py
tests/test_externals/test_sis_enrollments_api.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-172

BOAC-172 Screen out athletic enrollments

---

boac/auth/cas_auth.py
boac/static/app/auth/authService.js
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/manageCohorts.html
boac/static/app/routes.js
boac/static/app/shared/googleAnalyticsService.js
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-179
* devAuth login is not tracked
* casLogin could be tracked server-side but it's not worth the effort, thus the minor hack.
* Service Lead can decide on other important events to track, if any. (Get out the Magic Eight Ball.)

BOAC-179, Google Analytics > track CAS login, view cohort and view student

---

boac/models/json_cache.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-192

BOAC-192 Avoid cache key conflict on falsey values

---

boac/api/cache_utils.py
boac/models/json_cache.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-192

BOAC-192 Reduce contention on DB sessions caused by lengthy API calls

---

boac/lib/merged.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-186

BOAC-186 De-duplicate enrollments from SIS API

---

boac/api/cohort_controller.py
boac/models/cohort_filter.py
boac/models/team_member.py
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortService.js
boac/static/app/cohort/createCohortController.js
boac/static/app/cohort/manageCohorts.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-187
https://jira.ets.berkeley.edu/jira/browse/BOAC-180
This PR also resolves the 'analytics data not served when cohort is custom and/or unsaved' problem (BOAC-180).

BOAC-187, searching and saving is now possible in cohort 'matrix' view

---

boac/static/app/main.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-181

BOAC-181, find-user dropdown to eight visible options

---

boac/lib/merged.py
fixtures/sis_enrollments_api_11667051_2172.json
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-173

BOAC-173 Suppress dropped enrollments from past terms

---

boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-194

BOAC-194 Hush, JavaScript error

---

boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-189
Layout continues to not be beautiful, but we'll be shuffling everything into a nicer-looking table soon enough.

BOAC-189 Surface Canvas course code for unmatched sites

---

boac/lib/merged.py
boac/static/app/student/student.html
fixtures/sis_student_api_11667051.json
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-135

BOAC-135 Surface multiple majors; suppress meaningless fromDate

---

boac/static/app/shared/googleAnalyticsService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-205

BOAC-205 Fix JS error on cohort view

---

boac/lib/merged.py
fixtures/sis_student_api_11667051.json

https://jira.ets.berkeley.edu/jira/browse/BOAC-207
Compare https://github.com/ets-berkeley-edu/calcentral/blob/master/app/models/my_academics/college_and_level.rb#L255

BOAC-207 Include majors of all sorts

---

boac/lib/analytics.py
boac/static/app/student/courseSiteMetrics.html
boac/static/app/student/courseSiteMetricsDirective.js
boac/static/app/student/student.html
boac/static/app/student/studentController.js
fixtures/canvas_course_enrollments_7654321.json
tests/test_api/test_user_controller.py
tests/test_lib/test_analytics.py
tox.ini

Collect 'em all:
https://jira.ets.berkeley.edu/jira/browse/BOAC-146
https://jira.ets.berkeley.edu/jira/browse/BOAC-147
https://jira.ets.berkeley.edu/jira/browse/BOAC-175
Next is actually showing the the Canvas course scores somewhere (aka BOAC-204).

BOAC-146 BOAC-175 Improve analytics for sparse data sets; add Canvas course scores

---

boac/api/cache_utils.py
boac/models/json_cache.py
run.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-204
Cain't show what ain't thar.

BOAC-204 Add limited support for Canvas score/grade loading

---

boac/merged/sis_enrollments.py
config/default.py
fixtures/sis_enrollments_api_11667051_2162.json
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-174

BOAC-174 Add configurable term limit

---

boac/merged/sis_enrollments.py
boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html
boac/templates/index.html
tests/test_api/test_cohort_controller.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-185
https://jira.ets.berkeley.edu/jira/browse/BOAC-190
Not yet implemented, although data is present in the feed: the small per-class "Activity" percentile bar.

BOAC-185 BOAC-195 Front end: SIS and course data in cohort member list

---

boac/api/cohort_controller.py
boac/externals/asc_cohorts.py
boac/models/cohort_filter.py
boac/models/development_db.py
boac/models/team_member.py
boac/static/app/cohort/cohortFactory.js
boac/static/app/cohort/manageCohorts.html
boac/static/app/cohort/myCohortsDropdown.html
boac/static/app/shared/utilService.js
boac/templates/index.html
scripts/db/migrate/20171206-BOAC-212/create_team_members_column_intensive.sql
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-212
Available in Cohorts dropdown as seen in https://jira.ets.berkeley.edu/jira/browse/BOAC-120

BOAC-212, 'intensive' cohort for all

---

bower.json
package.json

https://jira.ets.berkeley.edu/jira/browse/BOAC-218
Release notes:
* https://github.com/d3/d3/releases
* http://fontawesome.io/whats-new/
* https://github.com/eslint/eslint/releases

BOAC-218, minor upgrade to limited set of third-party deps: d3, fontawesome, eslint, etc.

---

boac/merged/sis_enrollments.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-219

BOAC-219 Associate sections by course, not class name

---

boac/merged/sis_enrollments.py
fixtures/sis_enrollments_api_11667051_2172.json
tests/test_api/test_user_controller.py

I worry that Central Casting has pigeonholed me in this role.
https://jira.ets.berkeley.edu/jira/browse/BOAC-221

BOAC-221 Disambiguate multiple concurrent primary-section enrollments

---

.eslintrc.yml
boac/api/cohort_controller.py
boac/api/user_controller.py
boac/externals/asc_cohorts.py
boac/merged/calnet.py
boac/models/cohort_filter.py
boac/models/development_db.py
boac/models/team_member.py
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortFactory.js
boac/static/app/routes.js
boac/static/app/student/studentController.js
boac/static/app/student/studentFactory.js
scripts/db/migrate/20171207-BOAC-188/01_create_new_team_members_columns.sql
scripts/db/migrate/20171207-BOAC-188/02_drop_member_name_column.sql
tests/test_api/test_cohort_controller.py
tests/test_merged/test_calnet.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-188
* Script to load names from CSV updated
* Pre- and post-migration scripts (SQL)
* Front-end changes per orderBy first and last name

BOAC-188, orderBy on cohort view; db mod scripts; tweak to load_cohorts_from_asc.py

---

boac/api/util.py
boac/static/app/student/student.html
fixtures/sis_enrollments_api_11667051_2178.json
tests/test_api/test_user_controller.py
tests/test_externals/test_sis_enrollments_api.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-226
It's not fire-engine red and blinking, but it's there.

BOAC-226 Show mid-term grades if available

---

boac/merged/sis_enrollments.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-202

BOAC-202 Sort enrollments by course display name

---

boac/static/app/cohort/cohortService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-228

 BOAC-228 Restore matrix / scatterplot view

---

boac/api/cohort_controller.py
boac/merged/member_details.py
boac/models/cohort_filter.py
boac/models/team_member.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-215
A bit of clean-up before complicating the analytics merge.

BOAC-215 Move complex controller-specific merges out of low-level model class

---

boac/api/cache_utils.py
boac/lib/analytics.py
boac/static/app/student/courseSiteMetrics.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-204
This will show stats/boxplot for "Total scores" beneath "Assignments on time" on the student page.

BOAC-204 Merge Canvas site "current score" into student course metrics

---

boac/api/user_controller.py
boac/lib/analytics.py
boac/merged/member_details.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-215
First time through with a big team can still be painful, but at least it gets nicer afterwards.

BOAC-215 Improve cohort view performance with in-memory cache

---

boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/shared/boxplot.css
boac/static/app/shared/boxplotService.js
boac/static/app/student/studentController.js
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-220
Per designs at https://confluence.ets.berkeley.edu/confluence/display/LRSASC/Cohort+View+Page
Highcharts boxplot-drawing code is removed to its own Angular service, offering plots in minified and non-minified flavors.

BOAC-220 Minified activity boxplots in cohort view

---

boac/externals/import_asc_athletes.py
boac/models/athletics.py
boac/models/student.py
scripts/db/migrate/20171211-BOAC-227/create_student_athletes_table.sql
scripts/import_asc_data.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-227
Proposal on how we load and store ASC data: `athletics` and `students` linked by `student_athletes`. Schema would allow for students on zero teams.
When this work is done, we'll delete `scripts/load_cohorts_from_asc.py`.

BOAC-227, proposal on how to normalize 'team_members' data

---

boac/api/user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-224
Durn idioms.

BOAC-224 Fix KeyError when matriculation not present

---

boac/merged/sis_enrollments.py
fixtures/canvas_user_courses_61889.json
tests/test_api/test_user_controller.py
tests/test_externals/test_canvas.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-209

BOAC-209 Sort course site listings by id

---

boac/merged/sis_enrollments.py
boac/static/app/student/student.html
fixtures/sis_enrollments_api_11667051_2178.json
tests/test_api/test_user_controller.py
tests/test_externals/test_sis_enrollments_api.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-222

BOAC-222 Sort sections per enrollment

---

boac/static/app/student/findStudentDirective.js
boac/static/app/student/findStudentSelect.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-234
Sample option-group: "Football, Defensive Line"

BOAC-234, teamGroupName option-groups in findStudent dropdown

---

boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-166

BOAC-166 Tooltips for cohort matrix

---

boac/models/team_member.py
boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortService.js
boac/static/app/cohort/createCohortModal.html
boac/static/app/cohort/deleteCohortModal.html
boac/static/app/cohort/manageCohorts.html
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-236
https://jira.ets.berkeley.edu/jira/browse/BOAC-216
'Show details' now shows list of team-groups.
Disable create-cohort when zero filters are selected (e.g., 'Intensive' cohort)

BOAC-216/BOAC-236, minor fixes to create and manage cohort views

---

boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-241
Not the meatiest burger, this one.

BOAC-241 Cohort list view: change "Activity" to "Page Views"

---

boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohortMatrix.css
boac/static/app/cohort/cohortService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-244
Also consolidate cohort-matrix-related styles in cohortMatrix.css.

BOAC-244 Matrix view: expand user circles on mouseover

---

boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortService.js
boac/static/app/cohort/createCohortController.js
boac/static/app/cohort/createCohortModal.html
boac/static/app/cohort/deleteCohortModal.html
boac/static/app/cohort/manageCohorts.html
boac/static/app/cohort/manageCohortsController.js
boac/static/app/cohort/myCohortsDropdown.html
boac/static/app/cohort/myCohortsDropdownDirective.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-238
https://jira.ets.berkeley.edu/jira/browse/BOAC-239
* Very long Cohort names don't fall off page 
* Cohort names can match neither 'Intensive' nor other cohorts owner by user

BOAC-238, validation and display fixes w.r.t cohort label

---

boac/static/app/cohort/manageCohorts.html
boac/static/app/cohort/manageCohortsController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-255

BOAC-255, change cohort label, click cancel and then reset value in scope

---

boac/static/app/cohort/cohortMatrix.css
boac/static/app/cohort/cohortService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-243

BOAC-243 Restyling with background gradient for cohort matrix

---

boac/api/cache_utils.py
boac/api/user_controller.py
boac/externals/sis_degree_progress_api.py
boac/lib/http.py
boac/lib/mockingbird.py
boac/merged/sis_profile.py
boac/static/app/student/student.css
boac/static/app/student/student.html
config/default.py
fixtures/sis_degree_progress_11667051.xml
fixtures/sis_degree_progress_9999999.xml
requirements.txt
tests/test_api/test_user_controller.py
tests/test_externals/test_sis_degree_progress_api.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-142
Adds support for XML APIs.
Adds link to CalCentral Student Overview page.
Hacks contractually-agreed-upon notes into the Degree Progress UX - needs fixin'!
Please review but don't merge until I've made sure boac-dev is configured for the new API endpoint.

BOAC-142 Integrate undergraduate degree progress data from CS

---

boac/merged/sis_enrollments.py
boac/static/app/student/student.css
boac/static/app/student/student.html
boac/static/app/student/studentController.js
fixtures/sis_enrollments_api_11667051_2178.json
tests/test_api/test_athletics_controller.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_user_controller.py
tests/test_externals/test_sis_enrollments_api.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-260
https://jira.ets.berkeley.edu/jira/browse/BOAC-262
Designs: https://jira.ets.berkeley.edu/jira/browse/BOAC-257
Rebased version of #195.

BOAC-260 BOAC-262 Student profile: reformat class listings

---

README.md
boac/api/athletics_controller.py
boac/api/cohort_controller.py
boac/externals/import_asc_athletes.py
boac/externals/sis_degree_progress_api.py
boac/models/athletics.py
boac/models/cohort_filter.py
boac/models/development_db.py
boac/models/student.py
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortFactory.js
boac/static/app/cohort/createCohortController.js
boac/static/app/cohort/manageCohorts.html
boac/static/app/student/findStudentDirective.js
boac/static/app/student/findStudentSelect.html
tests/test_api/test_athletics_controller.py
tests/test_api/test_cohort_controller.py
tests/test_models/test_cohort_filter.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-265
* `scatterplotRefresh` was missed during refactor of `athletics_controller`, etc.
*  `None` check needed in sis_degree_progress_api
*  refactor var names (eg, `teamGroup.teamGroupCode` is now `teamGroup.groupCode`)

BOAC-265, fix matrix view for Intensive cohort

---

boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-262
Follow-up to #198 per design tweak in https://jira.ets.berkeley.edu/jira/browse/BOAC-213.

BOAC-262 Add border styling to set off dropped classes

---

.ebextensions/01_create_apache_conf.config

https://jira.ets.berkeley.edu/jira/browse/BOAC-193
Commit was cherry-picked from `python36` branch and deployed (via CodePipeline) to https://app-dev.ets-berkeley-boac.net

BOAC-193, master branch: 01_create_apache_conf.config > python-path > python3.6

---

boac/externals/import_asc_athletes.py
tests/test_externals/test_import_asc_athletes.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-143
Request to fix bad ASC data in csv file: https://jira.ets.berkeley.edu/jira/browse/BOAC-269

BOAC-143, test coverage on script to import_asc_data: one athlete on multiple teams

---

boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-262 (following up #198 and #199)

BOAC-262 Tame double border separator

---

boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-245
Designs: https://confluence.ets.berkeley.edu/confluence/display/LRSASC/Cohort+View+Page

BOAC-245 Restyle list of team members without graphable data

---

boac/templates/index.html

NOJIRA, boxplot.css is no more

---

boac/api/cache_utils.py
boac/models/job_progress.py
boac/models/json_cache.py
tests/test_models/test_job_progress.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-138
Preliminaries to support an admin API to manage a long-running job on a background thread.

 BOAC-138 Add background job progress tracker

---

boac/models/cohort_filter.py
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-184
Let's do our best to avoid bad `filter_criteria` data.

BOAC-184, validate all filter_criteria before /cohort/create

---

boac/static/app/shared/header.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-242

BOAC-242 Show name, not UID, in the header

---

boac/api/status_controller.py
tests/test_api/test_status_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-249
Like Junction, we'll call it `/api/ping`.

BOAC-249 Add app status monitoring endpoint

---

boac/models/cohort_filter.py
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortFactory.js
boac/static/app/cohort/createCohortController.js
boac/static/app/student/studentFactory.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-184
Wire the front-end to new filter-criteria support on the backend. In this PR we have reference impl of 'levels' menu, a pattern other filters will follow.

BOAC-184, front-end essentials in support of multiple filter-criteria UI

---

boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-134

BOAC-134 Show ASC-provided name, not SIS primary name, on student profile

---

boac/api/util.py
boac/static/app/student/student.css
boac/static/app/student/student.html
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-268
Grading basis translations are the same as those used by CalCentral.

BOAC-268 Clearly distinguish midpoint grade from final grade

---

boac/api/user_controller.py
boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortService.js
boac/static/app/student/studentFactory.js
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-184
UX: https://jira.ets.berkeley.edu/jira/browse/BOAC-12
Two filter-criteria in one dropdown?! Double your pleasure, double your fun!

BOAC-184, 'Units' dropdown/filter has two sections: pacing and eligibility

---

boac/api/admin_controller.py
boac/api/cache_utils.py
boac/models/job_progress.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-285
Also fixes bug in Canvas scores loader.

BOAC-285 Add non-current-term option to admin data refresh API

---

boac/api/user_controller.py
boac/models/normalized_cache_student_major.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-279
Really liking our new cache...

BOAC-279, user normalized_cache_student_major to pull only relevant_majors

---

boac/static/app/cohort/myCohortsDropdown.html
boac/static/app/main.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-206
I hope Teena Marie will approve.

BOAC-206, style '.dropdown-menu > li > span' like an anchor

---

boac/static/app/cohort/myCohortsDropdown.html
boac/static/app/main.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-206
Cohort filters were impacted by new `.dropdown-menu > li > span` style.

BOAC-206, previous fix to myCohorts dropdowns broke filters dropdowns

---

boac/api/cache_utils.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-291

BOAC-291 Add Canvas Course User Assignments Analytics API to data loads

---

boac/api/cohort_controller.py
boac/lib/util.py
boac/models/development_db.py
boac/models/student.py
boac/static/app/cohort/cohortController.js
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-293
* Sort order options in cohort list view: first_name, gpa, group_code, last_name, level, major
* Includes fix to `/cohort/intensive` (missing member_details)

BOAC-293, cohort list view: order by GPA, level, major, etc.

---

boac/models/athletics.py
boac/models/student.py
tests/test_api/test_athletics_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-295
`/api/team` must rely on the now infamous `get_students` query.

BOAC-295, order by GPA, level, major, etc. support for /api/team

---

boac/static/app/cohort/cohort.css
boac/static/app/cohort/manageCohorts.html
boac/static/app/cohort/myCohortsDropdown.html
boac/static/app/main.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-296
See screenshot in Jira above.

BOAC-296, 'My cohorts dropdown' in header gets proper mouseover behavior

---

boac/__init__.py
boac/api/cache_utils.py
boac/externals/import_asc_athletes.py
boac/merged/calnet.py
boac/models/base.py
boac/models/cohort_filter.py
boac/models/development_db.py
boac/models/job_progress.py
boac/models/json_cache.py
boac/models/normalized_cache_student.py
boac/models/normalized_cache_student_major.py
scripts/obfuscate_cohort_fixtures.py
tests/test_models/test_cohort_filter.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-292

BOAC-292 Exceptions during a commit require explicit session rollback

---

boac/static/app/cohort/cohortMatrix.css
boac/static/app/cohort/cohortService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-297

BOAC-297 Matrix view: make axis labels visible

---

boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-317
$Location, $location, $location.

BOAC-317, update browser location URL after cohort creation

---

boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-312
I've checked and this doesn't break @johncrossman 's https://github.com/ets-berkeley-edu/boac/pull/237 fix.

BOAC-312 Switch the cohort matrix Y-axis to Assignment Grades

---

boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/shared/boxplotService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-298

BOAC-298 Performance improvements to cohort boxplot rendering

---

boac/static/app/student/student.html
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-288

BOAC-288 Hide preferred name when identical to primary name

---

boac/static/app/cohort/cohort.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-302

BOAC-302 1 Result is 1 Result

---

boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-298
Follow-up to #241. Without this explicit nudging, boxplots won't draw for custom cohorts.

BOAC-298 Custom cohorts need boxplots too

---

boac/models/cohort_filter.py
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-277
The 'cohortController` is simplified if we make a few assumptions:
* `cohort` is always defined, even if we are execute-search mode
* `cohort.code` is always defined for team and custom cohort
* the block of code under `$scope.$watch('$location' ...` might be used for 'Return to results', too.     Note: `$location` is not immediately available during init phase

BOAC-277, bookmarkeable matrix view; cohort object is always defined, even in search

---

boac/api/admin_controller.py
boac/api/cache_utils.py
scripts/refresh_current_term_cache.sh

https://jira.ets.berkeley.edu/jira/browse/BOAC-322
Here's hoping this gives enough information to go on...

BOAC-322 One bug fix, some diagnostic logging for cache refresh

---

boac/static/app/cohort/cohort.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-277
See comments in PR #246

BOAC-277, cohort.code tells us if we have a saved or unsaved cohort

---

boac/static/app/shared/boxplotService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-301

BOAC-301 Fix unwanted tooltip persistence

---

boac/api/cohort_controller.py
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-333
Fix regressions caused by 'bookmarkability' work.

BOAC-333, fix workflow to 'create cohort'; put 'Intensive' name to feed

---

boac/api/athletics_controller.py
boac/api/cohort_controller.py
boac/api/config_controller.py
boac/api/error_handlers.py
boac/api/errors.py
boac/api/status_controller.py
boac/api/user_controller.py
boac/auth/cas_auth.py
boac/lib/http.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-329
Everything's tolerant! Everything's ugly!

BOAC-329 Standardize JSON API formatting

---

boac/api/user_controller.py
boac/lib/analytics.py
boac/merged/member_details.py
fixtures/canvas_course_assignments_analytics_7654321_61889.json
tests/test_externals/test_canvas.py
tests/test_lib/test_analytics.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-314
The merged data does not yet appear in the UX, so this change is not aimed for QA and the first production release.

BOAC-314 Merge Course Student Assignments Analytics data (server-side)

---

boac/lib/analytics.py
fixtures/canvas_course_assignments_analytics_7654321_61889.json

https://jira.ets.berkeley.edu/jira/browse/BOAC-338
No hobgoblins disturb the minds of Canvas developers.

BOAC-338 Handle inconsistent Course Student Assignments Analytics feeds

---

boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-256

BOAC-256 Cross-browser styling for cohort filter buttons

---

LICENSE
boac/static/app/shared/footer.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-331
Does anyone really know what time it is? Does anyone really care?

BOAC-331 New year, same Regents

---

boac/lib/analytics.py
fixtures/canvas_course_enrollments_7654321.json
tests/test_externals/test_canvas.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-321

BOAC-321 Round raw score to match rounded min, max, median

---

boac/static/app/bootstrap.js
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/student/student.html
boac/static/app/student/studentController.js
boac/templates/index.html
bower.json

https://jira.ets.berkeley.edu/jira/browse/BOAC-319
We `base64.encode` the cohort view URL before heading to student profile. Return to student (with anchor) using Angular `$anchorScroll`

BOAC-319, link on student profile to 'return to cohort'

---

boac/merged/sis_profile.py
fixtures/sis_student_api_11667051.json
tests/test_externals/test_sis_student_api.py
tests/test_merged/test_sis_profile.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-334
QA version of #256. Per QA Dept we may as well get the code in, since its effects are present in the shared db.

[QA] BOAC-334 Skip concurrent-enrollment academic status

---

boac/static/app/bootstrap.js
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/student/student.html
boac/static/app/student/studentController.js
boac/templates/index.html
bower.json

https://jira.ets.berkeley.edu/jira/browse/BOAC-319
master PR: #266

[QA] BOAC-319, link on student profile to 'return to cohort'

---

boac/externals/canvas.py
boac/lib/analytics.py
fixtures/canvas_user_courses_61889.json
tests/test_externals/test_canvas.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-348

BOAC-348 Do not include sites unless the student became a member

---

boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortFactory.js
boac/static/app/cohort/manageCohortsController.js
boac/static/app/landing/landing.html
boac/static/app/main.css
boac/static/app/routes.js
boac/static/app/student/student.css
boac/static/app/student/student.html
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-299
https://jira.ets.berkeley.edu/jira/browse/BOAC-345
A few small fixes/refinements:
* 'Return to cohort' link sends you back to highlighted anchor in list
* large spinner on student profile; no footer until `!isLoading`
* broadcast "cohort-deletion" event for responsive `/manageCohorts` page

BOAC-299/BOAC-345, matrix view must play nice with search and return from profile

---

boac/api/cache_utils.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-294

BOAC-294 Empty lists are not always failures

---

boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortFactory.js
boac/static/app/cohort/manageCohortsController.js
boac/static/app/landing/landing.html
boac/static/app/main.css
boac/static/app/routes.js
boac/static/app/student/student.css
boac/static/app/student/student.html
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-299
https://jira.ets.berkeley.edu/jira/browse/BOAC-345
master PR is #269

[QA] BOAC-299/BOAC-345, matrix view must play nice search and return from profile

---

boac/models/student.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-323

BOAC-323, secondary_sort = 'last_name' if order_by == 'first_name' else 'first_name'

---

buildspec.yml

https://jira.ets.berkeley.edu/jira/browse/BOAC-354

BOAC-354, give buildspec.yml valid 'Image' value in eb_codebuild_settings

---

boac/lib/util.py
boac/merged/sis_profile.py
fixtures/sis_student_api_11667051.json
tests/test_lib/test_util.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-288
Follow-up to #242.

BOAC-288 Clean up extra whitespace from SIS Student API

---

.ebextensions/00_ami.config

https://jira.ets.berkeley.edu/jira/browse/BOAC-275

BOAC-275 Add immutable deployment policy to ebextensions

---

buildspec.yml

https://jira.ets.berkeley.edu/jira/browse/BOAC-354
master PR is #274

[QA] BOAC-354, buildspec.yml has an invalid 'Image' value in eb_codebuild_settings

---

.ebextensions/00_ami.config

https://jira.ets.berkeley.edu/jira/browse/BOAC-275

BOAC-275 Add enhanced health reporting to ebextensions

---

boac/lib/util.py
boac/merged/sis_profile.py
fixtures/sis_student_api_11667051.json
tests/test_lib/test_util.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-288
Master PR #273 
Since the effects of this code are visible in the boac_shared database, may as well get it into the qa branch for consistency.

[QA] BOAC-288 Clean up extra whitespace from SIS Student API

---

boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-351

BOAC-351 Do not assume that all course sites have had student viewers

---

bower.json

[QA] NOJIRA, qa branch is now v1.0

---

bower.json

I'll submit qa PR with version: 1.0

NOJIRA, master branch is now v1.1

---

boac/static/app/cohort/cohortController.js

QA version of https://github.com/ets-berkeley-edu/boac/pull/280

[QA] BOAC-351 Do not assume that all course sites have had student viewers

---

boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-359
Ensures it's still picked up when returning from student profile.

BOAC-359 Change location of boxplot drawing call

---

.gitignore
boac/api/config_controller.py
buildspec.yml
scripts/create-build-summary.sh
tests/test_api/test_config_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-361
Version and build info moves out of `/api/config`

BOAC-361, /api/version has version and build info

---

.ebextensions/00_ami.config

https://jira.ets.berkeley.edu/jira/browse/BOAC-275
Master PRs: #277, #278, #282.

[QA] BOAC-275 Enable immutable deployments, managed updates in ebextensions

---

boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-359
Master PR #283.

[QA] BOAC-359 Change location of boxplot drawing call

---

boac/static/app/cohort/cohort.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-358
Firefox only. See screenshot in Jira.

BOAC-358, no snipping tails off cohort name

---

boac/static/app/cohort/cohort.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-358
master PR is #291

[QA] BOAC-358, no snipping tails off cohort name

---

boac/merged/sis_profile.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-362

BOAC-362 Catch & log malformed Hub Student API feed rather than failing

---

boac/merged/sis_profile.py

QA version of https://github.com/ets-berkeley-edu/boac/pull/293

[QA] BOAC-362 Catch & log malformed Hub Student API feed rather than failing

---

boac/static/app/cohort/cohortService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-349

BOAC-349 Fix clip path, overflow for users on matrix

---

boac/static/app/cohort/cohortService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-349
Master PR #295.

[QA] BOAC-349 Fix clip path, overflow for users on matrix

---

boac/static/app/cohort/cohortService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-349
Follow-up to #295.

BOAC-349 Even expanded heads do not deserve to be cut off

---

boac/static/app/cohort/cohortService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-349
Master PR #301.
Follow-up to #295 / QA #296.

[QA] BOAC-349 Even expanded heads do not deserve to be cut off

---

boac/models/student.py
boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html
tests/test_api/test_cohort_controller.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-341

BOAC-341 Add team memberships to cohort list view

---

boac/models/student.py
boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html
tests/test_api/test_cohort_controller.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-341
Master PR #304.

[QA] BOAC-341 Add team memberships to cohort list view

---

LICENSE
boac/static/app/shared/footer.html

QA version of https://github.com/ets-berkeley-edu/boac/pull/264

[QA] BOAC-331 New year, same Regents

---

boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-360
`auto-close="outsideClick"` is a well documented feature (see http://angular-ui.github.io/bootstrap/) and it has [a known issue with workaround](https://github.com/angular-ui/bootstrap/issues/6038), as seen in this PR.

BOAC-390, click outside cohort-filter dropdown to close it

---

boac/lib/analytics.py
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortMatrix.css
boac/static/app/cohort/cohortService.js
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-353
https://jira.ets.berkeley.edu/jira/browse/BOAC-347
New headers, changed labels.

BOAC-347 BOAC-353 Clarify data sources in the Cohort Matrix view

---

boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-256
https://jira.ets.berkeley.edu/jira/browse/BOAC-360
Commits are from master PRs #258 and #308

[QA] BOAC-256/BOAC-360, cross-browser filter buttons; dropdowns close when you click outside

---

boac/models/development_db.py
boac/models/student.py
boac/static/app/cohort/cohortController.js
tests/test_api/test_athletics_controller.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_user_controller.py
tests/test_merged/test_sis_profile.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-370
Wait until master PR #310 is merged, in case amendments are needed.

[QA] BOAC-370, order by group_name, not group_code

---

boac/static/app/cohort/cohortController.js
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-373

BOAC-373 Clear temporary query strings from browser history

---

boac/static/app/cohort/cohortController.js
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-373
Master PR #312.

[QA] BOAC-373 Clear temporary query strings from browser history

---

boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-360
master PR is #314  (I verified on boac-dev)

[QA] BOAC-360, Angular ui-bootstrap needs menu-options in DOM for auto-close=outsideClick to work

---

boac/lib/analytics.py
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortMatrix.css
boac/static/app/cohort/cohortService.js
tests/test_api/test_cohort_controller.py

QA version of https://github.com/ets-berkeley-edu/boac/pull/307

[QA] BOAC-347 BOAC-353 Clarify data sources in the Cohort Matrix view

---

boac/models/student.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-375
Master PR #318 didn't cause any obvious problems on dev; let's see if this solves anything on qa.

[QA] BOAC-375 Keep db connection open while iterating through results

---

boac/api/cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-369

BOAC-369, order by first_name, last_name on 'Everyone's Cohorts'

---

boac/merged/member_details.py
boac/models/student.py
tests/test_api/test_athletics_controller.py
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-374
Easy part: order team groups and majors alphabetically.
Hard part: ensure that, in the edge case where group or major is both a filter criterion and an ordering criterion, alphabetical order is still respected. This requires an extra join in the query; I'm the first to admit this is a little persnickety for an edge case, but it is at least discreetly tucked away under a conditional.

BOAC-374 Cohort ordering for multiple teams, majors

---

consoler.py

I told @paulkerschen I'd add this in October, I think. Maybe it's still of some interest to a dev somewhere?

NOJIRA BOAC console support for PyCharm or command line

---

boac/static/app/cohort/cohortService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-378

BOAC-378 Matrix view: shift tooltip down, fix centering

---

boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-357

BOAC-357, restore pagination when clicking back to List view

---

boac/api/util.py
boac/externals/canvas.py
boac/lib/analytics.py
boac/models/base.py
scripts/cohort_fixtures.py
scripts/obfuscate_cohort_fixtures.py
tox.ini

https://jira.ets.berkeley.edu/jira/browse/BOAC-379
Minor tweaks to conclude tox enhancements.

BOAC-379, last of CI enhancements, for now: pep8-naming and fstrings

---

boac/externals/import_asc_athletes.py
consoler.py
tests/test_externals/test_import_asc_athletes.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-368
Also restores a consoler.py line mistakenly deleted by an earlier PR.

BOAC-368 Modify ASC student/team import to handle latest TSV file

---

boac/api/cache_utils.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-389

BOAC-389 Let the UX see freshly loaded students & teams

---

.ebextensions/00_ami.config

https://jira.ets.berkeley.edu/jira/browse/BOAC-307

[QA] BOAC-307, swap in ARN of asc-pilot: 00_ami.config

---

.ebextensions/00_ami.config

Master version of https://github.com/ets-berkeley-edu/boac/pull/334

BOAC-307, swap in ARN of asc-pilot: 00_ami.config

---

boac/models/development_db.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-405
Vanessa and Flint, to be specific.

BOAC-405, BOAC access for two more PDG staff

---

boac/models/cohort_filter.py
boac/models/development_db.py
tests/test_api/test_athletics_controller.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-404

BOAC-404 Team group codes no longer require hyphenated suffixes

---

boac/models/cohort_filter.py
boac/models/development_db.py
tests/test_api/test_athletics_controller.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_user_controller.py

QA version of https://github.com/ets-berkeley-edu/boac/pull/339

[QA] BOAC-404 Team group codes no longer require hyphenated suffixes

---

.ebextensions/03_download_local_configuration.config
scripts/deploy_boac_config.sh

https://jira.ets.berkeley.edu/jira/browse/BOAC-385
`AWS_PROFILE=boac` is not needed in this particular approach. Tested on boac-dev.

BOAC-385, script uses EB_ENVIRONMENT to deploy s3://boac-config/__.py to production-local.py

---

.ebextensions/00_ami.config
.ebextensions/01_create_apache_conf.config

https://jira.ets.berkeley.edu/jira/browse/BOAC-413
Hat tip for https://stackoverflow.com/questions/14693852/how-to-force-https-on-elastic-beanstalk/38751749#38751749 for a workable solution.

BOAC-413 Redirect http to https

---

.ebextensions/00_ami.config
.ebextensions/01_create_apache_conf.config

https://jira.ets.berkeley.edu/jira/browse/BOAC-413
QA version of #342.

[QA] BOAC-413 Redirect http to https

---

boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortService.js
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-402
Two commits for what turned out to be two unrelated front-end issues.
The first one honors gulp-rev-replace's expectation that a given reference will only appear once per file.

 BOAC-402 Make base64 URL-safe, fix console error

---

boac/__init__.py
boac/api/config_controller.py
bower.json

https://jira.ets.berkeley.edu/jira/browse/BOAC-361
This convention is used by [`pip` project](https://packaging.python.org/guides/single-sourcing-package-version/)

BOAC-361, boac/__init__.py is our single source for version info

---

boac/static/app/landing/landing.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-421
Whoops.

BOAC-421, link to student needs UID, not SID

---

boac/static/app/main.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-435
Collateral damage of PR #333

BOAC-435, the large spinner is not too big to fail

---

boac/static/app/landing/landing.html
boac/static/app/student/findStudentDirective.js
boac/static/app/user/watchlistToggleDirective.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-428

BOAC-428, SID in findStudent options; NOJIRA, 'Watchlist' is now 'My List'

---

boac/static/app/student/findStudent.html
boac/static/app/student/findStudentDirective.js
boac/static/app/student/findStudentFilter.js
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-397
Two filters needed:
* filter list of students per input
* put `<strong>` on matching substrings
Default filters were not good enough.

BOAC-397, search by first and last name, even if student has middle name

---

boac/externals/import_asc_athletes.py
boac/models/student.py
scripts/import_asc_data.py
tests/test_externals/test_import_asc_athletes.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-386
https://jira.ets.berkeley.edu/jira/browse/BOAC-407
Currently `merge_tsv` has to be run manually rather than from a server, but since this version of code will hit Production and QA data, we might as well make it official.

[QA] BOAC-407 Support merging of updates from ASC

---

boac/api/alerts_controller.py
boac/models/alert.py
boac/models/authorized_user.py
boac/models/db_relationships.py
boac/models/development_db.py
boac/routes.py
scripts/db/migrate/20180122-BOAC-422/create_alerts_tables.sql
tests/test_api/test_alerts_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-422
https://jira.ets.berkeley.edu/jira/browse/BOAC-423
https://jira.ets.berkeley.edu/jira/browse/BOAC-424
https://jira.ets.berkeley.edu/jira/browse/BOAC-425
Models, controller and tests for showing alerts to their viewers. Not included: 
- How is viewership of a given alert decided? (requirements TBD)
- How are alerts generated in the first place? (spoiler: they will probably have to be tied to our data update logic)

BOAC-422 BOAC-423 BOAC-424 BOAC-425 Back end for alerts framework

---

scripts/db/migrate/20180125-BOAC-440/alter_existing_production_schema.sql

https://jira.ets.berkeley.edu/jira/browse/BOAC-440
After review, I'll test this against the QA DB.

BOAC-440 Fix gaps in the existing Prod/QA DB schemas

---

boac/externals/import_asc_athletes.py
boac/models/student.py
scripts/import_asc_data.py
tests/test_externals/test_import_asc_athletes.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-386
https://jira.ets.berkeley.edu/jira/browse/BOAC-407
The Student deletion code is simpler than https://github.com/ets-berkeley-edu/boac/pull/354 thanks to `ON DELETE CASCADE` settings in the boac_shared schema.

BOAC-386 BOAC-407 Support merging of updates from ASC TSV files

---

boac/static/app/student/student.css
boac/static/app/student/student.html
boac/static/app/student/studentController.js
boac/static/app/student/studentFactory.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-427
Design ticket: https://jira.ets.berkeley.edu/jira/browse/BOAC-168
With a couple of starter alert types supported.

BOAC-427 Show alerts on student profile pages

---

boac/api/cohort_controller.py
boac/api/util.py
boac/externals/import_asc_athletes.py
boac/models/athletics.py
boac/models/development_db.py
boac/models/student.py
scripts/db/migrate/20180129-BOAC-380/store_student_active_status.sql
scripts/db/schema.sql
tests/test_api/test_cohort_controller.py
tests/test_externals/test_import_asc_athletes.py
tests/test_merged/test_sis_profile.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-380

BOAC-380 Add IS_ACTIVE, STATUS to students DB

---

boac/externals/import_asc_athletes.py
boac/models/student.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-380
When I started using the newly merged code, I immediately tripped over a couple of bugs I'd missed. Oh well.

BOAC-380 Followup fixes to support inactive students

---

boac/static/app/landing/landing.css
boac/static/app/landing/sortableAlertsTable.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-445

BOAC-445 If you got no issues, say so

---

boac/models/alert.py
boac/static/app/student/student.html
boac/static/app/student/studentController.js
tests/test_api/test_advisor_watchlist_controller.py
tests/test_api/test_alerts_controller.py
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-443

BOAC-443 Include dismissed alerts in per-student alerts feed

---

boac/static/app/student/student.css
boac/static/app/student/student.html
boac/static/app/student/studentAlertMessage.html
boac/static/app/student/studentAlertMessageDirective.js
boac/static/app/student/studentController.js
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-444

BOAC-444 Student profile: front-end toggle for dismissed alert display

---

boac/models/student.py
boac/static/app/landing/landing.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-455
We assume that students with GPA=0 have no GPA (e.g., incoming freshman). Exclude such persons when searching...

BOAC-455, exclude students with GPA=0 when searching by gpaRange(s)

---

boac/externals/import_asc_athletes.py
tests/test_externals/test_import_asc_athletes.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-447

BOAC-447 Students can be Active on one team, Inactive on another

---

boac/api/cache_utils.py
boac/lib/berkeley.py
boac/models/alert.py
scripts/db/migrate/20180122-BOAC-422/create_alerts_tables.sql
tests/conftest.py
tests/test_api/test_alerts_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-461
Because a call to action for last October is nothing but a cruel taunt.

BOAC-461 Restrict student status alerts by term

---

boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-438
First things first.

BOAC-438, put myWatchlist to scope before rendering matrix

---

boac/merged/sis_enrollments.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-437
Most of the code change is actually just rearrangement because tox thought merge_sis_enrollments_for_term was too complex.

BOAC-437 Show units and grading basis for waitlisted classes

---

boac/static/app/cohort/cohort.html
boac/static/app/main.css
boac/static/app/student/student.html
boac/static/app/user/watchlistToggle.html
boac/static/app/user/watchlistToggleDirective.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-454
https://jira.ets.berkeley.edu/jira/browse/BOAC-462
The UX...

BOAC-454/BOAC-462, fa-plus/fa-minus for myList add/remove; no icon in h1 and h3 please

---

boac/api/admin_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-464

BOAC-464 Follow the wandering current_term_id

---

boac/static/app/cohort/cohort.html

See most recent comments in https://jira.ets.berkeley.edu/jira/browse/BOAC-463

BOAC-463, keep the list/matrix toggle when zero results in matrix view

---

.eslintrc.yml
boac/api/cohort_controller.py
boac/api/user_controller.py
boac/lib/util.py
boac/models/cohort_filter.py
boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortFactory.js
boac/static/app/cohort/createCohortController.js
boac/static/app/cohort/myCohortsDropdown.html
boac/static/app/routes.js
boac/static/app/shared/utilService.js
boac/static/app/student/studentFactory.js
tests/test_api/test_cohort_controller.py
tests/test_api/test_user_controller.py
tests/test_lib/test_util.py
tests/test_models/test_cohort_filter.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-326
UX is in the Jira. I ripped out `/api/intensive_cohort` endpoint in favor of optional 'intensive' arg in `/api/student`. A remaining task: the manageMyCohorts view must include proper "pill" icon if intensive is true.

BOAC-326, 'inIntensiveCohort' is new attribute in cohortFilters object and checkbox on cohort view

---

boac/models/student.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-470

BOAC-470, case-insensitive 'order by' in get_students query

---

boac/api/admin_controller.py
boac/api/cache_utils.py
boac/models/job_progress.py
tests/test_models/test_job_progress.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-407
This also makes the cachejob status report less verbose and more informative.

BOAC-407 Add admin API support for ASC imports

---

boac/static/app/cohort/cohortController.js
boac/static/app/cohort/manageCohortsController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-477
https://jira.ets.berkeley.edu/jira/browse/BOAC-476

BOAC-477, filter out college-specific 'undeclared' major options

---

boac/api/cache_utils.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-475

BOAC-475 Align cache-load and API logic for analytics feeds

---

boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-480

BOAC-480, pre-pop groupCodes dropdown when c=team_code

---

boac/static/app/student/student.css
boac/static/app/student/student.html

Per discussion in https://jira.ets.berkeley.edu/jira/browse/BOAC-324, the unmatched course sites currently on view come across best with course name only.

BOAC-324 Adjust layout for unmatched course sites

---

boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-479

BOAC-479, align/style the Intensive checkbox label

---

boac/api/cohort_controller.py
boac/api/user_controller.py
boac/models/cohort_filter.py
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortFactory.js
boac/static/app/cohort/cohortService.js
boac/static/app/cohort/createCohortController.js
boac/static/app/cohort/myCohortsDropdown.html
boac/static/app/routes.js
boac/static/app/student/student.css
boac/static/app/student/student.html
boac/static/app/student/studentFactory.js
tests/test_api/test_cohort_controller.py
tests/test_api/test_user_controller.py
tests/test_models/test_cohort_filter.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-409
https://jira.ets.berkeley.edu/jira/browse/BOAC-414
https://jira.ets.berkeley.edu/jira/browse/BOAC-415

BOAC-414 BOAC-415 Add ability to view Inactive students

---

boac/models/student.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-473
See Jira for use case.

BOAC-473, tertiary sort order for get_students

---

boac/static/app/cohort/cohort.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-486
Thanks for the catch, @pfarestveit !

BOAC-486 Fix Inactive checkbox positioning

---

boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-487
Regressions are a sign of productivity. The culprit is PR #391

BOAC-487, preset filter/dropdown with option.value; look up team with groupCode

---

boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-487
master PR is #398

[QA] BOAC-487, preset filter/dropdown with option.value; look up team with groupCode

---

boac/merged/import_asc_athletes.py
tests/test_merged/test_import_asc_athletes.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-467

BOAC-467 Disambiguate "remainder" team groups

---

boac/models/athletics.py
boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-487
https://jira.ets.berkeley.edu/jira/browse/BOAC-497
master PRs: #398 #404
This time it's really going to 'qa' branch...

[QA] BOAC-487 / BOAC-497, 'Teams' filter options need proper name and checkboxes that remain checked

---

boac/lib/util.py
boac/models/student.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-488
Master PR #403.

[QA] BOAC-488 De-duplicate sids within students query

---

boac/static/app/cohort/manageCohorts.html
boac/static/app/landing/landing.css
boac/static/app/landing/landing.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-489
A call to action! (We do not use 'Create your first...' because it's not necessarily the user's first.)

BOAC-489, You have no cohorts? Create one.

---

boac/models/alert.py
config/default.py
tests/test_api/test_alerts_controller.py
tests/test_api/test_cache_utils.py
tests/test_models/test_alert.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-502

BOAC-502 Adjust alert due dates for sunny California

---

boac/models/alert.py
config/default.py
tests/test_api/test_alerts_controller.py
tests/test_api/test_cache_utils.py
tests/test_models/test_alert.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-502
QA version of #409.

[QA] BOAC-502 Adjust alert due dates for sunny California

---

boac/api/status_controller.py
boac/externals/data_loch.py
config/default.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-164
I'll add it to the Dev configuration after the merge (if any).

BOAC-164 Configure & verify Data Loch connection

---

boac/merged/sis_enrollments.py
boac/models/alert.py
fixtures/sis_enrollments_api_11667051_2172.json
tests/test_api/test_alerts_controller.py
tests/test_api/test_cache_utils.py
tests/test_merged/test_sis_enrollments.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-452
The tests might be getting a little over-finicky, but I didn't try a big overhaul.

BOAC-452 Add Midterm Grade alert

---

boac/models/student.py
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/landing/landingController.js
boac/static/app/landing/sortableAlertsTable.html
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-509
Behavior changes for:
- "My List" and cohort member lists on landing page
- Default primary or secondary sort order on cohort list view (unless explicitly sorting by first name)
- "Missing Student Data" list under the cohort matrix view

BOAC-509 Default to sorting lists of students by last name

---

boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/main.css
boac/static/app/student/student.css
boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-513
A surprising amount of this is just alphabetizing CSS.

BOAC-513 Midterm and final grades in cohort view

---

boac/models/alert.py
boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html
boac/static/app/landing/landing.css
boac/static/app/landing/sortableAlertsTable.html
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-522

BOAC-522 Add Inactive indicators

---

boac/static/app/student/student.css
boac/static/app/student/student.html

`uib-accordion` does the heavy lifting. There are a couple outstanding tasks (e.g., show total units per term).

BOAC-484, accordion style for student profile > classes per term

---

boac/static/app/student/student.css
boac/static/app/student/student.html
boac/static/app/student/studentController.js

* one and only one course can have `isShowingDetails = true`
* if no canvasSites then message: 'No additional info'
* remove stray 'Dropped'

BOAC-484, click to see course details causes other courses to collapse

---

boac/static/app/student/student.css
boac/static/app/student/student.html
boac/static/app/student/studentController.js

After "soaking" in dev for a day, the feature gets a tweak: do not auto-collapse course details when clicking elsewhere.

BOAC-484, student profile accordion UX action: close-others=false

---

boac/static/app/course/course.html
boac/static/app/course/courseController.js
boac/static/app/routes.js
boac/static/app/user/authFactory.js
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-531
Similar to cohort view, we rely on `$location.search()` – useful when implementing `Return to History 101` link on student profile page.

BOAC-531, basic wiring for /course?c=123 with a little cleanup in routes.js

---

boac/auth/cas_auth.py
boac/static/app/routes.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-468
This replaces current "redirect unauthorized requests to home page" behavior.

BOAC-468 Redirect unauthorized requests to CAS, preserving target URL

---

boac/api/user_controller.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-538

BOAC-538 Require student db record to serve photo

---

boac/api/config_controller.py
boac/api/user_controller.py
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/landing/sortableAlertsTable.html
boac/static/app/landing/sortableAlertsTableDirective.js
boac/static/app/main.css
boac/static/app/student/findStudentDirective.js
boac/static/app/student/student.html
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-539
We can improve/iterate on this approach. A good-enough impl for purpose of upcoming demos.

BOAC-539, if demoMode then demo-mode-blur style on sensitive info in UI

---

boac/api/config_controller.py
boac/api/user_controller.py
boac/lib/util.py
boac/static/app/main.css
tests/test_api/test_config_controller.py
tests/test_lib/test_util.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-539

BOAC-539, demo_mode fix for /api/user/photo: proper config key needed

---

boac/static/app/shared/boxplotService.js
boac/static/app/student/student.css
boac/static/app/student/student.html
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-540

BOAC-540 Tooltip for student unit progress bar

---

boac/static/app/cohort/cohortService.js
boac/static/app/shared/utilService.js
boac/static/app/student/findStudentDirective.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-539
One more bit of blurring.

BOAC-539, demo-mode-blur for names in matrix view; student names in search replaced with random gen

---

boac/__init__.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-546

[QA] BOAC-546, qa branch is now v1.2

---

boac/__init__.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-546
QA PR is #437

BOAC-546, master branch is now v1.3

---

boac/static/app/student/student.css
boac/static/app/student/student.html

I suggest you review with `?w=1`

[QA] BOAC-484, move droppedSections block out of unmatchedCanvasSites block

---

boac/static/app/student/student.css
boac/static/app/student/student.html

BOAC-484, move droppedSections block out of unmatchedCanvasSites block

---

boac/auth/cas_auth.py
boac/lib/http.py
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-468
QA version of #441.

[QA] BOAC-468 CAS redirect: parse URLs right

---

boac/static/app/student/student.css
boac/static/app/student/student.html
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-548
For example:

[QA] BOAC-548, prominent display of 'Waitlisted' on student profile, per course

---

boac/static/app/student/student.css
boac/static/app/student/student.html
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-548
QA PR is #444

BOAC-548, prominent display of 'Waitlisted' on student profile, per course

---

boac/static/app/student/student.css
boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-550
QA PR is #446

BOAC-550, group dropped sections in last row of course list, per term

---

boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-544

BOAC-544 Links to Berkeley Academic Guide should open in a new tab

---

boac/static/app/student/student.html
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-554
QA PR is #451

BOAC-554, unmatchedCanvasSites rendered with same template code as term.enrollments

---

boac/api/util.py
boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortService.js
boac/static/app/course/course.html
boac/static/app/course/courseController.js
boac/static/app/main.css
boac/static/app/shared/matrix.css
boac/static/app/shared/matrix.html
boac/static/app/shared/tabs.html
boac/static/app/shared/utilService.js
boac/static/app/student/student.css
boac/static/app/student/student.html
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-533
A lot of CSS shuffling. Shared template code: matrix and tabs.

BOAC-533, student list/matrix views on course page; shared code

---

boac/static/app/shared/matrix.html
boac/static/app/student/courseSiteMetricsDirective.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-515

BOAC-515 Clarify online assignment timeliness metric

---

boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/course/course.html
boac/static/app/course/courseController.js
boac/static/app/shared/matrix.css
boac/static/app/shared/tabs.html
boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-534
https://jira.ets.berkeley.edu/jira/browse/BOAC-541
Bonus: email and phone icons

BOAC-534, matrix view on class page

---

boac/api/course_controller.py
boac/models/normalized_cache_enrollment.py
boac/static/app/course/courseFactory.js
boac/static/app/shared/profile.css
boac/static/app/shared/utilService.js
boac/static/app/student/student.css
boac/static/app/student/student.html
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-535
I use `fa-external-link` as a UX placeholder.

BOAC-535, link to class/section pages from student view

---

boac/merged/import_asc_athletes.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-560

BOAC-560 Keep BOAC student names and UIDs up to date with CalNet

---

boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-552

BOAC-552 Disable "Save Cohort" if there are no selection filters

---

boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/course/course.html
boac/static/app/course/courseController.js
boac/static/app/routes.js
boac/static/app/shared/matrix.html
boac/static/app/shared/utilService.js
boac/static/app/student/studentController.js
boac/static/app/student/studentService.js
boac/templates/index.html
tests/test_api/test_api_errors.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-537
https://jira.ets.berkeley.edu/jira/browse/BOAC-561
Our 'return-to-previous' and 'anchor-scroll' logic will be shared. PR also includes a step towards meaningful page titles.

BOAC-537, user clicks to student from class page then offer 'Return to' link

---

boac/static/app/cohort/cohortController.js
boac/static/app/course/course.html
boac/static/app/course/courseController.js
boac/static/app/shared/utilService.js
boac/static/app/student/student.html
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-537

BOAC-537, more on 'Return to course' from student page

---

boac/api/util.py
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/course/course.css
boac/static/app/course/course.html
boac/static/app/course/courseController.js
boac/static/app/shared/matrix.html
boac/static/app/shared/profile.css
boac/static/app/shared/utilService.js
boac/static/app/student/studentController.js
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-532
https://jira.ets.berkeley.edu/jira/browse/BOAC-537

BOAC-532, class page sidebar; return-to link has informative label

---

boac/static/app/cohort/cohort.html
boac/static/app/course/course.css
boac/static/app/course/course.html
boac/static/app/main.css
boac/static/app/shared/header.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-533
This kind of nonsense seems appropriate:
```
.course-column-headers {
align-content: flex-end;
align-items: flex-start;
display: flex;
justify-content: flex-end;
}
```
https://css-tricks.com/snippets/css/a-guide-to-flexbox/

BOAC-533, gettin' jiggy with flexbox in course column headers

---

boac/api/cache_utils.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-579
No need to be shy about it.

BOAC-579 Catch & log errors in background job thread

---

boac/static/app/cohort/cohortService.js
boac/static/app/course/class-group-icon.svg
boac/static/app/course/course.html
boac/static/app/course/courseController.js
boac/static/app/shared/boxplotService.js
boac/static/app/shared/matrix.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-536
* icon (svg) is from BOAC-394 (design Jira)
* changes in `courseController` allow graceful fail when 'no such section'

BOAC-536, phantom student, 'Class Average', using mock data for now

---

boac/externals/asc_athletes_api.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-579

BOAC-579 Do not let ASC API failures block cache refresh

---

boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/course/course.html
boac/static/app/course/courseController.js
boac/static/app/shared/boxplotService.js
boac/static/app/visual/boxplotPageViewsDirective.js
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-545
Reusable code with less complexity.

BOAC-545, boxplotPageViewsDirective replaces scope.postDigest strategy

---

boac/merged/sis_enrollments.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-585

BOAC-585, student is enrolled if enrollmentStatus == 'E'

---

boac/lib/analytics.py
tests/test_lib/test_analytics.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-551

BOAC-551 Use roundedUpPercentile consistently for display

---

boac/api/course_controller.py
boac/static/app/course/course.css
boac/static/app/course/course.html
boac/static/app/course/courseController.js
boac/static/app/course/courseFactory.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-536
Move extraneous stuff out of `courseController.js`. Mock data is still present but the structure is taking shape. Includes small enhancements on front-end.

BOAC-536, begin to move average-student logic to server

---

boac/static/app/landing/sortableAlertsTable.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-590

BOAC-590 Restore alert counts in My List

---

boac/static/app/cohort/cohort.html
boac/static/app/course/course.html
boac/static/app/student/student.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-592
There's a gotcha in gulp-rev-replace such that it only expects one occurrence of any given resource per file.

BOAC-592 Update student-avatar-large for asset versioning

---

boac/externals/data_loch.py

Follow-up to #480, oops.
https://jira.ets.berkeley.edu/jira/browse/BOAC-557

BOAC-557 Fix data loch course scores query

---

boac/merged/sis_profile.py
boac/static/app/student/student.html
fixtures/sis_student_api_11667051.json
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-578

BOAC-578 Display expected graduation term

---

boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-553

BOAC-553 Ensure inactive/intensive filters don't get lost on redirect

---

boac/static/app/shared/utilService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-596
After a few weeks/months we can decide: resurrect a more sensible strategy or delete the logic.

BOAC-596, breadcrumbs are complicated and horrible

---

boac/api/util.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-597
Examples:

BOAC-597, Who is Mo? Mo is Monday

---

boac/static/app/cohort/cohortController.js
boac/static/app/course/courseController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-600

BOAC-600 Firmly insist that Angular update location from within d3 visualizations

---

boac/static/app/student/studentFactory.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-607
Design ticket https://jira.ets.berkeley.edu/jira/browse/BOAC-525

BOAC-607 What is a Sophomore?

---

boac/static/app/student/studentFactory.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-607

BOAC-607 Fix unit counts in level definitions

---

boac/static/app/shared/profile.css
boac/static/app/student/student.css
boac/static/app/student/student.html
boac/static/app/student/studentController.js
boac/static/app/user/authFactory.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-598
Disabling `uib-accordion` click-row-anywhere was non-trivial.

BOAC-598, student profile page > enhance UI with screenreader in mind

---

boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-603

BOAC-603, no 'Expected graduation' term if Grad student

---

boac/static/app/course/courseController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-611

BOAC-611, includeAverage=false for now

---

boac/static/app/cohort/cohort.html
boac/static/app/shared/matrix.html
boac/static/app/student/student.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-601

BOAC-601, student name, in list view, cannot collide with adjacent column

---

boac/static/app/splash/splash.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-620
Use `?w=1` to review

BOAC-620, autofocus on dev-auth UID and ng-submit on form

---

boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-621

[QA] BOAC-621, student name in page title matches h1

---

boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-621
QA PR is #501

BOAC-621, student name in page title matches h1

---

boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortFilterDropdown.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-622
QA PR is #504

BOAC-622, cohort 'level' dropdown must pre-pop with 'value' compare

---

boac/static/app/cohort/manageCohorts.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-562

BOAC-562, link to cohort from /cohorts/manage page

---

config/default.py

NOJIRA, default.py gets DEMO_MODE = False and a bit o' documentation

---

boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html
boac/static/app/course/course.css
boac/static/app/course/course.html
boac/static/app/student/student.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-612
UX snippet:
Master PR after today's demo.

[QA] BOAC-612, organize class page markup for easier management, alignment

---

boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html
boac/static/app/course/course.css
boac/static/app/course/course.html
boac/static/app/student/student.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-612
QA PR is #509

BOAC-612, organize class page markup for easier management, alignment

---

boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-623

BOAC-623, cohort search filter preset > param is either string or array

---

.ebextensions/00_ami.config

https://jira.ets.berkeley.edu/jira/browse/BOAC-605

BOAC-605 Add custom security groups to eb config

---

.ebextensions/03_download_local_configuration.config
scripts/deploy_boac_config.sh

https://jira.ets.berkeley.edu/jira/browse/BOAC-586

BOAC-586 Use centralized config file source

---

boac/models/json_cache.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-644
Hat tip to http://skien.cc/blog/2014/01/15/sqlalchemy-and-race-conditions-implementing/

[QA] BOAC-644 Better handling for race conditions in cache

---

boac/models/json_cache.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-644
QA PR was #515.

BOAC-644 Better handling for race conditions in cache

---

scripts/db/migrate/20180327-BOAC-613/02_copy_advisor_lists_to_student_groups_table.sh
scripts/db/migrate/20180327-BOAC-613/copy_advisor_lists_to_student_groups_table.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-654
Secrets stolen from `run.py`.

BOAC-654, script must source /opt/python/current/env prior to py execution

---

boac/static/app/group/studentGroupToggle.html
boac/static/app/home/home.css
boac/static/app/home/home.html
boac/static/app/home/sortableAlertsTable.html
boac/static/app/main.css
boac/static/app/nav/footer.html
boac/static/app/nav/nav.css
boac/static/app/nav/sidebar.html
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-669
The UX goal is BOAC-401

BOAC-669, home gets proper flex treatment w.r.t sortableAlertsTable

---

boac/api/cohort_controller.py
boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohortFactory.js
boac/static/app/cohort/cohortService.js
boac/static/app/cohort/manageCohorts.html
boac/static/app/group/studentGroupFactory.js
boac/static/app/group/studentGroupService.js
boac/static/app/home/home.css
boac/static/app/home/home.html
boac/static/app/home/homeController.js
boac/static/app/main.css
boac/static/app/nav/nav.css
boac/static/app/nav/sidebar.html
boac/static/app/routes.js
boac/static/app/shared/focusOnDirective.js
boac/static/app/shared/utilService.js
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-667
For example:

BOAC-667, finishing touches on sidebar; listeners for addOrRemoveMyGroup events, etc.

---

boac/api/user_controller.py
boac/models/student_group.py
boac/static/app/cohort/createCohortModal.html
boac/static/app/group/createStudentGroupController.js
boac/static/app/group/createStudentGroupModal.html
boac/static/app/group/studentGroupFactory.js
boac/static/app/group/studentGroupService.js
boac/static/app/home/home.css
boac/static/app/home/home.html
boac/static/app/home/homeController.js
boac/static/app/nav/nav.css
boac/static/app/nav/sidebar.html
boac/static/app/nav/sidebarNavController.js
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-667

BOAC-667, create group with modal dialog; sidebar gracefully updates when add/remove groups

---

boac/api/user_controller.py
boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html
boac/static/app/group/studentGroupFactory.js
boac/static/app/nav/sidebarNavController.js
boac/static/app/shared/matrix.html
boac/static/app/shared/profile.css
boac/static/app/student/student.css
boac/static/app/student/student.html
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-684
The list o' checkboxes design needs discussion when Flint is back. For now, we match the spec (see BOAC-673).
Example:

BOAC-684, revamp student profile page (v2 design)

---

boac/static/app/cohort/cohortController.js
boac/static/app/course/course.html
boac/static/app/group/createStudentGroupController.js
boac/static/app/group/groupController.js
boac/static/app/group/studentGroupFactory.js
boac/static/app/group/studentGroupToggle.html
boac/static/app/group/studentGroupToggleDirective.js
boac/static/app/nav/sidebarNavController.js
boac/static/app/student/student.html
boac/static/app/student/studentController.js
boac/static/app/visual/visualizationService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-693
It is no longer sufficient to pass around student SIDs. The listeners need whole student objects.

BOAC-693, add/remove students and groups should refresh sidebar

---

boac/api/user_controller.py
boac/models/development_db.py
tests/test_api/test_athletics_controller.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-699
To verify the fix, I took Oliver off the Football team. No hard feelings.

BOAC-699, sid is None if no such student

---

boac/static/app/cohort/createCohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-701
Following patterns from the rest of the refactor in #533.

BOAC-701 Fix JS error on cohort creation

---

boac/api/cohort_controller.py
boac/api/student_groups_controller.py
boac/merged/member_details.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_student_groups_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-696

BOAC-696 Add member details, remove analytics from homepage feeds

---

boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/course/course.css
boac/static/app/course/course.html
boac/static/app/group/listViewStudentGroupsSelector.html
boac/static/app/group/listViewStudentGroupsSelectorDirective.js
boac/static/app/main.css
boac/static/app/student/student.css
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-707
Shared code makes sense here.

BOAC-707, bulk add students to group with directive (course and cohort view)

---

boac/static/app/home/home.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-714

BOAC-714, 'My Students' header on homepage links to full on list view

---

boac/static/app/group/manageGroups.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-700

BOAC-700 No delete or rename for My Students

---

boac/static/app/home/sortableAlertsTable.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-697

BOAC-697 Majors look like everything else

---

boac/api/student_groups_controller.py
tests/test_api/test_student_groups_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-713

BOAC-713, reject unauthorized users w.r.t /api/group/:group_id

---

boac/static/app/nav/header.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-722

BOAC-722, home href in header reloads page, even on /home

---

boac/static/app/cohort/all.html
boac/static/app/cohort/teams.html
boac/static/app/main.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-698
https://jira.ets.berkeley.edu/jira/browse/BOAC-690
Most of the diff in `main.css` is alphabetization.

BOAC-698, 'body' 100% height to avoid truncated sidebar blue

---

boac/static/app/home/home.css
boac/static/app/home/home.html
boac/static/app/main.css
boac/static/app/nav/sidebar.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-694
https://jira.ets.berkeley.edu/jira/browse/BOAC-703
https://jira.ets.berkeley.edu/jira/browse/BOAC-716

BOAC-694, tooltip on sidebar alerts; font-size corrections on home

---

boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-721

BOAC-721 Link those groups

---

boac/static/app/student/findStudent.html
boac/static/app/student/student.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-706

BOAC-706 Search for students with awesome magnifying glass

---

boac/static/app/cohort/cohort.html
boac/static/app/group/group.html
boac/static/app/group/groupController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-735
Since we don't have filters or pagination as on the cohort page, we can do everything more straightforwardly on the front end.

BOAC-735 Sorting for group page; restore sorted first names

---

boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html
boac/static/app/course/course.css
boac/static/app/course/course.html
boac/static/app/group/listViewStudentGroupsSelector.html
boac/static/app/group/listViewStudentGroupsSelectorDirective.js
boac/static/app/group/manageGroupsController.js
boac/static/app/group/studentGroupService.js
boac/static/app/main.css
boac/static/app/nav/sidebar.html
boac/static/app/nav/sidebarNavController.js
boac/static/app/student/student.css
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-734
https://jira.ets.berkeley.edu/jira/browse/BOAC-732
https://jira.ets.berkeley.edu/jira/browse/BOAC-737
Includes fix to: 'My Students' checkbox not preset on student profile page.

BOAC-734, no duplicates in sidebar; alignment fixes

---

boac/api/util.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-741
From debugger, here is what we ignore:

BOAC-746, section meeting info is ignored if there is no 'there' there

---

boac/static/app/group/manageGroups.html
boac/static/app/student/student.css
boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-739

BOAC-739 Wrapping fixes for long group names

---

boac/api/student_groups_controller.py
boac/api/user_controller.py
boac/models/development_db.py
boac/models/student_group.py
boac/static/app/cohort/createCohortController.js
boac/static/app/cohort/createCohortModal.html
boac/static/app/cohort/manageCohortsController.js
boac/static/app/course/course.css
boac/static/app/group/createGroupController.js
boac/static/app/group/createGroupModal.html
boac/static/app/group/listViewStudentGroupsSelector.html
boac/static/app/group/manageGroups.html
boac/static/app/group/manageGroupsController.js
boac/static/app/group/studentGroupService.js
boac/static/app/home/home.html
boac/static/app/home/homeController.js
boac/static/app/nav/sidebar.html
boac/static/app/shared/validationService.js
boac/static/app/student/student.css
boac/static/app/student/student.html
boac/static/app/user/authService.js
boac/templates/index.html
tests/test_api/test_student_groups_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-740
https://jira.ets.berkeley.edu/jira/browse/BOAC-748
https://jira.ets.berkeley.edu/jira/browse/BOAC-743
https://jira.ets.berkeley.edu/jira/browse/BOAC-741
1. Consistent behavior when saving/updating groups and cohorts. Read diff with `?w=1`
1. Simplify 'Manage Groups' and My-Students always on top
If you prefer, review commits individually.

BOAC-740, create/manage dialog for groups and cohorts get a little cleanup

---

boac/static/app/student/student.css
boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-752

BOAC-752 Student page: fix padding on long group names

---

boac/static/app/routes.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-710
For now, a simple fix affects all state changes, including the back button. The harder problem of correctly handling scroll position on back navigation will have to wait for a follow-up.

BOAC-710 Scroll to top on state change

---

boac/static/app/main.css
boac/static/app/nav/nav.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-757

BOAC-757 Give the sidebar more leg room

---

boac/static/app/group/group.css
boac/static/app/group/listViewStudentGroupsSelector.html
boac/static/app/group/listViewStudentGroupsSelectorDirective.js
boac/static/app/main.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-733
https://jira.ets.berkeley.edu/jira/browse/BOAC-754
**Extra:** No need to invoke `studentGroupFactory.getMyGroups` when `me` has what we need.

BOAC-733, confirm 'added to group' on cohort and course pages

---

boac/static/app/group/groupController.js
boac/static/app/group/listViewStudentGroupsSelectorDirective.js
boac/static/app/group/studentGroupFactory.js
boac/static/app/group/studentGroupService.js
boac/static/app/nav/sidebarNavController.js
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-754
Jira has details. The fix is improved event mgmt.

BOAC-754, play nice when add-group and add-students collide

---

boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-720

BOAC-720, no splash before current user is in rootScope

---

boac/static/app/student/student.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-758

BOAC-758 Fixed width for class units and grades

---

boac/api/util.py
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-756

BOAC-756 Include athletic memberships on class page

---

boac/__init__.py

In the unlikely case we re-cut the 'qa' branch, we'll revert this commit.

NOJIRA, master bumped to v2.1

---

boac/static/app/routes.js
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-720
On the coattails of @paulkerschen's `scrollTop` work, from yesterday.

BOAC-720, angularStateName is accurate if set after stateChangeSuccess

---

boac/static/app/nav/sidebar.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-764

BOAC-764 Clear inactive status from sidebar links

---

boac/static/app/nav/sidebar.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-764
QA version of #576.

[QA] BOAC-764 Clear inactive status from sidebar links

---

boac/static/app/cohort/createCohortModal.html
boac/static/app/cohort/deleteCohortModal.html
boac/static/app/cohort/manageCohorts.html
boac/static/app/group/createGroupModal.html
boac/static/app/group/deleteGroupModal.html
boac/static/app/group/manageGroups.html
boac/static/app/main.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-753
Use `?w=1`.  A keyboard friendly experience is the goal.

BOAC-753, reduce keystrokes when create/delete/edit groups and cohorts

---

boac/static/app/cohort/all.html
boac/static/app/cohort/cohort.html
boac/static/app/cohort/manageCohorts.html
boac/static/app/course/course.html
boac/static/app/group/group.html
boac/static/app/group/manageGroups.html
boac/static/app/nav/sidebar.html
boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-755

BOAC-755, no h2s in sidebar; facelift for allCohorts; consistent header style

---

boac/static/app/main.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-767

[QA] BOAC-767, Firefox wants reassurance on height: 100%

---

boac/static/app/main.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-767
QA PR is #582

BOAC-767, Firefox wants reassurance on height: 100%

---

boac/static/app/nav/sidebar.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-755

BOAC-755, sidebar header indent depends on presence of href

---

.eslintrc.yml
.gitignore
boac/models/development_db.py
boac/static/app/group/manageGroupsController.js
boac/static/app/routes.js
bower.json
package.json
requirements.txt

https://jira.ets.berkeley.edu/jira/browse/BOAC-790
The one significant change is angular-ui-router (now v1.0.15) which required use of new [Transition Lifecycle Hooks](https://ui-router.github.io/guide/ng1/migrate-to-1_0).

BOAC-790, 3rd party deps: minor version upgrades, necessary code fixes

---

boac/auth/cas_auth.py
boac/auth/dev_auth.py
boac/static/app/nav/headerController.js
boac/static/app/splash/splash.html
boac/static/app/splash/splashController.js
boac/static/app/user/authFactory.js
tests/test_auth/test_cas_auth.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-791
If/when BOAC has a broader audience, unauthorized users must know they are unauthorized.

BOAC-791, show error message on splash page if user is unauthorized

---

boac/api/cache_utils.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-802

BOAC-802 Teach cacheload JobProgress about the new tasks

---

boac/api/user_controller.py
boac/merged/import_asc_athletes.py
boac/models/athletics.py
boac/models/cohort_filter.py
boac/models/development_db.py
boac/models/student.py
boac/static/app/search/searchController.js
boac/static/app/search/searchResults.html
boac/static/app/student/studentFactory.js
fixtures/asc_athletes.json
tests/test_api/test_alerts_controller.py
tests/test_api/test_athletics_controller.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_course_controller.py
tests/test_api/test_user_controller.py
tests/test_merged/test_import_asc_athletes.py
tox.ini

https://jira.ets.berkeley.edu/jira/browse/BOAC-809
* changes in test data in order to test various search scenarios
* `is_active_asc` defaults to `None` which impacts ASC; Jira created with reqts question: https://jira.ets.berkeley.edu/jira/browse/BOAC-817
* a lot of work remains on UX of results page

BOAC-809, search-by matches on start of any name or sid

---

boac/static/app/search/searchController.js
boac/static/app/search/searchResults.html
boac/static/app/shared/validationService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-809
50 results per page.

BOAC-809, pagination for search results

---

boac/static/app/nav/sidebar.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-808

BOAC-808 Restore sidebar manage cohorts links

---

boac/static/app/search/searchController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-809
Sample URL: `/search?q=d&o=gpa&p=2`

BOAC-809, search with orderBy and bookmarkable pages

---

boac/static/app/cohort/cohortController.js
boac/static/app/group/groupController.js
boac/static/app/routes.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-821
Wow, that first round didn't come out very well. Let's try to do this right.

BOAC-821 Follow-up fixes for page titles

---

boac/static/app/group/manageGroups.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-818

BOAC-818 Fix markup on Manage Curated Cohorts

---

boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-792

BOAC-792 Cohort filter criteria aren't searched, they are applied

---

boac/static/app/main.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-775

BOAC-775 Untruncate the sidebar

---

boac/api/user_controller.py
boac/models/student.py
boac/static/app/cohort/cohort.html
boac/static/app/course/course.html
boac/static/app/group/groupsSelectorDirective.js
boac/static/app/nav/sidebarNavController.js
boac/static/app/search/searchResults.html
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-828

BOAC-828, search scenarios: support middle name, commas and lastName first

---

boac/api/util.py
boac/merged/sis_enrollments.py
fixtures/canvas_course_sections_7654330.json
tests/test_api/test_user_controller.py
tests/test_merged/test_sis_enrollments.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-627

BOAC-627 Term enrollments feed: add primary status, site-to-section mappings

---

boac/static/app/cohort/all.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/manageCohorts.html
boac/static/app/course/course.css
boac/static/app/course/course.html
boac/static/app/group/manageGroups.html
boac/static/app/home/home.html
boac/static/app/nav/sidebar.html
boac/static/app/search/searchController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-798
https://jira.ets.berkeley.edu/jira/browse/BOAC-776
https://jira.ets.berkeley.edu/jira/browse/BOAC-833
Includes a tweak for consistent markup on 'manage' pages.

BOAC-776, sidebar links always reload; paginate > scroll to top

---

boac/api/admin_controller.py
boac/api/cache_utils.py
boac/models/job_progress.py
boac/models/json_cache.py
boac/models/normalized_cache_enrollment.py
run.py
tests/test_models/test_job_progress.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-267 and its li'l buddies
https://jira.ets.berkeley.edu/jira/browse/BOAC-813
https://jira.ets.berkeley.edu/jira/browse/BOAC-814
https://jira.ets.berkeley.edu/jira/browse/BOAC-815
https://jira.ets.berkeley.edu/jira/browse/BOAC-816

BOAC-267 Keep current cache available while refreshing

---

boac/static/app/cohort/createCohortController.js
boac/static/app/cohort/deleteCohortController.js
boac/static/app/course/course.css
boac/static/app/group/createGroupController.js
boac/static/app/group/deleteGroupController.js
boac/static/app/group/group.css
boac/static/app/group/groupsSelector.html
boac/static/app/routes.js
boac/static/app/splash/splashController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-822
https://jira.ets.berkeley.edu/jira/browse/BOAC-824
https://jira.ets.berkeley.edu/jira/browse/BOAC-834
A generic errorHandler is used in place of `transition.onError`.
Modal handling per https://github.com/angular-ui/bootstrap/issues/6412

BOAC-822/BOAC-834, quiet benign console errors; no curated cohort msg

---

boac/auth/cas_auth.py
boac/auth/dev_auth.py
boac/lib/berkeley.py
boac/models/development_db.py
boac/models/university_dept.py
tests/test_auth/test_dev_auth.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-835
If user ain't authorized:

BOAC-835, users in authorized_users table are not always authorized

---

boac/static/app/cohort/createCohortController.js
boac/static/app/cohort/deleteCohortController.js
boac/static/app/group/createGroupController.js
boac/static/app/group/deleteGroupController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-822
I was hoping `finally(angular.noop);` would be good enough but no.

BOAC-822, no need for $scope.$destory when user hits esc key

---

boac/api/user_controller.py
boac/api/util.py
boac/lib/berkeley.py
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortFactory.js
boac/static/app/main.css
boac/static/app/nav/sidebarNavController.js
boac/static/app/shared/utilService.js
boac/static/app/splash/outage.html
boac/static/app/splash/splash.css
boac/static/app/student/studentFactory.js
boac/static/app/student/studentSearchService.js
boac/static/app/user/authService.js
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-817

BOAC-817, ASC rules on front-end benefit from a simpler '/api/profile' feed

---

boac/static/app/shared/validationService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-837

BOAC-837, cut red tape and regulation in cohort naming

---

boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/course/course.html
boac/static/app/course/courseController.js
boac/static/app/group/group.html
boac/static/app/group/groupController.js
boac/static/app/nav/nav.css
boac/static/app/nav/sidebar.html
boac/static/app/search/searchResults.html
boac/static/app/shared/matrix.html
boac/static/app/shared/utilService.js
boac/static/app/student/student.html
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-820
https://jira.ets.berkeley.edu/jira/browse/BOAC-796
https://jira.ets.berkeley.edu/jira/browse/BOAC-839
Power users have at least 50 tabs open at once.

BOAC-839/BOAC-796, allow open in new tab; sidebar styling

---

boac/api/student_groups_controller.py
boac/static/app/cohort/createCohortController.js
boac/static/app/cohort/deleteCohortController.js
boac/static/app/cohort/manageCohorts.html
boac/static/app/group/createGroupController.js
boac/static/app/group/deleteGroupController.js
boac/static/app/group/group.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-819
https://jira.ets.berkeley.edu/jira/browse/BOAC-832
https://jira.ets.berkeley.edu/jira/browse/BOAC-838
No more `no-ops` on parade.

BOAC-832/BOAC-838, tabbing stays in modal; avoid multiple modals

---

boac/static/app/nav/sidebar.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-820
PR #614 was supposed to include...

BOAC-820, missed a style on sidebar: sidebar-row-link-label

---

gulpfile.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-799
I've tested this locally with Apache. Not a guaranteed fix but the odds are decent.

BOAC-799, gulp rev third party js

---

boac/api/cohort_controller.py
boac/api/search_controller.py
boac/api/user_controller.py
boac/models/cohort_filter.py
boac/models/development_db.py
boac/models/student.py
boac/routes.py
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortFactory.js
boac/static/app/search/searchController.js
boac/static/app/search/searchResults.html
boac/static/app/student/studentFactory.js
tests/test_api/test_cohort_controller.py
tests/test_api/test_search_controller.py
tests/test_api/test_user_controller.py
tests/test_models/test_cohort_filter.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-840
https://jira.ets.berkeley.edu/jira/browse/BOAC-841
The other "fix" here is to remove pagination in search results. If the first 50 results ain't got what you need then sorry, Charlie.

BOAC-841, if user is ASC then search excludes 'inactive' students

---

boac/static/app/student/studentSearchService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-843

BOAC-843, non-ASC users do not get 'Team' order-by and similar

---

boac/static/app/cohort/all.html
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortFilterDropdown.html
boac/static/app/cohort/createCohortModal.html
boac/static/app/cohort/manageCohorts.html
boac/static/app/cohort/teams.html
boac/static/app/course/course.html
boac/static/app/group/createGroupModal.html
boac/static/app/group/group.html
boac/static/app/group/groupsSelector.html
boac/static/app/group/manageGroups.html
boac/static/app/home/home.html
boac/static/app/home/sortableAlertsTable.html
boac/static/app/nav/sidebar.html
boac/static/app/search/searchResults.html
boac/static/app/shared/tabs.html
boac/static/app/splash/outage.html
boac/static/app/splash/splashController.js
boac/static/app/student/student.html
boac/templates/index.html
bower.json

https://jira.ets.berkeley.edu/jira/browse/BOAC-844
fa fa fas

BOAC-844, fontawesome 5

---

boac/api/cache_utils.py
boac/lib/berkeley.py
boac/models/job_progress.py
tests/test_lib/test_berkeley.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-836

BOAC-836 Add API support for cachejob/refresh?term=all

---

boac/static/app/home/home.css
boac/static/app/home/home.html
boac/static/app/home/sortableAlertsTable.html
boac/static/app/home/sortableAlertsTableDirective.js
boac/static/app/main.css
boac/static/app/search/searchController.js
boac/static/app/search/searchResults.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-785

BOAC-785, student search gets sortable-alerts UX w/ curated-cohort selector

---

scripts/db/copy_external_cache_from_file.sql
scripts/db/copy_external_cache_to_file.sql

https://jira.ets.berkeley.edu/jira/browse/BOAC-845
Not ideal, but it should give us more to go on after the next release.

BOAC-845 SQL scripts to copy external cache data in release

---

boac/static/app/nav/header.html
boac/static/app/nav/nav.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-849
Need help finding help? Hint: click on stuff in the header.

BOAC-849, find log-out and help in header > name > menu

---

boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/course/course.html
boac/static/app/course/courseController.js
boac/static/app/group/group.html
boac/static/app/group/groupController.js
boac/static/app/home/sortableAlertsTable.html
boac/static/app/home/sortableAlertsTableDirective.js
boac/static/app/nav/sidebarNavController.js
boac/static/app/search/searchController.js
boac/static/app/shared/validationService.js
boac/static/app/student/student.html
boac/static/app/student/studentController.js
boac/static/app/student/studentSearchService.js
boac/static/app/user/authService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-848
https://jira.ets.berkeley.edu/jira/browse/BOAC-837

BOAC-837/BOAC-848, if advisor is ASC then show 'inactives'

---

boac/static/app/nav/header.html
boac/static/app/nav/sidebar.html
boac/static/app/nav/sidebarNavController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-849
'Log out' was too well hidden. Throw 'em a caret.

BOAC-849, add caret to name/logout button

---

boac/api/cohort_controller.py
boac/api/search_controller.py
boac/lib/berkeley.py
boac/static/app/nav/sidebar.html
tests/test_api/test_cohort_controller.py
tests/test_api/test_search_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-856
https://jira.ets.berkeley.edu/jira/browse/BOAC-854
We protect what might be sensitive data.

BOAC-856, Everyone's Cohorts is, for now, an ASC-only feature

---

boac/api/search_controller.py
boac/api/util.py
tests/test_api/test_search_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-858

BOAC-858, correct alert counts in search results

---

boac/api/search_controller.py
boac/api/util.py
tests/test_api/test_search_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-858
master PR #631

[QA] BOAC-858, correct alert counts in search results

---

boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/course/course.html
boac/static/app/group/groupsSelector.html
boac/static/app/group/groupsSelectorDirective.js
boac/static/app/home/sortableAlertsTable.html
boac/static/app/home/sortableAlertsTableDirective.js
boac/static/app/search/searchResults.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-861
master PR is #635

[QA] BOAC-861, curated-cohort-selector must behave across browsers, result-sets

---

boac/externals/data_loch.py
config/default.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-870
Most of this work was handled by @raydavis on a working branch - the only other change required was a column name update.

BOAC-870 Make BOAC and Nessie talk to each other

---

boac/models/json_cache.py
boac/models/normalized_cache_enrollment.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-872

BOAC-872 Use shared conflict-check code for JSON cache inserts

---

boac/api/course_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-871
QA version of #639.

[QA] BOAC-871 Falsey check for student term in course controller

---

boac/models/json_cache.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-881
In general, we expect the runtime table to find all items while the staging table fills itself. At some point, we may even want to boost the logging level to WARN for runtime cache.
The PR also standardizes string formatting.

BOAC-881 Clarify which json_cache table is missing an entry

---

boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-793

BOAC-793, students do not always have preferredName

---

boac/static/app/cohort/cohort.html
boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-793
Total student count per canvas-course-site is Jira/PR coming soon.

BOAC-793, student view gets daysSinceLastActivity

---

boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-896
Blur phone, too.

BOAC-896, demo-mode-blur for lastActivity summary on student profile

---

boac/static/app/cohort/allCohortsController.js
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/manageCohortsController.js
boac/static/app/cohort/teamsController.js
boac/static/app/course/courseController.js
boac/static/app/group/group.css
boac/static/app/group/group.html
boac/static/app/group/groupController.js
boac/static/app/group/groupsSelectorDirective.js
boac/static/app/group/manageGroupsController.js
boac/static/app/main.css
boac/static/app/nav/nav.css
boac/static/app/nav/sidebar.html
boac/static/app/nav/sidebarNavController.js
boac/static/app/search/searchController.js
boac/static/app/search/searchStudentsForm.html
boac/static/app/search/searchStudentsFormDirective.js
boac/static/app/shared/page.js
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-866
* The Jira has UX of reusable search box.
* The use of rootScope in `page.loading(...)` gives illusion of a more responsive tool. Such responsiveness is especially important when kicking off search.

BOAC-866, reusable search directive; faster transition to isLoading

---

boac/static/app/student/student.html
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-866

BOAC-866, page.loading(..) in one more spot

---

boac/__init__.py
boac/api/course_controller.py
boac/merged/sis_sections.py
boac/models/normalized_cache_enrollment.py
boac/static/app/course/courseFactory.js
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-910
My local test also shows the following as fixed:
Missing instructors - https://jira.ets.berkeley.edu/jira/browse/BOAC-901
Missing class pages - https://jira.ets.berkeley.edu/jira/browse/BOAC-913
And v2.1 seems like a long time ago....

BOAC-910 Fix Class page links for Loch

---

boac/__init__.py
boac/api/course_controller.py
boac/merged/sis_sections.py
boac/models/normalized_cache_enrollment.py
boac/static/app/course/courseFactory.js
boac/static/app/student/studentController.js

QA version of https://github.com/ets-berkeley-edu/boac/pull/660

[QA] BOAC-910 Fix Class page links for Loch

---

boac/static/app/shared/utilService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-915

BOAC-915, NaN comparison is not enough; use isNaN()

---

boac/static/app/shared/utilService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-915
master PR: https://github.com/ets-berkeley-edu/boac/pull/662

[QA] BOAC-915, NaN comparison is not enough; use isNaN()

---

boac/__init__.py

NOJIRA, bump BOAC master version to 2.3

---

boac/lib/analytics.py
boac/static/app/course/course.html
boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-900
https://jira.ets.berkeley.edu/jira/browse/BOAC-902

BOAC-900 BOAC-902 Do not conflate displayPercentile, boxPlottable, & "No Data"

---

boac/merged/sis_sections.py
tests/test_merged/test_sis_sections.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-923
Also handle blank instructor columns, since we get one of those in the same SIS Sections query.

BOAC-923 Online courses typically lack start/end times

---

boac/static/app/group/groupController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-934

BOAC-934 Teach curated cohorts about demo mode

---

boac/api/course_controller.py
boac/merged/sis_sections.py
boac/static/app/cohort/cohort.html
boac/static/app/course/course.html
boac/static/app/group/group.html
boac/static/app/student/student.css
boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-918
https://jira.ets.berkeley.edu/jira/browse/BOAC-921
https://jira.ets.berkeley.edu/jira/browse/BOAC-922
https://jira.ets.berkeley.edu/jira/browse/BOAC-937
A cluster of minor fixes.

BOAC-922, class page fixes: course site info, meeting times, student enroll status

---

boac/api/config_controller.py
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/course/course.html
boac/static/app/group/group.html
boac/static/app/group/groupController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-920
https://jira.ets.berkeley.edu/jira/browse/BOAC-914

BOAC-914, cohort/group pages let know who is not enrolled in current term

---

boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-941

BOAC-941 Remove redundant course site score summaries

---

boac/api/student_groups_controller.py
boac/models/student_group.py
tests/test_api/test_student_groups_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-930
Protections on `/api/group/<group_id>/add_student/<sid>` and `/api/group/students/add`

BOAC-930, catch IntegrityError, complain and carry on

---

boac/api/config_controller.py
boac/api/user_controller.py
boac/static/app/student/student.css
boac/static/app/student/student.html
boac/static/app/student/studentController.js
fixtures/loch_sis_enrollments_98765_2172.csv
fixtures/loch_student_canvas_courses_98765.csv
fixtures/loch_user_for_uid_98765.csv
fixtures/sis_student_api_2345678901.json
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-914
One UX issue to get off my plate.

BOAC-914, notify user when student has no enrollments in current term

---

boac/static/app/cohort/cohortController.js
boac/static/app/course/course.html
boac/static/app/course/courseController.js
boac/static/app/search/searchController.js
boac/static/app/shared/utilService.js
boac/static/app/student/student.html
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-945
Something to do during the big Nessie-API pile-on.

BOAC-945 Remove dead breadcrumbs code

---

requirements.txt

https://jira.ets.berkeley.edu/jira/browse/NS-110
Aligns BOAC with Nessie's deps:
https://github.com/ets-berkeley-edu/nessie/pull/72

NS-110, upgrade SQLAlchemy for BOAC

---

boac/static/app/main.css
boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-928

BOAC-928 Align student site metrics

---

boac/api/course_controller.py
boac/static/app/course/course.html
boac/static/app/course/courseController.js
boac/static/app/course/courseFactory.js
boac/static/app/shared/matrix.html
boac/static/app/visual/visualizationService.js

https://jira.ets.berkeley.edu/jira/browse/NS-105
https://jira.ets.berkeley.edu/jira/browse/BOAC-536
A little more housecleaning to lighten the burden of the move.

NS-105 Remove unused averageStudent logic left by BOAC-536

---

boac/api/cohort_controller.py
boac/api/search_controller.py
boac/api/student_groups_controller.py
boac/api/user_controller.py
boac/api/util.py
boac/merged/student_details.py
boac/models/alert.py
tests/test_api/test_search_controller.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/NS-105
Aside from the improved tests, this isn't so much a clean-up as a getting-out-of-the-way. The top-level code is de-DRYed a bit, but I think it'll make it simpler to shuffle the middleware around.

NS-105 Move some payload tweaks up to controller packages

---

.ebextensions/01_create_apache_conf.config

https://jira.ets.berkeley.edu/jira/browse/BOAC-942
BOAC version of https://github.com/ets-berkeley-edu/nessie/pull/88.

BOAC-942 Remove unneeded python-path; overwrite duplicate WSGI config

---

boac/api/cohort_controller.py
boac/api/user_controller.py
boac/lib/analytics.py
boac/lib/util.py
boac/merged/student_details.py
boac/models/alert.py
boac/models/authorized_user.py
boac/models/cohort_filter.py
boac/models/json_cache.py
boac/models/student_group.py
boac/models/university_dept.py
tox.ini

https://jira.ets.berkeley.edu/jira/browse/NS-124
A good rule to follow, methinks. Use `noqa: A003` to ignore.

NS-124, flake8-builtins to avoid builtin/variable name collision

---

boac/static/app/cohort/cohort.html
boac/static/app/course/course.html
boac/static/app/group/group.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-957

BOAC-957 Not just any ACTIVITY but BCOURSES ACTIVITY

---

boac/externals/asc_athletes_api.py
boac/lib/http.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-982

BOAC-982 Work around ASC API URL transition

---

boac/externals/asc_athletes_api.py
boac/lib/http.py

QA version of https://github.com/ets-berkeley-edu/boac/pull/691

[QA] BOAC-982 Work around ASC API URL transition

---

boac/merged/calnet.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-984
TODO : This must be moved into Nessie in some form (once Nessie's new form is better settled).

BOAC-984 Describe students which were not found in LDAP

---

boac/api/athletics_controller.py
boac/api/cache_utils.py
boac/api/cohort_controller.py
boac/api/course_controller.py
boac/api/search_controller.py
boac/api/student_groups_controller.py
boac/api/user_controller.py
boac/api/util.py
boac/lib/berkeley.py
boac/merged/sis_enrollments.py
boac/merged/sis_profile.py
boac/merged/student_details.py
boac/static/app/cohort/cohort.html
boac/static/app/course/course.html
boac/static/app/group/group.html
boac/static/app/nav/sidebarNavController.js
boac/static/app/student/student.html
boac/static/app/student/studentController.js
tests/test_api/test_student_groups_controller.py
tests/test_api/test_user_controller.py
tests/test_merged/test_sis_profile.py

https://jira.ets.berkeley.edu/jira/browse/NS-105

NS-105 Unified student-and-terms data sources for controllers

---

scripts/db/migrate/20180626-BOAC-965/pre_deploy_01_add_COE_advisors.sql

https://jira.ets.berkeley.edu/jira/browse/BOAC-965

BOAC-965, SQL script creates authorized_user then maps UID to College of Engineering

---

boac/externals/sis_enrollments_api.py
boac/merged/sis_enrollments.py
tests/test_externals/test_sis_enrollments_api.py

https://jira.ets.berkeley.edu/jira/browse/NS-134

NS-134 Fix for Drops-and-Midterms caching and Midterm Alerts

---

boac/api/cohort_controller.py
boac/models/student.py
boac/static/app/cohort/allCohortsController.js
boac/static/app/cohort/manageCohorts.html
boac/static/app/user/authService.js
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-993

BOAC-993, COE advisor gets 404 for /cohorts/all

---

boac/api/cohort_controller.py
boac/api/search_controller.py
boac/api/util.py
boac/lib/berkeley.py
boac/models/development_db.py
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/course/course.html
boac/static/app/course/courseController.js
boac/static/app/group/group.html
boac/static/app/group/groupController.js
boac/static/app/home/sortableAlertsTable.html
boac/static/app/home/sortableAlertsTableDirective.js
boac/static/app/nav/sidebar.html
boac/static/app/nav/sidebarNavController.js
boac/static/app/search/searchController.js
boac/static/app/shared/validationService.js
boac/static/app/student/student.html
boac/static/app/student/studentController.js
boac/static/app/student/studentSearchService.js
boac/static/app/user/authService.js
tests/test_api/test_athletics_controller.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_course_controller.py
tests/test_api/test_search_controller.py
tests/test_api/test_student_groups_controller.py
tests/test_api/test_user_controller.py
tests/test_lib/test_berkeley.py
tests/test_models/test_authorized_user.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-993
* `can_view_cohort` util used to filter results in controller
* Variable renaming touched many files and tests. With COE in the mix, readability is important.

BOAC-993, advisor can view cohorts of dept colleagues; admin sees all

---

boac/api/cohort_controller.py
boac/static/app/cohort/cohortController.js
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-993

BOAC-993, unauthorized users get 404 from /api/cohort/{id}

---

.eslintrc.yml
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-987

BOAC-987, more support for coeAdvisorUid/isCannedCoeCohort on the front-end

---

boac/merged/student.py
boac/models/alert.py
boac/models/development_db.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_course_controller.py
tests/test_api/test_search_controller.py
tests/test_api/test_student_groups_controller.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-864

BOAC-864 Include athletics data in feeds for ASC and admins only

---

boac/models/student_group.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1011

BOAC-1011 Cascade delete for curated cohort memberships

---

boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-992

BOAC-992 Restore student name to "last visited the course site"

---

.ebextensions/00_ami.config

https://jira.ets.berkeley.edu/jira/browse/BOAC-979
Previously tested off of `boac-etsla-ops` branch.

[BOAC-979] Custom VPC security groups and SSH restriction

---

.ebextensions/00_ami.config

https://jira.ets.berkeley.edu/jira/browse/BOAC-979
master PR is #711

[QA] BOAC-979, Custom VPC security groups and SSH restriction

---

boac/api/course_controller.py
boac/externals/data_loch.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1018
You always miss one.

BOAC-1018 Constrain class page student list by advisor authorization

---

boac/lib/analytics.py
boac/merged/student.py
boac/static/app/course/course.html
boac/static/app/group/groupController.js
boac/static/app/home/sortableAlertsTable.html
fixtures/loch_sis_section_enrollments_2178_90200.csv
fixtures/loch_student_enrollment_term_11667051_2178.json
tests/test_api/test_athletics_controller.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_course_controller.py
tests/test_api/test_search_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1021
Did some cleanup along the way...

BOAC-1021 Add course-specific matrix to class page

---

config/default.py
config/test.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1028

BOAC-1028, obsolete configs removed

---

boac/static/app/nav/header.html
boac/static/app/nav/headerController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1036
A link that is quick.

BOAC-1036, admin users in non-prod get link to 'Admin' in top right menu

---

boac/api/cohort_controller.py
boac/api/search_controller.py
boac/api/util.py
boac/externals/data_loch.py
boac/merged/student.py
boac/models/cohort_filter.py
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortFactory.js
boac/static/app/cohort/createCohortController.js
boac/static/app/student/studentFactory.js
boac/static/app/student/studentSearchService.js
tests/test_api/test_cohort_controller.py
tests/test_models/test_cohort_filter.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-989
The `advisorLdapUid` checkbox now works for 'My students' but not yet working if I browse another COE advisor's canned cohort. Non-COE advisors do not have access to this feature.

BOAC-989, advisorLdapUid checkbox on filtered cohort

---

boac/api/user_controller.py
boac/static/app/admin/adminController.js
boac/static/app/admin/adminFactory.js
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/user/authFactory.js
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-989

BOAC-989, advisorLdapUid checkbox label will include name if uid is not me.uid

---

boac/static/app/shared/matrix.css
boac/static/app/visual/visualizationService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-968

BOAC-968 Add clarifying labels to Matrix view

---

boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-953

BOAC-953 Hide last site activity for past terms

---

boac/static/app/cohort/manageCohortsController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1025

BOAC-1025, manage cohorts > show details > include pill per advisorLdapUid

---

boac/static/app/cohort/cohort.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1026

BOAC-1026, ellipsis-style pagination for list view

---

boac/api/user_controller.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1017

BOAC-1017, /profile/my feed should not exclude my_groups.students info

---

boac/api/config_controller.py
boac/static/app/nav/header.html
boac/static/app/nav/headerController.js
boac/static/app/splash/splash.html
boac/static/app/splash/splashController.js
config/default.py
tests/test_api/test_config_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-978

BOAC-978, put new support email address in config (default.py)

---

boac/static/app/student/student.css
boac/static/app/student/student.html
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1010

BOAC-1010, unit totals for non-ASC; Degree Progress 'no data' when no data

---

boac/externals/data_loch.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1027
Ignore case differences and punctuation: "MCB" before "Mechanical" before "ME/NE" before "Me - You = Lonely".

BOAC-1027 "Naturalize" ordering of strings in SQL queries

---

boac/api/cohort_controller.py
boac/api/util.py
boac/static/app/cohort/all.html
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortFactory.js
boac/static/app/cohort/manageCohorts.html
boac/static/app/cohort/manageCohortsController.js
boac/static/app/home/home.html
boac/static/app/nav/sidebar.html
boac/static/app/nav/sidebarNavController.js
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1055
https://jira.ets.berkeley.edu/jira/browse/BOAC-1054

BOAC-1055, read-only cohort naming is whack-a-mole

---

boac/api/cohort_controller.py
boac/api/util.py
boac/static/app/cohort/all.html
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortFactory.js
boac/static/app/cohort/manageCohorts.html
boac/static/app/cohort/manageCohortsController.js
boac/static/app/home/home.html
boac/static/app/nav/sidebar.html
boac/static/app/nav/sidebarNavController.js
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1055
https://jira.ets.berkeley.edu/jira/browse/BOAC-1054
IMO, having this in the upcoming release is necessary; we want a stable naming convention.
Master PR is #736

[QA] BOAC-1055, read-only cohort naming is whack-a-mole

---

boac/api/athletics_controller.py
boac/api/cohort_controller.py
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/teamsController.js
tests/test_api/test_athletics_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1058

BOAC-1058, only ASC and admin can reach /teams

---

boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/createCohortController.js
boac/static/app/student/studentSearchService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1053
master PRs: #739 and #738

[QA] BOAC-1053, consistent pattern for managing checkboxes on /cohort search

---

boac/api/athletics_controller.py
boac/api/cohort_controller.py
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/teamsController.js
tests/test_api/test_athletics_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1058
master PR: #740

[QA] BOAC-1058, only ASC and admin can reach /teams

---

boac/static/app/main.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-1022
As far as I can tell this fixes the issue without breaking anything else, but you know, CSS.

BOAC-1022 Content area height fix for Firefox

---

boac/externals/data_loch.py
boac/merged/student.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1048

BOAC-1048 SID is ordering field of last resort

---

boac/externals/data_loch.py
boac/merged/student.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1048
QA version of #746.

[QA] BOAC-1048 SID is ordering field of last resort

---

boac/api/athletics_controller.py
boac/api/search_controller.py
boac/api/util.py
boac/merged/athletics.py
boac/models/development_db.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_search_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1061
None is sometimes None and sometimes False. Confusing requirements is True.

BOAC-1061, ASC users see inactives on class page and in custom cohort only

---

boac/api/athletics_controller.py
boac/api/search_controller.py
boac/api/util.py
boac/merged/athletics.py
boac/models/development_db.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_search_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1061
master PR is #748

[QA] BOAC-1061, ASC users see inactives on class page and in custom cohort only

---

boac/api/cohort_controller.py
boac/api/util.py
boac/lib/berkeley.py
boac/models/development_db.py
tests/test_api/test_api_util.py
tests/test_api/test_user_controller.py
tests/test_lib/test_berkeley.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1063
master PR is #750

[QA] BOAC-1063, logic of is_active_asc filter must rely on cohort owner, not current_user

---

boac/api/cohort_controller.py
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1064

BOAC-1064, allow admin to create cohort with non-None advisor_ldap_uid

---

boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-938

BOAC-938 Show midterm grades for current term only

---

.ebextensions/00_ami.config
boac/__init__.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1065
Another necessary config tweak. Gives me the change to bump version.

[release] BOAC-1065, SSHSourceRestriction change also needed for prod VPC move

---

boac/api/cohort_controller.py
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1064
master PR is #753

[QA] BOAC-1064, allow admin to create cohort with non-None advisor_ldap_uid

---

.ebextensions/11_install_pandas.config
.travis.yml
README.md
requirements.txt

https://jira.ets.berkeley.edu/jira/browse/BOAC-1071
Read `pandas` v0.23.2 notes: https://github.com/pandas-dev/pandas/releases

BOAC-1071, minor upgrades: SQLAlchemy, pandas, pytest, etc.

---

scripts/db/add_advisor_per_dept_id.sql
scripts/db/create_university_dept.sql

https://jira.ets.berkeley.edu/jira/browse/BOAC-1070
Extracted useful bits from `post_deploy_01_add_COE_advisors` (BOAC-1070).

BOAC-1070, db utils: add_advisor_per_dept_id and create_university_dept

---

boac/externals/data_loch.py
boac/static/app/student/studentFactory.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1069

BOAC-1069 Include no-units-yet students in the 'Units 0 - 29' filter

---

boac/externals/data_loch.py
boac/merged/student.py
config/default.py
config/test.py

https://jira.ets.berkeley.edu/jira/browse/NS-182

NS-182 Reroute loch search queries to RDS index tables

---

boac/api/status_controller.py
boac/externals/data_loch.py
tests/test_api/test_search_controller.py

https://jira.ets.berkeley.edu/jira/browse/NS-182

NS-182 Redshift is dethroned as sole safe executor

---

boac/api/status_controller.py
boac/externals/data_loch.py
boac/merged/student.py
config/default.py
config/test.py
tests/test_api/test_search_controller.py

https://jira.ets.berkeley.edu/jira/browse/NS-182
QA version of #763 and #764.

 [QA] NS-182 Reroute loch search queries to RDS index tables

---

scripts/db/add_advisor_per_dept_id.sql

https://jira.ets.berkeley.edu/jira/browse/BOAC-1070
I used this script to add users to boac-demo env and discovered room for improvement.
Follow up to PR #759

BOAC-1070, add 'exists' tolerance to add_advisor_per_dept_id.sql

---

boac/api/config_controller.py
boac/static/app/cohort/cohortController.js
boac/static/app/course/courseController.js
boac/static/app/shared/tabs.html
boac/static/app/shared/utilService.js
config/default.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1091
Details in the Jira.

[QA] BOAC-1091, disable Matrix view if student count exceeds threshold

---

boac/api/config_controller.py
boac/static/app/cohort/filtered/cohortController.js
boac/static/app/course/courseController.js
boac/static/app/shared/tabs.html
boac/static/app/shared/utilService.js
config/default.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1091
QA PR is #770

BOAC-1091, disable Matrix view if student count exceeds threshold

---

boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-999

BOAC-999 Fix name _.gettin' for page title

---

boac/static/app/cohort/filtered/cohort.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1057

BOAC-1057 Pluralization for filtered cohort counts

---

boac/api/athletics_controller.py
boac/api/search_controller.py
boac/externals/data_loch.py
boac/merged/athletics.py
boac/static/app/athletics/teams.html
boac/static/app/athletics/teamsController.js
boac/static/app/cohort/_filtered/cohort.html
boac/static/app/cohort/_filtered/cohortController.js
boac/static/app/cohort/_filtered/menu.html
boac/static/app/cohort/filtered/manage.html
boac/static/app/student/studentFactory.js
boac/static/app/student/studentSearchService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1118
Click on a team and you get a search with custom page title.

BOAC-1118, point the Teams page at new filtered-cohort view

---

boac/api/config_controller.py
boac/api/user_controller.py
boac/static/app/cohort/curated/cohort.html
boac/static/app/cohort/filtered/cohort.html
boac/static/app/course/course.html
boac/static/app/home/sortableAlertsTable.html
boac/static/app/main.css
boac/static/app/shared/matrix.html
boac/static/app/student/student.html
boac/static/app/student/studentController.js
boac/static/app/visual/visualizationService.js
config/default.py
tests/test_api/test_config_controller.py
tests/test_lib/test_util.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1120
* `demoMode.blur` to obscure names, profile pics
* `demoMode.betaTesting` for user testing (in demo env) of the new filtered-cohort-view starting ~Aug 20. We will not deploy the feature to prod until ~Sep 4 (BOAC v2.6).

BOAC-1120, demoMode img blur; demoMode.betaTesting for feature previews in demo env

---

boac/__init__.py

[QA] NOJIRA, bump BOAC to v2.4

---

boac/api/user_controller.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1089
The background image will display instead.

BOAC-1089 Missing photos should not generate 404s

---

boac/__init__.py

Our grandchildren may live to see it.

NOJIRA Bump BOAC version to 2.5

---

boac/api/util.py
boac/static/app/athletics/teamsController.js
boac/static/app/cohort/_filtered/cohort.html
boac/static/app/cohort/_filtered/cohortController.js
boac/static/app/cohort/_filtered/menuDirective.js
boac/static/app/cohort/cohortService.js
boac/static/app/cohort/filtered/cohortController.js
boac/static/app/cohort/filtered/deleteController.js
boac/static/app/cohort/filtered/deleteModal.html
boac/static/app/home/home.html
boac/static/app/nav/sidebar.html
boac/static/app/routes.js
boac/static/app/shared/utilService.js
boac/static/app/student/studentFactory.js
boac/static/app/student/studentSearchService.js
tests/test_api/test_filtered_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1121
The delicate art of reusability.

BOAC-1121, delete cohort add to new filtered cohort view

---

boac/static/app/cohort/_filtered/filterCriteriaService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1140

BOAC-1140, expose getMajors in filterCriteriaService

---

boac/api/cache_utils.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1142

BOAC-1142 Optimize midterm alerts query in cache refresh

---

boac/static/app/cohort/_filtered/filterCriteria.html
boac/static/app/cohort/_filtered/filterCriteriaComponent.js
boac/static/app/cohort/_filtered/filterCriteriaService.js
boac/static/app/cohort/_filtered/filterCriteriaUtil.js
boac/static/app/shared/utilService.js
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1072
More work on adding unsaved-filter to criteria. Clean up some naming and enrich filter definition object.

BOAC-1072, add unsaved filter to working set of filterCriteria

---

scripts/db/migrate/20180809-BOAC-1147/create_my_students_cohort_per_uid.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1147
For example:
```
python3 scripts/db/migrate/20180809-BOAC-1147/create_my_students_cohort_per_uid.py 12345 Jane
```
Much safer/easier than composing raw SQL.

[QA] BOAC-114, create_my_students_cohort_per_uid script

---

boac/api/search_controller.py
boac/api/user_controller.py
boac/api/util.py
boac/static/app/admin/adminController.js
boac/static/app/cohort/_filtered/filterCriteria.html
boac/static/app/cohort/_filtered/filterCriteriaComponent.js
boac/static/app/cohort/_filtered/filterCriteriaService.js
boac/static/app/cohort/_filtered/filterCriteriaUtil.js
boac/static/app/cohort/filtered/allController.js
boac/static/app/cohort/filtered/cohortController.js
boac/static/app/cohort/filtered/manageController.js
boac/static/app/user/authService.js
boac/static/app/user/userFactory.js
boac/templates/index.html
bower.json
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1146

BOAC-1146, populate 'Advisor' filter with data of /api/profiles/dept/{dept_code}

---

boac/static/app/cohort/_filtered/cohort.html
boac/static/app/cohort/_filtered/cohortController.js
boac/static/app/cohort/_filtered/cohortUtils.js
boac/static/app/cohort/_filtered/filterCriteriaComponent.js
boac/static/app/cohort/_filtered/filterCriteriaFactory.js
boac/static/app/cohort/_filtered/filterCriteriaService.js
boac/static/app/cohort/curated/cohort.html
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1088
More tweaks.

BOAC-1088, advisorUID criteria loads and 'Apply' does a proper search

---

scripts/db/migrate/20180809-BOAC-1147/create_my_students_cohort_per_uid.py
scripts/db/migrate/20180809-BOAC-1147/create_my_students_cohort_per_uid.sh

https://jira.ets.berkeley.edu/jira/browse/BOAC-1147
QA PRs: #788 and #790

BOAC-1147, create_my_students_cohort_per_uid script

---

boac/static/app/cohort/_filtered/cohort.html
boac/static/app/cohort/_filtered/cohortController.js
boac/static/app/cohort/_filtered/cohortUtils.js
boac/static/app/cohort/_filtered/filterCriteria.html
boac/static/app/cohort/_filtered/filterCriteriaComponent.js
boac/static/app/cohort/_filtered/filterCriteriaFactory.js
boac/static/app/cohort/_filtered/filterCriteriaService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1124
* Wire 'Apply' button to exec search function.
* Disable available options when added to criteria.
* Event listeners

BOAC-1124, execute search, disable options and query-args per filters

---

boac/static/app/cohort/_filtered/cohort.html
boac/static/app/cohort/_filtered/cohortController.js
boac/static/app/cohort/_filtered/filterCriteriaComponent.js
boac/static/app/cohort/_filtered/filterCriteriaService.js
boac/static/app/nav/sidebar.html
boac/static/app/routes.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1124
https://jira.ets.berkeley.edu/jira/browse/BOAC-1155
...and tabs and pagination.

BOAC-1124, student photo and sis data in new cohort view

---

boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1078

BOAC-1078, No phone? No icon.

---

boac/static/app/home/home.html
boac/static/app/nav/sidebar.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1155

BOAC-1155, two more sidebar links get null args in filteredCohort() ref

---

boac/static/app/cohort/curated/cohortController.js
boac/static/app/cohort/filtered/cohortController.js
boac/static/app/course/courseController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1154
`args.tab` matches convention of new CF view.

BOAC-1154, tab query arg pulled from $location.search().tab

---

boac/__init__.py

NOJIRA, master branch is now v2.6

---

boac/static/app/cohort/_filtered/cohort.html
boac/static/app/cohort/_filtered/cohortController.js
boac/static/app/cohort/_filtered/cohortUtils.js
boac/static/app/cohort/_filtered/filterCriteriaComponent.js
boac/static/app/cohort/_filtered/filterCriteriaService.js
boac/static/app/shared/utilService.js
boac/static/app/student/studentFactory.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1151
Use `?w=1` for a more reasonable diff.

BOAC-1151, sort existing/added filters in cognitively appropriate manner

---

boac/static/app/cohort/curated/cohort.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1160
master PR is #805

[QA] BOAC-1160, collateral damage in CSS class name

---

boac/static/app/cohort/_filtered/cohort.html
boac/static/app/cohort/_filtered/cohortController.js
boac/static/app/cohort/_filtered/cohortUtils.js
boac/static/app/cohort/_filtered/filterCriteriaComponent.js
boac/static/app/cohort/_filtered/filterCriteriaFactory.js
boac/static/app/cohort/filtered/deleteController.js
boac/static/app/shared/utilService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1121
A few minor fixes along the way.

BOAC-1121, delete cohort and then go home

---

.eslintrc.yml
boac/static/app/cohort/_filtered/cohort.html
boac/static/app/cohort/_filtered/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1161
Wrap `_.map()` in `_.reject()` so unavailable filters do not surface as `undefined`.

BOAC-1161, exclude ASC/COE filters based on user role and then sort

---

boac/static/app/cohort/_filtered/cohort.html
boac/static/app/cohort/_filtered/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1163
https://jira.ets.berkeley.edu/jira/browse/BOAC-1116
* `ng-show` allows matrix view render while `isLoading`
* `anchorSchool` (to top) when paging
* the odd `studentCountExceedsMatrixThreshold`

BOAC-1163, tab to matrix view with proper location.args

---

boac/merged/student.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1173

BOAC-1173 Suppress dropped sections from past terms

---

boac/static/app/cohort/_filtered/cohort.html
boac/static/app/cohort/_filtered/cohortController.js
boac/static/app/cohort/_filtered/cohortUtils.js
boac/static/app/cohort/_filtered/filterCriteria.html
boac/static/app/cohort/_filtered/filterCriteriaComponent.js
boac/static/app/cohort/_filtered/filterCriteriaFactory.js
boac/static/app/cohort/cohort.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-1164
`w=1` might help with diff

BOAC-1164, header styles - including buttons in rename mode

---

boac/static/app/cohort/_filtered/cohort.html
boac/static/app/cohort/_filtered/cohortController.js
boac/static/app/cohort/_filtered/createController.js
boac/static/app/cohort/_filtered/createModal.html
boac/static/app/cohort/_filtered/filterCriteria.html
boac/static/app/cohort/_filtered/filterCriteriaComponent.js
boac/static/app/cohort/filtered/filteredCohortFactory.js
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1122
Passing a set of "callbacks" to `filterCriteriaComponent` seems cleanest.

BOAC-1122, save cohort without reloading search results

---

boac/api/filtered_cohort_controller.py
boac/api/search_controller.py
boac/api/util.py
boac/externals/data_loch.py
boac/merged/student.py
boac/models/cohort_filter.py
boac/static/app/cohort/_filtered/cohort.html
boac/static/app/cohort/_filtered/createController.js
boac/static/app/cohort/_filtered/filterCriteriaFactory.js
boac/static/app/cohort/_filtered/filterCriteriaService.js
boac/static/app/cohort/filtered/filteredCohortFactory.js
boac/static/app/student/studentSearchService.js
scripts/db/migrate/20180822-BOAC-1165/alter_advisor_uid_key_in_cohort_json.py
scripts/db/migrate/20180822-BOAC-1165/alter_advisor_uid_key_in_cohort_json.sh
tests/test_api/test_filtered_cohort_controller.py
tests/test_models/test_cohort_filter.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1165
Includes db migration script `20180822-BOAC-1165/alter_advisor_uid_key_in_cohort_json.py`

BOAC-1165, multiple advisor UIDs can go in cohort-filter JSON

---

boac/api/filtered_cohort_controller.py
boac/api/util.py
boac/models/development_db.py
boac/static/app/cohort/_filtered/cohort.html
boac/static/app/cohort/_filtered/cohortController.js
tests/test_api/test_api_util.py
tests/test_api/test_filtered_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1177
Today is all about feature deletion.

BOAC-1177, toss out the COE-read-only-cohort feature

---

boac/static/app/nav/nav.css
boac/static/app/nav/sidebar.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1029

BOAC-1029, What's better than pills? Bigger pills.

---

scripts/db/migrate/20180822-BOAC-1165/alter_advisor_uid_key_in_cohort_json.sh

https://jira.ets.berkeley.edu/jira/browse/BOAC-1165
It was commented out during local test.

BOAC-1165, restore line commented out in shell script

---

boac/static/app/nav/sidebar.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1029
Fallout from the pill fix. Review with `w=1`

BOAC-1029, the fa-plus icon needs to float right in sidebar

---

boac/static/app/cohort/_filtered/createController.js
boac/static/app/cohort/_filtered/filterCriteriaComponent.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1182

BOAC-1182, fix attribute names in create function; hide 'Save' if filter list is empty

---

boac/api/filtered_cohort_controller.py
boac/api/student_controller.py
boac/api/util.py
boac/externals/data_loch.py
boac/merged/student.py
boac/models/cohort_filter.py
boac/routes.py
boac/static/app/cohort/_filtered/cohortController.js
boac/static/app/cohort/_filtered/createController.js
boac/static/app/cohort/_filtered/filterCriteriaComponent.js
boac/static/app/cohort/_filtered/filterCriteriaFactory.js
boac/static/app/cohort/_filtered/filterCriteriaService.js
boac/static/app/cohort/filtered/filteredCohortFactory.js
boac/static/app/student/studentFactory.js
fixtures/loch.sql
fixtures/loch_student_coe_profile_11667051.json
fixtures/loch_student_coe_profile_7890123456.json
fixtures/loch_student_coe_profile_9000000000.json
fixtures/loch_student_coe_profile_9100000000.json
tests/test_api/test_student_controller.py
tests/test_api/test_user_controller.py
tests/test_models/test_cohort_filter.py
tox.ini

https://jira.ets.berkeley.edu/jira/browse/BOAC-1166
Involved taming the complexity in `data_loch.get_students_query()`

BOAC-1166, add COE PREP as search option in new filtered-cohort

---

boac/api/cache_utils.py
boac/externals/data_loch.py
boac/models/alert.py
config/default.py
fixtures/loch.sql
fixtures/loch_student_enrollment_term_3456789012_2178.json
tests/conftest.py
tests/test_api/test_cache_utils.py
tests/test_api/test_curated_cohort_controller.py
tests/test_api/test_filtered_cohort_controller.py
tests/test_models/test_alert.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1094
All the important numbers are in configs because we have no idea how the third week will look until it hits us.

BOAC-1094 Alerts for no course site activity, configurable cutoffs

---

boac/static/app/cohort/filtered/cohortController.js
boac/static/app/visual/visualizationService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1170
SVG blurring on the matrix turns out to look weird, so we'll go back to Generic Gray Head.
Also hook up demo-mode blurring for the new filtered cohort view.

BOAC-1170 Round out demo-mode image obfuscation

---

boac/static/app/shared/utilService.js
boac/static/app/student/student.html
fixtures/loch_student_enrollment_term_11667051_2178.json

https://jira.ets.berkeley.edu/jira/browse/BOAC-1112

BOAC-1112 Remove frozen daysSinceLastActivity value

---

boac/lib/cohort_filter_definition.py
boac/static/app/cohort/filtered/cohortController.js
boac/static/app/cohort/filtered/filterCriteria.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1189

BOAC-1189, fix pagination; sort ethnicities and advisors

---

boac/static/app/cohort/curated/selector.html
boac/static/app/cohort/filtered/filterCriteria.html
boac/static/app/course/course.html
boac/static/app/nav/sidebar.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1135
More to come...

BOAC-1135, aria-labels for sidebar links/buttons

---

boac/api/filtered_cohort_controller.py
boac/api/student_controller.py
boac/api/util.py
boac/merged/student.py
boac/static/app/cohort/filtered/cohortController.js
boac/static/app/cohort/filtered/cohortUtils.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1193
https://jira.ets.berkeley.edu/jira/browse/BOAC-1194

BOAC-1193, on search, reset page to one; treat nil boolean arg as null in student query

---

boac/merged/student.py
fixtures/loch_student_coe_profile_11667051.json
fixtures/loch_student_coe_profile_7890123456.json
fixtures/loch_student_coe_profile_9000000000.json
fixtures/loch_student_coe_profile_9100000000.json
tests/test_api/test_student_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1195

BOAC-1195 Unstring the COE profile

---

boac/static/app/cohort/filtered/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1161

BOAC-1161, do not allow negative offset; typeof check when location update

---

boac/static/app/admin/admin.html
boac/static/app/athletics/teams.html
boac/static/app/cohort/curated/cohort.html
boac/static/app/cohort/curated/manage.html
boac/static/app/cohort/filtered/all.html
boac/static/app/cohort/filtered/cohort.html
boac/static/app/cohort/filtered/filterCriteriaComponent.js
boac/static/app/course/course.html
boac/static/app/home/home.html
boac/static/app/home/sortableAlertsTable.html
boac/static/app/nav/sidebar.html
boac/static/app/search/searchResults.html
boac/static/app/shared/uibPaginationTemplate.html
boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1203
https://jira.ets.berkeley.edu/jira/browse/BOAC-1139
Enhance `uib-pagination` accessibility-wise. IMO, customizing bootstrap template is safe because that project is "feature-complete and no longer being maintained". They've moved on to Angular 2.
Plus, aria attributes here and there.

BOAC-1139, voice pagination; better show/hide for save button; various accessibility

---

boac/lib/cohort_filter_definition.py
boac/static/app/cohort/filtered/cohort.html
boac/static/app/cohort/filtered/cohortController.js
boac/static/app/cohort/filtered/filterCriteria.html
boac/static/app/course/course.html
boac/static/app/shared/tabs.html
boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1135

BOAC-1135, voice curated cohort checkboxes and more; f before m

---

boac/static/app/athletics/teamsController.js
boac/static/app/cohort/filtered/all.html
boac/static/app/cohort/filtered/cohortController.js
boac/static/app/home/home.html
boac/static/app/nav/sidebar.html
boac/static/app/routes.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1204
Params that are explicit in `routes.js` are readable and matched in sidebar.

BOAC-1204, fix links to inactive and intensive from sidebar

---

boac/models/alert.py
fixtures/loch_student_enrollment_term_5678901234_2178.json

https://jira.ets.berkeley.edu/jira/browse/BOAC-1207

BOAC-1207 Fix Alerts code for sites with no activity

---

boac/static/app/cohort/filtered/cohortService.js
boac/static/app/home/home.css
boac/static/app/home/home.html
boac/static/app/main.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-1040
Accordions.

BOAC-1040 Collapsible cohorts on homepage

---

boac/api/filtered_cohort_controller.py
boac/lib/cohort_filter_definition.py
boac/static/app/cohort/cohort.css
boac/static/app/cohort/filtered/cohortUtils.js
boac/static/app/cohort/filtered/filterCriteriaComponent.js
tests/test_api/test_filtered_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1210
https://jira.ets.berkeley.edu/jira/browse/BOAC-1206 (CSS tweak)
See BOAC-1210 description.

BOAC-1210, organize filter_definitions into categories for less work on client-side

---

boac/static/app/cohort/filtered/cohort.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1208

BOAC-1208, disable rename-button if the input is empty

---

boac/static/app/cohort/filtered/cohort.html
boac/static/app/cohort/filtered/cohortController.js
boac/static/app/cohort/filtered/cohortUtils.js
boac/static/app/cohort/filtered/filterCriteriaComponent.js
boac/static/app/cohort/filtered/filteredCohortFactory.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1190
https://jira.ets.berkeley.edu/jira/browse/BOAC-1204

BOAC-1190, fix bookmarkability of filtered-cohort page (eg, Team page links)

---

boac/static/app/cohort/filtered/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1214

BOAC-1214 lastActivityDays util for filtered cohorts

---

boac/api/filtered_cohort_controller.py
boac/api/student_controller.py
boac/api/util.py
boac/static/app/cohort/filtered/cohortService.js
tests/test_api/test_filtered_cohort_controller.py
tests/test_api/test_student_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1209
* Gives admins access to all order-by options
* Allows us to add COE sort options w/o worry

BOAC-1209, auth check on student/cohort searches per dept_code rules

---

boac/api/student_controller.py
boac/static/app/cohort/cohort.css
boac/static/app/cohort/filtered/cohort.html
boac/static/app/nav/sidebar.html
boac/static/app/student/student.html
tests/test_api/test_student_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1205
...and a little `aria` related work.

BOAC-1205, handle long cohort names; fix TODO

---

boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1131

BOAC-1131, give phone number a tabindex

---

boac/externals/data_loch.py
boac/merged/student.py
tests/test_api/test_student_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1209
See latest comment in the Jira.

BOAC-1209, order_by (eg, ASC team) can influence query scope

---

boac/static/app/cohort/cohort.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-1213

BOAC-1213, Safari and Firefox need explicit button background-color

---

boac/__init__.py

NOJIRA, BOAC master branch is now v2.7

---

boac/static/app/home/sortableAlertsTable.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1045

BOAC-1045 More sorting on front page

---

boac/static/app/cohort/filtered/createController.js
boac/static/app/cohort/filtered/filterCriteriaComponent.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1228

BOAC-1228, if cancel save operation then re-enable save button

---

boac/static/app/cohort/filtered/createController.js
boac/static/app/cohort/filtered/filterCriteriaComponent.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1228
master PR is #864

[QA] BOAC-1228, if cancel save operation then re-enable save button

---

boac/static/app/cohort/filtered/cohortController.js
boac/static/app/cohort/filtered/cohortService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1224

BOAC-1224, include page number in filtered-cohort bookmark

---

boac/static/app/cohort/curated/cohortController.js
boac/static/app/cohort/filtered/cohortController.js
boac/static/app/course/courseController.js
boac/static/app/shared/tabs.html
boac/static/app/visual/visualizationService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1051

BOAC-1051 An empty matrix is not a satisfying UX

---

boac/api/cache_utils.py
boac/externals/data_loch.py
tests/test_api/test_cache_utils.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1211

BOAC-1211 Remove now-unavailable students from curated cohort lists

---

boac/api/filtered_cohort_controller.py
boac/models/cohort_filter.py
boac/static/app/cohort/cohort.css
boac/static/app/cohort/filtered/cohort.html
boac/static/app/cohort/filtered/cohortController.js
boac/static/app/cohort/filtered/filterCriteria.html
boac/static/app/cohort/filtered/filterCriteriaComponent.js
boac/static/app/cohort/filtered/filteredCohortFactory.js
tests/test_api/test_filtered_cohort_controller.py
tests/test_models/test_cohort_filter.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1236
Toggle logic and styles.

BOAC-1236, cohort filters are editable: initial wiring

---

boac/static/app/cohort/cohort.css
boac/static/app/cohort/filtered/cohort.html
boac/static/app/cohort/filtered/cohortController.js
boac/static/app/cohort/filtered/filterCriteria.html
boac/static/app/cohort/filtered/filterCriteriaComponent.js
boac/static/app/cohort/filtered/filterCriteriaEditSubcategory.html
boac/static/app/cohort/filtered/filterCriteriaEditSubcategory.js
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1236
* Shared template code for 'add' or 'edit existing' filter.
* Wire 'save' button up to `/api/cohort/update` on backend
* CSS name shortening

BOAC-1236, update existing cohort or start from scratch to create new

---

.gitignore

Ignore Visual Studio artifact and remove extraneous.

NOJIRA, clean up gitignore and add .vscode

---

boac/static/app/visual/visualizationService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1261
Designs at https://jira.ets.berkeley.edu/jira/browse/BOAC-1111.

BOAC-1261 Matrix view: meet the little blue dots

---

boac/api/admin_controller.py
boac/static/app/admin/admin.css
boac/static/app/admin/admin.html
boac/static/app/admin/adminController.js
boac/static/app/admin/adminFactory.js
boac/static/app/home/home.html
boac/templates/index.html
tests/test_api/test_admin_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1256

BOAC-1256, /admin gets demo-mode toggle and users organized by dept

---

boac/static/app/cohort/filtered/cohort.html
boac/static/app/cohort/filtered/filterCriteriaComponent.js
boac/static/app/cohort/filtered/filteredCohortFactory.js
boac/static/app/home/homeController.js
boac/static/app/nav/sidebarNavController.js
boac/static/app/user/authService.js
tests/test_api/test_admin_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1263
https://jira.ets.berkeley.edu/jira/browse/BOAC-1251
Also, removed pointless listener in homeController.

BOAC-1263, delete-cohort modal fix; save-cohort post op fix

---

boac/lib/mockingbird.py
requirements.txt

https://jira.ets.berkeley.edu/jira/browse/NS-224
BOAC version of https://github.com/ets-berkeley-edu/nessie/pull/206

NS-224 Brain transplant for Mockingbird: httpretty -> responses

---

boac/static/app/admin/admin.html
boac/static/app/cohort/cohort.css
boac/static/app/cohort/filtered/cohortUtils.js
boac/static/app/cohort/filtered/deleteController.js
boac/static/app/cohort/filtered/filterCriteria.html
boac/static/app/cohort/filtered/filterCriteriaComponent.js
boac/static/app/cohort/filtered/filterCriteriaEditSubcategory.html
boac/static/app/cohort/filtered/filteredCohortFactory.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1264
* 'range' filter fix
* The `buttons` object in component js was out of control.  I moved "button objects" under the relevant contexts. This lil' refactor simplified the code a bit.
* Fixed minor bug in `Save cohort` callback
I recommend `?w=1` to view.

BOAC-1264, fix last-name filter (range) related bug; organize component js

---

boac/static/app/visual/visualizationService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1253

BOAC-1253 Disable zoom on matrix view

---

boac/static/app/shared/matrix.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-1052

BOAC-1052 Matrix CSS fixes

---

boac/static/app/cohort/cohort.css
boac/static/app/cohort/curated/cohort.html
boac/static/app/cohort/curated/cohortController.js
boac/static/app/cohort/filtered/cohort.html
boac/static/app/cohort/filtered/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1266

BOAC-1266, no matrix view option on curated/filtered cohort views

---

boac/api/filtered_cohort_controller.py
boac/models/cohort_filter.py
boac/static/app/cohort/cohort.css
boac/static/app/cohort/curated/cohort.html
boac/static/app/cohort/filtered/cohort.html
boac/static/app/course/course.html
boac/static/app/student/student.css
boac/static/app/student/studentAvatar.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1255

BOAC-1255, has-alerts notification on top of student-avatar (cohort and course views)

---

boac/lib/cohort_filter_definition.py
boac/static/app/cohort/curated/cohort.html
boac/static/app/cohort/filtered/cohort.html
boac/static/app/cohort/filtered/cohortService.js
boac/static/app/home/sortableAlertsTable.html
boac/static/app/student/student.html
boac/static/app/visual/visualizationService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1246

BOAC-1246 Disambiguate "Units" labels

---

boac/api/course_controller.py
boac/api/curated_cohort_controller.py
boac/models/alert.py
boac/models/cohort_filter.py
tests/test_api/test_alerts_controller.py
tests/test_api/test_course_controller.py
tests/test_api/test_curated_cohort_controller.py
tests/test_api/test_filtered_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1255
Reusability is the word that you heard.

BOAC-1255, alert-count per student on course page; test coverage

---

boac/static/app/visual/visualizationService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1260
Design at https://jira.ets.berkeley.edu/jira/browse/BOAC-1110.

BOAC-1260 Add risk quadrants to matrix view

---

boac/static/app/cohort/filtered/filterCriteriaComponent.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1269
As Teena expects.

BOAC-1269, 'Cancel' button must show after initial filter category is selected

---

boac/static/app/student/student.css
boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1254

BOAC-1254 Add SID to student profile

---

boac/static/app/shared/utilService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1237

BOAC-1237 Today becomes yesterday at midnight browser time

---

boac/static/app/cohort/filtered/cohort.html
boac/static/app/cohort/filtered/filterCriteria.html
boac/static/app/cohort/filtered/filterCriteriaComponent.js
boac/static/app/cohort/filtered/filterCriteriaEditSubcategory.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1271
An `ets-qa` PR will follow.

BOAC-1271, click cancel then not isSaving; ids for Teena

---

boac/static/app/visual/visualizationService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1052

BOAC-1052 Change relative time labels on matrix

---

boac/static/app/cohort/filtered/cohortController.js
boac/static/app/cohort/filtered/filterCriteriaComponent.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1271
The previous PR done broke the create cohort callback.

BOAC-1271, noop callback for rename cohort; create cohort callback fix

---

boac/static/app/cohort/cohort.css
boac/static/app/cohort/filtered/filterCriteria.html
boac/static/app/cohort/filtered/filterCriteriaComponent.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1275
...and simplified `acknowledgeSave` on button.

BOAC-1275, other people's cohorts must be read-only; no option to Save-As

---

boac/static/app/student/studentController.js
boac/static/app/visual/visualizationService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1279

BOAC-1279 Ensure units chart indicates correct current term

---

boac/externals/data_loch.py
tests/test_api/test_student_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1280

BOAC-1280, register 'minority' as COENG db column

---

boac/lib/util.py
boac/models/alert.py
tests/test_lib/test_util.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1277

BOAC-1277 Localize date diffs in infrequent activity alerts

---

boac/static/app/visual/visualizationService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1284
What a function is, what a function does.

BOAC-1284 Fix yAxisMeasure reference in visualizationService

---

boac/static/app/cohort/curated/curatedCohortFactory.js
boac/static/app/cohort/filtered/filteredCohortFactory.js
boac/static/app/course/courseController.js
boac/static/app/nav/headerController.js
boac/static/app/shared/googleAnalyticsService.js
boac/static/app/student/studentController.js
boac/static/app/user/authService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-481
I'm still working to understand Google Analytics dashboard. However, this seems to be the recommended pattern (see link in Jira) for session tracking.

BOAC-481, user-id with each googleAnalyticsService.track

---

boac/static/app/course/course.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1286

BOAC-1286, no 'Score' label for assignments submitted

---

boac/static/app/student/student.css
boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-529

BOAC-529 Per-term unit totals on student profile

---

boac/static/app/shared/matrix.css
boac/static/app/visual/visualizationService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1290
QA PR will follow a successful review...

BOAC-1290 Imaginary entities should not be clickable in matrix

---

boac/static/app/shared/matrix.css
boac/static/app/visual/visualizationService.js

QA version of https://github.com/ets-berkeley-edu/boac/pull/912

[QA] BOAC-1290 Imaginary entities should not be clickable in matrix

---

boac/static/app/visual/visualizationService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1296
QA PR will follow.

BOAC-1296 Matrix imaginary mean should not block student data

---

boac/static/app/visual/visualizationService.js

QA version of https://github.com/ets-berkeley-edu/boac/pull/914

[QA] BOAC-1296 Matrix imaginary mean should not block student data

---

boac/static/app/cohort/cohort.css
boac/static/app/cohort/filtered/filterCriteria.html
boac/static/app/cohort/filtered/filterCriteriaComponent.js
boac/static/app/shared/utilService.js
boac/static/app/splash/splashController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1297

BOAC-1297, popup error message if invalid edit on an added cohort filter

---

boac/static/app/cohort/cohort.css
boac/static/app/cohort/filtered/filterCriteria.html
boac/static/app/cohort/filtered/filterCriteriaComponent.js
boac/static/app/shared/utilService.js
boac/static/app/splash/splashController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1297
master PR is #916

[QA] BOAC-1297, popup error message if invalid edit on an added cohort filter

---

boac/lib/analytics.py

QA version of https://github.com/ets-berkeley-edu/boac/pull/922

[QA] BOAC-1299 Zero-percentiles are still legitimate data

---

boac/models/alert.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1291

BOAC-1291 One course site without alarms means no course alarms

---

boac/static/app/student/student.html

QA first PR for https://jira.ets.berkeley.edu/jira/browse/BOAC-1307

[QA] BOAC-1307 Demo mode must blur SID

---

boac/static/app/student/student.html

Master version of https://github.com/ets-berkeley-edu/boac/pull/925

BOAC-1307 Demo mode must blur SID

---

boac/static/app/home/home.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1303

BOAC-1303, one students is wrongs

---

boac/static/app/shared/googleAnalyticsService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1310
master PR is #929

[QA] BOAC-1310, no googleAnalytics without 'ga'

---

boac/static/app/admin/admin.html

https://jira.ets.berkeley.edu/jira/browse/CS-6922

BOAC-1314, no avatars for those listed on /admin page

---

.ebextensions/00_ami.config

https://jira.ets.berkeley.edu/jira/browse/BOAC-1313

BOAC-1313 Change health check URL to /api/ping

---

boac/static/app/course/courseController.js
boac/static/app/shared/matrix.css
boac/static/app/shared/matrix.html
boac/static/app/visual/visualizationService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1282

BOAC-1282 Matrix zoom controls

---

.ebextensions/01_create_apache_conf.config

https://jira.ets.berkeley.edu/jira/browse/BOAC-1309

BOAC-1309, SSL private key location (S3 URL) changed

---

boac/static/app/student/student.css
boac/static/app/student/student.html
boac/static/app/student/studentController.js
boac/static/app/visual/visualizationService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-506
Designs at https://jira.ets.berkeley.edu/jira/browse/BOAC-20.

BOAC-506 Term GPA and trend on student profile page

---

boac/static/app/student/student.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-529

BOAC-529 Add breathing room between semesters

---

boac/externals/data_loch.py
boac/merged/student.py
fixtures/loch.sql
tests/test_api/test_curated_cohort_controller.py
tests/test_api/test_filtered_cohort_controller.py
tests/test_externals/test_data_loch.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-507

BOAC-507 Include term GPAs in cohort API feeds

---

boac/externals/data_loch.py
boac/static/app/cohort/curated/cohort.html
boac/static/app/cohort/filtered/cohort.html
boac/static/app/student/student.css
boac/static/app/student/student.html
boac/static/app/student/studentController.js
boac/static/app/visual/gpaChartDirective.js
boac/static/app/visual/visualizationService.js
boac/templates/index.html
tests/test_api/test_curated_cohort_controller.py
tests/test_api/test_filtered_cohort_controller.py
tests/test_externals/test_data_loch.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-507
Designs in https://jira.ets.berkeley.edu/jira/browse/BOAC-494.

BOAC-507 Term GPA sparklines in cohort view: front end

---

boac/static/app/cohort/curated/cohort.html
boac/static/app/cohort/filtered/cohort.html
boac/static/app/shared/profile.css
boac/static/app/student/student.css
boac/static/app/student/student.html
boac/static/app/visual/gpaChartDirective.js
boac/static/app/visual/visualizationService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1335
Charts that size to the window! Three count them three decimal places!

BOAC-1335 Styling fixes for GPA

---

boac/merged/student.py
boac/static/app/home/home.css
boac/static/app/home/sortableAlertsTable.html
boac/static/app/home/sortableAlertsTableDirective.js
tests/test_api/test_curated_cohort_controller.py
tests/test_api/test_filtered_cohort_controller.py
tests/test_api/test_student_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1327

BOAC-1327 Expected graduation term on homepage and search results

---

boac/static/app/home/sortableAlertsTableDirective.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1338

BOAC-1338 Tolerate missing graduation term in front end

---

boac/static/app/shared/matrix.css
boac/static/app/visual/visualizationService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-935
https://jira.ets.berkeley.edu/jira/browse/BOAC-1323

BOAC-935 BOAC-1321 Matrix tooltips: majors and wrapping fix

---

boac/api/filtered_cohort_controller.py
boac/models/cohort_filter.py
boac/models/development_db.py
scripts/db/migrate/20181015-BOAC-1056/alter_cohort_filters_rename_label.sql
scripts/db/schema.sql
tests/test_api/test_filtered_cohort_controller.py
tests/test_models/test_cohort_filter.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1056
Will submit a follow-up PR with front-end changes.

BOAC-1056: re-'names' filtered cohort label field

---

boac/merged/sis_sections.py
boac/static/app/course/course.html
tests/test_merged/test_sis_sections.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1152

BOAC-1152 Deal with placeholder units in EAP classes

---

boac/api/filtered_cohort_controller.py
boac/models/cohort_filter.py
boac/static/app/cohort/filtered/filteredCohortFactory.js
tests/test_api/test_filtered_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1056
Follow-up to #946

BOAC-1056: Renames filtered cohort element on front-end

---

boac/static/app/home/home.css
boac/static/app/home/sortableAlertsTable.html
boac/static/app/shared/variablePrecisionNumberFilter.js
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-846

BOAC-846 Adjust units/GPA alignment, decimal precision

---

boac/__init__.py

NOJIRA, bump BOAC master branch to v2.9

---

boac/api/curated_cohort_controller.py
boac/api/filtered_cohort_controller.py
boac/api/user_controller.py
boac/models/cohort_filter.py
boac/static/app/cohort/curated/curatedCohortFactory.js
boac/static/app/cohort/filtered/cohortService.js
boac/static/app/cohort/filtered/filteredCohortFactory.js
boac/static/app/home/home.html
boac/static/app/home/homeController.js
boac/static/app/home/sortableAlertsTable.html
boac/static/app/home/sortableAlertsTableDirective.js
boac/static/app/nav/sidebarNavController.js
boac/static/app/search/searchResults.html
boac/static/app/student/student.css
tests/test_api/test_curated_cohort_controller.py
tests/test_api/test_filtered_cohort_controller.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1340
My-cohorts in sidebar and on homepage are served from the same lightweight user profile data. Student lists are lazy loaded. Homepage _should_ more quickly load.

BOAC-1340, improve homepage performance by reducing queries

---

boac/merged/student.py
boac/static/app/course/courseController.js
boac/static/app/shared/matrix.css
boac/static/app/shared/matrix.html
boac/static/app/shared/utilService.js
boac/static/app/visual/visualizationService.js
tests/test_api/test_course_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1339
Designs at https://jira.ets.berkeley.edu/jira/browse/BOAC-1258, though not everything in the designs is implemented.
https://jira.ets.berkeley.edu/jira/browse/BOAC-1321 (cancel the foam party) came along for the ride.

BOAC-1321 BOAC-1339 Front end: matrix axes selectable by dropdown, include GPA

---

boac/merged/sis_sections.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1346

BOAC-1346 Falsey check in EAP units handler

---

boac/merged/sis_sections.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1346
QA version of #956.

[QA] BOAC-1346 Falsey check in EAP units handler
