ets-berkeley-edu/boac

.eslintrc.yml
.gitignore
.stylelintrc.yml
.travis.yml
boac/api/errors.py
boac/api/status_controller.py
boac/auth/cas_auth.py
boac/auth/dev_auth.py
boac/db.py
boac/externals/canvas.py
boac/lib/http.py
boac/models/authorized_user.py
boac/models/base.py
boac/routes.py
boac/static/css/main.css
boac/static/js/app.js
boac/static/js/factories/landingFactory.js
requirements.txt
tox.ini

https://jira.ets.berkeley.edu/jira/browse/BOAC-35
ESLint:
* absorbed JSCS
* solid adoption and documentation
* eslintrc.yml copied from SuiteC)
Stylelint
* impressive docs: https://stylelint.io
* active committers
* nice plugins
* lacks the annoying verbosity of other linters
* I believe it's worth a try
Tox
* https://tox.readthedocs.io/en/latest/
* designed for Python projects
* Gulp equivalent without the need for wrapper modules (e.g., gulp-eslint)
* lightweight and familiar syntax

BOAC-35, Python, JS, CSS linters

---

boac/lib/http.py
tests/test_externals/test_canvas.py

For starters, we'll want to distinguish "this user has no Canvas account" from "Canvas is being unfriendly."

NOJIRA Let external API clients see error statuses

---

boac/api/config_controller.py
boac/configs.py
boac/routes.py
tests/test_api/test_config_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-45
Front-end bootstrap will use `/api/config` such that:
```
<div data-ng-if="config.devAuthEnabled && ...">
Log in with dev-auth credentials.
```
`/api/config` is public and contains 'version'.

BOAC-45, /api/config provides devAuthEnabled (needed in templates) and version

---

.eslintrc.yml
boac/static/js/factories/authFactory.js
config/default.py
run.py
tests/conftest.py
tests/test_externals/test_canvas.py
tox.ini

As promised, `flake8` covers all py files. Bonus: eslint rules unleashed.

NOJIRA, expand scope of code linting (py, js)

---

boac/api/config_controller.py
boac/lib/mockingbird.py
config/default.py

This change makes the fixtures path configurable per environment. For example, including a `FIXTURES_PATH` value in your `demo-local.py` will load fixtures from that path under `BOAC_ENV=demo`, rather than from the default path in source control. This allows us to demo from large bodies of local unobfuscated JSON if need be.
The BASE_DIR config value is also changed to a better path.

NOJIRA Make it easy to use fixtures outside source control

---

boac/auth/cas_auth.py
boac/auth/dev_auth.py
boac/static/js/controllers/landingController.js
boac/static/js/factories/authFactory.js
boac/static/templates/landing.html
config/default.py
tests/test_auth/test_cas_auth.py
tests/test_auth/test_dev_auth.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-44
Notes:
* move CAS callback logic out of `/cas/login`
* dual-purpose `/logout` for simplicity
* `window.location = {redirect_url}` for simplicity and to skip _Access-Control-Allow-Origin_ error

BOAC-44, CAS login button on landing; backend wiring

---

boac/models/authorized_user.py
tox.ini

Notes:
* `tox.ini` is cleaner with `[flake8]` configs at bottom.
* colorful output for eslint and flake8

NOJIRA, a cleaner tox.ini; pep fix on py file

---

boac/lib/mockingbird.py

As it turns out, without this little fix test failures will cascade in confounding ways.

NOJIRA Ensure mocks are unregistered on assertion failure

---

boac/api/errors.py
boac/api/user_controller.py
boac/lib/analytics.py
fixtures/canvas_user_for_uid_61889.json
requirements.txt
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-37
Big thanks to @sandeepmjay for the introduction to pandas.
This endpoint will be slow in production, given the number of Canvas requests involved; however, it should provide enough data to construct a demo-worthy view of an individual user.

BOAC-37 Distill per-user analytics feed from Canvas stats

---

boac/externals/canvas.py
boac/lib/mockingbird.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-8
The `@mockable` and `@mocking` decorators still exist if needed, but the `@fixture` decorator now provides the equivalent of both, taking a template string which is dynamically evaluated at request time in order to find the proper fixture filename. 
Apart from concision, what's the benefit of introducing more magic into the mix? Associating an evaluable pattern directly with the request function means that the function "knows" what its fixtures ought to look like, and can be told (in a follow-up PR) to generate them as it goes, VCR-style.

BOAC-8 @fixture decorator is your one-stop mock shop

---

boac/lib/mockingbird.py
boac/lib/scriptify.py
scripts/example_generate_fixtures.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-8
Thanks @raydavis for working out the scriptify part of this!
Usage as shown in `scripts/example_generate_fixtures.py` is straightforward. Request functions must be decorated with `@fixture` in order to write fixture files; but then you can rest easy that the function will find the right file when it comes time to read the fixture back.
It's also possible to generate fixtures by starting the app with a `FIXTURE_OUTPUT_PATH` environment variable and clicking around; but I assume that will be a less common case for us.

BOAC-8 Allow scripts to quickly pull down a whole lotta JSON

---

scripts/example_generate_fixtures.py
scripts/scriptpath.py
tox.ini

This seems to work - put the funny business in `scriptpath.py` and tell flake8 to ignore it.

NOJIRA Make python scripts lintable

---

.gitignore
boac/externals/sis_athlete_api.py
boac/models/authorized_user.py
boac/models/base.py
boac/models/cohort.py
boac/models/development_db.py
config/default.py
fixtures/sis_athlete_api_FHW.json
requirements.txt
tests/fixtures/cohorts.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-46
It would be nice to be able to load the sample Cohorts data (at the JIRA ticket) through a `run.py` CLI command, but I didn't want to delay this PR any longer. Here's how I did it through a scriptified console:
```
from boac.models.cohort import Cohort
Cohort.load_csv('tmp/cohorts.csv')
```

BOAC-46 Support sample cohorts

---

boac/api/cohort_controller.py
boac/api/error_handlers.py
boac/api/errors.py
boac/models/cohort.py
boac/routes.py
tests/conftest.py
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-51
Since the whole backing of the cohort model is likely to change, I kept tests simple and at the controller level.
However, these are BOAC's first tests that directly depend on database-backed fixtures, and some additional changes were needed to get things working.

BOAC-51 Simple API feeds for cohort data

---

.eslintrc.yml
boac/api/user_controller.py
boac/lib/http.py
boac/static/js/controllers/studentController.js
boac/static/templates/student.html
boac/templates/index.html
bower.json
requirements.txt

https://jira.ets.berkeley.edu/jira/browse/BOAC-47
Standard (Flask) encoder does not produce valid JSON when given `float('nan')`.  The front-end would choke when, for example, feed included: `"zscore": NaN`.   [simplejson](https://simplejson.readthedocs.io) has a solution whereby _float('nan')_ translates to `null` in the feed.

BOAC-47, tolerant_jsonify will not put NaN to JSON response; student view ng-repeats

---

scripts/install-tox-deps.sh
tox.ini

https://jira.ets.berkeley.edu/jira/browse/BOAC-52
The `commands` section of tox.ini file does not allow for BASH-like conditional. Delegating to a script seems acceptable if we get faster linting.

BOAC-52, npm install tox deps only if necessary (faster linting)

---

README.md
scripts/load_cohorts_csv.py
tox.ini

`scripts/load_cohorts_csv.py` will be removed when we're done with `cohorts` table (demo mode).
PR includes `tox.ini` enhancement:
```
tox -e lint-js -- boac/static/js/controllers/cohortController.js
tox -e lint-py -- scripts/cohort_fixtures.py
```

NOJIRA, script to load cohort.csv

---

scripts/example_generate_fixtures.py

PyCharm wants a dot, but the dot seems to make the script unrunnable. Sorry, PyCharm!

NOJIRA Fix example fixture script

---

boac/static/app/cohort/cohortController.js
boac/static/app/shared/scatterplot.css
boac/templates/index.html
bower.json

https://jira.ets.berkeley.edu/jira/browse/BOAC-62
- Newer D3 versions have a substantially different API;
- `translateExtent` keeps us from panning out of bounds;
- moving chart margins out of SVG calculations and into straight CSS fixes weird offset-on-zoom issues.

BOAC-62 Upgrade D3 to v4; constrain panning on cohort plot

---

boac/models/cohort.py
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-65
This is a quick way to support obfuscated team names without explicitly defining them in code. With this change, Postgres data can be altered to use arbitrary demo codes:
`update cohorts set code = 'Demo Team - Women' where code = 'CRW';`
and the app will handle them without complaint.

BOAC-65 Handle cohort codes with no hardcoded code-to-name translation

---

boac/api/cohort_controller.py
boac/api/user_controller.py
boac/api/util.py
boac/externals/canvas.py
boac/lib/analytics.py
tests/fixtures/cohorts.py
tests/test_api/test_user_controller.py
tests/test_externals/test_canvas.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-75
It's a good old Junction-style data munge, with some extra refactoring to keep the analytics module focused on analytics rather than overall feed transformation.

BOAC-75 Include SIS enrollment data in user API feeds when present

---

boac/lib/analytics.py
boac/static/app/cohort/cohort.css
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/shared/scatterplot.css
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-59
Points with no y-axis data are plotted below the x-axis. Points with no data at all get a separate list off the grid. It ain't the prettiest, but I don't suppose any of these dev designs are going out on the road.

BOAC-59 Distinguish zero from no data in scatter plot

---

.ebextensions/00_ami.config
.ebextensions/10_install.config
.ebextensions/20_configure_environment.config
.ebextensions/99_apache_restart.config
.gitignore
buildspec.yml
config/apache-boac.conf

https://jira.ets.berkeley.edu/jira/browse/BOAC-97
There are a few outstanding tasks:
* Proper `python3 run.py` on deploy (the `99_post_deployment_hook` is not a likely solution)
* Tweaks to buildspec
* More Apache config work

BOAC-97, .ebextensions and apache conf; buildspec (draft) for CodePipeline

---

buildspec.yml

For now, buildspec only serves to exclude `test/` and similar resources

BOAC-97, buildspec does not need npm and pip install

---

boac/api/cohort_controller.py
boac/api/user_controller.py
boac/externals/canvas.py
boac/externals/sis_athlete_api.py
boac/externals/sis_enrollments_api.py
boac/externals/sis_student_api.py
boac/models/development_db.py
boac/models/json_cache.py
config/default.py
requirements.txt
scripts/cohort_fixtures.py
scripts/student_api_fixtures.py
tests/conftest.py
tests/fixtures/cohorts.py
tests/test_api/test_user_controller.py
tests/test_externals/test_canvas.py
tests/test_externals/test_sis_enrollments_api.py
tests/test_externals/test_sis_student_api.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-103
Also:
- Avoid Flask-SQLAlchemy session deadlocks in tests.
- Enable automatic transaction handling.
Known minuses:
- Because HTTP responses aren't JSON-serializable, failure information is discarded on the way up the call stack.
- Extra functions are defined to work around the lack of clean decorator nesting.

BOAC-103 Add DB-based caching

---

boac/externals/asc_cohorts.py
boac/externals/calnet.py
boac/lib/merged.py
boac/models/cohort.py
scripts/load_cohorts_from_asc.py
tests/fixtures/cohorts.py
tests/test_lib/test_merged.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-103 (although in retrospect this really should have been broken out into its own task)
Besides loading relevant rows from an ASC-provided spreadsheet, this PR add columns to the Cohorts table for ASC's in-house team names, which differ quite a bit from the Athletes API.

BOAC-103 Add ability to create Cohorts from ASC data export

---

boac/api/cohort_controller.py
boac/api/user_controller.py
boac/externals/canvas.py
boac/lib/merged.py
boac/lib/scriptify.py
boac/models/json_cache.py
config/default.py
scripts/refresh_external_data_for_term.py
tests/test_api/test_user_controller.py
tests/test_externals/test_canvas.py
tests/test_externals/test_sis_enrollments_api.py
tests/test_externals/test_sis_student_api.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-103
Also:
* Change our CANVAS_CURRENT_ENROLLMENT_TERM configuration from an unpredictable number to something more human-readable (e.g., "Fall 2017").
* Cache the Canvas User Profile (unless it encountered a non-404 error).
* Add some missing test fixtures.

BOAC-103 Add cache-filling script

---

boac/api/cohort_controller.py
boac/api/user_controller.py
tox.ini

Cause of mysterious Travis failure (https://travis-ci.org/ets-berkeley-edu/boac/builds/298832425) was unexpected `flake8-import-order` version. Devs will get latest with this PR.

NOJIRA, upgrade flake8-import-order per Travis; two lint-py fixes

---

README.md
boac/models/authorized_user.py
boac/models/development_db.py
scripts/db/migrate/20171107-BOAC-92/create_cohort_filters_table.sql
tests/test_models/test_authorized_user.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-92
We don't need to roll out many-to-many in BOAC UX and yet having such support on the backend gives us the option to manually create shared filters (e.g., low_gpa_filter). Plus, we avoid a future refactor.
**Note:** I'll amend this with a few more tests if we like this direction.

BOAC-92, cohort_filters table, many-to-many with authorized_users

---

boac/api/cohort_controller.py
boac/api/user_controller.py
boac/models/authorized_user.py
boac/models/development_db.py
boac/static/app/cohort/cohortFactory.js
boac/static/app/landing/landing.html
boac/static/app/landing/landingController.js
tests/conftest.py
tests/fixtures/cohorts.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_user_controller.py
tests/test_lib/test_merged.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-93
All teams are cohorts but not all cohorts are teams. 
* I generalized `/api/cohort/<cohort_code>`
* the custom cohorts are always available in `current_user` object
* next step is to rework the front-end

BOAC-93, BOAC/api to support GET custom cohorts

---

boac/api/cache_utils.py
boac/models/json_cache.py
run.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-138
Example usage:
```
boac> flask load_external_data
boac> flask load_external_data
boac> flask load_external_data
boac> flask refresh_external_data
[2017-11-14 09:38:18,803] - INFO: Will delete 2472 entries not matching term_% [in /Users/raydavis/Code/ets/boac/boac/models/json_cache.py:38]
[2017-11-14 09:38:18,898] - INFO: Will delete 2578 entries matching term_Fall 2017% [in /Users/raydavis/Code/ets/boac/boac/models/json_cache.py:32]
...
Complete. Fetched 9716 external feeds.
```

BOAC-138 Add support for cache loading and refreshing

---

boac/api/user_controller.py
boac/static/app/cohort/cohortsDropdownDirective.js
boac/static/app/cohort/dropdownNav.html
boac/static/app/landing/landing.html
boac/static/app/landing/landingController.js
boac/static/app/main.css
tests/test_api/test_cohort_controller.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-95
* `myCohorts` is not needed in `/api/profile`
* wrap-reverse on landing puts my-cohorts on top
* isLoading for dropdown in header nav

BOAC-95, cohort counts on landing; wrap-reverse puts myCohorts on top

---

boac/models/authorized_user.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-148
This matches the intention, as seen in [scripts/db/migrate/20171107-BOAC-92/create_cohort_filters_table.sql](https://github.com/ets-berkeley-edu/boac/blob/master/scripts/db/migrate/20171107-BOAC-92/create_cohort_filters_table.sql).
On localhost, a stale schema (in which `cohort_filter_owners.user_id` was varchar) was masking the problem.  Once I refreshed my local schema I could reproduce (then fix) the bug.

BOAC-148, fix db.Table def of cohort_filter_owners

---

boac/api/cohort_controller.py
boac/models/development_db.py
boac/static/app/cohort/manage.html
boac/static/app/cohort/manageCohortsController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-149
Furthermore, do not cache team data if load_canvas_profile=False. (The change in `development_db.py` allows use to load test-cohort-data when test-user-data is already present in the db – e.g., boac-dev)

BOAC-149, when get_cohort_list, include member_count per cohort and exclude Canvas user profile

---

boac/auth/dev_auth.py
tests/conftest.py
tests/test_api/test_user_controller.py
tests/test_auth/test_dev_auth.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-153
Why support `request.form` if we don't need it?

BOAC-153, dev_auth need only support json POST

---

boac/models/team_member.py
boac/static/app/cohort/cohort.html
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-156
The importance of `totalMemberCount` on cohort view:
* if equals 0 or more then you're viewing search results or saved cohort
* if null then you're starting from scratch (ie, 'create a cohort')

BOAC-156, cohort view must have totalMemberCount for all cohorts, incl. teams

---

boac/lib/analytics.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-151
In some cases the front end will decide to round further, but there's no need to pass all those floating-point digits into the API.

BOAC-151 Back-end percentile rounding to one decimal place

---

boac/api/cache_utils.py
boac/api/cohort_controller.py
boac/api/user_controller.py
boac/api/util.py
boac/externals/canvas.py
boac/lib/analytics.py
boac/lib/berkeley.py
boac/lib/merged.py
boac/models/json_cache.py
boac/static/app/student/courseSiteMetrics.html
boac/static/app/student/courseSiteMetricsDirective.js
boac/static/app/student/student.html
boac/static/app/student/studentController.js
boac/templates/index.html
fixtures/canvas_course_sections_7654325.json
fixtures/canvas_course_sections_7654330.json
fixtures/canvas_user_courses_61889.json
fixtures/sis_enrollments_api_11667051_2172.json
tests/test_api/test_user_controller.py
tests/test_externals/test_canvas.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-121
https://jira.ets.berkeley.edu/jira/browse/BOAC-127
Apologies for the large PR, but these two wanted to come together.
A few UX topics:
- Unmatched Canvas sites from a given term appear immediately after courses for that term. This means that prior to Fall 2016, we show a bunch of courses with no sites and then a bunch of sites with no courses. Suppress some or all of this?
- Our current enrollments-fetching code only looks at primary sections, so Canvas sites associated with secondary sections only will remain unmatched.
- Phys Ed courses taken by athletes now appear in the mix. Suppress these, even if (as occasionally happens) there's a Canvas site associated? Should any other enrollments be considered noise? 
- Dropped enrollments are …

BOAC-121 BOAC-127 Show enrollments from all terms with best-effort Canvas site association

---

.ebextensions/01_create_apache_conf.config

https://jira.ets.berkeley.edu/jira/browse/BOAC-193

[python36] BOAC-193, bump python-path (in 01_create_apache_conf.config) to python3.6

---

boac/externals/canvas.py
tests/test_externals/test_canvas.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-147
For a while on Thursday, these expensive feeds were being cached with a "term_None" prefix.

BOAC-147 Bring Canvas scores APIs in line with BOAC-127 terms handling

---

boac/api/util.py
boac/externals/sis_enrollments_api.py
boac/lib/merged.py
boac/static/app/student/courseSiteMetrics.html
boac/static/app/student/courseSiteMetricsDirective.js
boac/static/app/student/student.css
boac/static/app/student/student.html
boac/static/app/student/studentController.js
fixtures/sis_enrollments_api_11667051_2178.json
tests/test_api/test_user_controller.py
tests/test_externals/test_sis_enrollments_api.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-159
https://jira.ets.berkeley.edu/jira/browse/BOAC-171
Since this change will result in more courses with multiple sites attached, per-site headings are added to address https://jira.ets.berkeley.edu/jira/browse/BOAC-195.
It appears that the SIS enrollments API returns secondary sections only back to Fall 2016.
While the page structure will change following deployment of this PR, the underlying data will not show on boac-dev until the enrollments API cache is refreshed.

BOAC-159 BOAC-171 BOAC-195 Secondary section handling

---

boac/api/cache_utils.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-208
We lost this filter from boac.canvas.externals in #127.

BOAC-208 Restore per-term filter to Canvas cache reload

---

boac/api/cohort_controller.py
boac/api/user_controller.py
boac/models/cohort_filter.py
boac/models/development_db.py
boac/models/team_member.py
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortFactory.js
boac/static/app/cohort/createCohortController.js
scripts/db/migrate/20171205-BOAC-198/cohort_filter_criteria_jsonb.sql
tests/conftest.py
tests/test_api/test_cohort_controller.py
tests/test_models/test_cohort_filter.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-198
Changes:
* db script to change `filter_criteria` column to jsonb
* `team_groups` support in cohort feed
* list of `team_group_codes` defines custom cohorts and determines logic of "Teams" filter UX
* simpler setup of cohort test data (and no longer included as a step in `flask initdb`)

BOAC-198, teams-filter is now team-groups-filter, plus db column 'filter_criteria' scheme/type change

---

boac/lib/analytics.py
tests/test_lib/test_analytics.py

```
=================================================== warnings summary ===================================================
None
pytest-catchlog plugin has been merged into the core, please remove it from your requirements.
TeamMember detail API returns a well-formed response on a valid code if authenticated
/Users/raydavis/Code/ets/boac/.venv/lib/python3.6/site-packages/pandas/core/frame.py:3035: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame
See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
downcast=downcast, **kwargs)
...
```

BOAC-146 Eliminate Pandas warning

---

boac/merged/sis_enrollments.py
boac/models/cohort_filter.py
boac/models/team_member.py
tests/conftest.py
tests/test_api/test_cohort_controller.py

You said the cohort members API feed wasn't slow or bulky enough... and we listened!
Back end only for:
https://jira.ets.berkeley.edu/jira/browse/BOAC-185
https://jira.ets.berkeley.edu/jira/browse/BOAC-190
Querying and filtering on level and GPA, as opposed to just surfacing them, probably calls for additional work to extract those values into new database columns, unless we want to try the wild world of JSONB.

BOAC-185 BOAC-190 Add SIS profile and current-term courses to cohort

---

boac/api/user_controller.py
boac/models/team_member.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-223
https://jira.ets.berkeley.edu/jira/browse/BOAC-225
Short-circuiting on an empty Canvas feed is a holdover from the demo.

BOAC-223 BOAC-225 Show enrollments for students with no current-term course sites

---

boac/models/team_member.py
boac/static/app/cohort/cohort.html
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-229
Bonus fix: Id of search element in cohort view.

BOAC-229, Intensive cohort is not a saved-search and should not pre-populate search filters

---

boac/lib/analytics.py
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortService.js
boac/static/app/student/courseSiteMetrics.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-204
Currently only shows on the scatterplot matrix via "?yAxis=analytics.courseCurrentScore".
Changed display name to "Assignment grades" to avoid confusion with other "score" labels.

BOAC-204 Merge Canvas site "current score" stats into cohort-wide means

---

boac/models/team_member.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-232
I'll remove front-end ref to `name` when normalizing `team_member` data. For now, let's go for the easy fix.

BOAC-232, put 'name' in the all_students feed

---

boac/merged/sis_enrollments.py
fixtures/sis_enrollments_api_11667051_2172.json

https://jira.ets.berkeley.edu/jira/browse/BOAC-173
This PR plugs a hole in our dropped-section-removal logic. Previously, enrollments were removed only if all sections of a given class were dropped. We should also remove dropped sections from courses where not all sections were dropped.

BOAC-173 Suppress all dropped sections in previous terms

---

boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortMatrix.css
boac/templates/index.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-116
Fun fact: the letter "I" was disappearing from the Berkeley logo because it's defined as an SVG `rect`, whereas all other letters are `path` or `polygon`.

BOAC-116 Disallow cohort matrix CSS from romping all over the app

---

boac/api/athletics_controller.py
boac/api/cohort_controller.py
boac/api/util.py
boac/externals/import_asc_athletes.py
boac/models/athletics.py
boac/models/development_db.py
boac/models/student.py
boac/models/team_member.py
boac/routes.py
tests/test_api/test_athletics_controller.py
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-227
Incremental cutover continues.  The `athletics_controller` serves  '/api/team_groups/all' and '/api/teams/all' in a backwards compatible way. Plus, development_db loads test data in old and new schemas.

BOAC-227, '/api/teams/all' is in athletics_controller; development_db.py loads old and new tables

---

boac/api/athletics_controller.py
boac/api/cohort_controller.py
boac/api/util.py
boac/models/athletics.py
boac/models/authorized_user.py
boac/models/cohort_filter.py
boac/models/db_relationships.py
boac/models/development_db.py
boac/models/student.py
boac/models/team_member.py
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortFactory.js
tests/test_api/test_athletics_controller.py
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-227
This PR leaves TeamMember with one remaining function: `get_all_athletes()`. The trickier `get_students()` has been moved to new schema.

BOAC-184, athletics_controller serves /api/team*; get_students() moves to new schema

---

buildspec.yml

It seems AWS has upgraded support on CodeBuild

NOJIRA, bump python version to 3.6.3 in CodeBuild buildspec

---

boac/models/student.py
boac/static/app/student/findStudentDirective.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-274
The front-end fix ensures that the full list of students is fetched only once, instead of on every change to search text.
The back-end fix forces SQLAlchemy to eager load athletics associations. Specifically, it changes the underlying SQL query from:
```
SELECT students.created_at AS students_created_at, students.updated_at AS students_updated_at, students.sid AS students_sid, students.uid AS students_uid, students.first_name AS students_first_name, students.last_name AS students_last_name, students.in_intensive_cohort AS students_in_intensive_cohort 
FROM students LEFT OUTER JOIN (student_athletes AS student_athletes_1 JOIN athletics ON athletics.group_code = student_athletes_1.group_code) ON students.sid = student_athletes_1.sid
```
to: …

BOAC-274 Performance improvements to student search dropdown

---

boac/api/user_controller.py
boac/models/student.py
boac/static/app/student/findStudentDirective.js
boac/static/app/student/student.css
boac/static/app/student/student.html
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-247
https://jira.ets.berkeley.edu/jira/browse/BOAC-273
Note that surfacing multiple team memberships requires changing the structure of the /api/students/all feed, which in turn requires the search dropdown directive to do more work to parse multiple memberships. 
Per the design suggestion in https://jira.ets.berkeley.edu/jira/browse/BOAC-247, students on multiple teams will appear multiple times in the dropdown. If we decide we don't like this behavior, it's easy to change; the important thing is that we've decoupled this logic from the API feed structure and located it entirely in the front end.

BOAC-247 BOAC-273 Show all team names in student profile and search dropdown

---

boac/api/admin_controller.py
boac/api/cache_utils.py
boac/routes.py
run.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-138
This PR knowingly makes an utter hash of the cache_utils module. The goal is to support a non-destructive test of this background job approach on AWS. Once we have something that seems OK, I'll tidy the place up.

BOAC-138 Add admin API endpoints to manage refresh jobs

---

boac/externals/canvas.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-282
Without this, we run a high risk of 500 errors due to enrollment list mismatches between Canvas APIs, as well as losing important analytics.

BOAC-282 Do not lose Canvas data after a course site has been concluded

---

boac/api/cache_utils.py
boac/merged/sis_profile.py
boac/models/development_db.py
boac/models/normalized_cache_student.py
boac/models/normalized_cache_student_major.py
scripts/db/migrate/20171221-BOAC-278/create_normalized_cache_tables.sql
tests/test_merged/test_sis_profile.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-278
Before deploy, the included SQL script should be run on boac-shared to create new tables.
After deploy, the `load_merged_sis_profiles` method can be used to fill the tables. Since it will be running off cached JSON, it should go quickly.

BOAC-278 Normalized database cache for SIS profile

---

boac/externals/cal1card_photo_api.py
boac/externals/canvas.py
boac/externals/sis_degree_progress_api.py
boac/externals/sis_enrollments_api.py

Our externals code needs to survive cases where `response.raw_response` is `None`. But since error responses evaluate to falsey, the simple check `response.raw_response and response.raw_response.status_code == 404` will never return true.

NOJIRA Safe, sane, consistent 404 checks

---

boac/models/development_db.py
boac/models/student.py
tests/test_api/test_user_controller.py
tests/test_merged/test_sis_profile.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-290
Leveraging new `normalized_` tables. The unit-range filters are still TODO.

BOAC-290, Student model query: get_students by gpa_ranges, levels, majors

---

boac/api/admin_controller.py
boac/api/cache_utils.py
boac/models/development_db.py
config/default.py
run.py
tests/test_api/test_admin_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-138
- Full refresh through the admin API.
- External API access by in-the-know applications (if enabled).
- New non-admin user account in development_db load.
**COOKBOOK**
* *Check caching job status* : api/admin/cachejob
* *Refresh the current term's cached data* : api/admin/cachejob/refresh
* *Load any missing data for Summer 2017* : api/admin/cachejob/load?term=2175
* *Clear the caching job tracker after an interrupted job*: api/admin/cachejob/clear
* *Continue loading current term data after an interrupted refresh* : api/admin/cachejob/load

 BOAC-138 Full API support to manage cache from script

---

boac/merged/sis_enrollments.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-287
The Hub doesn't explicitly tell us which sections are primary. We've been using "nonzero unit count" as a proxy, but it looks like the occasional zero-unit primary section is a thing. Let's try a different metric! Fundamental as this change is, I haven't found any issues in spot checks on various students.

BOAC-287 Redefine 'primary section' as 'section with a grading basis'

---

boac/api/admin_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-322
Earlier commits have broken the caching job API on boac-dev. So far as I can tell from my local environment, this should be a fix, but I can't be sure until it lands on the server.

BOAC-322 Fix API header check

---

boac/api/admin_controller.py
scripts/refresh_current_term_cache.sh

https://jira.ets.berkeley.edu/jira/browse/BOAC-322
- Also removes temporary API request diagnostics.
@johncrossman , if this tests out on boac-dev, it would be my last change for the QA branch.

BOAC-322 Adapt sample cache refresh script to AWS environment

---

boac/static/app/cohort/myCohortsDropdown.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-327
This ensures that selecting a dropdown item forces a reload of the original criteria, even if the browser location hasn't changed in the meantime.

BOAC-327 Cohort dropdown: use ui-router to force reload

---

boac/merged/sis_profile.py
fixtures/sis_student_api_11667051.json
tests/test_externals/test_sis_student_api.py
tests/test_merged/test_sis_profile.py

See https://jira.ets.berkeley.edu/jira/browse/BOAC-334 for rationale on why skipping this part of the feed is probably better than trying to fold it in.

BOAC-334 Skip concurrent-enrollment academic status

---

boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/myCohortsDropdown.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-339
https://jira.ets.berkeley.edu/jira/browse/BOAC-340
Small fixes:
* `isCreateCohortMode=false` the moment you search
* hide 'Units' filter until we have reqts
* pagination when mode=search
* put orderBy to `$location.search`
* no page refresh when save new cohort
I'll create QA PR when this is merged to master.

BOAC-339/BOAC-340, no page reload when save cohort; proper pagination; orderBy to location.search

---

boac/__init__.py
boac/models/cohort_filter.py
boac/models/development_db.py
boac/models/job_progress.py
boac/models/json_cache.py
boac/models/normalized_cache_student.py
boac/models/normalized_cache_student_major.py
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-258
A separate commit centralizes the test-environment check on db session commits to avoid data leakage between tests.

 BOAC-258 Order per-user cohort list alphabetically

---

.ebextensions/00_ami.config

Managed updates seem to require this setting - see tail end of https://jira.ets.berkeley.edu/jira/browse/BOAC-275.

BOAC-275 Set service role in .ebextensions

---

.ebextensions/01_create_apache_conf.config
boac/routes.py
config/default.py
config/development.py
config/test.py
gulpfile.js
package.json
tox.ini

https://jira.ets.berkeley.edu/jira/browse/BOAC-355
Note: In process of eb-deploy, we rev our static files before the `bower install`; that's a good thing, I believe.

BOAC-355, each AWS deploy will get a new rev of js and css files

---

.ebextensions/01_create_apache_conf.config

https://jira.ets.berkeley.edu/jira/browse/BOAC-355
I've added same snippet used in bower_install step.
See failed deploy due to 'node not found': https://us-west-2.console.aws.amazon.com/codepipeline/home?region=us-west-2#/view/boac-dev

BOAC-355, install node before npm install > gulp dist

---

.ebextensions/01_create_apache_conf.config

https://jira.ets.berkeley.edu/jira/browse/BOAC-355
Follow up to PR #298  
See [latest CP deploy failure](https://us-west-2.console.aws.amazon.com/codepipeline/home?region=us-west-2#/view/boac-dev)
If this does not fix the problem then I intend to revert the commits to unblock boac-dev.

BOAC-355, 'npm install -g gulp' to avoid command not found

---

.ebextensions/01_create_apache_conf.config
.ebextensions/12_bower_install.config
buildspec.yml

https://jira.ets.berkeley.edu/jira/browse/BOAC-355
Okay, one last try – I'm hoping `--allow-root` is the secret sauce. And, I neglected to include necessary `gulpfile.js` in buildspec.
If does not work, I'll revert, set up my own pipeline, get it right and then submit proper PR.

BOAC-355, gulp dist --allow-root in same block as other npm installs

---

boac/models/development_db.py
boac/models/student.py
boac/static/app/cohort/cohortController.js
tests/test_api/test_athletics_controller.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_user_controller.py
tests/test_merged/test_sis_profile.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-370
Most of the diff is under `tests`.  Front-end no longer passes 'group_code'.

BOAC-370, order by group_name, not group_code

---

boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-360
`auto-close=outsideClick` works on initial page load cuz DOM is in order. But, due to `ng-if`, the DOM is tweaked post-search and a click on menu-options is seen as an "outsideClick".

BOAC-360, Angular ui-bootstrap needs menu-options in DOM for auto-close=outsideClick to work

---

boac/static/app/auth/authFactory.js
boac/static/app/auth/authService.js
boac/static/app/cohort/allCohortsController.js
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/manageCohortsController.js
boac/static/app/landing/landing.html
boac/static/app/landing/landingController.js
boac/static/app/routes.js
boac/static/app/student/studentController.js

A robust fix for https://jira.ets.berkeley.edu/jira/browse/BOAC-332 requires introducing a pattern where login status is checked on every front-end state change. The standard way of doing this in ui-router 0.x is with resolvers:
https://github.com/angular-ui/ui-router/wiki#resolve
An advantage of the resolver pattern is that it makes authentication entirely the responsibility of routes.js, so we don't have to remember to include auth wrapping in our controllers.

BOAC-332 Integrate authentication with ui-router

---

boac/models/student.py

Hard to be sure this will address https://jira.ets.berkeley.edu/jira/browse/BOAC-375, but let's give it a shot. The best guide I've found on the rather confusing SQLAlchemy connection interface is here:
https://stackoverflow.com/questions/34322471/sqlalchemy-engine-connection-and-session-difference
and the rule of thumb seems to be that the connection should stay open as long as you're directly interacting with the result set, but no longer.

BOAC-375 Keep db connection open while iterating through results

---

boac/api/cohort_controller.py
boac/api/user_controller.py
boac/externals/calnet.py
boac/merged/calnet.py
boac/models/authorized_user.py
boac/static/app/cohort/all.html
boac/static/app/cohort/allCohortsController.js
boac/static/app/shared/header.html
tests/test_api/test_cohort_controller.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-377
https://jira.ets.berkeley.edu/jira/browse/BOAC-369
Profile data of `authorized_users` is pulled from CalNet. Benefit to the customer: 'Everyone's Cohorts' page displays names, not UIDs.

BOAC-377, get_calnet_user_for_uid used by '/api/cohorts/all' and '/api/profile'

---

boac/static/app/cohort/manageCohorts.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-264
Ordering by `labelOriginal` rather than `label` ensures that resorting happens only once the 'Rename' button is clicked, not while the user is typing.

BOAC-264 Update Manage Cohorts sort order on rename

---

.ebextensions/01_create_apache_conf.config
boac/static/app/main.css
boac/static/app/maintenance.html
gulpfile.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-251
* I'm using placeholder image: http://cuddlebuggery.com/wp-content/uploads/2012/05/TV-error-signal.png
* `maintenance.html` is in `boac/static/app` because it's convenient w.r.t  Apache config and existing `gulp dist` action. 
* Handles status codes:
** 502 Bad Gateway
** 503 Service Unavailable
** 504 Gateway Timeout
** Should we include 500s?

BOAC-251, maintenance page when HTTP status code 502, 503 or 504

---

.ebextensions/03_download_local_configuration.config
boac/api/config_controller.py
tests/test_api/test_config_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-385
`EB_ENVIRONMENT` is put to production-local.py at deploy time. The value of that config:
* surfaces in `/api/config`
* will be used by upcoming BOAC-385 script
See `ebEnvironment` in https://asc-pilot-dev.berkeley.edu/api/config  (deployed with my CodePipeline)

BOAC-385, put EB_ENVIRONMENT in config file (03_download_local_configuration)

---

boac/static/app/cohort/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-403
Unlike search and sortBy, the URL change when you click to 'matrix' view is not recorded in browser history. We must use an explicit `$location.state(url)`.

BOAC-403, put URL to history before matrix view > student profile

---

boac/api/advisor_watchlist_controller.py
boac/api/alerts_controller.py
boac/api/cohort_controller.py
boac/lib/util.py
boac/models/alert.py
boac/models/authorized_user.py
boac/models/cohort_filter.py
boac/models/student.py
tests/conftest.py
tests/test_api/test_advisor_watchlist_controller.py
tests/test_api/test_alerts_controller.py
tests/test_api/test_cohort_controller.py

As arrived at in https://jira.ets.berkeley.edu/jira/browse/BOAC-441, this more or less flips the role of our "AlertView" association objects. Instead of explicitly associating advisors with displayed alerts, they are now used only to explicitly dismiss alerts for a particular advisor.
Since the latest designs bundle in alert counts on the homepage with cohort and list displays, we can use cohort and list memberships to work out alert visibility logic on the fly, and can dispense with a separate '/api/alerts/current' feed. (Per-student alert feeds are still useful and present.)

BOAC-441 Per-advisor alert visibility logic

---

boac/__init__.py
boac/api/cache_utils.py
boac/api/user_controller.py
boac/api/util.py
boac/lib/analytics.py
boac/merged/member_details.py
boac/models/alert.py
tests/test_api/test_alerts_controller.py
tests/test_api/test_cache_utils.py
tests/test_lib/test_analytics.py
tests/test_models/test_alert.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-411 has subtasks, but I could figure out no clever and clean way to split up the work into separate PRs.

BOAC-411 Derive student status alerts from assignment analytics

---

boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortService.js
boac/static/app/cohort/createCohortController.js
boac/static/app/shared/utilService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-466
The goal: Angular directive to render cohort-view dropdown. In order to have such a directive we must standardize property naming in menu options. Eg, `option.id` that plays nice in `<input id="team-{{option.id}}" />`

BOAC-466, menu options on cohort view get property-naming convention

---

boac/static/app/user/watchlistToggle.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-472
Per https://github.com/twbs/bootstrap/issues/11359, Firefox doesn't like tooltips on elements within buttons.

BOAC-472 Move tooltip from icon to button element

---

boac/static/app/student/findStudentFilter.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-469
See https://siderite.blogspot.com/2011/11/careful-when-reusing-javascript-regexp.html on this gotcha when using JavaScript global regexes; a secret index state persists from one test to the next and leads to all kinds of unexpected behavior. Since our filter is performing a simple yes-or-no test, it shouldn't need to worry about multiple matches.

BOAC-469 No global regex in user search filter

---

boac/static/app/student/courseSiteMetricsDirective.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-485
Sometimes I feel AngularJS 1 pushes us into unnecessary replication. This isn't one of those times.

BOAC-485 Drop "Participations" metrics from the UX

---

boac/lib/util.py
boac/models/student.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-488
Using GROUP BY instead of DISTINCT preserves our ordering logic but de-duplicates within SQL. This eliminates the need for an extra function and ensures that de-duplication works across pagination offsets.

BOAC-488 De-duplicate sids within students query

---

boac/models/athletics.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-497
On the front-end, if feed does not have 'name' property then it defaults to 'value'. So, name = groupName (according to feed).

BOAC-497, 'name' is 'groupName' in team_groups feed

---

.ebextensions/03_download_local_configuration.config
scripts/deploy_boac_config.sh

https://jira.ets.berkeley.edu/jira/browse/BOAC-496
This change should go unnoticed, except that one will have to use `sudo` to view the file when logged into an instance as ec2-user.

BOAC-496 Tighten permissions on local config file

---

boac/lib/analytics.py
boac/lib/util.py
boac/models/alert.py
tests/test_api/test_cache_utils.py
tests/test_lib/test_analytics.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-521
This PR inserts more stringent criteria for what counts as a late or missing assignment, in an attempt to screen out false positives as discovered in https://jira.ets.berkeley.edu/jira/browse/BOAC-519.
If the code passes muster and is merged, I'd like to follow it up with a cache refresh on boac-dev. We should then be able to take a broad look at which alerts survived the cull, and decide on this feature's fate for the sprint.

BOAC-521 Tighten criteria for assignment alerts

---

boac/static/app/main.css
boac/static/app/shared/header.html
boac/static/app/student/student.html
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-528
The `hideFeedbackLink` is pretty cheesy, but alternative approaches I considered brought in too many redundancies for comfort. Let me know if you'd rather have the duplications, or if you see a better way.

BOAC-528 Display feedback link

---

boac/static/app/student/student.css
boac/static/app/student/student.html
boac/static/app/student/studentController.js
bower.json

https://jira.ets.berkeley.edu/jira/browse/BOAC-490
Darker blue for cumulative units, lighter blue for units in progress, no warning indicators until we have a better idea of what the criteria should be.

BOAC-490 Student profile: unit totals progress bar

---

boac/auth/cas_auth.py
boac/lib/http.py
boac/static/app/student/studentController.js

Fix for the reopened https://jira.ets.berkeley.edu/jira/browse/BOAC-468; and because there's always something extra, make sure the added CAS login param doesn't leak into constructed return URLs.

BOAC-468 CAS redirect: parse URLs right

---

boac/static/app/student/student.css
boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-550
I used "always open" accordion block as seen at https://angular-ui.github.io/bootstrap/

[QA] BOAC-550, group dropped sections in last row of course list, per term

---

boac/static/app/student/student.html
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-554
We decorate the list of `unmatched` and then combine it with `term.enrollments`.  A dozen fewer lines in the template.

[QA] BOAC-554, unmatchedCanvasSites rendered with same template code as term.enrollments

---

boac/api/course_controller.py
boac/merged/member_details.py
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/course/course.html
boac/static/app/course/courseController.js
boac/static/app/shared/boxplotService.js
tests/test_api/test_athletics_controller.py
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-533
* `member_details.merge_all` now has optional `term_id` arg (relevant to cache-key)
* front-end `drawBoxplot` logic is now shared 
* designs: https://jira.ets.berkeley.edu/jira/browse/BOAC-394

BOAC-533, class page > list view gets columns similar to cohort view

---

boac/models/normalized_cache_enrollment.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-583
Bulk deletion with SQL Alchemy has some gotchas according to [their own docs](http://docs.sqlalchemy.org/en/latest/orm/query.html#orm-specific-query-constructs) (see section on `delete synchronize_session=False`). I've encountered no such `IntegrityError` locally but boac-dev is a much better load test on this code. We want guaranteed order of operations: delete then add.

BOAC-583, commit the db delete before proceeding to db inserts

---

boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/shared/boxplotService.js
boac/static/app/student/student.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-569
The change in cohortController fixes a small bug: we had a stranded call to `drawBoxplots()` – not evident in the diff below. Furthermore, the function does not need to live in `utilService`.

BOAC-569, avatar-large for list view; fix drawBoxplots() ref

---

boac/api/cache_utils.py
boac/merged/sis_enrollments.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-584
From local testing, it looks like NormalizedCacheEnrollment logic can get expensive when run in series on many students in a cohort. We should get performance improvements by treating it like other normalized cache tables, updating only when a cache reload updates the source data.

BOAC-584 Stow and preload merge_enrollments

---

boac/static/app/cohort/cohort.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-592
Because the matrix/list toggle is a `data-ng-show` for d3 reasons, the boxplot directive needs an extra `data-ng-if` so it knows not to draw when it's not there.

BOAC-592 Restrict cohort boxplot directive to draw in list mode only

---

boac/api/course_controller.py
boac/lib/analytics.py
boac/lib/berkeley.py
boac/merged/member_details.py
boac/merged/sis_enrollments.py
boac/static/app/course/course.css
boac/static/app/course/course.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-581
Do not show canvas-course-code if section id maps to a single canvas course site (ccn). Such filtering is used when calculating 'Average Student' numbers – still a work in progress.

BOAC-581, class page > filter canvas_sites per section id

---

boac/static/app/cohort/cohortController.js
boac/static/app/cohort/cohortFilterDropdown.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-622
Sneaky bonus fix: `fa-spinner` and `fa-chevron-down` cannot coexist on the page.

[QA] BOAC-622, cohort 'level' dropdown must pre-pop with 'value' compare

---

boac/lib/http.py
boac/lib/mockingbird.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-626
Sharing the generic part of ets-berkeley-edu/nessie#6 back to BOAC.

BOAC-626 Add library support for non-GET HTTP methods

---

boac/lib/mockingbird.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-626
Small but important follow-up to #508; the no-op mock (used in non-test environments) has to take `kwargs` or the `method` keyword will blow it up.

BOAC-626 No-op mock needs no-op kwargs

---

boac/api/advisor_watchlist_controller.py
boac/models/authorized_user.py
boac/models/db_relationships.py
boac/models/development_db.py
boac/models/student.py
boac/models/student_group.py
scripts/db/drop_schema.sql
scripts/db/migrate/20180327-BOAC-613/01_create_student_groups_tables.sql
scripts/db/migrate/20180327-BOAC-613/02_copy_advisor_lists_to_student_groups_table.py
scripts/db/migrate/20180327-BOAC-613/03_drop_advisor_watchlists_table.sql
scripts/db/schema.sql
tests/test_api/test_advisor_watchlist_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-613
* Flint and l settled on `student_groups`. Using `list` in the name is vague and overlaps with `cohort` def'n
* Although we're dropping the `advisor_watchlists` table, the `/api/watchlist*` endpoints will be supported in the interim.
* All the TODOs will be dealt with soon.

BOAC-613, backend support for student_groups to replace 'watchlist'

---

boac/api/advisor_watchlist_controller.py
boac/models/student_group.py
tests/test_api/test_advisor_watchlist_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-653
Bonus: `/api/group/<group_id>` added and test coverage on reported bug.

BOAC-653, student-groups backend must account for empty watchlists during transition

---

boac/static/app/home/sortableAlertsTable.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-708
Apparently ordering needs to come before tracking or Angular gets flummoxed.

BOAC-708 Fix ordering/tracking in cohort summary lists

---

boac/static/app/nav/nav.css
boac/static/app/nav/sidebar.html
boac/static/app/nav/sidebarNavController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-742
Using CSS lets us specify pixel width rather than character count, catching out even the fattest of characters.

BOAC-742 CSS handling for text overflow in sidebar

---

boac/static/app/nav/nav.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-747
We apologize for the earlier mechanical issue and look forward to serving you in the clouds.

BOAC-747 Wide text was still too wide

---

boac/api/user_controller.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-760
BOAC assumes 'My Students' is _always_ present. This PR does not change the `/api/profile` contract; it simply instantiates `myPrimaryGroup` in a more certain way.

[QA] BOAC-760, auto-create 'My Students' if not exists, for all users

---

boac/api/user_controller.py
boac/api/util.py
boac/models/db_relationships.py
boac/models/development_db.py
boac/models/university_dept.py
scripts/db/drop_schema.sql
scripts/db/migrate/20180418-BOAC-782/post_deploy_01_drop_authorized_users_column_is_advisor.sql
scripts/db/migrate/20180418-BOAC-782/pre_deploy_01_create_university_depts_table.sql
scripts/db/migrate/20180418-BOAC-782/pre_deploy_02_migrate_asc_advisors.py
scripts/db/migrate/20180418-BOAC-782/pre_deploy_02_migrate_asc_advisors.sh
scripts/db/schema.sql
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-782
The `authorized_users` table remains but `is_advisor` and `is_director` have been moved to `university_dept_members` table, which maps users to departments (code, name). ASC advisors will map to 'UWASC',  EE/CompSci to 'EHEEC', etc. Admin users (eg, PDGers) are in with `authorized_users.is_admin=true` and no dept mapping.

BOAC-782, an authorized_user can belong to zero or more university_depts

---

boac/api/status_controller.py
boac/static/app/cohort/cohort.html
boac/static/app/course/course.css
boac/static/app/course/course.html
boac/static/app/main.css
boac/static/app/routes.js
boac/static/app/shared/googleAnalyticsService.js
boac/static/app/student/student.css
boac/static/app/student/student.html
boac/static/app/user/authFactory.js
boac/static/app/user/authService.js
tests/test_api/test_status_controller.py
tests/test_auth/test_dev_auth.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-780
Tossing `authenticated_as` out of the `/api/status` response reduces front-end confusion a bit.

BOAC-780, give '/api/status' a conventional and sensible response.json

---

boac/api/student_groups_controller.py
boac/api/util.py
boac/static/app/group/group.html
boac/static/app/group/studentGroupService.js
boac/static/app/home/home.html
boac/static/app/nav/nav.css
tests/test_api/test_student_groups_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-806
https://jira.ets.berkeley.edu/jira/browse/BOAC-808
Continuing on from #592:
- Remove unused CSS;
- Groups on the homepage only list students with alerts;
- Clear out more obsolete "group" terminology.

BOAC-806 BOAC-808 Further cleanup on cohort/group refactor

---

boac/api/athletics_controller.py
boac/api/cohort_controller.py
boac/api/course_controller.py
boac/api/student_groups_controller.py
boac/api/user_controller.py
boac/merged/calnet.py
boac/merged/student_details.py
boac/models/athletics.py
boac/models/cohort_filter.py
boac/static/app/cohort/all.html
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/manageCohorts.html
boac/static/app/cohort/teams.html
boac/static/app/group/group.html
boac/static/app/group/groupsSelectorDirective.js
boac/static/app/group/manageGroups.html
boac/static/app/home/home.html
boac/static/app/nav/sidebar.html
boac/static/app/nav/sidebarNavController.js
boac/static/app/search/searchResults.html
tests/test_api/test_athletics_controller.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-807
We have filtered cohorts and curated cohorts; let's have consistent naming given that they both contain students.  The word 'member' is reserved for `university_dept_members` usage.

BOAC-807, consistent naming fix: cohorts have students and depts have members

---

boac/api/student_groups_controller.py
boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortFactory.js
boac/static/app/cohort/cohortFilterDropdown.html
boac/static/app/cohort/createCohortController.js
boac/static/app/cohort/createCohortModal.html
boac/static/app/cohort/deleteCohortModal.html
boac/static/app/cohort/manageCohorts.html
boac/static/app/cohort/manageCohortsController.js
boac/static/app/course/course.html
boac/static/app/group/createGroupController.js
boac/static/app/group/createGroupModal.html
boac/static/app/group/deleteGroupModal.html
boac/static/app/group/group.html
boac/static/app/group/groupsSelector.html
boac/static/app/group/groupsSelectorDirective.js
boac/static/app/group/manageGroups.html
boac/static/app/group/manageGroupsController.js
boac/static/app/home/home.html
boac/static/app/nav/sidebar.html
boac/static/app/nav/sidebarNavController.js
boac/static/app/search/searchResults.html
boac/static/app/shared/validationService.js
boac/static/app/student/student.html
boac/static/app/user/authService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-812
https://jira.ets.berkeley.edu/jira/browse/BOAC-825
https://jira.ets.berkeley.edu/jira/browse/BOAC-830
https://jira.ets.berkeley.edu/jira/browse/BOAC-829
* sensible `ids` for Teena
* bye-bye "Groups"
* `authService` now listens for all cohort create/delete/rename events

BOAC-829/BOAC-830, replace term 'group' in text and element ids

---

boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/course/course.html
boac/static/app/group/groupsSelector.html
boac/static/app/group/groupsSelectorDirective.js
boac/static/app/home/sortableAlertsTable.html
boac/static/app/home/sortableAlertsTableDirective.js
boac/static/app/search/searchResults.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-861
Some added insurance to this feature:
* do not render `curated-cohort-selector` until students have loaded
* `event.stopPropagation()` in case of cross-browser differences
* put the `toggle` function on each student instance, to guarantee its presence

BOAC-861, curated-cohort-selector must behave across browsers, result-sets

---

boac/api/course_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-871
Subtle and annoying gotcha: if a dict key exists but has `None` value, Python `get` will return `None` rather than using the provided fallback.

BOAC-871 Falsey check for student term in course controller

---

boac/lib/analytics.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_user_controller.py
tests/test_lib/test_analytics.py

We hope to eliminate our dependency on the expensive Canvas `analytics/student_summaries` API:
https://jira.ets.berkeley.edu/jira/browse/BOAC-873
https://jira.ets.berkeley.edu/jira/browse/BOAC-793
This PR just clears a little noise out of the way.

NOJIRA Remove unused "participations" metric

---

boac/lib/analytics.py
boac/static/app/cohort/cohort.html
boac/static/app/course/course.html
boac/static/app/group/group.html
boac/static/app/main.css
boac/static/app/shared/boxplotService.js
boac/static/app/shared/matrix.css
boac/static/app/shared/matrix.html
boac/static/app/student/student.html
boac/static/app/visual/visualizationService.js
tests/test_api/test_cohort_controller.py
tests/test_api/test_user_controller.py
tests/test_lib/test_analytics.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-793
I expect we'll revisit the matrix view design. Next step: plug in real "days since" data.

BOAC-793, swap out page-views on the front-end; prep for days-since-course-site-visited metric

---

boac/externals/data_loch.py

https://jira.ets.berkeley.edu/jira/browse/LA-448
The corresponding Nessie change: https://github.com/ets-berkeley-edu/nessie/pull/42

LA-448, data_loch view 'user_course_scores' was renamed

---

boac/api/cache_utils.py
boac/merged/sis_enrollments.py
boac/models/normalized_cache_enrollment.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-906
Clean up some garbage from https://github.com/ets-berkeley-edu/boac/pull/655 .
* Obsolete call from cache_utils.
* Missed section de-duplication on the way to NormalizedCacheEnrollment.

BOAC-906 Fixes for cache management

---

bower.json

https://jira.ets.berkeley.edu/jira/browse/BOAC-903
Angular seems to have a bug in 1.7.0; related to https://github.com/angular/angular/issues/9275? I'm locking us down at 1.6.10. I believe the other minor upgrades (eg, lodash) are safe.

BOAC-903, lock down bower dependencies (angular, bootstrap)

---

boac/lib/analytics.py
tests/test_lib/test_analytics.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-917
An incomplete test gave us too much confidence in that reasonable-looking code.

BOAC-917 Null last_activity_at should be falsey

---

boac/merged/sis_sections.py
tests/test_merged/test_sis_sections.py

QA version of https://github.com/ets-berkeley-edu/boac/pull/669
Because throwing a 500 for every online course makes BOAC look like a fuddy-duddy old stick-in-the-mud.

[QA] BOAC-923 Online courses typically lack start/end times

---

boac/api/cache_utils.py
boac/merged/sis_enrollments.py
boac/merged/sis_profile.py
boac/models/json_cache.py
boac/models/normalized_cache_enrollment.py
boac/models/normalized_cache_student.py
tests/conftest.py
tests/test_api/test_cache_utils.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_course_controller.py
tests/test_api/test_student_groups_controller.py
tests/test_merged/test_sis_enrollments.py
tests/test_merged/test_sis_profile.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-943
A lot of files are touched here, but I hope the principle is clear enough: normalized cache load and alert load move up into `boac.api.cache_utils`, and tests come along for the ride.

BOAC-943 Disentangle external cache load from application-specific table updates

---

boac/api/cache_utils.py
boac/merged/calnet.py
boac/merged/import_asc_athletes.py

Step one of https://jira.ets.berkeley.edu/jira/browse/NS-100
When the code first deploys, the CalNet merge will usually be redundant effort since it's also done in the Import ASC Students task. But because the entire long chain of student updates and refreshes will be refactored in this sprint, I don't expect it to stay redundant for long. If you prefer that I eliminate the duplication now, just let me know.

NS-100 Move CalNet load up into cache_utils for easier relocation

---

boac/externals/sis_enrollments_api.py

https://jira.ets.berkeley.edu/jira/browse/NS-87
Following #680, our cache load is looping through `sis_enrollments_api.drops_and_midterms` twice. First, explicitly, here:
https://github.com/ets-berkeley-edu/boac/blob/e5f0a1c2bf38b153211cf4cdfb594ce3a9ac71be/boac/api/cache_utils.py#L322
And second, as part of `merged.sis_enrollments.merge_sis_enrollments_for_term`:
https://github.com/ets-berkeley-edu/boac/blob/e5f0a1c2bf38b153211cf4cdfb594ce3a9ac71be/boac/api/cache_utils.py#L340
https://github.com/ets-berkeley-edu/boac/blob/e5f0a1c2bf38b153211cf4cdfb594ce3a9ac71be/boac/merged/sis_enrollments.py#L60
Since the merge is so complex overall and is going to get refactored anyway, probably the easiest thing for the moment is to add a `@stow` to prevent duplicate API calls.

NS-87 Stow drops and midterms from SIS enrollments API

---

boac/api/cohort_controller.py
boac/api/search_controller.py
boac/api/user_controller.py
boac/api/util.py
boac/models/cohort_filter.py
boac/models/student.py
tests/test_api/test_cohort_controller.py
tests/test_models/test_cohort_filter.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-987
* Decoration in cohort_filter model puts undue work on simple operations (eg, delete) and tests. Ultimately, only controllers need students, alerts, etc. added to a cohort_filter instance.
* We will give COE advisors access to their students with read-only cohort_filters configured with criteria `coe_advisor_uid=12345`

BOAC-987, coe_advisor_uid added to cohort_filter options; decorate in cf model moved to controller level

---

boac/api/cohort_controller.py
boac/api/util.py
boac/lib/berkeley.py
boac/models/development_db.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-986
And, only COE advisors can leverage the `coeAdvisorUid` criteria.

BOAC-990, cohort defined by coeAdvisorUid alone is read-only

---

boac/api/util.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1014
This impacts student lists on both class and group pages.

BOAC-1014, default student sort order is last_name, first_name

---

boac/static/app/cohort/cohort.html
boac/static/app/cohort/cohortController.js
boac/static/app/cohort/createCohortController.js
boac/static/app/student/studentSearchService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1053
`cohortController.js` is too complex and the problem worsened with `advisorLdapUid` logic. The code is more manageable when all checkboxes follow a similar pattern.

BOAC-1053, consistent pattern for managing checkboxes on /cohort search

---

boac/static/app/cohort/cohort.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1053
`data-ng-checked` replaces `data-ng-model` in this new checkbox pattern.

BOAC-1053, inactive checkbox must use data-ng-checked pattern (missed in previous PR)

---

boac/api/athletics_controller.py
tests/test_api/test_athletics_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1058
The one and only call to the `/api/team_groups/all` feed is baked into the `cohortController.js` logic. Although team data does not surface to COE advisors, they are being impacted by the 404. The safest fix, given our release schedule, is to return an empty list to unauthorized users and keep the response.status at 200.

BOAC-1058, /api/team_groups/all returns empty list for unauthorized users

---

.ebextensions/00_ami.config

https://jira.ets.berkeley.edu/jira/browse/BOAC-1065
Expect it to match what is on `master` and `qa`: (https://github.com/ets-berkeley-edu/boac/blob/qa/.ebextensions/00_ami.config)

[release] BOAC-1065, 00_ami.config gets new security-group setting for custom VPC

---

.ebextensions/00_ami.config

https://jira.ets.berkeley.edu/jira/browse/BOAC-1087
`arn` grabbed from https://jira.ets.berkeley.edu/jira/browse/BOAC-1083

BOAC-1087, new SSL cert for boac.berkeley.edu

---

scripts/db/migrate/20180809-BOAC-1147/create_my_students_cohort_per_uid.sh

https://jira.ets.berkeley.edu/jira/browse/BOAC-1147
Shell script invokes the mandatory `source /opt/python/current/env && env`

[QA] BOAC-1147, shell script wraps create_my_students_cohort_per_uid.py script

---

.eslintrc.yml
boac/static/app/cohort/_filtered/cohortController.js
boac/static/app/cohort/_filtered/filterCriteria.html
boac/static/app/cohort/_filtered/filterCriteriaComponent.js
boac/static/app/cohort/_filtered/filterCriteriaService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1079
A little restructuring. Added TODO: do not re-init dropdown options in updateFilters.

BOAC-1079, button show/hide updated by redraw in scope.watch

---

boac/static/app/cohort/_filtered/filterCriteriaService.js
boac/static/app/cohort/filtered/cohortController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1149
The BOAC-1149 fix was in PR #795 and yet while verifying I discovered `$scope` usage in `filterCriteriaService`. This puts that bit of legacy code back in legacy controller.

BOAC-1149, legacy select-majors-filter belongs in legacy controller

---

boac/externals/data_loch.py
boac/merged/athletics.py
fixtures/loch.sql
tests/test_api/test_athletics_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1145
https://jira.ets.berkeley.edu/jira/browse/BOAC-1158
No impact on ASC's exclude-inactives-in-search requirement but it does bring Big (Junk) Data to the "Teams" dropdown.

BOAC-1145, do not omit ASC team-groups with zero active students

---

boac/static/app/cohort/filtered/filterCriteriaFactory.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1185
Three-valued logic strikes again!
Setting ASC intensive or inactive to `false` rather than `null` introduces an ASC criterion into the mix and limits the result set to ASC students.
We want inactives to be excluded by default for ASC users but not admins.
We don't want intensives to be excluded by default for anyone.
@johncrossman should make sure this makes sense.

BOAC-1185 Default value fixes for ASC criteria

---

boac/externals/data_loch.py
boac/merged/student.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1198
Since the lack of this logic causes frequent errors in the admin view, it seems worth getting in before any more departments are folded in.

BOAC-1198 Handle intersection of filter criteria from multiple departments

---

boac/static/app/cohort/cohort.css
boac/static/app/cohort/filtered/filterCriteria.html
boac/static/app/cohort/filtered/filterCriteriaComponent.js
boac/static/app/home/home.html
boac/static/app/routes.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1201
https://jira.ets.berkeley.edu/jira/browse/BOAC-1188
Relying on listeners to redraw all buttons risks strange and unwanted show/hide behavior.
This includes removal of 'Manage Cohorts' from home and flex-width tweak in added-filter rows.

BOAC-1201, simplify redrawButtons in filterCriteriaComponent

---

boac/static/app/athletics/teams.html
boac/static/app/athletics/teamsController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1190
`totalStudentCount` will be inaccurate for Football because a SID might be double counted if student is on two squads. IMO, fixing this is not worth the effort.

BOAC-1190, fix Teams page and remove its inaccurate totalStudentCount

---

boac/static/app/cohort/filtered/cohort.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1199
Ironically, the `uib-pagination` element intended for only list-view had a faulty `ng-if` and never rendered. The second `uib-pagination` (how'd we get two?!) was showing up on both list and matrix view. I fixed the former and tossed out the latter.

BOAC-1199, remove stray and unnecessary uib-pagination

---

boac/logger.py

https://jira.ets.berkeley.edu/jira/browse/NS-223
I think what's going on here is that under Flask 0.x, the app logger and root Python logger kept a respectful distance, but under Flask 1.x they're confederates in the same hierarchy and may be functionally the same thing. We'll see if this helps out boac-dev.
<s>For some reason, this change requires reverting the test changes that were, for some reason, required in #873.</s>

NS-223 Call no logger by multiple names

---

boac/models/alert.py
fixtures/loch_student_enrollment_term_3456789012_2178.json
fixtures/loch_student_enrollment_term_5678901234_2178.json
tests/test_models/test_alert.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1245
Activity alerts are now keyed by term id + course display name rather than Canvas site id.

BOAC-1245 No duplicate activity alerts for multiple course sites under same enrollment

---

boac/lib/analytics.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1299
To venture onto BOAC-1272's turf, most of the examples I've found have greater-than-zero rounded-up percentiles.

BOAC-1299 Zero-percentiles are still legitimate data

---

boac/static/app/shared/googleAnalyticsService.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1310
Notice the `asycn` in `index.html`:
```
<script async src='https://www.google-analytics.com/analytics.js'></script>
```
Do not use 'ga' until the async is done.

BOAC-1310, no googleAnalytics without 'ga'

---

boac/lib/berkeley.py
boac/models/alert.py
fixtures/loch_student_enrollment_term_11667051_2178.json
tests/test_api/test_filtered_cohort_controller.py
tests/test_api/test_student_controller.py
tests/test_lib/test_berkeley.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1324
A query of `intermediate.course_sections` (Redshift) view for 'GRP' sections and catalog_id pattern (below) returns only 'group study' and 'directed study' sections. I believe this fits with the requirement. A second pair of eyes is welcome.
Use `?w=1` for an easier diff read.

BOAC-1324, no alerts for DeCal courses (directed/group study)

---

boac/static/app/home/home.html
boac/static/app/home/sortableAlertsTable.html
boac/static/app/home/sortableAlertsTableDirective.js
boac/static/app/search/searchResults.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1333
This should help homepage perf a bit; lazy-loading students on-cohort-click would be a real winner, methinks.

BOAC-1333, no student avatars on homepage listings

---

.ebextensions/01_create_apache_conf.config

https://jira.ets.berkeley.edu/jira/browse/BOAC-1174
Having heard no howls of protest at https://jira.ets.berkeley.edu/jira/browse/BOAC-1399, I'd like to see if this makes any difference when BOAC is serving multiple sessions with lots of photos.

BOAC-1174 Increase thread count in WSGI process

---

boac/static/app/cohort/curated/selector.html
boac/static/app/cohort/curated/selectorComponent.js
boac/static/app/cohort/filtered/cohort.html
boac/static/app/course/course.html
boac/static/app/home/sortableAlertsTable.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1403
I think the reported bug had to do with browser-specific conflicts between ng-model binding and explicit ng-click calls.

BOAC-1403 ng-change listeners for ng-model bound checkboxes

---

boac/static/app/cohort/curated/cohort.html
boac/static/app/cohort/curated/cohortController.js
boac/static/app/cohort/curated/createModal.html
boac/static/app/cohort/curated/deleteModal.html
boac/static/app/cohort/curated/manage.html
boac/static/app/cohort/curated/selector.html
boac/static/app/cohort/curated/selectorComponent.js
boac/static/app/cohort/filtered/cohort.html
boac/static/app/cohort/filtered/createModal.html
boac/static/app/cohort/filtered/deleteModal.html
boac/static/app/course/course.html
boac/static/app/home/home.css
boac/static/app/home/home.html
boac/static/app/home/sortableAlertsTable.html
boac/static/app/nav/sidebar.html
boac/static/app/routes.js
boac/static/app/student/student.css
boac/static/app/student/student.html

https://jira.ets.berkeley.edu/jira/browse/BOAC-1308
Designs: https://jira.ets.berkeley.edu/jira/browse/BOAC-1238
User-facing text is changed to match the new "cohort"/"curated group" distinction, but I didn't go down the road of changing paths, filenames, variables, etc., since we expect Vue to have its own opinion on such things before long.

BOAC-1308 Simplify cohort sidebar navigation

---

buildspec.yml

https://jira.ets.berkeley.edu/jira/browse/BOAC-1440
See available CodeBuild docker images:
https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html

BOAC-1440, vue-cli-service requires Node >=8; update buildspec

---

buildspec.yml

https://jira.ets.berkeley.edu/jira/browse/BOAC-1442
As you might assume, `gulp dist` was blowing away the dist dir. I look forward to ditching gulp.

BOAC-1442, order of build commands (buildspec) matters; gulp dist comes first

---

boac/static/app/nav/nav.css
src/components/HeaderMenu.vue
src/components/curated/CuratedGroupSelector.vue
src/components/curated/CuratedStudentCheckbox.vue
src/components/search/SortableStudentRow.vue
src/components/search/SortableStudents.vue
src/components/sidebar/SearchStudents.vue
src/components/student/StudentAvatar.vue
src/layouts/StandardLayout.vue
src/main.ts
src/views/Search.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-1494
In `main.ts` you'll see `Vue.prototype.$eventHub = ...`. This eventHub pattern is described in
https://vuejs.org/v2/guide/migration.html (see "...when communicating between distant descendants/ancestors..."). For reasons described in that documentation, I decided against both:
1. the "new in Vue 2.3.0+" `$sync` modifier; see [Binding-Native-Events-to-Components](https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components)
2. Vuex store
Although the CuratedGroupSelector component is far from finished, the event handling is working. 
This PR includes a minor UI fix to the nav menu in header.

BOAC-1494, Vue component to add students to curated group (eg, in context of search results)

---

boac/api/curated_cohort_controller.py
boac/routes.py
boac/static/app/nav/sidebarNavComponent.js
config/test.py
package-lock.json
package.json
requirements.txt
src/api/cohorts.ts
src/components/sidebar/CuratedGroups.vue
src/main.ts
src/router.ts
src/store.ts
src/views/group/CuratedGroup.vue
src/views/group/CuratedGroups.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-1477
I added the [Flask-Cors](https://flask-cors.readthedocs.io/en/latest/) library to handle cross-origin requests from Vue components (localhost:8080) to APIs (localhost:5000).  GET, POST, and OPTIONS can be handled without it, but DELETE and PUT require the `Content-Type` header to be explicitly set.

BOAC-1468: Rewrites curated group page header in Vue

---

boac/__init__.py

The `qa` branch (v2.10) was cut moments ago.

NOJIRA, BOAC master branch is now v2.11

---

src/api/cohort.ts
src/api/curated.ts
src/components/curated/CuratedGroupHeader.vue
src/components/curated/CuratedGroupList.vue
src/components/curated/CuratedGroupSelector.vue
src/views/cohort/AllCohorts.vue
src/views/group/CuratedGroup.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-1525
The `/cohort` view is coming soon and we'll need a dedicate client-side file for cohort api calls.

BOAC-1525, separate 'curated' and 'cohort' in front-end /api structure

---

boac/api/curated_cohort_controller.py
boac/api/filtered_cohort_controller.py
boac/api/user_controller.py
boac/api/util.py
tests/test_api/test_curated_cohort_controller.py
tests/test_api/test_filtered_cohort_controller.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1539
The Vue front-end will load user profile and cohorts/groups separately. The key benefit is a more manageable front-end store. If we plan to add/remove/rename cohorts then I'd like to detach them from the user object. Also, a faster `/profile/my` causes certain page elements (eg, header-menu) to load more quickly.  This has no impact on Angular side of things.

BOAC-1539, 'excludeCohorts' option in /api/profile/my if front-end wants data modularity

---

src/components/curated/CuratedGroupStudent.vue
src/mixins/StudentMetadata.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-1493
The trouble with mixins! We also have a `lastActivityDays` method over in https://github.com/ets-berkeley-edu/boac/blob/master/src/mixins/StudentAnalytics.vue, which is distinguished from StudentMetadata.vue by focusing specifically on our bCourses analytics (and is about to get some more methods to help with boxplots and the matrix).

BOAC-1493 Consolidate duplicate lastActivityDays methods

---

src/mixins/Util.vue
src/views/Student.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-1562
Since Vue templates don't have the same implicit short-circuit evaluation as Angular 1, we need a better guard against errors of the `Cannot read property 'length' of null` type. After some hemming and hawing, I decided that the least obtrusive way of handling it was to explicitly add a couple of Lodash utils to our arsenal.

BOAC-1562 Leverage Lodash utils in Vue templates

---

src/main.ts

https://jira.ets.berkeley.edu/jira/browse/BOAC-1562
Switching around the initialization logic quiets `vue-analytics.js:1 t.replace is not a function` errors in local testing.

BOAC-1562 Fix vue-analytics console error

---

boac/routes.py
boac/static/app/routes.js
config/test.py
src/api/user.ts
src/components/sidebar/Cohorts.vue
src/router.ts
src/store/modules/context.ts
src/store/modules/user.ts
tests/test_routes.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1569
The most delicate fix in this PR is found in `router.ts` where we must parse VUE_PATHS config and perform "legacyPathRedirect" if the URL path is not yet supported in Vue-land. This split-brain code will be removed in late Jan.

BOAC-1569, router fixes (py, js and vue) to support split-brain testing

---

boac/static/app/main.css
src/components/curated/CuratedGroupHeader.vue
src/mixins/Loading.vue
src/views/Course.vue
src/views/Student.vue
src/views/cohort/AllCohorts.vue
src/views/group/CuratedGroups.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-1500
Page headers should acquire focus on load, which requires them to be included in the tab order; but the visual outline is distracting and, unlike such outlines on links or buttons, provides no context for the user's next action.

BOAC-1500 Autofocus page headers audibly but not visibly

---

src/components/course/SortableCourseList.vue
src/components/search/SortableStudents.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-1577
Also removes the no-op `dropup`/`caret` classes which were copied from the AngularJS implementation.
While testing this, I noticed a couple of more minor visual glitches relating to caret spacing:
* The first sort on "GPA" bounces the column header text to the left (because it's currently right-aligned).
* The first sort on a wrapped column header (e.g., "Term Units" in my testing) bounces all rows down (because the caret appears under the header text).
This is bug-for-bug compatible with the Angular page, though, so I'll leave it as is for the nonce.

BOAC-1577 Vue: add carets for student search result sorts

---

boac/static/app/student/student.html
boac/static/app/student/studentController.js

https://jira.ets.berkeley.edu/jira/browse/BOAC-1613
https://docs.angularjs.org/api/ng/directive/ngChange says, "ngChange is only evaluated when ... new value to be committed to the model". I verified on Chrome and Safari.

BOAC-1613, use predictable ng-change on curated checkbox (student profile)

---

config/default.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1617
Purely a housekeeping PR, since local configs override this value.

BOAC-1617 Update LDAP host in default config

---

src/App.vue
src/components/admin/DevAuth.vue
src/components/cohort/ApplyAndSaveButtons.vue
src/components/cohort/CohortPageHeader.vue
src/components/cohort/CreateCohortModal.vue
src/components/cohort/DeleteCohortModal.vue
src/components/cohort/FilterRow.vue
src/components/curated/CreateCuratedGroupModal.vue
src/components/curated/CuratedGroupHeader.vue
src/components/sidebar/Cohorts.vue
src/layouts/Login.vue
src/layouts/StandardLayout.vue
src/mixins/Util.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-1664
https://jira.ets.berkeley.edu/jira/browse/BOAC-1661
W.r.t `reloadRouteKey`, a better approach than https://github.com/ets-berkeley-edu/boac/pull/1182, methinks. Includes fix to NOT reload route when user creates new cohort.
This PR also has commit for bootstrap button color override.

BOAC-1664/ BOAC-1661, reloadRouteKey force route reload; history.pushState in /cohort; btn colors

---

src/components/cohort/CohortPageHeader.vue
src/components/cohort/FilterRow.vue
src/store/modules/cohort-edit-session.ts

https://jira.ets.berkeley.edu/jira/browse/BOAC-1320
I'm tossing out the use of `this.$eventHub.$on` when it comes to state management in filter rows – each row allows add/edit/remove of filter – in favor of a more intuitive use of `EDIT_MODE_TYPES`.  (We keep `editMode` value in Vuex store.)

BOAC-1320, if user edits filter then auto-cancel other filter row edit

---

src/components/curated/CuratedStudentCheckbox.vue
src/components/home/HomeCohort.vue
src/components/student/StudentAlerts.vue
src/components/student/StudentUnitsChart.vue
src/views/Course.vue
src/views/Home.vue
src/views/cohort/Cohort.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-1703
The Bootstrap-Vue pagination widget works differently than Angular's - the ellipsis is not meant to be clickable.  Instead, pages 11-_n_ can be accessed via the arrow buttons (first, previous, next, and last).
I also realized that unless `scoped` is specified, anything in the `<style>...</style>` section of a component applies to the entire app.

BOAC-1703: enables pagination arrows and scopes styles

---

src/router.ts

https://jira.ets.berkeley.edu/jira/browse/BOAC-1603
Redirect to login when an unauthenticated user requests a protected route was already working, but now the user will be re-redirected to the protected route after login.

BOAC-1603: redirects to requested route after login

---

boac/externals/data_loch.py
boac/lib/berkeley.py
boac/models/development_db.py
config/default.py
tests/test_api/test_student_controller.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1643
I thought this was going to be more complicated, but apparently we designed it right the first time. Creation of department and user records in the database will be handled via scripts under release instructions.

BOAC-1643 Add physics dept to advising groups

---

boac/api/alerts_controller.py
boac/models/alert.py
src/components/student/profile/AcademicTimeline.vue
src/mixins/Util.vue
tests/test_api/test_alerts_controller.py
tests/test_api/test_cache_utils.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_curated_group_controller.py
tests/test_models/test_alert.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1723
Suitable to new UX paradigm.

BOAC-1723, structural change to /api/alerts json: 'dismissed' prop on all alert objects

---

src/App.vue
src/components/curated/CreateCuratedGroupModal.vue
src/components/curated/CuratedGroupSelector.vue
src/components/student/profile/StudentGroupSelector.vue
src/components/student/profile/StudentProfileHeader.vue
src/mixins/Util.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-1712
https://jira.ets.berkeley.edu/jira/browse/BOAC-1736
`@keyup.space.prevent.stop` does add/remove student per selected group _but_ it does not prevent scroll. I'll circle back to that later.

BOAC-1712, final touches on curated-groups dropdown on /student

---

src/components/student/profile/AcademicTimeline.vue
src/components/student/profile/StudentProfileGPA.vue
src/components/student/profile/StudentProfileUnits.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-1713
Includes sneaky fix to AcademicTimeline: show no tabs when distinct alert types <= 1.

BOAC-1713, StudentProfileGPA accessibility

---

boac/api/notes_controller.py
src/api/notes.ts
tests/test_api/test_notes_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1771

BOAC-1771, client-side notes.ts to match /api/notes; was_read() added

---

boac/api/alerts_controller.py
boac/api/student_controller.py
boac/api/util.py
boac/merged/student.py
boac/models/alert.py
src/api/student.ts
src/components/student/profile/AcademicTimeline.vue
src/mixins/Util.vue
src/views/Student.vue
tests/conftest.py
tests/test_api/test_alerts_controller.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_curated_group_controller.py
tests/test_api/test_student_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1788
A substantial refactor allowed for a lot of code removal and faster page load. Plus, having alerts/holds/etc. bundled in one spot is more intuitive.

BOAC-1788, refactor to put alerts/holds/etc. under student['notifications']

---

boac/api/auth_controller.py
src/components/admin/DemoModeToggle.vue
src/components/admin/DevAuth.vue
src/components/student/profile/AcademicTimeline.vue
src/layouts/Login.vue
src/main.ts
src/mixins/Context.vue
src/mixins/UserMetadata.vue
src/router.ts
src/store/modules/context.ts
src/views/Admin.vue
tests/test_api/test_auth_controller.py
tests/test_auth/test_dev_auth.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1737
Simplified some code. Improved wording in errors. Popover instead of modal. Hold on to error when `router.ts` does redirect.

BOAC-1737, proper error messages on /login

---

boac/api/search_controller.py
boac/api/student_controller.py
boac/merged/student.py
boac/routes.py
src/api/search.ts
src/api/student.ts
src/components/sidebar/SearchStudents.vue
src/views/Admin.vue
src/views/Search.vue
tests/test_api/test_search_controller.py
tests/test_api/test_student_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1830
Incorporates notes into the existing students/courses search, broken out into its own controller.
Also folds in @johncrossman's work from #1321 (https://jira.ets.berkeley.edu/jira/browse/BOAC-1808) to remove the inactivity constraint from student search by name.

BOAC-1808 BOAC-1830 New search API: get your notes, get your inactive students

---

src/components/admin/DevAuth.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-1809
If unauthenticated user hits a protected route (e.g. /student/999), lands on /login, and authenticates using dev auth, they will be conveniently redirected to /student/999 instead of /home.

BOAC-1809: enables deeplinks for dev auth

---

package-lock.json
package.json
src/assets/styles/ckeditor-custom.css
src/components/note/AdvisingNote.vue
src/components/note/NewNoteModal.vue
src/main.ts

https://jira.ets.berkeley.edu/jira/browse/BOAC-1841
Styles are customized according to [docs](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/theme-customization.html). Injecting aria attributes in toolbar is not possible with `ckeditor5`. Work remains in assessing accessibility.

BOAC-1841, rich-text editor for note details (ckeditor5)

---

boac/api/notes_controller.py
boac/api/user_controller.py
boac/api/util.py
boac/externals/calnet.py
boac/lib/berkeley.py
boac/merged/calnet.py
boac/merged/student.py
boac/models/development_db.py
boac/models/note.py
scripts/db/migrate/20190220-BOAC-1835/DEV_ONLY_drop_notes_table.sql
scripts/db/migrate/20190220-BOAC-1835/pre_deploy_01_create_notes_table.sql
scripts/db/schema.sql
src/api/user.ts
src/components/note/AdvisingNote.vue
tests/test_api/test_notes_controller.py
tests/test_api/test_student_controller.py
tests/test_api/test_user_controller.py
tests/test_merged/test_student.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1880
I will drop/create the `notes` table if/when merged. (QA approved the dropping of test data in dev.) The `/api/user/{id}` endpoint is not `get_by_uid`.

BOAC-1880, notes table captures advisor's current name, role, and depts

---

boac/merged/calnet.py
boac/models/development_db.py
fixtures/calnet_search_entries.json
src/components/note/AdvisingNote.vue
tests/test_api/test_student_controller.py
tests/test_models/test_cohort_filter.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1869
Repurpose (otherwise unused) `fixtures/calnet_search_entries.json` to verify that legacy advisor name and dept load properly. And, assign `author.name` on server-side.

BOAC-1869, test coverage on legacy note 'author' metadata

---

boac/externals/data_loch.py
boac/merged/advising_note.py
fixtures/loch.sql
tests/test_merged/test_advising_note.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1891
Give `itemgetter` a sorted list _or_ lazy-init `topics_by_id[advising_note_id]` before append topics.

BOAC-1891, all topics per note: operator.itemgetter requires a sorted list

---

.ebextensions/03_download_local_configuration.config

The finally-required BOAC equivalent of https://github.com/ets-berkeley-edu/nessie/pull/30.
To fix (we hope) the failed deploy of #1360 (https://jira.ets.berkeley.edu/jira/browse/BOAC-1780).

BOAC-1780 Suppress PYTHONPATH for AWS CLI command in .ebextensions

---

boac/api/notes_controller.py
boac/externals/data_loch.py
boac/merged/advising_note.py
fixtures/loch.sql
src/components/note/AdvisingNote.vue
tests/test_api/test_notes_controller.py
tests/test_merged/test_advising_note.py
tests/util.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1914
The predictably formatted `attachment.sisFilename` is always used for API calls. We give display preference to `attachment.userFilename` when available (non-UCBCONVERSION attachments).

BOAC-1914 Friendly filenames for CS-sourced attachments

---

boac/api/cohort_controller.py
boac/api/util.py
fixtures/loch_student_enrollment_term_11667051_2162.json
fixtures/loch_student_enrollment_term_11667051_2172.json
fixtures/loch_student_enrollment_term_11667051_2178.json
fixtures/loch_student_enrollment_term_11667051_2182.json
fixtures/loch_student_enrollment_term_11667051_2185.json
fixtures/loch_student_enrollment_term_2345678901_2172.json
fixtures/loch_student_enrollment_term_3456789012_2178.json
fixtures/loch_student_enrollment_term_5678901234_2178.json
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/NS-429
BOAC no longer attempts to show term-wide averages of analytics data, but the underlying numbers were still being supplied by Nessie until https://github.com/ets-berkeley-edu/nessie/pull/371.

NS-429 Remove vestiges of term-wide analytics averaging

---

src/components/note/AdvisingNote.vue
src/components/note/EditAdvisingNote.vue
src/components/note/NewNoteModal.vue
src/components/student/profile/AcademicTimeline.vue
src/layouts/Login.vue
src/layouts/StandardLayout.vue
src/mixins/Context.vue
src/router.ts
src/store/modules/context.ts

https://jira.ets.berkeley.edu/jira/browse/BOAC-1938
Having screenreader-alerts managed via `context` (vuex store) allows modals to close without user missing the announcement. This PR also puts sr-only "edit note" button after note subject in tab order.

BOAC-1938, screenreader alerts (eg, from modal) go to shared, polite sr-only

---

src/components/curated/CuratedGroupSelector.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-1735
Screen reader will now say "Select all students to add to a curated group checkbox checked" or "Select all students to add to a curated group checkbox not checked".  I found this easier to grok than "select" vs. "un-select".

BOAC-1735: Makes group checkbox label more legible for screen reader

---

boac/api/config_controller.py
boac/api/user_controller.py
config/default.py
config/development.py
config/test.py
src/components/HeaderMenu.vue
src/mixins/Context.vue
src/store/modules/context.ts
src/views/Admin.vue
tests/conftest.py
tests/test_api/test_admin_controller.py
tests/test_api/test_auth_controller.py
tests/test_api/test_config_controller.py
tests/test_api/test_user_controller.py
tests/test_auth/test_dev_auth.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1969
* further use of `override_config`
* review with `?w=1` for a simpler diff

BOAC-1969, decouple dev-auth and demo-mode

---

src/mixins/GoogleAnalytics.vue
src/mixins/Loading.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-1816
On pages that have a component or sub-component reliant on the `user` object, the spinner will spin until the `api/profile/my` response is received.

BOAC-1816: Makes pages wait for user data before finishing loading

---

src/components/note/NewNoteModal.vue
src/components/student/profile/AcademicTimeline.vue
src/mixins/NoteEditSession.vue
src/store/index.ts
src/store/modules/note-edit-session.ts
src/views/Student.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-1967
Vuex store used to watch `newNoteMode` and `editingNoteId`.  Only the top-level `Student` can use `beforeRouteLeave()` (which captures the navigate-away event) because it's the component registered in `router.ts`. See docs: https://router.vuejs.org/guide/advanced/navigation-guards.html#in-component-guards

BOAC-1967, if create/edit note in progress then 'Are you sure?' if navigating away

---

boac/api/cohort_controller.py
boac/api/util.py
boac/lib/cohort_filter_definition.py
src/views/Admin.vue
src/views/AllCohorts.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-2011
https://jira.ets.berkeley.edu/jira/browse/BOAC-1877
In this PR, we treat one symptom of, according to CalNet, former-employee-advisors. The root cause will be handled in https://jira.ets.berkeley.edu/jira/browse/NS-417

BOAC-2011, both /cohorts/all and /admin must handle empty advisor name

---

boac/api/util.py
boac/merged/calnet.py
fixtures/calnet_search_entries.json

https://jira.ets.berkeley.edu/jira/browse/BOAC-1877
The current logic assumes at a pretty low level that we get faked results from LDAP when real results aren't returned, and so I made the decision optional for now. In a follow-up, I'd like to leave the choice up to higher-level code.

BOAC-1877 Do not include ex-advisors in Act As list

---

boac/externals/calnet.py
boac/merged/calnet.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1917
Broadening our calnet query allows us to put off https://jira.ets.berkeley.edu/jira/browse/NS-417  
Plus, we're evaluating advisor data from SIS. When we have a clearer picture we will reconsider a shadow db table in Nessie-land.

BOAC-1917, expand LDAP/CalNet query to include 'expired people'

---

boac/api/notes_controller.py
boac/merged/advising_note.py
boac/models/db_relationships.py
boac/models/note.py
scripts/db/drop_schema.sql
scripts/db/migrate/20190409-BOAC-2043/pre_deploy_01_create_note_attachments_table.sql
scripts/db/schema.sql
tests/test_api/test_curated_group_controller.py
tests/test_api/test_notes_controller.py
tests/test_merged/test_advising_note.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2043
Introduced `id` pkey on `note_attachments` table cuz the front-end cannot work with composite key `note_id` + `path_to_attachment`.  The pre-deploy script will make the adjustment if run again on BOA db.

BOAC-2043, '/api/notes/attachment/upload' API with tests; put id pkey on note_attachments table

---

boac/api/notes_controller.py
boac/merged/advising_note.py
boac/models/db_relationships.py
boac/models/development_db.py
boac/models/note.py
boac/models/note_attachment.py
src/api/api-utils.ts
src/api/notes.ts
tests/test_api/test_notes_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2069
* `update_note` can add and remove attachments in a single transaction.
* includes the appropriate front-end work

BOAC-2069, add attachments in /update/note; verify delete note.attachments

---

src/components/note/AdvisingNote.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-2064
When editing of a note is saved or cancelled, it causes the AdvisingNote component to go through its lifecycle again - this time in a pre-opened state.  Since the value of `isOpen` is already `true` and doesn't change, the author wasn't being set.  We need to check for this condition when the component is created and set the author if appropriate.

BOAC-2064: Sets author on notes that render in an open state

---

src/components/note/EditAdvisingNote.vue
src/components/note/ManageNoteAttachments.vue
src/components/note/NewNoteModal.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-2104
I hope this manage-attachments component will make the impl of BOAC-2104 easier.

BOAC-2104, move dupe logic/styles in new-note and edit-note to manage-attachments

---

boac/api/cache_utils.py
boac/api/course_controller.py
boac/api/curated_group_controller.py
boac/api/user_controller.py
boac/api/util.py
boac/models/alert.py
boac/models/cohort_filter.py
boac/models/curated_group.py
boac/models/db_relationships.py
boac/models/development_db.py
src/api/curated.ts
src/api/user.ts
tests/test_api/test_cache_utils.py
tests/test_api/test_curated_group_controller.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2071
* Remove `myCohorts` and `myCurated` from `/api/my/profile` because the front-end manages those lists separately. See https://github.com/ets-berkeley-edu/boac/pull/1195 
* This refactor is a nice start to enhancing the API – clarity in naming.

BOAC-2071, refactor away 'curated_cohort' naming; remove cohorts/groups from /api/profile/my

---

src/components/curated/CuratedGroupSelector.vue
src/components/sidebar/Cohorts.vue
src/components/sidebar/CuratedGroups.vue
src/components/student/profile/AcademicTimeline.vue
src/views/CuratedGroupBulkAdd.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-2072
https://jira.ets.berkeley.edu/jira/browse/BOAC-2070
The re-introduced sidebar create-group link takes you to bulk-add SIDs. The component is wired to update/create groups but work remains w.r.t https://jira.ets.berkeley.edu/jira/browse/BOAC-2124

BOAC-2072/BOAC-2070, create or update curated group with list o' SIDs

---

src/components/sidebar/CuratedGroups.vue
src/views/CuratedGroup.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-2133
See screenshots in the Jira. I did not touch 'context' prop in `SearchForm` – it might prove to be useful.

BOAC-2133, empty curated group UX: Keep it simple st__id

---

boac/api/config_controller.py
boac/models/tool_setting.py
scripts/db/drop_schema.sql
scripts/db/migrate/20190506-BOAC-2079/pre_deploy_01_create_tool_settings_table.sql
scripts/db/schema.sql
src/api/config.ts
src/components/admin/EditServiceAnnouncement.vue
src/layouts/StandardLayout.vue
src/mixins/Context.vue
src/store/modules/context.ts
src/views/Admin.vue
tests/test_api/test_config_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2079
https://jira.ets.berkeley.edu/jira/browse/BOAC-2080
Server-side (incl. db) work to support get/set of service-announcement. On the front-end, toolSettings are folded in with the 'config' store. This PR includes front-end api and store logic. The textarea/checkbox on Admin page works – the styling on the announcement div and Admin component is not done.

BOAC-2079, tool_settings table and protected get/update service-announcement API

---

boac/api/config_controller.py
tests/test_api/test_config_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2179

BOAC-2179, if user is not auth then /api/service_announcement returns None

---

src/components/curated/CuratedGroupSelector.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-2153
Dupe was introduced in attempt to support keyboard-only use of dropdown – I will reopen BOAC-1736. (I also removed dupe aria-label.)

BOAC-2153, remove dupe curatedGroupCheckboxClick() to avoid duplicate key db error

---

src/components/Footer.vue
src/components/sidebar/Cohorts.vue
src/components/sidebar/CuratedGroups.vue
src/components/sidebar/SearchForm.vue
src/components/sidebar/Sidebar.vue
src/layouts/StandardLayout.vue
src/views/AllCohorts.vue
src/views/Cohort.vue
src/views/CuratedGroup.vue
src/views/Home.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-2186
In a narrow viewport (eg, mobile) the header, sidebar and main-content elements will fall into a single column. This PR also trims down the amount of CSS. 

BOAC-2186, b-container:fluid in StandardLayout for responsive template

---

src/components/note/AdvisingNote.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-2202
See suggested solutions in https://zzz.buzz/2017/07/31/prevent-tooltip-over-truncated-text-in-safari
I chose "the most obvious solution ... add a title attribute"

[QA] BOAC-2202, if text is truncated then Safari has full-text tooltip (a problem for demo-mode)

---

requirements.txt

https://jira.ets.berkeley.edu/jira/browse/NS-532
I'm unable to reproduce reported 1.8.3 breakages locally, but the dev environment is made to be broken, so let's try it there.

NS-532 Update smart_open to 1.8.3

---

boac/externals/s3.py

https://jira.ets.berkeley.edu/jira/browse/NS-532
Because `smart_open.smart_open` is a little too pushy about its smartness.

NS-532 Update deprecated smart_open signature

---

boac/api/cache_utils.py
boac/api/curated_group_controller.py
boac/api/util.py
boac/models/curated_group.py
boac/models/db_relationships.py
boac/models/development_db.py
src/api/curated.ts
src/mixins/Util.vue
src/views/CuratedGroup.vue
tests/test_api/test_cache_utils.py
tests/test_api/test_curated_group_controller.py
tests/test_api/test_student_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-855
I had to remove the SQLAlchemy join on students and load students (or sids) on demand, with offset and limit options. Remember that curated groups are special in that we filter SIDs of the group based on user's `dept_code`.

BOAC-855, paginated curated groups

---

boac/api/notes_controller.py
boac/lib/util.py
requirements.txt
tests/test_api/test_notes_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-1898
https://jira.ets.berkeley.edu/jira/browse/BOAC-1897
`linkify` does its job but we don't want it parsing properly tagged URLs, thus the custom pre-processing (see `placeholder`).

BOAC-1898, recognize/tag URLs in body text of new/updated notes

---

buildspec.yml

https://jira.ets.berkeley.edu/jira/browse/NS-528
Read Jira description and overview of syntax in https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-syntax

NS-528, update buildspec to v0.2 spec, use 'runtime versions'

---

buildspec.yml

https://jira.ets.berkeley.edu/jira/browse/NS-528
`sudo` is not available on CodeBuild's transient Docker image – maybe because `root` is default user in new 0.2 spec.  So `sudo` is out. (We tested this change, from my working branch, on boac-dev pipeline and deploy succeeded.)

NS-528, remove sudo from buildspec.yml

---

package-lock.json
package.json

https://jira.ets.berkeley.edu/jira/browse/BOAC-2222
We can revisit this mystery if/when we need the latest [highcharts](https://github.com/highcharts/highcharts).

BOAC-2222, fix tooltips: revert highcharts to 6.2.0

---

boac/merged/calnet.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2218
Per Calnet lookup logic elsewhere - because otherwise a failure will slow us down every time.

BOAC-2218 Bulk advisor lookup: cache failed results too

---

.ebextensions/00_ami.config
.ebextensions/12_set_default_region.config
boac/externals/s3.py
config/default.py
config/test.py
tests/util.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2235
1) Boto authentication is switched to create session using STS credentials. This limits credential exposure. The commit changes the auth scheme for BOA while interacting with AWS services like S3. A Short term credential(includes temp key, secret, token) is created for every interaction which is alive for 15 minutes duration using STS service. Permissions are given to the developer group to assume roles in the context of the app and environment they will be running which limits cross stack access, limiting the blast radius.  
2) Elastic Beanstalk changes to represent the use of IAM instance roles. IAM instance profile on EC2 servers will have the app_role attached to it which provides the same permissions for instances to assume roles …

[BOAC-2235] Changing AWS auth scheme to use STS tokens and app_roles.

---

src/components/sidebar/SearchForm.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-2224
As far as I can tell, having the text button wink in and out of existence was confusing Bootstrap's flex implementation. Simply toggling CSS visibility keeps things stable.

BOAC-2224 Don't let that old notes checkbox disappear

---

src/components/note/AdvisingNoteTopics.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-2228
This allows a full-width list of options to appear in Safari, and I think is easier to read anyhow.

BOAC-2228 Widen advising note topic input

---

.ebextensions/00_ami.config

Passes app_roles to the instance profiles vis environment variables. This prevents code changes during stack promotion and deployments. 
https://jira.ets.berkeley.edu/jira/browse/NS-531

[NS-531] Use environment variables to pass app_role to instance profile.

---

src/views/Cohort.vue
src/views/CuratedGroup.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-2300
By an accident of history, `this.loading` is a data value, while `this.loaded()` is a setter function returning nothing.

BOAC-2300 Fix loading-aware conditional in cohort/group sort

---

src/mixins/Util.vue
src/views/Cohort.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-2302
The 'continueExistingSession' logic allows users to click to (1) view a student and then (2) use back-button to return to the working state of cohort view. For example, page number and filter edits are preserved.
In the 'continueExistingSession' logic, we're getting false-positives from `$routerHistory.hasForward()` when user is clicking around links in sidebar. This PR avoids such false-positives by only supporting back button when user goes /cohort to /student and then back-button to /cohort. IMO, this is an intuitive limit on back-button support.

BOAC-2302, 'continueEdit-if-back-button' logic in /cohort is fooled by clicking around sidebar

---

src/mixins/Util.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-2303
Before this fix, floats were compared via _.toInt() – a world where 3.1 equals 3.9.

[QA] BOAC-2303, fix sortable columns: if args _.isNumber then compare w/o type conversion

---

src/components/sidebar/Cohorts.vue
src/components/sidebar/CuratedGroups.vue
src/components/sidebar/Sidebar.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-2236
No QA PR needed here. With narrower sidebar, `flex-wrap` plays well in narrow viewport.

BOAC-2236, flex-wrap on rows of cohorts/groups in sidebar

---

boac/api/cache_utils.py
boac/api/cohort_controller.py
boac/api/menu_controller.py
boac/lib/berkeley.py
boac/lib/cohort_filter_definition.py
boac/models/cohort_filter.py
scripts/db/migrate/20190606-BOAC-2271/pre_deploy_01_create_sids_column.sql
scripts/db/schema.sql
src/api/cohort.ts
src/api/menu.ts
src/store/modules/cohort-edit-session.ts
tests/test_api/test_cache_utils.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_menu_controller.py
tests/test_lib/test_berkeley.py
tests/test_models/test_cohort_filter.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2271
For batch note creation, we must quickly convert a list of cohort ids to proper list o’ SIDs. This new column provides that fast access and is maintained same way of ‘student_count’.  We use SQLAlchemy's `deferred(db.Column)` so `sids` array is only loaded if `undefer(...)` is used.
Other noteworthy changes:
* `to_api_json()` is invoked under-the-hood (i.e., the model's CRUD methods) because it enforces vital biz logic (e.g., update student_count and sids when `update()` is invoked.) IMO, this change makes code more readable.
* The front-end no longer posts 'studentCount'. The value only changes when `/update` and the back-end has it covered.

BOAC-2271, add column 'sids' to cohort_filters for fast batch note creation

---

boac/api/notes_controller.py
boac/models/note.py
boac/models/note_attachment.py
tests/test_api/test_notes_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2271
Using postgres native `json_populate_recordset` for bulk inserts seems to be faster than what's listed in https://docs.sqlalchemy.org/en/13/_modules/examples/performance/bulk_inserts.html   The use of `INSERT ... returning id` allows `db.session.execute(...)` to treat the query as SELECT, getting a list of note `ids` in result-set.
Notice the log message "...records inserted in ... seconds" – I will further profile batch creation once in `boa-dev`.

BOAC-2271, notes_controller support for batch note creation

---

boac/externals/data_loch.py
boac/merged/advising_note.py
fixtures/loch.sql
tests/test_api/test_search_controller.py
tests/test_merged/test_advising_note.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2238
First attempt at squeezing ASC notes into the note search results paradigm. Since they don't have a note body, they won't have a note snippet to display - just the advisor name and date.

BOAC-2238: Makes ASC notes searchable

---

boac/api/cohort_controller.py
boac/api/util.py
boac/models/cohort_filter.py
tests/test_api/api_test_utils.py
tests/test_api/test_cache_utils.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_notes_controller.py
tests/test_models/test_cohort_filter.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2365
To verify that `current_user` has access to cohort we do not need the expensive:
`cls.query.filter(cls.owners.any(uid=uid)).order_by(cls.name).all()`

BOAC-2365, remove expensive CohortFilter.all_owned_by call when verifying user perm to edit/view cohort

---

boac/api/auth_controller.py
boac/api/cohort_controller.py
boac/api/notes_controller.py
boac/api/user_controller.py
boac/api/util.py
boac/lib/cohort_filter_definition.py
boac/merged/student.py
boac/merged/user_session.py
boac/models/authorized_user.py
boac/routes.py
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2377
In flask-login we `login_user(..., remember=True)` so this cached user-session-json will persist across browser restarts. This cuts `/api/my/profile`time in half which is one of the main offenders in blocking the "painting" if initial page load. (Cache is refreshed when user logs in again or toggles demo-mode.)

BOAC-2377, cache user_session json by user_id; flush on login, demoMode toggle

---

src/components/sidebar/SearchForm.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-2370
"Create note" and similar form-submits do not seem to suffer same problem on Safari.

BOAC-2370, keyboard-only search on Safari

---

boac/lib/cohort_filter_definition.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2409
Cohort created by COE advisor, in March, had 'Sociology BA' major selected. 'Sociology BA' is no longer in COE scope. This does not break queries but it does disrupt front-end when rendering menu options. I'm working around the problem by tolerating nulls in menu render.
This bug is unlikely to recur after we desilo-ize but if it does, we can consider a more sophisticated fix.

BOAC-2409, obsolete cohort filter values (eg, 'Sociology BA') should not bust front-end

---

boac/__init__.py

`qa` branch was cut 30 min ago. The `boa-qa` CodePipeline has an "Approve" step so code will not deploy until Ops is ready.

NOJIRA, BOA master branch is v2.20

---

boac/api/notes_controller.py
boac/api/student_controller.py
boac/externals/data_loch.py
boac/merged/student.py
src/api/notes.ts
src/api/student.ts
src/components/note/AdvisingNoteTopics.vue
src/components/note/EditAdvisingNote.vue
src/components/note/NewNoteModal.vue
src/components/sidebar/Sidebar.vue
src/components/student/profile/AcademicTimeline.vue
src/mixins/StudentEditSession.vue
src/store/index.ts
src/store/modules/student-edit-session.ts
src/views/Student.vue
tests/conftest.py
tests/test_api/test_alerts_controller.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_curated_group_controller.py
tests/test_api/test_notes_controller.py
tests/test_api/test_student_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2279
On front-end, our vue mixin `EditNoteSession` is now `StudentEditSession`, lending itself to a nice code pattern whereby student profile can be refreshed when, for example, a note is created via batch-create. Using `$eventHub` to emit events was not a good solution here.
In order to make this work we needed two small BOA API changes: (1) `/api/student` takes SID instead of UID and (2) if create note is  "batch-mode" then server always return an array of SIDs.
IMO, it's a fairly intuitive arrangement.

BOAC-2279, refresh student in /student if note created per sid

---

boac/api/notes_controller.py
boac/merged/student.py
boac/models/note.py
boac/models/note_read.py
src/api/api-utils.ts
src/api/notes.ts
src/components/student/profile/AcademicTimeline.vue
src/mixins/StudentEditSession.vue
src/store/modules/student-edit-session.ts
src/views/Student.vue
tests/test_api/test_notes_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2279
Both "batch" and standard note creation use `eventHub.emit` tactic (instead of mixin) to refresh notes list in student's profile. My earlier concerns w/ listener-related memory leak were assuaged.
(I'm keeping the unused `/api/student/by_sid/<sid>` in place, for now.)

BOAC-2279, efficient use of eventHub.emit to update AcademicTimeline with new note

---

src/assets/styles/bootstrap-overrides.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-2428
font-good-enough instead of font-awesome. See https://en.wikipedia.org/wiki/Geometric_Shapes

[QA] BOAC-2428, odd case of ::after in bootstrap-override requires generic unicode

---

src/components/cohort/ApplyAndSaveButtons.vue
src/components/cohort/FilterRow.vue
src/components/note/NewNoteModal.vue
src/views/Cohort.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-2289
I'm also taking "unsaved" out as default cohort name cuz it's confusing in GA events.

BOAC-2289, ids on batch-note-modal to empower Teena

---

boac/merged/user_session.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2430
Type matters.

[QA] BOAC-2430, flask-login persists user_id as string; we force int when de-serialized

---

boac/merged/user_session.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2430
Corresponding `qa` PR is #1695

BOAC-2430, flask-login persists user_id as string; we force int when de-serialized

---

boac/api/notes_controller.py
boac/api/student_controller.py
boac/externals/data_loch.py
boac/lib/cohort_filter_definition.py
boac/merged/advising_note.py
boac/merged/student.py
boac/models/curated_group.py
boac/models/note.py
src/mixins/StudentMetadata.vue
tests/test_api/test_cohort_controller.py
tests/test_api/test_curated_group_controller.py
tests/test_api/test_notes_controller.py
tests/test_api/test_search_controller.py
tests/test_api/test_student_controller.py
tests/test_merged/test_advising_note.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2379
Our concept of "scope" doesn't go away, but it now has less to do. A search for students via name or cohort filter now pulls in all students that BOA knows about, with their profiles and advising notes accessible, no matter who you are.
Restrictions that remain in place:
- Advisors can't view cohorts belonging to other departments.
- Advisors can't perform cohort searches with data from other departments as a criterion.
- Advisors don't see data from other departments in student feeds.

BOAC-2379 All advisors can see all students, but not all per-student data

---

boac/api/cohort_controller.py
boac/api/menu_controller.py
boac/api/util.py
boac/externals/data_loch.py
boac/lib/cohort_filter_definition.py
boac/merged/student.py
boac/models/cohort_filter.py
boac/routes.py
fixtures/loch.sql
src/api/cohort.ts
src/api/menu.ts
src/store/modules/cohort-edit-session.ts
tests/test_api/test_cohort_controller.py
tests/test_api/test_menu_controller.py
tests/test_api/test_student_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2168
This reverts PR #1711 
Expectation with gender and ethnicity/URM data is that the existing CoE filters should be renamed to include "(COE)" and moved to the department-specific filter section. COE advisors will have access to multiple gender filters.

Revert: BOAC-2168, 'Gender' cohort filter for all

---

boac/merged/advising_note.py
tests/test_api/test_notes_controller.py
tests/test_merged/test_advising_note.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2479
Lenient comparison between `created_at` and `updated_at`.

BOAC-2479, do not show updated_at if note has not been modified since creation

---

boac/merged/cohort_filter_options.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2496
Most advisor-student associations from our SIS source are associated with an academic plan, but a handful of them represent the plan as either null or a blank string. Cohort filters aren't playing well with this state of affairs; let's suppress blank plans in the app and look into fixing the data upstream.

BOAC-2496 Ignore planless advisor-student associations

---

boac/api/auth_controller.py
boac/routes.py
config/default.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2452
The goal is to log a user out after they close the browser - this will also log them out if the browser hasn't made any requests for 60 minutes.
This will likely be annoying for developers; I recommend overriding `INACTIVE_SESSION_LIFETIME` in your local config.

BOAC-2452: Sets inactivity lifespan on session cookie

---

boac/merged/advising_note.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2551
Historical SIS attachments are grouped in folders by SID, but ongoing/incremental attachments are not.

BOAC-2551: Removes SID from attachment S3 key

---

boac/externals/data_loch.py

QA-first PR for https://jira.ets.berkeley.edu/jira/browse/BOAC-2574.
https://github.com/ets-berkeley-edu/nessie/pull/505 cleared out null topics from RDS, but turns out BOA is still querying Redshift for notes. The right fix is to have BOA start querying RDS (and maybe keep null topics out of our internal Redshift as well). But rather than make an architectural change the day before release, this should plug the gap.

[QA] BOAC-2574 Suppress null advising note topics from Redshift

---

boac/api/note_templates_controller.py
boac/lib/util.py
boac/models/note_template.py
boac/models/note_template_attachment.py
boac/models/note_template_topic.py
boac/routes.py
scripts/db/drop_schema.sql
scripts/db/migrate/20190814-BOAC-2541/pre_deploy_01_create_note_templates_table.sql
scripts/db/schema.sql
tests/test_api/test_note_templates_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2541
Note:
* Soft-delete for `note_template_attachments` (see `deleted_at` column) because file uploads might be audited.
* `note_template_topics` table has neither `author_uid` nor `deleted_at`.  Those attributes will be tracked in the actual notes.
* If an authorized_user is deleted then we `DELETE CASCADE` per `note_templates.creator_id`
* The initial tests in `test_note_templates_controller` are for basic verification of the models.

BOAC-2541, note_template/topic/attachment tables and SQLAlchemy models

---

boac/api/note_templates_controller.py
boac/api/notes_controller.py
boac/models/note.py
boac/models/note_attachment.py
boac/models/note_template.py
boac/models/note_template_topic.py
boac/models/note_topic.py
src/api/notes.ts
src/components/note/EditAdvisingNote.vue
tests/conftest.py
tests/test_api/test_note_templates_controller.py
tests/test_api/test_notes_controller.py
tests/test_api/test_student_controller.py
tests/test_merged/test_advising_note.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2542
Per reqts, `note_template` API does not need dedicated add/remove attachment endpoints. See [latest comment in BOAC-2542](https://jira.ets.berkeley.edu/jira/browse/BOAC-2519?focusedCommentId=310693&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-310693).

BOAC-2542, note_template update API endpoint plus cleanup

---

src/assets/styles/bootstrap-overrides.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-2596

BOAC-2596, hide default sort arrows in bootstrap b-table

---

src/components/util/Status.vue

Only noticeable in local env, where no build-information file exists and `version.build` is nil. No need for QA PR.

NOJIRA, null check in 'Status  > Version' section of /admin page

---

boac/externals/data_loch.py
boac/merged/cohort_filter_options.py
src/components/cohort/FilterRow.vue
tests/test_api/test_cohort_controller.py
tests/test_externals/test_data_loch.py

Like the customer ordered in https://jira.ets.berkeley.edu/jira/browse/BOAC-2608:
- Revert term interpolation (#1788);
- Order latest to earliest;
- Insert a divider between present term and past terms.
I don't love the 'divider' convention but I didn't want to further redo the filter framework for the sake of putting one divider in one dropdown.

BOAC-2608 Fixes to expected graduation term filter options

---

boac/externals/data_loch.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2618
Upstream from these queries, `boac.merged.advising_note` joins topics to notes with a Python `groupby`, which unlike its easygoing Ruby cousin will give entirely unexpected results when it doesn't get things in order.

BOAC-2618 Add id ordering to note topic queries

---

src/components/student/profile/AcademicTimeline.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-2639
Note IDs should start with a digit and end with a digit, but things get crazy in the middle.

BOAC-2639 Loosen match criteria for note ID permalinks

---

boac/logger.py
config/default.py

Now defaults to INFO level. Log level can be overridden by setting LOGGING_PROPAGATION_LEVEL in the configs.
https://jira.ets.berkeley.edu/jira/browse/BOAC-2659

[BOAC-2659] Suppress log levels on botocore as it is too verbose in debug mode. 

---

src/assets/styles/boac-global.css
src/assets/styles/bootstrap-overrides.css
src/components/note/NewNoteModal.vue
src/components/note/NewNoteModalButtons.vue
src/components/note/NewNotePageHeader.vue
src/store/modules/note-edit-session.ts

https://jira.ets.berkeley.edu/jira/browse/BOAC-2658
Plus:
* after clicking 'create template', the modal stays open and resets the form
* fade-after-five-seconds, dismissible alert when create/cancel new template

BOAC-2658, move 'Create Template' to top-right 'Templates' menu

---

src/components/admin/EditServiceAnnouncement.vue
src/components/note/EditAdvisingNote.vue
src/components/note/create/CreateNoteModal.vue
src/components/util/RichTextEditor.vue
src/mixins/NoteEditSession.vue
src/mixins/Util.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-2663
The cause of this bug is explained in [my post on Stack Overflow](https://stackoverflow.com/questions/57877722/how-can-i-get-ckeditor-5-link-dialog-box-to-pin-to-custom-dom-element-instead). Unfortunately, CKEditor config options do offer a path to a solution.
The fix in this PR involves a bit of a hack – see `correctTheDOM()`  – but this is an opportunity to reduce redundant code. For example, fewer lines in the advising-notes-related components.

BOAC-2663, RichTextEditor wraps ckeditor so we can 'correct the DOM', if necessary

---

src/components/note/create/CreateNoteModal.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-2685
This fixes an edge case. The standard workflow, (1) load template and (2) create note(s), has been working: only one file in S3.

BOAC-2685, if create template and then immediately create note: avoid dupe files in S3

---

src/components/note/AdvisingNote.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-2613
A minor issue but serving dead links in prod is a bad idea.
master PR is #1897

[QA] BOAC-2613, link to directory if and only if note.author.uid

---

fixtures/loch_student_profile_11667051.json
src/components/student/StudentRow.vue
src/components/student/profile/StudentClasses.vue
tests/test_merged/test_student.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2753
https://jira-secure.berkeley.edu/browse/SISRP-48560
Why suppress? See comments in BOAC-2753. QA PR will follow.

BOAC-2753, suppress the unitsMin and unitsMax messaging in BOA

---

boac/api/user_controller.py
boac/api/util.py
boac/models/authorized_user.py
src/api/user.ts
src/components/admin/Users.vue
src/store/modules/user.ts
src/views/Admin.vue
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2844
The new table allows filtering by department, but that doesn't include not-real departments like Admin and Notes Only.  I'll submit another PR to expand filtering capabilities to include permissions and status.

BOAC-2711: Revamps admin page

---

boac/api/alerts_controller.py
boac/api/auth_controller.py
boac/api/cache_utils.py
boac/api/cohort_controller.py
boac/api/course_controller.py
boac/api/curated_group_controller.py
boac/api/note_templates_controller.py
boac/api/notes_controller.py
boac/api/search_controller.py
boac/api/student_controller.py
boac/api/user_controller.py
boac/api/util.py
boac/merged/user_session.py
boac/models/development_db.py
boac/models/university_dept_member.py
scripts/db/migrate/20191007-BOAC-2805/pre_deploy_01_add_column_is_scheduler.sql
scripts/db/schema.sql
tests/test_api/test_cache_utils.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_course_controller.py
tests/test_api/test_curated_group_controller.py
tests/test_api/test_notes_controller.py
tests/test_api/test_search_controller.py
tests/test_api/test_student_controller.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2795
https://jira.ets.berkeley.edu/jira/browse/BOAC-2805
Basic features of BOA are only available to admins and advisors. If user `is_scheduler` then s/he only gets `/appt/desk`. PR for front-end will follow.

BOAC-2795, university_dept_members gets 'is_scheduler'; protect APIs from non-advisor scheduler

---

src/components/HeaderMenu.vue
src/components/student/SortBy.vue
src/layouts/DropInDesk.vue
src/layouts/shared/StandardHeaderLayout.vue
src/mixins/UserMetadata.vue
src/router.ts

https://jira.ets.berkeley.edu/jira/browse/BOAC-2804
We'll want to demo the '/appt/desk' page. Therefore, the "scheduler" user must have an Admin page that uses the custom `DropInDesk` page layout.

BOAC-2804, header dropdown in '/appt/desk' view includes 'Settings' option

---

src/components/sidebar/SearchForm.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-2860
The recent upgrade of `vue-router` brought in its new promise API. See https://github.com/vuejs/vue-router/issues/2872  The fix is a noop callback.

BOAC-2860, Vue discourages router.push if target path matches current path

---

boac/api/appointments_controller.py
boac/api/util.py
boac/models/appointment.py
boac/models/appointment_read.py
src/api/appointments.ts
src/components/student/profile/AcademicTimeline.vue
src/views/AppointmentWaitlist.vue
tests/test_api/test_appointments_controller.py
tests/test_api/test_student_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2813
I also removed advisor info from `/appointment/create` transaction. Advisor info is expected only at check-in.

BOAC-2813, API and tests for 'mark appointment as read'

---

src/components/admin/Users.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-2864
On /admin, it appears that toggling details was triggering the pagination to reset (probably because it sets a property on the item whose details you want to see).
The fix is to prevent pagination resets unless the items array actually changed.

BOAC-2864: Fixes details toggle + pagination mischief

---

src/components/appointment/AppointmentTopics.vue
src/components/appointment/CreateAppointmentModal.vue
src/components/note/AdvisingNoteTopics.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-2843
`v-model` is used solely to reset the dropdown.

BOAC-2843, select multiple topics for new appt; render 'Select...' instead of blank

---

src/App.vue
src/mixins/Context.vue
src/store/modules/context.ts

This will only surface on developer workstations. The goal is to raise awareness of screenreader alerts and, hopefully, improve 'em.

NOJIRA, localhost only: screenReaderAlert is the dismissible message in footer

---

src/mixins/DropInWaitlistContainer.vue
src/views/DropInAdvisorHome.vue
src/views/DropInDesk.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-2971
A shared DropInWaitlistContainer mixin is silly, but the alternative I was attempting (making DropInWaitlist responsible for its own data updates) really didn't play well with the nested components model.

BOAC-2971 Shared appointments polling for scheduler and drop-in advisor

---

boac/api/appointments_controller.py
boac/models/appointment.py
boac/models/appointment_event.py
boac/models/development_db.py
scripts/db/drop_schema.sql
scripts/db/migrate/2019/20191031-BOAC-2993/create_appointment_events_table.sql
scripts/db/schema.sql
tests/test_api/test_appointments_controller.py
tests/test_api/test_search_controller.py
tests/test_api/test_student_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2993
The appointments test data did not represent expected use cases (e.g., advisor metadata was inserted in db without checked_in status being set) so this refactor included test data overhaul.  Therefore, many expectations in tests had to change.  I'm hoping for very few client-side breakages – we'll take this one step at a time.

BOAC-2993, refactor appointments-related schema and necessary model/API work

---

boac/api/appointments_controller.py
boac/api/util.py
boac/models/appointment.py
boac/models/appointment_event.py
boac/models/authorized_user.py
boac/models/development_db.py
scripts/db/migrate/2019/20191031-BOAC-2993/create_appointment_events_table.sql
scripts/db/schema.sql
src/api/appointments.ts
src/components/appointment/AdvisingAppointment.vue
src/components/appointment/DropInWaitlist.vue
src/components/student/profile/AcademicTimeline.vue
src/mixins/DropInWaitlistContainer.vue
src/views/DropInAdvisorHome.vue
src/views/DropInDesk.vue
tests/test_api/test_appointments_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2995
Notable:
* fix `appointments_fts_index`: only grab latest event from `appointment_events` table, no dupe rows per appointment_id
* remove `canceledAt`, `canceledBy`, `reservedAt`, etc. in favor of `statusBy` and `statusDate`
* remove unnecessary calls to `refresh_search_index()`

BOAC-2995, most recent appointment_event for appointments_fts_index; simplify API

---

boac/api/appointments_controller.py
boac/api/notes_controller.py
boac/api/topic_controller.py
boac/models/development_db.py
boac/routes.py
src/api/appointments.ts
src/api/notes.ts
src/api/topics.ts
src/components/appointment/AppointmentTopics.vue
src/components/appointment/DropInAvailabilityToggle.vue
src/components/sidebar/SearchForm.vue
src/store/modules/note.ts
tests/test_api/test_appointments_controller.py
tests/test_api/test_notes_controller.py
tests/test_api/test_topic_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-3004
* With topic CRUD around the corner, breaking off a new controller seems appropriate.
* 'Other' is always last in list.

BOAC-3004, topics graduate to top-level API, dedicated controller

---

boac/api/appointments_controller.py
boac/models/appointment.py
src/api/appointments.ts
src/components/appointment/CreateAppointmentModal.vue
src/components/appointment/DropInWaitlist.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-3010
Passing all advisor info from the client, as done in this PR, is surprisingly less complex than using `advisor_uid` on server-side to pull from various data-sources.

BOAC-3010, if advisor uid when create appt then all advisor info please

---

src/components/note/AdvisingNote.vue

This un-reverts the revert (#2053) and restores #2050.

BOAC-2951: Removes logic preventing download of old attachments (un-revert)

---

boac/api/user_controller.py
src/components/note/AdvisingNote.vue
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-3041
* server-side must `raise`, not return, errors.ResourceNotFoundError
* client-side should gracefully handle advisor-not-found (no console error)

BOAC-3041, Student profile > note author not found > graceful 404 server-side

---

boac/api/appointments_controller.py
boac/models/appointment.py
src/components/appointment/DropInAppointmentDropdown.vue
src/components/appointment/DropInWaitlist.vue
src/components/appointment/DropInWaitlistAppointment.vue
tests/test_api/test_appointments_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-3034
To get layout working properly with spinners and such, much of the waitlist component is refactored into a new component for appointment rows, and the waistlist API feed is split into "unresolved" (above the fold) and "resolved" (below the fold) portions. Some obsolete code is also cleared out.

BOAC-3034 Untangle drop-in waitlist ordering

---

boac/api/user_controller.py
boac/models/authorized_user.py
boac/models/development_db.py
src/api/user.ts
src/components/admin/Users.vue
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-2882
Passenger Manifest `filter` and `search` include deleted users. Now `Admins` option does the same.

BOAC-2882, include deleted users in Passenger Manifest get-admin-users

---

scripts/db/migrate/2019/20191123-BOAC-3045/pre_deploy_01_topic_unique_constraint.sql
scripts/db/schema.sql
tests/test_api/test_appointments_controller.py
tests/test_api/test_notes_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-3045
For the indecisive advisor: No error when re-adding a topic.

BOAC-3045, topic_unique_constraint includes deleted_at – for notes and appts

---

boac/api/user_controller.py
src/components/note/AdvisingNote.vue
tests/test_api/test_user_controller.py

IMO, the safest fix is to _not_ return 404 from API and make sure front-end is null tolerant.

[QA] BOAC-3068, no 404 when advisor not found; nil tolerant front-end

---

boac/api/user_controller.py
src/api/user.ts
src/components/note/AdvisingNote.vue
src/store/modules/user.ts
tests/test_api/test_user_controller.py

Originally, `/api/user/by_csid/<csid>` and `/api/user/by_uid/<uid>` were strictly CalNet-based. Recent changes to Passenger Manifest added an `authorized_user` dependency. I don't want to roll back that work BUT the get-advisor-info calls on student profile needs a CalNet-only API endpoint.
Fyi, these two new endpoints will not return 404.

[QA] BOAC-3068, get-advisor-info is strictly CalNet-based, no authorized_user dependency

---

boac/api/user_controller.py
src/api/user.ts
src/components/note/AdvisingNote.vue
src/store/modules/user.ts
tests/test_api/test_student_controller.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-3069
The work of BOAC-3068 made `/api/user/by_csid` obsolete. *Note:* client-side caching of CalNet data is overkill cuz it's cached on server-side; we don't need the overhead in vue-store.

BOAC-3069, remove unused /api/user/by_csid

---

boac/api/admin_controller.py
boac/api/cache_utils.py
boac/api/config_controller.py
boac/api/search_controller.py
boac/externals/data_loch.py
boac/lib/berkeley.py
boac/merged/cohort_filter_options.py
boac/merged/reporter.py
boac/merged/sis_terms.py
boac/merged/student.py
boac/models/alert.py
boac/models/cohort_filter.py
config/default.py
fixtures/loch.sql
run.py
tests/test_api/test_cache_utils.py
tests/test_externals/test_data_loch.py
tests/test_lib/test_berkeley.py
tests/test_merged/test_sis_terms.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-3002
boa-dev will continue to rely on the term configs in boac-dev.py until those are switched to 'auto'.   I'll wait until things are settled on the Nessie side before making that switch.

BOAC-3002: Looks to the loch for term configs

---

src/components/appointment/DropInAppointmentDropdown.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-3094
Low-risk enhancement for `qa`: 'Assign to me' on Drop-in advisor `/home`.  The full BOAC-3094 fix will land on master.

[QA] BOAC-3094, drop-in advisor sees 'Assign to me' rather than 'Assign'

---

src/views/DropInAdvisorHome.vue
src/views/DropInDesk.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-3102
We do not want another refresh-waitlist thread every time user edits an appt.

BOAC-3102, do not set apptDeskRefreshInterval on user-initiated appt update

---

boac/api/appointments_controller.py
boac/api/util.py
src/components/appointment/DropInAppointmentDropdown.vue
tests/test_api/test_appointments_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-3102
The appointment API – in case of reserve, unreserve, cancel, and check-in – does not return an appointment object (JSON). This streamlines the transactions and has the front-end feeling zippier.

BOAC-3102, fix for un-assign self from appt, then appt not updated immediately

---

scripts/db/migrate/2019/20191218-BOAC-3163/pre_deploy_01_revise_topics.sql

https://jira.ets.berkeley.edu/jira/browse/BOAC-3163
I think a hard delete is justified because (1) `available_in_notes = false` and (2) the appointments feature is not yet in use.

BOAC-3163, remove unwanted topic: Readmission, Withdrawal

---

src/components/student/profile/StudentClasses.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-3173
Also, `relevantTerms` does not need to be "computed" value.

[QA] BOAC-3173, Student page > no 'more semesters' button if enrollmentTerms.length <= size(relevantTerms)

---

boac/models/authorized_user.py
scripts/db/migrate/2020/20200106-BOAC-3189/pre_deploy_01_add_search_history_column.sql
scripts/db/schema.sql

https://jira.ets.berkeley.edu/jira/browse/BOAC-3189
We will keep it simple in first iteration of this feature: add `search_history` column to `authorized_users`.

BOAC-3189, db schema mod for search history feature

---

boac/api/search_controller.py
src/api/search.ts
src/components/sidebar/SearchForm.vue
src/components/util/Autocomplete.vue
tests/test_api/test_search_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-3191
Suggestions from search history are shown when you first put focus on input and the list narrows as you type. The new `restrict` prop in `Autocomplete` allows for a query that is _not_ in list o' suggestions.

BOAC-3191, suggestions from search-history using Autocomplete component

---

src/components/sidebar/SearchForm.vue
src/components/util/Autocomplete.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-3204
Two fixes:
* We use the more reliable `$refs.searchInput.getQuery()` instead of computed `searchInput`. 
* In sidebar search, do not clear input when `clickOutside`.

BOAC-3204, SearchForm uses getQuery in child component to get input

---

src/components/util/Autocomplete.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-3207
Before search history work, this function was:
```
onClickOutside(evt) {
if (!this.$el.contains(evt.target)) {
this.closeSuggestions();
}
}
```
This PR restores that outer conditional.

BOAC-3207, search: onClickOutside if evt.target is outside input el

---

boac/models/authorized_user.py
src/components/sidebar/SearchForm.vue
src/components/util/Autocomplete.vue
tests/test_api/test_search_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-3209
Search input and search history entries have max-length 256.

BOAC-3209, friendly truncation of search history entries

---

src/components/appointment/DropInAdvisorList.vue
src/components/appointment/DropInAvailabilityToggle.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-3223
Gets the front-end element in place and working, but doesn't yet disentangle the new supervisor status from the old supervisor person type.

BOAC-3223 Three-way toggle for drop-in advisor status

---

boac/api/user_controller.py
boac/models/development_db.py
boac/models/drop_in_advisor.py
scripts/db/migrate/2020/20200128-BOAC-3269/pre_deploy_01_add_drop_in_advisors_status.sql
scripts/db/schema.sql
src/api/user.ts
tests/test_api/test_cache_utils.py
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-3269
Adding a new status field required cleaning up some previous loose usage of the word "status."
The "isAvailable" boolean feed value represents not a "status" but an "availability."
The entire feed object corresponding to a row in the drop_in_advisors table is not a "status" but a "membership."

BOAC-3269 Back end for drop-in status text

---

src/components/appointment/AppointmentAssignModal.vue
src/components/appointment/CheckInModal.vue
src/components/appointment/CreateAppointmentModal.vue
src/components/appointment/DropInAppointmentDropdown.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-3094
Plus, `availableAdvisors` should always include `currentUser`, if s/he is an advisor in dept.

BOAC-3094, drop-in home: check-in student on behalf of other advisor

---

boac/lib/cohort_utils.py
boac/merged/cohort_filter_options.py
boac/models/cohort_filter.py
tests/test_api/test_cohort_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-3325
https://jira.ets.berkeley.edu/jira/browse/BOAC-3340
* using filter keys from `cohort_filter_options` guarantees consistency in `cohort.to_api_json`
* in `cohort_filter`, I broke off `to_base_json()` to reduce complexity in `to_api_json` (fewer lines of code)
* no more `_mock_ce3_students()`

BOAC-3340, simpler cohort_filters.to_api_json uses get_all_filter_categories() to get keys and types

---

src/store/modules/current-user-extras.ts

https://jira.ets.berkeley.edu/jira/browse/BOAC-3432
Seems like Vue can't track updates to this value unless it starts out in the store.

BOAC-3432 Restore admit search checkbox

---

boac/api/appointments_controller.py
boac/api/notes_controller.py
boac/api/search_controller.py
boac/externals/data_loch.py
boac/lib/berkeley.py
boac/lib/util.py
boac/merged/advising_appointment.py
boac/merged/advising_note.py
boac/models/appointment.py
boac/models/development_db.py
boac/models/note.py
fixtures/calnet_search_entries.json
fixtures/loch.sql
tests/test_api/test_search_controller.py
tests/test_merged/test_advising_appointment.py

- Updates search form Advisor autocomplete to include SIS appointment advisors
- Includes new SIS appointment tables in the search query
- Introduces `advising_appointment` merged model to represent both BOA and SIS appointments
- Resolves some technical debt in the notes code

BOAC-3309: Includes SIS appointments in appointment search results

---

buildspec.yml

https://jira.ets.berkeley.edu/jira/browse/BOAC-3521
In Jira above, Darlene asks, "Is there a way to trigger a build failure to see if the CodePipeline notification rule catches it?"
Yes there is...

BOAC-3521, force AWS CodeBuild failure to test Slack integration

---

boac/externals/data_loch.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-3540

BOAC-3540: Makes appts without advisor details searchable in Acad Timeline

---

boac/externals/data_loch.py

master PR #2490 
https://jira.ets.berkeley.edu/jira/browse/BOAC-3540

[qa] BOAC-3540: Makes appts without advisor details searchable in Acad Timeline

---

requirements.txt
tox.ini

Travis failed on PR #2508 due to mysterious flake8 error. I'm bumping up related deps to avoid a repeat.

NOJIRA, upgrade tox and flake8 to avoid weird lint-py errors

---

boac/api/auth_controller.py
boac/api/user_controller.py
requirements.txt

https://jira.ets.berkeley.edu/jira/browse/BOAC-3611
Flask-login release notes: https://github.com/maxcountryman/flask-login/blob/0.5.0/CHANGES. (`user_callback` and `reload_user` changes rolled out in https://github.com/maxcountryman/flask-login/pull/378)

BOAC-3611, update py-deps; flask-login dropped user_callback and reload_user

---

README.md

https://jira.ets.berkeley.edu/jira/browse/BOAC-3621
A complete run of BOA tests and linters in parallel mode is ~60 seconds faster than standard Tox mode.
Use `tox -p` instead of `tox`.

BOAC-3621, recommend 'tox --parallel' in README

---

boac/api/notes_controller.py
boac/api/student_controller.py
boac/merged/advising_note.py
boac/merged/student.py
src/api/notes.ts
src/api/student.ts
src/components/note/create/BatchNoteFeatures.vue
src/components/note/create/CreateNoteFooter.vue
src/components/note/create/CreateNoteModal.vue
src/components/student/profile/AcademicTimeline.vue
src/mixins/NoteEditSession.vue
src/store/modules/note-edit-session.ts
tests/test_api/test_notes_controller.py
tests/test_api/test_student_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-3626
`/api/notes/batch/distinct_student_count` is now `/api/students/distinct_sids` because (1) there's nothing note specific about it, and (2) speeds up client-side by having complete-sids-set instead of just a count.

BOAC-3626, better communication between create-note transaction and AcademicTimeline

---

src/components/admin/Users.vue
src/views/DropInDesk.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-3637
I recently removed parens from `@change="$refs.users.refresh()"` per best practice.  Without parens, Vue immediately loads the pointer `$refs.users.refresh`, which bombs if `$refs.users` is not yet initialized.

BOAC-3637, account for undefined $refs.users during Passenger Manifest page load

---

package-lock.json
package.json

https://jira.ets.berkeley.edu/jira/browse/BOAC-3635
https://bootstrap-vue.org/docs/reference/changelog

BOAC-3635, upgrade bootstrap-vue from to 2.4.0 to 2.16.0

---

src/assets/styles/bootstrap-overrides.css

https://jira.ets.berkeley.edu/jira/browse/BOAC-3638
Restore fragment removed in [PR 2565](https://github.com/ets-berkeley-edu/boac/pull/2565/files#diff-877d6aefac3ef44a76822e86b083ab39) and tweak the CSS, adding `div::after`.

BOAC-3638, fix b-table sort icon after bootstrap upgrade

---

boac/externals/data_loch.py
boac/merged/student.py
boac/models/alert.py
tests/test_api/test_alerts_controller.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_curated_group_controller.py
tests/test_api/test_student_controller.py
tests/test_models/test_alert.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-3630
In this scheme for `academic_standing` alerts, we set `created_at = action_date` and then leverage `preserve_creation_date`. But, with a fixed `created_at` date we run up against the uniqueness constraint of the `alerts` table: if we `create_or_activate()` twice then we hit uniqueness violation. We work around this by adding (1) `action_date` to the key and (2) optional `create_or_activate(... force_use_existing)` arg – for now, used solely by `academic_standing` alerts.
I'll submit QA PR if/when this is merged.

BOAC-3630, academic_standing alerts: use action_date for created_at and preserve

---

requirements.txt

https://jira.ets.berkeley.edu/jira/browse/BOAC-3662

BOAC-3662, downgrade ldap3 from 2.8 to 2.7

---

src/components/note/EditAdvisingNote.vue
src/components/note/SessionExpired.vue
src/components/note/create/BatchNoteFeatures.vue
src/components/note/create/CreateNoteFooter.vue
src/components/note/create/CreateNoteHeader.vue
src/components/note/create/CreateNoteModal.vue
src/main.ts
src/mixins/NoteEditSession.vue
src/store/modules/note-edit-session.ts

https://jira.ets.berkeley.edu/jira/browse/BOAC-3656
This UI change does not perfectly match design in https://jira.ets.berkeley.edu/jira/browse/BOAC-3628 but it serves its purpose. QA and UX can state their opinions after merge.
Use `?w=1`
In screenshot below, notice that buttons are gone and alert is shown. Plus, all form elements are disabled.

BOAC-3656, disable create/edit note when BOA session expires, with messaging

---

src/components/sidebar/SearchForm.vue
src/components/util/Autocomplete.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-3686
I'm removing the `required` attribute on the auto-suggest search input element – it's only set to true for a particular type of sidebar search. The aria-label better communicates state. I've also added sr-alerts and better focus.

BOAC-3686, screen-reader friendly search input, validation

---

src/components/note/AdvisingNote.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-3697

BOAC-3697: Hides attachments from SR when note is collapsed

---

src/views/Search.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-1575
The sr-only h1 is present, even before results load. Informative sub-headings get `aria-live=polite`.

BOAC-1575, polite sr alerts when search results load

---

buildspec.yml

I want to rule out shifting node versions as a cause.

BOAC-3746, buildspec: 'nvm use' before vue-cli build, in case wrong node version

---

buildspec.yml

`nvm` is not in $PATH but we were able to verify that proper node version is in use. Let's run another build to test the recent removal of `npm install -g @vue/cli`.

BOAC-3746, remove 'nvm use'; build phase has expected node version

---

src/components/note/create/CreateNoteModal.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-3700

BOAC-3700: Prevents arrow keys from breaking out of create note modal

---

buildspec.yml
package-lock.json

CodeBuild spits out warning: 
```
[Container] 2020/10/14 23:23:38 Running command npm install
--
34 | npm WARN lifecycle boac@~preinstall: cannot run in wd boac@ npx npm-force-resolutions 
```
Which lead me to https://til.codes/npm-install-failed-with-cannot-run-in-wd-2 and the wishful fix is in this PR. Also, I did a fresh `npm install` locally and package-local was modified, so I include it.

BOAC-3746, 'npm install --unsafe-perm' to debug 'cannot run in wd' error (CodePipeline)

---

src/components/student/profile/StudentProfileHeader.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-3695
Swap columns in the page structure, use `flex-direction: row-reverse` to preserve visual layout.

BOAC-3695 Change student profile structure for screenreader ordering

---

buildspec.yml

Explicit global install of `vue/cli` should not be necessary – in fact, CodePipeline has had success without it. And yet, Nessie and Diablo buildspecs have it. Perhaps it will end our random failures.

NOJIRA, buildspec: npm install -g @vue/cli

---

src/components/cohort/ApplyAndSaveButtons.vue
src/components/student/SortBy.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-3755
Also, the stray `screenReaderAlert` in `ApplyAndSaveButtons` caused double-speak of alerts.

BOAC-3755, improve visual grouping in sort-by dropdown

---

src/components/cohort/FilterRow.vue
src/components/student/SortBy.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-3760
Oddly, the `dropdown-item` class was disabling nav by arrow keys. I have a small Teena change that will follow this PR merge.

BOAC-3760, cohort filter dropdowns navigable by arrow keys

---

package-lock.json
package.json
src/api/user.ts
src/components/appointment/DropInWaitlist.vue
src/components/cohort/ApplyAndSaveButtons.vue
src/components/curated/CuratedGroupSelector.vue
src/components/curated/CuratedStudentCheckbox.vue
src/components/note/EditAdvisingNote.vue
src/components/note/create/CreateNoteModal.vue
src/components/student/SortBy.vue
src/components/student/profile/AcademicTimeline.vue
src/main.ts
src/store/modules/current-user-extras.ts
src/store/modules/note-edit-session.ts
src/views/AdmitStudents.vue
src/views/Cohort.vue
src/views/CuratedGroup.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-3624
This event-listening pattern is one of the [few breaking changes on path to Vue 3 upgrade](https://medium.com/js-dojo/vue-3-new-features-breaking-changes-a-migration-path-e075a9b3d3d5). This change seems low risk and now is a good time for it, with full-regression testing scheduled on accessibility work. (Link above has details on "replace Event bus usages with mitt library.")

BOAC-3624, discard deprecated Vue.prototype.$eventHub.emit pattern

---

package-lock.json
package.json

This PR is aimed at our CodePipeline failures.
If this version of `execa` is too far ahead of the vue-cli curve then I'll try `execa v2.0.0`.

BOAC-3746, force 'execa' v4.0.3 for more error info and support for more recent node

---

package-lock.json
package.json

Re: CodePipeline fails. I've been going through commit history looking for clues. There was a babel upgrade not long before the start of periodic CodeBuild failures. Furthermore, `babel` is not a runtime dependency so I'm testing it out in dev-deps section.

BOAC-3746, move babel to dev deps (package.json) and execa to 'resolutions' section

---

src/components/curated/dropdown/ManageStudent.vue
src/components/student/StudentRow.vue

Keep the widget visible during add/remove confirmation by delegating `sr-only` to the child component.

BOAC-1481, manage curated-groups per student: styles and focus

---

src/App.vue
src/layouts/StandardLayout.vue
src/views/Course.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-1480
And, in `App.vue` we want `aria-live` on footer warning and not debug info devs get in local env. This should clear up dupe sr-voicing.

BOAC-1480, sr-alert when switching between 50 and 100 results

---

src/App.vue
src/components/util/DismissibleFooterAlert.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-1476
When devs are running BOA in local env, sr-alerts are visible in footer. But, in App.vue, `$announcer.data.content` changes were not rendering. Having a dedicated component fixed the prob. Cleaner.

BOAC-1476, local env: sr-alert in dismissible footer was not updating

---

src/components/cohort/CohortPageHeader.vue
src/components/cohort/FilterRow.vue
src/views/Cohort.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-1476
If a button has `disabled=true` then focus cannot be put on it and its label is not announced. If we toss out `disabled=true` and have only `aria-disabled=true` then sighted users can click on it. This is a [known issue w.r.t screen-readers and disabled buttons](https://ux.stackexchange.com/questions/103239/should-disabled-elements-be-focusable-for-accessibility-purposes).
I have cheated a bit. If menu option is disabled then a sr-only `aria-disabled` button is put under the hood. The screen-reader voices the button content and sighted users see no difference.

BOAC-1476, screen reader tells us if filter option is disabled

---

src/api/auth.ts
src/layouts/shared/ServiceAnnouncement.vue
src/main.ts
src/store/modules/context.ts

https://jira.ets.berkeley.edu/jira/browse/BOAC-3678
Fixed bug in which service-announcement is not loaded after dev-auth login. This would not impact real users because CAS login forces page refresh. Nonetheless, a bug.

BOAC-3678, sr-only header above service-announce; refresh alert on dev-auth

---

scripts/db/migrate/2019/20190924-BOAC-2620/post_deploy_01_gpa_json_in_cohort_filter.py
src/components/student/profile/StudentProfileGPA.vue
tox.ini

https://jira.ets.berkeley.edu/jira/browse/BOAC-1420
We were getting "no such alertScreenReader() method" error in console.

BOAC-1420, Context mixin for srAlert call

---

src/components/note/AdvisingNote.vue

I believe this clears up the blocker issue in https://jira.ets.berkeley.edu/jira/browse/BOAC-3799, but our whole caching setup for note authors has gotten pretty unruly and seems due for a rethink.

[QA] BOAC-3799 Fix unwanted in-component caching of note authors

---

boac/api/reports_controller.py
boac/models/alert.py
boac/models/cohort_filter.py
scripts/db/migrate/2020/20201211-BOAC-3596/pre_deploy_01_put_deleted_at_on_alerts.sql
scripts/db/schema.sql
tests/test_api/test_reports_controller.py
tests/test_models/test_alert.py

To fulfill the request for "alert duration" (see latest comment in Jira above) we convert the 'active' column to 'deleted_at' and then do the math to determine: how long was it active?  The 'deleted_at' value will often be flipped off and on during `update_all_alerts` job and that's okay.

BOAC-3596, ALTER TABLE alerts ADD COLUMN deleted_at (and drop 'active' column)

---

package-lock.json
package.json
src/components/admin/AlertsLogExport.vue
src/components/sidebar/SearchForm.vue

For reasons of accessibility, we might want to drop `v-calendar` and use Bootstrap's https://bootstrap-vue.org/docs/components/calendar, which calls out accessibility and keyboard-only features.

BOAC-3596, bootstrap input wrapped in v-date-picker -> breakage

---

boac/merged/cohort_filter_options.py
src/components/cohort/FilterRow.vue
src/components/cohort/FilterSelect.vue
src/store/modules/cohort-edit-session.ts

https://jira.ets.berkeley.edu/jira/browse/BOAC-3743
* Do not render options until server-side has disabled options, etc.
* Slim down JSON payload with `option['availableTo'] = '*'` instead of complete dept list

BOAC-3743, cohort filter select menu disabled until latest optGroups loaded

---

boac/lib/berkeley.py
boac/merged/student.py
src/components/student/profile/StudentClasses.vue
src/components/student/profile/StudentCourse.vue
src/components/student/profile/StudentEnrollmentTerm.vue
src/mixins/Berkeley.vue
tests/test_api/test_student_controller.py
tests/test_lib/test_berkeley.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-3828
https://jira.ets.berkeley.edu/jira/browse/BOAC-3842
https://jira.ets.berkeley.edu/jira/browse/BOAC-3837
For every academic year in which the student is enrolled in at least one term, all three terms (Fall, Spring, and Summer) will be shown.  The current academic year will be expanded by default.

BOAC-3828, BOAC-3842, BOAC-3837: Displays relevant empty terms

---

.travis.yml
requirements.txt

https://jira.ets.berkeley.edu/jira/browse/BOAC-3819
Travis concurrency is not free and `tox --parallel` is.

BOAC-3819, no more concurrent jobs in travis.yml; use tox --parallel

---

src/components/search/InputAutocomplete.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-3912
The existing `@submit` will handle key-press events.

BOAC-3912, keypress.enter.prevent=noop for input-autocomplete widget

---

src/views/AdmitStudent.vue

I decided to make it an h6 instead of an h2, since h2 is way too big, and h6 better matches the design docs. Attached pic is with h2.
JIRA: https://jira.ets.berkeley.edu/jira/browse/BOAC-3943

BOAC-3943: Changed table headings to headings, fixed language for SR

---

boac/api/user_controller.py
boac/api/util.py
boac/merged/user_session.py
boac/models/authorized_user.py
boac/models/development_db.py
scripts/db/drop_schema.sql
scripts/db/migrate/2021/20210406-BOAC-3965/pre_deploy_01_add_degree_progress_permission.sql
scripts/db/schema.sql
tests/test_api/test_user_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-3965
The `authorized_users` table is modified as below and yet the `user_session` object has aliased properties: `can_edit_degree_progress` and `can_read_degree_progress`.
```
CREATE TYPE generic_permission_types AS ENUM ('read', 'read_write');
ALTER TABLE authorized_users ADD COLUMN degree_progress_permission generic_permission_types;
```
Constructive criticism is welcome.

BOAC-3965, authorized_user table gets degree_progress_permission (read, read_write)

---

boac/api/cache_utils.py
boac/api/degree_progress_controller.py
boac/models/authorized_user.py
boac/models/development_db.py
fixtures/loch/loch.sql
tests/test_api/test_cache_utils.py
tests/test_api/test_user_controller.py
tests/test_externals/test_data_loch.py
tests/test_models/test_university_dept.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-3967
BOA's test data is becoming technical debt. Add a mock user and you get a handful of failures.

BOAC-3967, cache_utils + create_or_restore_user() will keep custom degree-progress perm

---

boac/api/degree_progress_controller.py
src/router.ts
src/views/degree/ManageDegreeChecks.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-4028
And I renamed `DegreeChecks.vue` to `ManageDegreeChecks.vue`.

BOAC-4028, fix rename validation: int(id) needed when comparing ids

---

boac/api/degree_progress_api_utils.py
boac/models/degree_progress_category.py
boac/models/degree_progress_course.py
src/components/degree/CoursesTable.vue
src/components/degree/student/CourseAssignmentMenu.vue
src/components/degree/student/UnassignedCourses.vue
src/mixins/DegreeEditSession.vue
src/store/modules/degree-edit-session.ts
tests/test_api/test_degree_progress_student_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-4067
Keeping `unassignedCourses` in vuex story allows us to refresh page content behind the scenes.

BOAC-4067, fix server-side logic in get_unassigned; keep 'unassigned' courses in vuex store

---

boac/api/degree_progress_controller.py
boac/api/degree_progress_student_controller.py
boac/api/student_controller.py
boac/api/util.py
boac/models/degree_progress_template.py
tests/test_api/test_degree_progress_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-4164
Degree template/check objects are bloated by categories, courses, etc. The listing pages only need name, id, and not much else.

BOAC-4164, speed up page load of /degrees and /degree/history with slimmer queries

---

requirements.txt

https://jira.ets.berkeley.edu/jira/browse/BOAC-4175
Flask 2: https://flask.palletsprojects.com/en/2.0.x/

BOAC-4175, upgrade flask-cors to move past vulnerability; includes Flask upgrade

---

src/components/degree/CoursesTable.vue
src/store/modules/degree-edit-session.ts
src/views/degree/StudentDegreeCheck.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-4172
CSS to highlight drop-zones without shakiness in DOM elements.

BOAC-4172, drag (and drop) gotta have style

---

src/components/degree/student/UnassignedCourses.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-4229
I missed this line when turning `UnassignedCourses` into shared component.

BOAC-4229, fix dragContext value when dragging from junk -> unassigned

---

boac/api/config_controller.py
boac/api/degree_progress_student_controller.py
boac/models/degree_progress_category.py
scripts/db/migrate/2021/20210608-BOAC-4198/pre_deploy_degree_progress_category_type_add_value.sql
scripts/db/schema.sql
src/components/degree/CoursesTable.vue
tests/test_api/test_config_controller.py
tests/test_api/test_degree_progress_student_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-4198
The db.migrate script adds a new category_type to identify “copied” courses. Read the Jira for more detail.

BOAC-4198, copied-course can be moved and, in the process, its placeholder category is deleted

---

boac/api/degree_progress_student_controller.py
boac/models/degree_progress_category.py
src/api/degree.ts
src/components/degree/Category.vue
src/components/degree/CoursesTable.vue
src/components/degree/student/AddCourseToCategory.vue
src/components/degree/student/CourseAssignmentMenu.vue
src/components/degree/student/UnassignedCourses.vue
src/mixins/DegreeEditSession.vue
src/store/modules/degree-edit-session.ts
tests/test_api/test_degree_progress_student_controller.py

https://jira.ets.berkeley.edu/jira/browse/BOAC-4251
Previously, we would simply delete the placeholder-category and rely on Postgres to cascade-delete. Now we need custom logic to inspect the assignment and protect courses which are _not_ copies.

BOAC-4251, new rules for copied courses (eg, pay attention to category_type of assignment)

---

src/components/degree/CoursesTable.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-4259
And, component has no `drop-zone-off` style so it is removed from the `tr`.

BOAC-4259, remove bg color on course-row when hover is done

---

src/components/degree/student/CourseAssignmentMenu.vue
src/views/degree/PrintableDegreeTemplate.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-4282
Printable view did not get this fix when it was dropped on standard view. PR also includes sr-only text for course-assignment-menu button.

BOAC-4282, /print view must include courses associated directly w/ (sub)categories

---

boac/models/cohort_filter.py
src/main.ts

https://jira.ets.berkeley.edu/jira/browse/BOAC-4335
For certain edge cases, `main.ts` was invoking `/api/user/my_profile` which is invalid. It's been corrected.

BOAC-4335, sids=[] and student_count=0 when creating empty cohort

---

src/views/degree/BatchDegreeCheck.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-4334
I removed the `isRecalculating || isValidating` condition from message block to avoid a herky jerky div.

BOAC-4334, if sidsToInclude > 0 then show no 'group has no students' alert

---

src/components/sidebar/SearchForm.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-4337
According to https://www.w3.org/WAI/tutorials/forms/instructions/#placeholder-text, "placeholder text is not broadly supported across assistive technologies."

BOAC-4337, screen readers skip input placeholder; add the same text to sr-only label

---

src/main.ts

We recently fixed the API path used to refresh user "in case session expired." The fix surfaced a new bug, fixed here.

BOAC-4352, response.data when 403 in axios.interceptors.response.use

---

package-lock.json
package.json

The `vue-template-compiler` upgrade gets us past the error seen in PR #3191.

BOAC-4352, minor version bumps for vue, vue-router and vue-template-compiler

---

tsconfig.json

This is an experiment. I will either roll it back or bring back a subset of strict-type configs: https://www.typescriptlang.org/tsconfig#strict
Why I think this is worth a try:
https://github.com/VincentGarreau/particles.js/issues/123

BOAC-4352, experimental fix by removing strict=true from tsconfig

---

scripts/db/drop_schema.sql
scripts/db/migrate/2021/20210726-BOAC-4199/pre_deploy_01_course_manually_created_by.sql
scripts/db/schema.sql

https://jira.ets.berkeley.edu/jira/browse/BOAC-4355
Note:
* We drop the 'NOT NULL' constraint on `section_id` and `term_id` because manually created course may have neither value. And `display_name` added to unique-constraint because manually created courses must be unique in name.
* You'll notice that `accent_color` is not an enum. The mapping of color name to hex will be done in code. 
* Release instructions updated

BOAC-4355, degree progress schema change for manual course creation

---

src/components/degree/Category.vue
src/views/degree/PrintableDegreeTemplate.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-4360
https://jira.ets.berkeley.edu/jira/browse/BOAC-4367
Includes `text-wrap` fix on `<pre>`.
Use `?w=1` for simpler diff.

BOAC-4360, course.accentColor determines text style in /print view

---

scripts/db/migrate/2021/20210727-BOAC-4199/pre_deploy_01_degree_course_constraints.sql

https://jira.ets.berkeley.edu/jira/browse/BOAC-4199
I delayed this PR in case requirements changed again, requiring schema tweaks. Note: we're changing the uniqueness constraint because duplicate names are allowed in manually-created courses.

BOAC-4199, second db-modify script for manually-created courses (grade is nullable, tweak uniqueness constraint)

---

src/components/degree/CoursesTable.vue
src/components/degree/student/CourseAssignmentMenu.vue
src/components/degree/student/UnassignedCourses.vue
src/views/degree/StudentDegreeCheck.vue

https://jira.ets.berkeley.edu/jira/browse/BOAC-4409
Give and take w.r.t accessibility. After course assignment, the 'Unassigned' header is the only feasible focus target. Thus, the h3 gets tabindex="-1".  Same for 'Free Electives'.

BOAC-4409, after assign junk/unassigned course, put focus on component header

---

src/components/student/profile/AcademicTimelineTable.vue

https://jira-secure.berkeley.edu/browse/BOAC-4466
Owner cannot edit his/her own private note if s/he lost the `canAccessPrivateNotes` permission.

BOAC-4466, tweak logic on who can edit a private note

---

boac/api/notes_controller.py

https://jira-secure.berkeley.edu/browse/BOAC-4527

BOAC-4527, null-safe check during note attachment download

---

boac/api/notes_controller.py

https://jira-secure.berkeley.edu/browse/BOAC-4527
dev PR is #3361

[QA] BOAC-4527, null-safe check during note attachment download

---

src/components/student/DegreesAwarded.vue

Very minor tweak; QA PR not necessary. Guarantees flattened array for `join(plans, ';')`.

BOAC-4529, semicolon separator when 'plans' array is flat (DegreesAwarded)

---

.ebextensions/00_ami.config

Our use of JSON-based config might have screwy syntax?!

BOAC-4524, old-school YAML for cloudwatch config in 00_ami.config

---

boac/api/notes_controller.py
tests/test_api/test_notes_controller.py

https://jira-secure.berkeley.edu/browse/BOAC-4520
We do the same encoding in /api/notes/attachment/<attachment_id>
(Accidentally deleted branch of PR #3369)

BOAC-4520, /api/notes/download_for_sid: sanitize filename for download

---

.ebextensions/00_ami.config

Old-school YAML did not fix the problem.
This reverts commit d27ad397bf78259fc25bc8f65ea4a585a1662e2e.

BOAC-4524, Revert old-school YAML for cloudwatch config

---

src/mixins/Attachments.vue
src/views/degree/StudentDegreeCheck.vue

https://jira-secure.berkeley.edu/browse/BOAC-4503
Fixes error I hit when testing drag/drop on Windows + Chrome.

BOAC-4503, protect against null event.target.classList

---

.ebextensions/00_ami.config

Following AWS docs: https://aws.plainenglish.io/how-to-setup-aws-elasticbeanstalk-to-stream-your-custom-application-logs-to-cloudwatch-d5c877eaa242
More tweaks might follow.

BOAC-4524, ebextension: /etc/awslogs/config/logs.conf per AWS docs

---

boac/models/cohort_filter.py
boac/models/curated_group.py
boac/models/db_relationships.py
scripts/db/migrate/2021/20211206-BOAC-4562/add_domain_column_curated_groups.sql
scripts/db/schema.sql

https://jira-secure.berkeley.edu/browse/BOAC-4562
The db table of curated groups will leverage enum type `cohort_domain_type`. Renaming the enum would be too disruptive.

BOAC-4562, add 'domain' column to curated_groups table (as seen in cohorts table)

---

.ebextensions/00_ami.config

Seemingly benign syntax tweaks to match what we know is working: https://github.com/ets-berkeley-edu/nessie/blob/release/.ebextensions/30_create_cloudwatch_conf.config

BOAC-4524, Cloudwatch config: remove extraneous spaces, format tweaks

---

src/components/cohort/CohortPageHeader.vue
src/components/curated/CuratedGroupHeader.vue
src/components/sidebar/MyAdmitCohorts.vue
src/components/sidebar/Sidebar.vue

https://jira-secure.berkeley.edu/browse/BOAC-4595
https://jira-secure.berkeley.edu/browse/BOAC-4599
Plus, sidebar fix per `canAccessAdmittedStudents`.

BOAC-4599 & BOAC-4595, if cohort/group is CE3 then use 'admit', not 'student'

---

boac/merged/student.py
fixtures/loch/student_profile_11667051.json
fixtures/loch/student_profile_summary_11667051.json
fixtures/loch/student_profile_summary_2345678901.json
fixtures/loch/student_profile_summary_3456789012.json
fixtures/loch/student_profile_summary_5678901234.json
fixtures/loch/student_profile_summary_7890123456.json
fixtures/loch/student_profile_summary_8901234567.json
fixtures/loch/student_profile_summary_890127492.json
fixtures/loch/student_profile_summary_9000000000.json
fixtures/loch/student_profile_summary_9100000000.json
fixtures/loch/student_profile_summary_completed_2718281828.json
fixtures/loch/student_profile_summary_inactive_3141592653.json
tests/test_api/test_course_controller.py
tests/test_merged/test_student.py

https://jira-secure.berkeley.edu/browse/BOAC-2216
`termGpa` and `academicStanding` are not used on the course page, and `currentTerm` isn't used on any page.

BOAC-2216: Removes unused student profile elements currentTerm, termGpa, academicStanding

---

boac/api/cache_utils.py

https://jira-secure.berkeley.edu/browse/BOAC-4619

BOAC-4619, DP automated perms: consider (temporarily) deleted users during cachejob/refresh

---

boac/models/development_db.py
tests/conftest.py
tests/test_api/test_auth_controller.py
tests/test_api/test_cache_utils.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_course_controller.py
tests/test_api/test_curated_group_controller.py
tests/test_api/test_search_controller.py
tests/test_api/test_student_controller.py
tests/test_api/test_user_controller.py
tests/test_merged/test_advising_appointment.py
tests/test_models/test_university_dept.py

Trying to avoid the pitfalls of not-always-static test data.

NOJIRA, less hard-coded test data in development_db; advisor_factory fixture instead

---

boac/models/development_db.py
tests/conftest.py
tests/test_api/test_auth_controller.py
tests/test_api/test_cache_utils.py
tests/test_api/test_cohort_controller.py
tests/test_api/test_course_controller.py
tests/test_api/test_curated_group_controller.py
tests/test_api/test_search_controller.py
tests/test_api/test_student_controller.py
tests/test_models/test_authorized_user.py

https://jira-secure.berkeley.edu/browse/BOAC-4629
Test coverage is tricky when all test data is hard-coded in development_db. A bloated BOA needs smart fixtures w.r.t mock users and the associated data_loch rows. This is a first pass at more collision-proof test data.
A follow up PR will have fix to BOAC-4629 and test coverage w/ a multi-dept user.

BOAC-4629, conftest/development_db refactor to support users with 2+ depts

---

boac/merged/sis_sections.py
src/views/Course.vue

https://jira-secure.berkeley.edu/browse/BOAC-4639
See the Jira for details. Diablo has a similar issue: https://jira-secure.berkeley.edu/browse/DIABLO-717

BOAC-4639, if section has 2+ meetings, include start/end dates in uniqueness key
