boac/merged/student.py, tests/test_api/test_course_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1345
=> BOAC-1345 Include midterm grades on class pages

boac/merged/student.py, tests/test_api/test_course_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1345
QA version of #959.
=> [QA] BOAC-1345 Include midterm grades on class pages

README.md, boac/api/auth_controller.py, boac/static/app/nav/sidebarNavComponent.js, boac/static/app/routes.js, boac/static/app/splash/loginController.js, boac/static/app/user/authService.js, tests/test_api/test_auth_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1355
I snuck in README changes and a camelCaseFix.
=> BOAC-1355, sidebar-nav had wrong isAscUser logic after recent refactor

boac/static/app/course/courseController.js, boac/static/app/routes.js, boac/static/app/student/student.html
https://jira.ets.berkeley.edu/jira/browse/BOAC-1330
This satisfies the first requirement; will amend or submit a follow-up for the second.
=> BOAC-1330: displays searched student at top of class list

boac/__init__.py, boac/api/config_controller.py, boac/externals/cal1card_photo_api.py, boac/lib/berkeley.py, boac/lib/scriptify.py, boac/models/alert.py, boac/models/job_progress.py, consoler.py, run.py, scripts/db/migrate/20180327-BOAC-613/copy_advisor_lists_to_student_groups_table.py, scripts/db/migrate/20180418-BOAC-782/pre_deploy_02_migrate_asc_advisors.py, scripts/db/migrate/20180809-BOAC-1147/create_my_students_cohort_per_uid.py, scripts/db/migrate/20180822-BOAC-1165/alter_advisor_uid_key_in_cohort_json.py, scripts/scriptpath.py, scripts/student_api_fixtures.py, tests/test_models/test_cohort_filter.py, tests/test_models/test_job_progress.py, tox.ini
https://jira.ets.berkeley.edu/jira/browse/BOAC-1356
=> BOAC-1356, update flake8 linting rules and fix certain violations

boac/api/student_controller.py, boac/externals/data_loch.py, fixtures/loch.sql, tests/test_api/test_student_controller.py, tests/test_externals/test_data_loch.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1352
=> BOAC-1352 Query interface for student/course name search

.eslintrc.yml, boac/api/student_controller.py, boac/externals/data_loch.py, boac/static/app/main.css, boac/static/app/search/searchController.js, boac/static/app/search/searchResults.html, boac/static/app/search/searchStudentsForm.html, tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1353
Designs at https://jira.ets.berkeley.edu/jira/browse/BOAC-1325.
=> BOAC-1353 Front end for student/class search

boac/static/app/course/course.css, boac/static/app/course/course.html, boac/static/app/course/courseController.js, boac/static/app/main.css
https://jira.ets.berkeley.edu/jira/browse/BOAC-1330
=> BOAC-1330: adds control to change class list page size

boac/static/app/cohort/filtered/cohortController.js
https://jira.ets.berkeley.edu/jira/browse/BOAC-1404
=> BOAC-1404, restore ASC 'Inactive' alert on filtered-cohort view

boac/api/student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1395
=> BOAC-1395 Don't blow up on non-alphanumeric search phrases

boac/static/app/cohort/curated/createController.js, boac/static/app/cohort/curated/curatedCohortFactory.js, boac/static/app/cohort/curated/selector.html, boac/static/app/cohort/curated/selectorComponent.js, boac/static/app/shared/validationService.js
https://jira.ets.berkeley.edu/jira/browse/BOAC-1406
=> BOAC-1406, onCreateCuratedCohort callback adds students; event-listeners begone

boac/static/app/cohort/curated/cohort.html, boac/static/app/course/course.html
https://jira.ets.berkeley.edu/jira/browse/BOAC-1408
https://jira.ets.berkeley.edu/jira/browse/BOAC-1405
I swapped out the dead `warning.message` code in `course.html`.
=> BOAC-1408, the 'Yes you have on students' message on class page

boac/api/student_controller.py, boac/static/app/main.css, boac/static/app/search/searchResults.html, fixtures/loch.sql, tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1396
=> BOAC-1396 Include instructor names in class search results

boac/static/app/splash/splash.css
https://jira.ets.berkeley.edu/jira/browse/BOAC-1344
The perkier UX is in screenshot attached to BOAC-1344.
=> BOAC-1344, perk up the washed out splash page

boac/static/app/course/course.html, boac/static/app/shared/matrix.css
https://jira.ets.berkeley.edu/jira/browse/BOAC-1402
=> BOAC-1402 Matrix spacing

boac/api/admin_controller.py, boac/lib/http.py, tests/test_api/test_admin_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1293
=> BOAC-1293: Returns 500 status when cache refresh fails

boac/static/app/cohort/cohort.css
https://jira.ets.berkeley.edu/jira/browse/BOAC-1398
=> BOAC-1398, Save Cohort button styled as primary

boac/static/app/cohort/curated/createController.js, boac/static/app/cohort/curated/curatedCohortFactory.js
https://jira.ets.berkeley.edu/jira/browse/BOAC-1412
I discovered a bit of a bug in our error-handling, too.
=> BOAC-1412, if callback is nil when cohort-create then _.noop

boac/static/app/shared/matrix.css, boac/static/app/shared/matrix.html
https://jira.ets.berkeley.edu/jira/browse/BOAC-1137
=> BOAC-1137 Accessible layout for no-data students under matrix

boac/static/app/home/homeController.js, boac/static/app/search/searchController.js
https://jira.ets.berkeley.edu/jira/browse/BOAC-1334
Fixes funny Angular ordering with undefined values.
=> BOAC-1334 Fill in 0 for missing alert counts on front end

boac/lib/analytics.py, fixtures/loch_student_enrollment_term_11667051_2178.json, fixtures/loch_student_enrollment_term_3456789012_2178.json, fixtures/loch_student_enrollment_term_5678901234_2178.json, tests/test_api/test_course_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1272
=> BOAC-1272 Adjust matrix positions, show intuitive percentiles

boac/static/app/course/courseController.js
https://jira.ets.berkeley.edu/jira/browse/BOAC-1416
A Jira with "busted" in the summary is worth fixing.
=> BOAC-1416, scope.section check before googleAnalyticsService.track

boac/__init__.py
The `qa` branch was cut earlier today.
=> NOJIRA, BOAC master branch bumped to v2.10

boac/api/config_controller.py, boac/lib/http.py, config/default.py, package-lock.json, public/index.html, src/App.vue, src/api/config.ts, src/api/user.ts, src/boac.css, src/components/DisplayError.vue, src/components/Header.vue, src/components/Sidebar.vue, src/main.ts, src/router.ts, src/store.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-1436
=> BOAC-1436, structure App.vue to match legacy index; menu options in top-right header

boac/static/app/cohort/cohort.css, boac/static/app/shared/matrix.html
https://jira.ets.berkeley.edu/jira/browse/BOAC-1137
Let's try this again.
=> BOAC-1137 Accessibility fixes for missing student data table

boac/api/user_controller.py, boac/api/util.py, boac/static/app/admin/admin.html, boac/static/app/admin/adminController.js, boac/static/app/user/userFactory.js, buildspec.yml, package.json, scripts/production-vuejs-post-build.sh, src/App.vue, src/api/user.ts, src/components/DemoModeToggle.vue, src/main.ts, src/views/Admin.vue, tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1436
https://jira.ets.berkeley.edu/jira/browse/BOAC-1440
Attempt to fix CodeBuild by moving `npm run build-vue` out of shell script.
=>  BOAC-1436, becomeUsers section on /admin page; fix CodeBuild failure

boac/static/app/course/course.html, boac/static/app/search/searchResults.html
https://jira.ets.berkeley.edu/jira/browse/BOAC-1430
I added blurring on the search results page as well as the course page.
=> BOAC-1430: blurs instructor names in demo mode

package.json
https://jira.ets.berkeley.edu/jira/browse/BOAC-1443
Let's try the most obvious thing first.
=> [QA] BOAC-1443 Explicitly require 'del' in package.json

package.json
https://jira.ets.berkeley.edu/jira/browse/BOAC-1443
Master version of #995.
=> BOAC-1443 Explicitly require 'del' in package.json

boac/static/app/home/sortableAlertsTable.html, boac/static/app/home/sortableAlertsTableDirective.js, boac/static/app/search/searchController.js, boac/static/app/search/searchResults.html
https://jira.ets.berkeley.edu/jira/browse/BOAC-1361
https://jira.ets.berkeley.edu/jira/browse/BOAC-1362
https://jira.ets.berkeley.edu/jira/browse/BOAC-1363
=> BOAC-1361 BOAC-1362 BOAC-1363 Accessibility improvements to search

boac/static/app/course/courseController.js
https://jira.ets.berkeley.edu/jira/browse/BOAC-1411
=> BOAC-1411: adds page size param to course page URL

boac/static/app/student/student.css, boac/static/app/student/student.html, boac/static/app/student/studentController.js, boac/static/app/visual/visualizationService.js
https://jira.ets.berkeley.edu/jira/browse/BOAC-1373
https://jira.ets.berkeley.edu/jira/browse/BOAC-1374
https://jira.ets.berkeley.edu/jira/browse/BOAC-1375
=> BOAC-1373 BOAC-1374 BOAC-1375 Accessibility fixes for academic status

boac/static/app/cohort/curated/cohort.html, boac/static/app/cohort/filtered/cohort.html, boac/static/app/course/course.html, boac/static/app/student/student.html
https://jira.ets.berkeley.edu/jira/browse/BOAC-1132
https://jira.ets.berkeley.edu/jira/browse/BOAC-1370
https://jira.ets.berkeley.edu/jira/browse/BOAC-1384
https://jira.ets.berkeley.edu/jira/browse/BOAC-1385
https://jira.ets.berkeley.edu/jira/browse/BOAC-1392
=> BOAC-1132 BOAC-1370 BOAC-1384 BOAC-1385 BOAC-1392 Accessibility grab bag

boac/merged/sis_sections.py, boac/static/app/course/course.html, boac/static/app/student/student.html, boac/static/app/student/studentAvatar.html, tests/test_api/test_course_controller.py, tests/test_merged/test_sis_sections.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1386
https://jira.ets.berkeley.edu/jira/browse/BOAC-1387
https://jira.ets.berkeley.edu/jira/browse/BOAC-1390
https://jira.ets.berkeley.edu/jira/browse/BOAC-1391
=> BOAC-1386 BOAC-1387 BOAC-1390 BOAC-1391 More accessible accessories

boac/static/app/admin/admin.html, boac/static/app/admin/adminController.js, boac/static/app/nav/header.html
https://jira.ets.berkeley.edu/jira/browse/BOAC-1419
=> BOAC-1419: exposes read-only admin page in prod

boac/static/app/course/course.css, boac/static/app/course/course.html
https://jira.ets.berkeley.edu/jira/browse/BOAC-1389
=> BOAC-1389 Accessible layout for course page list view

boac/static/app/student/student.css, boac/static/app/student/student.html
https://jira.ets.berkeley.edu/jira/browse/BOAC-1369
https://jira.ets.berkeley.edu/jira/browse/BOAC-1372
=> BOAC-1369 BOAC-1372 Slight accessibility improvements to enrollment rows

boac/static/app/cohort/filtered/filterCriteria.html
https://jira.ets.berkeley.edu/jira/browse/BOAC-1380
=> BOAC-1380 Fix 'Save cohort' button labeling

boac/static/app/cohort/filtered/cohort.html, boac/static/app/cohort/filtered/filterCriteria.html, boac/static/app/cohort/filtered/filterCriteriaComponent.js, boac/static/app/cohort/filtered/filterCriteriaEditSubcategory.html
https://jira.ets.berkeley.edu/jira/browse/BOAC-1376
https://jira.ets.berkeley.edu/jira/browse/BOAC-1377
https://jira.ets.berkeley.edu/jira/browse/BOAC-1378
https://jira.ets.berkeley.edu/jira/browse/BOAC-1379
=> BOAC-1376 BOAC-1377 BOAC-1378 BOAC-1379 Accessibility for filters

boac/static/app/main.css, boac/static/app/student/student.html
PR https://jira.ets.berkeley.edu/jira/browse/BOAC-1371
=> BOAC-1371 Accessibility markup for list-view course site data

tsconfig.json
https://jira.ets.berkeley.edu/jira/browse/BOAC-1452
As described in https://github.com/vuematerial/vue-material/issues/530
=> BOAC-1452, disable ts compile rule to fix vue-material import

boac/static/app/cohort/filtered/cohort.html
https://jira.ets.berkeley.edu/jira/browse/BOAC-1448
https://jira.ets.berkeley.edu/jira/browse/BOAC-1449
https://jira.ets.berkeley.edu/jira/browse/BOAC-1450
One line, three bugs.
=> BOAC-1448 BOAC-1449 BOAC-1450 Remove duplicative HTML attribute

boac/static/app/course/course.css, boac/static/app/course/course.html, boac/static/app/course/courseController.js
https://jira.ets.berkeley.edu/jira/browse/BOAC-1422
=> BOAC-1422: improves page size control accessibility

boac/api/student_controller.py, boac/static/app/nav/sidebar.html, boac/static/app/routes.js, boac/static/app/search/searchController.js, boac/static/app/search/searchStudentsFormDirective.js, boac/static/app/student/studentFactory.js, tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1413
=> BOAC-1413 Search for courses in appropriate contexts only

boac/api/filtered_cohort_controller.py, boac/api/student_controller.py, boac/externals/data_loch.py, boac/lib/cohort_filter_definition.py, boac/merged/student.py, boac/models/cohort_filter.py, fixtures/loch.sql, fixtures/loch_student_coe_profile_11667051.json, fixtures/loch_student_coe_profile_7890123456.json, fixtures/loch_student_coe_profile_9000000000.json, fixtures/loch_student_coe_profile_9100000000.json, tests/test_api/test_filtered_cohort_controller.py, tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1445
=> BOAC-1445 Add COE probation filter

boac/static/app/home/sortableAlertsTable.html, boac/static/app/student/student.html, boac/static/app/student/studentController.js
https://jira.ets.berkeley.edu/jira/browse/BOAC-1343
=> BOAC-1343 More UX tweaks for students with minimal data

boac/static/app/home/sortableAlertsTable.html
https://jira.ets.berkeley.edu/jira/browse/BOAC-1453
=> BOAC-1453 Fix add-to-curated-group checkbox in search results

boac/static/app/home/sortableAlertsTable.html
See @johncrossman 's comment at https://github.com/ets-berkeley-edu/boac/pull/1023
=> BOAC-1272 Fix style glitch in previous PR

boac/static/app/course/course.html
https://jira.ets.berkeley.edu/jira/browse/BOAC-1462
https://jira.ets.berkeley.edu/jira/browse/BOAC-1464
=> BOAC-1462 BOAC-1464 View-per-page option only on list view with 50+ students

boac/static/app/home/home.html, boac/static/app/home/homeController.js, boac/static/app/routes.js, boac/static/app/user/authService.js
https://jira.ets.berkeley.edu/jira/browse/BOAC-1432
https://jira.ets.berkeley.edu/jira/browse/BOAC-1457
https://jira.ets.berkeley.edu/jira/browse/BOAC-1479
=> BOAC-1432 BOAC-1457 BOAC-1479 Reload that user profile

boac/static/app/admin/admin.css, package-lock.json, package.json, src/App.vue, src/api/config.ts, src/components/DemoModeToggle.vue, src/components/HeaderMenu.vue, src/main.ts, src/router.ts, src/views/Admin.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1486
With Vuetify out we need to fix the layout – not a big deal. See the Jira for "why BootstrapVue?".
=> BOAC-1486, use BootstrapVue (for now) and remove Vuetify and vue-material

boac/api/status_controller.py, boac/api/user_controller.py, boac/static/app/nav/sidebar.html, boac/static/app/splash/splash.css, src/App.vue, src/api/user.ts, src/components/HeaderMenu.vue, src/components/sidebar/Cohorts.vue, src/components/sidebar/CuratedGroups.vue, src/layouts/Login.vue, src/layouts/StandardLayout.vue, src/router.ts, src/views/Home.vue, src/views/Login.vue, tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1487
Fix to the dual layout problem informed by article on [Multiple Layouts for VueJS Single Page Apps ](https://medium.com/@kasvith/multiple-layouts-for-vue-spa-app-fafda6b2bfc7)
=> BOAC-1487, two Vue layouts: standard and login; remove Vuetify layout elements

boac/static/app/cohort/cohort.css, boac/static/app/cohort/curated/cohort.html, boac/static/app/cohort/filtered/cohort.html, boac/static/app/student/student.css
https://jira.ets.berkeley.edu/jira/browse/BOAC-1357
https://jira.ets.berkeley.edu/jira/browse/BOAC-1465
Flexbox is fun, but it's tables you come home to.
`w=1` helps with the diff.
=> BOAC-1357 BOAC-1465 Accessible class data tables in cohort lists

src/views/Admin.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1439
Using /admin page to experiment with Bootstrap: [tabs](https://bootstrap-vue.js.org/docs/components/tabs) and "grids". More accessibility testing to follow. Tabs support keyboard navigation – more accessibility testing to follow.
=> BOAC-1435, functioning become(uid) on Admin page

boac/static/app/main.css, src/api/student.ts, src/components/DisplayError.vue, src/components/search/SortableStudentRow.vue, src/components/student/StudentAvatar.vue, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1489
=> BOAC-1489 Student profile: bio, photo, academic status

src/components/DemoModeToggle.vue, src/components/curated/CuratedGroupSelector.vue, src/components/search/SortableStudents.vue, src/components/sidebar/Cohorts.vue, src/components/sidebar/CuratedGroups.vue, src/components/student/StudentAvatar.vue, src/main.ts, src/mixins/AppConfig.vue, src/mixins/StudentMetadata.vue, src/mixins/UserMetadata.vue, src/views/Search.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1469
https://jira.ets.berkeley.edu/jira/browse/BOAC-1439
* I have TODOs on filters and create/add-to curated group. New mixins added.
* Accessibility on /admin page > demoMode toggle
=> BOAC-1494, SortableStudents with student data and curated-group checkboxes

src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1497
=> BOAC-1497 Inactive status in student profile

boac/static/app/main.css
https://jira.ets.berkeley.edu/jira/browse/BOAC-1499
=> BOAC-1499, Rainy days and Mondays (and blue menu items) always get me down

boac/api/curated_cohort_controller.py, src/api/cohorts.ts, src/components/curated/CreateCuratedGroupModal.vue, src/components/curated/CuratedGroupSelector.vue, src/store.ts, src/views/group/CuratedGroup.vue, tests/test_api/test_curated_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1494
The modal will be next.
=> BOAC-1494, wired up api call to addStudents() to group

boac/static/app/main.css, src/components/curated/CuratedGroupHeader.vue, src/components/curated/CuratedGroupList.vue, src/components/curated/CuratedGroupStudent.vue, src/components/sidebar/SearchStudents.vue, src/mixins/UserMetadata.vue, src/views/group/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1468
subtask: https://jira.ets.berkeley.edu/jira/browse/BOAC-1503
=> BOAC-1468: Vueifies curated group sort and search

src/components/curated/CreateCuratedGroupModal.vue, src/components/curated/CuratedGroupSelector.vue, src/mixins/Validator.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1494
`src/mixins/Validator.vue` is for reuse (eg, when renaming cohort)
=> BOAC-1494, cohort/group name validation for create new/rename

boac/static/app/admin/admin.html
https://jira.ets.berkeley.edu/jira/browse/BOAC-1507
=> BOAC-1507 Don't blur the admins

boac/static/app/admin/admin.html
https://jira.ets.berkeley.edu/jira/browse/BOAC-1507
QA version of #1052.
=> [QA] BOAC-1507 Don't blur the admins

boac/static/app/main.css, src/router.ts, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1498
=> BOAC-1498 Vue front end: More styling for bCourses stats on student profile

boac/api/admin_controller.py, boac/api/auth_controller.py, boac/api/user_controller.py, boac/static/app/admin/adminFactory.js, boac/static/app/user/authFactory.js, public/index.html, src/App.vue, src/api/config.ts, src/api/user.ts, src/components/DemoModeToggle.vue, src/components/HeaderMenu.vue, src/components/sidebar/Sidebar.vue, src/components/student/StudentAvatar.vue, src/layouts/Login.vue, src/main.ts, src/mixins/AppConfig.vue, src/mixins/UserMetadata.vue, src/mixins/Validator.vue, src/router.ts, src/store.ts, tests/conftest.py, tests/test_api/test_admin_controller.py, tests/test_api/test_auth_controller.py, tests/test_api/test_user_controller.py, tests/test_auth/test_dev_auth.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1519
* auth-related endpoints get `/api/auth/` prefix
*  `store` tracks `isUserAuthenticated` and user object separately for speed in rendering
* error messaging in `/login`
* basic page title mgmt
* router.ts tidying
=> BOAC-1519, user auth in Vue-land: avoid browser reload and report errors on /login

package-lock.json, package.json, src/components/curated/CuratedGroupHeader.vue, src/components/curated/CuratedGroupList.vue, src/components/curated/CuratedGroupStudent.vue, src/components/student/StudentAvatar.vue, src/components/student/StudentGpaChart.vue, src/main.ts, src/mixins/StudentMetadata.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1524
Some TODOs left in there; will tackle those in a subsequent PR.
=> BOAC-1524: builds curated group student list in Vue

boac/api/status_controller.py, boac/api/user_controller.py, boac/static/app/bootstrap.js, package-lock.json, src/App.vue, src/api/auth.ts, src/api/user.ts, src/components/HeaderMenu.vue, src/components/search/SortableStudents.vue, src/components/sidebar/CuratedGroups.vue, src/components/student/StudentAvatar.vue, src/layouts/Login.vue, src/router.ts, src/views/NotFound.vue, src/views/cohort/AllCohorts.vue, tests/test_api/test_auth_controller.py, tests/test_api/test_status_controller.py, tests/test_api/test_user_controller.py, tests/test_auth/test_dev_auth.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1535
* A more readable and performant `router.ts`
* Simpler mgmt of login vs. standard wireframe
* Load user profile after template has loaded
* threw in NotFound view w/o UX
=> BOAC-1535, improved /login setup; lazy-init per reqts of route; better use of /status

config/test.py, src/components/sidebar/Cohorts.vue, src/components/sidebar/CuratedGroups.vue, src/components/sidebar/SearchStudents.vue, src/components/sidebar/Sidebar.vue, src/components/student/StudentAvatar.vue, src/mixins/StudentMetadata.vue, src/router.ts, src/views/Student.vue, src/views/cohort/AllCohorts.vue, tests/test_routes.py, vue.config.js
https://jira.ets.berkeley.edu/jira/browse/BOAC-1523
This isn't yet complete--a certain amount of wonkiness with redirects remains to be ironed out--but given that this ranges wide and is likely to conflict with other people's work, plus requiring local config changes, best to get it out early.
=> BOAC-1523 Support for nested paths in Vue (in progress)

boac/api/curated_cohort_controller.py, src/api/cohorts.ts, src/components/curated/CuratedGroupHeader.vue, src/components/curated/CuratedGroupList.vue, src/components/curated/CuratedGroupStudent.vue, src/main.ts, src/mixins/StudentMetadata.vue, src/store.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-1503
=> BOAC-1503: adds grade alert, enables removing student from curated group

src/components/curated/CuratedGroupHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1496
=> BOAC-1496: leverages Validator in renaming curated groups

src/components/student/StudentGpaChart.vue, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1491
Should work on student and cohort pages alike.
=> BOAC-1491 Highcharts GPA chart integration

src/main.ts, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1540
=> BOAC-1540 Collapsible term GPA table

src/api/student.ts, src/components/HeaderMenu.vue, src/components/course/SortableCourseList.vue, src/components/search/SortableStudents.vue, src/components/sidebar/SearchStudents.vue, src/components/sidebar/Sidebar.vue, src/components/student/StudentAvatar.vue, src/main.ts, src/mixins/StudentMetadata.vue, src/mixins/UserMetadata.vue, src/mixins/Validator.vue, src/store/modules/user.ts, src/views/Search.vue, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1533
=> BOAC-1533, search results > classes; plus, a few mixin fixes

package-lock.json, package.json, src/api/curated.ts, src/components/curated/CuratedGroupHeader.vue, src/main.ts, src/store/modules/curated.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-1495
=> BOAC-1495: Adds Google Analytics tracking for curated groups

src/filters.ts, src/main.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-1529
A do-over of PR #1074
=> BOAC-1529, move our custom Vue.filters to ./filters file; a cleaner main.ts

package-lock.json, package.json, src/filters.ts, src/main.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-1529
=> BOAC-1529, variablePrecisionNumber filter with help from vue-filter-number-format

src/components/course/SortableCourseList.vue, src/components/sidebar/Cohorts.vue, src/components/sidebar/Sidebar.vue, src/router.ts, src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1533
=> BOAC-1533, courses section of search results (sort, style, /course route)

boac/static/app/main.css, src/api/student.ts, src/components/student/StudentAlertMessage.vue, src/components/student/StudentAlerts.vue, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1522
=> BOAC-1522 Student page alert components

src/components/student/StudentBoxplot.vue, src/components/student/StudentUnitsChart.vue, src/components/student/student-chart.css, src/main.ts, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1493
Includes some reorganization of shared CSS.
=> BOAC-1493 Student-page boxplots

src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1546
=> BOAC-1546 Don't show course properties that ain't there

src/api/curated.ts, src/components/curated/CuratedGroupSelector.vue, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1492
=> BOAC-1492 Vue: Manage curated group membership from student page

package-lock.json, package.json, src/components/curated/CuratedGroupList.vue, src/mixins/Scrollable.vue, src/store/modules/user.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-1521
=> BOAC-1521: Adds scroll-to-anchor behavior

boac/static/app/main.css, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1558
=> BOAC-1558 Vue student page: CSS fixes

src/components/student/StudentBoxplot.vue, src/components/student/StudentUnitsChart.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1556
A switcheroo.
=> BOAC-1556 Vue student page: fix tooltip pointer directionality

src/views/group/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1560
=> BOAC-1560: sets curated group page title to include group name

boac/routes.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1569
I believe the bug is in client-side Angular routes.js but this logging on server side might prove useful.
=> BOAC-1569, server-side logging in routes.py to debug Vue-related redirects

src/components/curated/CuratedGroupList.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1521
=> BOAC-1521: Fixes anchor scroll error on curated group

src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1563
https://jira.ets.berkeley.edu/jira/browse/BOAC-1574
=> BOAC-1563 BOAC-1574 More short-circuit fixes on the Vue student page

src/components/curated/CuratedGroupHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1559
=> BOAC-1559: Improves rename curated group screen reader experience

boac/static/app/main.css, src/api/course.ts, src/components/student/StudentAvatar.vue, src/views/Course.vue, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1513
List/matrix tab, curated cohort selection, and pagination not yet functional, though many of the elements are present.
=> BOAC-1513 Vue: course page list view

boac/api/filtered_cohort_controller.py, tests/test_api/test_filtered_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1585
In our legacy front-end code, all of this was done on the client-side. I'd prefer a "translation service" on the server side in order to have pytest coverage and less complexity in the client.
=> BOAC-1585, Translate filterCriteria (JSON in db) to format compatible with edit-cohort view

boac/api/cohort_controller.py, boac/api/curated_group_controller.py, boac/lib/cohort_filter_definition.py, boac/routes.py, boac/static/app/cohort/curated/curatedCohortFactory.js, boac/static/app/cohort/filtered/filteredCohortFactory.js, src/api/cohort.ts, src/api/curated.ts, src/main.ts, src/store/modules/context.ts, tests/test_api/test_cohort_controller.py, tests/test_api/test_curated_group_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1586
I will be adding a few more `/api/cohort/` endpoints and I'd like a proper API namespace.
=> BOAC-1586, correct the naming convention in API routes

src/components/curated/CuratedGroupList.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1578
=> BOAC-1578: fixes sorting on curated group

boac/api/cohort_controller.py, package-lock.json, src/components/cohort/CohortFilter.vue, src/components/cohort/CohortPageHeader.vue, src/components/cohort/CohortStudents.vue, src/components/cohort/DeleteCohortModal.vue, src/components/curated/CuratedGroupSelector.vue, src/layouts/StandardLayout.vue, src/mixins/CohortEditSession.vue, src/router.ts, src/store/index.ts, src/store/modules/cohort-edit-session.ts, src/views/cohort/Cohort.vue, tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1586
Many TODOs ahead. The operations of this page are complex and I think dedicated `store` module is reasonable. The `CohortEditSession` mixin allows all sub-components to easily share getters and store actions.
=> BOAC-1586, show filters section of /cohort view with edit/remove links

src/components/cohort/CohortFilter.vue, src/components/cohort/CohortPageHeader.vue, src/mixins/CohortEditSession.vue, src/store/modules/cohort-edit-session.ts, src/views/cohort/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1586
=> BOAC-1586, add 'modes' to cohort-edit-session store

config/default.py, src/router.ts, src/views/Teams.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1587
cc: @pfarestveit
=> BOAC-1587, document all VUE_PATHS in config/default.py; add /teams route

src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1566
=> BOAC-1566 Vue: pagination for course list view

src/components/cohort/CohortFilter.vue, src/components/student/StudentRow.vue, src/components/student/Students.vue, src/mixins/Util.vue, src/views/cohort/Cohort.vue, src/views/group/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1589
The StudentsList component will get a bit more work; move-to-shared-location is the first step.
=> BOAC-1589, rename then reuse CuratedGroupList on /cohort page

src/components/curated/CuratedGroupSelector.vue, src/components/curated/CuratedStudentCheckbox.vue, src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1568
Component magic!
=> BOAC-1568 Vue: add to curated groups from course page

boac/routes.py, src/api/cohort.ts, src/components/cohort/CohortPageHeader.vue, src/components/cohort/DeleteCohortModal.vue, src/components/curated/CuratedGroupSelector.vue, src/mixins/CohortEditSession.vue, src/store/modules/cohort-edit-session.ts, src/store/modules/cohort.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-1541
Rename or delete cohort from `/cohort` from view.
=> BOAC-1541, rename/delete cohort and keep 'store' in sync

src/components/search/SortableStudents.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1583
=> BOAC-1583 Fix search results sorting in Vue

src/layouts/StandardLayout.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1579
This strategy described in https://stackoverflow.com/questions/52847979/what-is-router-view-key-route-fullpath
=> BOAC-1579, force component reload if route is re-requested with diff id in path

src/components/course/SortableCourseList.vue, src/components/search/SortableStudents.vue, src/filters.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-1582
Perhaps custom `variablePrecisionNumber` filter is not needed in Vue-land.
=> BOAC-1582, use numFormat filter to format cumulativeUnits in search column

boac/api/cohort_controller.py, boac/api/student_controller.py, boac/api/util.py, boac/lib/cohort_filter_definition.py, boac/models/cohort_filter.py, boac/models/development_db.py, src/api/cohort.ts, src/components/cohort/AddCohortFilterMenu.vue, src/components/cohort/CohortPageHeader.vue, src/components/cohort/CreateCohortModal.vue, src/components/util/SectionSpinner.vue, src/mixins/CohortEditSession.vue, src/store/modules/cohort-edit-session.ts, src/store/modules/cohort.ts, src/store/modules/context.ts, src/views/cohort/Cohort.vue, tests/test_api/test_cohort_controller.py, tests/test_api/test_user_controller.py, tests/test_models/test_cohort_filter.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1608
https://jira.ets.berkeley.edu/jira/browse/BOAC-1609
* Include `student_count` when `create_cohort`
* `/api/cohort/create` accepts an array of filters, as seen in UI
* click 'Apply' and only the students section of the page gets a spinner
=> BOAC-1608/BOAC-1609, Cohort view > proper results when user clicks 'Apply'; create cohort

boac/static/app/student/student.html, boac/static/app/student/studentController.js
https://jira.ets.berkeley.edu/jira/browse/BOAC-1613
Master PR is #1117
=> [QA] BOAC-1613, use predictable ng-change on curated checkbox (student profile)

boac/static/app/main.css, package-lock.json, package.json, src/components/matrix/Matrix.vue, src/components/matrix/MatrixUtil.vue, src/mixins/Berkeley.vue, src/store/modules/context.ts, src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1514
=> BOAC-1514 Vue class page: add matrix

src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1561
=> BOAC-1561 Number formatting for student page cumulative GPA

boac/static/app/student/student.html, boac/static/app/student/studentController.js
https://jira.ets.berkeley.edu/jira/browse/BOAC-1613
My previous 'qa' PR #1118 went to master. Whoops!
=> [QA] BOAC-1613, use predictable ng-change on curated checkbox (to qa branch this time)

boac/models/alert.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1501
=> BOAC-1501 Don't show activity alerts for courses with final grades

src/components/cohort/CohortPageHeader.vue, src/components/cohort/FilterRow.vue, src/views/cohort/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1606
Using [bootstrap utility classes](https://bootstrap-vue.js.org/docs/reference/utility-classes) to override styles that live in "legacy" css files.
=> BOAC-1606, proper styling for /cohort section to add-new-filter

src/components/home/HomeCohort.vue, src/components/search/SortableStudents.vue, src/filters.ts, src/store/modules/cohort.ts, src/views/Home.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1509
=> BOAC-1509: adds filtered cohorts to home page

boac/api/student_controller.py, boac/lib/util.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1616 witnesses these params confusing our authorization logic.
=> BOAC-1616 Strip extraneous params on student filter and search

src/components/course/SortableCourseList.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1619
=> BOAC-1619 Fix course sorting in search results

src/components/cohort/FilterRow.vue, src/views/cohort/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1611
=> BOAC-1611, more styling on add/edit/remove cohort filters

src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1618
=> BOAC-1618 Vue class page: fix items-per-page selector

boac/lib/cohort_filter_definition.py, src/components/cohort/FilterRow.vue, src/mixins/Util.vue, src/store/modules/cohort-edit-session.ts, tests/test_api/test_menu_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1640
=> BOAC-1640, on /cohort page, menu option 'Level' can be wrongly disabled

src/api/cohort.ts, src/api/curated.ts, src/components/home/HomeCohort.vue, src/store/modules/cohort.ts, src/store/modules/curated.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-1639
=> BOAC-1639: Restricts home page filtered cohort view to only students with alerts

boac/api/cohort_controller.py, src/components/cohort/ApplyAndSaveButtons.vue, src/components/cohort/CreateCohortModal.vue, src/components/cohort/FilterRow.vue, src/store/modules/cohort-edit-session.ts, tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1611
https://jira.ets.berkeley.edu/jira/browse/BOAC-1609
=> BOAC-1611/BOAC-1609, option to update existing cohort with 'filters' param; style modal

src/router.ts, src/views/Course.vue, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1614
https://jira.ets.berkeley.edu/jira/browse/BOAC-1615
=> BOAC-1614 BOAC-1615 Page titles

src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1581
=> BOAC-1581 Fix expand-a-course caret display in Safari

boac/lib/cohort_filter_definition.py, src/components/cohort/FilterRow.vue, src/mixins/Util.vue, tests/test_api/test_menu_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1610
Required server-side fix: `last_name` option is disabled if existing filters have a `last_name` entry.
=> BOAC-1610, last_name range support (validation, menu disable, etc.)

boac/static/app/main.css
https://jira.ets.berkeley.edu/jira/browse/BOAC-1564
=> BOAC-1564 Fix sidebar/content misalignment in Vue

boac/static/app/student/student.css
https://jira.ets.berkeley.edu/jira/browse/BOAC-1626
=> BOAC-1626 Consistent GPA column width

src/router.ts, src/store/modules/cohort-edit-session.ts, src/views/NotFound.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1641
=> BOAC-1641, 404 page; you get 404 when cohort no exist

src/components/student/StudentRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1627
=> BOAC-1627 Human-readable term name in student row

src/App.vue, src/components/Footer.vue, src/layouts/StandardLayout.vue, src/mixins/Util.vue, src/views/Course.vue, src/views/cohort/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1542
=> BOAC-1542, scroll to id for /cohort pagination

src/views/Course.vue, src/views/Student.vue, src/views/group/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1527
=> BOAC-1527, 404 when course/student/curated not found

src/components/cohort/CohortPageHeader.vue, src/components/cohort/FilterRow.vue, src/mixins/CohortEditSession.vue, src/views/Course.vue, src/views/Student.vue, src/views/cohort/Cohort.vue, src/views/group/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1642
Also, bug fix when add filter of type 'boolean'.
=> BOAC-1642, /cohort: remove 'encodedCriteria' param to support bookmarkable

src/components/home/HomeCohort.vue, src/components/home/HomeCuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1461
=> BOAC-1461: improves home page screen reader subtext

src/mixins/UserMetadata.vue, src/store/modules/user.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-1629
=> BOAC-1629 Front-end departmental view permissions

src/components/curated/CuratedGroupSelector.vue, src/mixins/Util.vue, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1638
=> BOAC-1638, 'undefined.length' never ends well, use _.size

src/components/curated/CuratedGroupSelector.vue, src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1645
=> BOAC-1645, style fixes in CuratedGroupSelector; checkbox gets its 'id' back

src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1636
=> BOAC-1636 Fix aria-label binding in add-to-curated checkbox

boac/api/cohort_controller.py, src/components/cohort/ApplyAndSaveButtons.vue, src/components/cohort/CohortPageHeader.vue, src/components/cohort/CreateCohortModal.vue, src/components/cohort/DeleteCohortModal.vue, src/components/cohort/FilterRow.vue, src/components/curated/CuratedGroupHeader.vue, src/components/curated/CuratedGroupSelector.vue, src/components/curated/CuratedStudentCheckbox.vue, src/components/student/StudentRow.vue, src/components/util/Spinner.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1649
Round one.
=> BOAC-1649, element id and wording fixes for ets-qa (Teena)

src/components/cohort/ApplyAndSaveButtons.vue, src/components/cohort/CohortPageHeader.vue, src/components/cohort/CreateCohortModal.vue, src/components/curated/CreateCuratedGroupModal.vue, src/components/curated/CuratedGroupHeader.vue, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1649
`ets-qa` PR is https://github.com/ets-berkeley-edu/ets-qa/pull/221
=> BOAC-1649, ids in /cohort and /curated modals are in sync for easier qa

src/components/cohort/ApplyAndSaveButtons.vue, src/components/cohort/DeleteCohortModal.vue, src/components/curated/CuratedGroupHeader.vue, src/mixins/Util.vue, src/views/Course.vue, src/views/Student.vue, src/views/cohort/Cohort.vue, src/views/group/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1650
=> BOAC-1650, cohort name in page title; id fixes for ets-qa

src/components/cohort/ApplyAndSaveButtons.vue, src/components/cohort/FilterRow.vue, src/components/home/HomeCohort.vue, src/components/home/HomeCuratedGroup.vue, src/components/sidebar/Cohorts.vue, src/components/sidebar/Sidebar.vue, src/components/student/SortBy.vue, src/filters.ts, src/views/Home.vue, src/views/cohort/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1649
=> BOAC-1649, use cohort.id in element ids on /home; pagination widget gets sr-only

boac/api/course_controller.py, boac/externals/data_loch.py, boac/merged/student.py, fixtures/loch_sis_section_enrollments_2178_90100.csv, fixtures/loch_sis_section_enrollments_2178_90200.csv, src/api/course.ts, src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1612
Many of the code changes are just to ensure that you can't type random UIDs into the address bar and have those students show up.
Proper test coverage for this kind of pagination-related logic might require some easier way to generate fake students in quantity.
=> BOAC-1612 Featured student appears on any page in class list

src/components/cohort/ApplyAndSaveButtons.vue, src/components/cohort/CohortPageHeader.vue, src/components/cohort/CreateCohortModal.vue, src/components/cohort/DeleteCohortModal.vue, src/components/cohort/FilterRow.vue, src/layouts/StandardLayout.vue, src/mixins/Util.vue, src/store/modules/cohort-edit-session.ts, src/views/cohort/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1645
=> BOAC-1645, accessibility fixes on /cohort: putFocus, action alerts

src/components/cohort/FilterRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1662
=> BOAC-1662, /cohort: wider 'value' dropdown; remove font-weight-bold on primary menu

src/components/sidebar/Cohorts.vue, src/layouts/StandardLayout.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1664
Sidebar router-links that want to force reload now have a way.
=> BOAC-1664, create_cohort from sidebar must reload /cohort

src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1663
=> BOAC-1663 Positioning fix for student-page enrollment rows

src/main.ts, src/views/Admin.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1605
If axios gets 401 or 403 from /api call then users gets 404.
=> BOAC-1605, 404 for non-admin on /admin

boac/static/app/nav/footer.html, boac/static/app/splash/login.html, src/components/Footer.vue, src/layouts/Login.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1654
=> BOAC-1654: Removes pesky punctuation from copyright

src/components/cohort/CohortPageHeader.vue, src/components/curated/CuratedGroupHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1635
=> BOAC-1635, consistent logic for curated and cohort header components

src/api/cohort.ts, src/api/curated.ts, src/store/modules/cohort-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-1644
I also moved logic to keep `cohort/store` in sync from `cohort-edit-session.ts` to `api/cohort`, consistent with other apis.
=> BOAC-1644, Google analytics for actions on /cohort

src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1666
=> BOAC-1666 Fix student-page activity typo

src/components/cohort/CohortPageHeader.vue, src/components/curated/CuratedGroupHeader.vue, src/views/cohort/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1665
=> BOAC-1665, page title for /cohort and /curated, changes when rename

src/components/curated/CuratedGroupSelector.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1637
=> BOAC-1637, 'add to group' confirmation for two seconds

src/store/modules/cohort.ts, src/store/modules/curated.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-1668
=> BOAC-1668 Ensure that cohorts/groups are refreshed on route change

README.md, boac/api/auth_controller.py, src/components/HeaderMenu.vue, src/layouts/Login.vue, src/main.ts, src/router.ts, src/store/modules/context.ts, src/store/modules/user.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-1675
Includes a little cleanup in code style.
=> BOAC-1675, do not remove user from Vuex store just before /logout

boac/static/app/cohort/cohort.css
https://jira.ets.berkeley.edu/jira/browse/BOAC-1672
=> BOAC-1672 Fixed width for course names in cohort rows

boac/static/app/home/home.css
https://jira.ets.berkeley.edu/jira/browse/BOAC-1219
=> BOAC-1219: prevents home page total issues count from wrapping

src/views/cohort/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1678
=> BOAC-1678, proper page title when create-a-cohort

boac/static/app/main.css, src/views/NotFound.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1676
=> BOAC-1676 Fix sizing on not-found screen

src/api/student.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-1544
=> BOAC-1544: Track searches with GA

src/components/sidebar/SearchStudents.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1685
=> BOAC-1685, btn-primary-color-override for Search button on /curated

src/components/curated/CuratedGroupSelector.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1687
Related: `v-model` on dropdown was unnecessary and removed.
=> BOAC-1687, disable CuratedGroup dropdown while data is loading

src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1688
=> BOAC-1688 Gracefully handle missing class-page enrollments

src/components/curated/CuratedGroupSelector.vue, src/components/curated/CuratedStudentCheckbox.vue, src/components/sidebar/CuratedGroups.vue, src/views/Home.vue, src/views/group/CuratedGroups.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1684
=> BOAC-1684, consistency in element ids: 'curated-cohort' is now 'curated-group'

boac/__init__.py
=> NOJIRA, BOAC version to 2.13

src/views/Home.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1696
=> [QA] BOAC-1696, /create_cohort is wrong; /cohort/new is right

src/views/Home.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1696
qa PR is #1212
=> BOAC-1696, /create_cohort is wrong; /cohort/new is right

boac/merged/student.py, src/components/student/StudentUnitsChart.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1674
=> BOAC-1674 Smooth over UX for unusual data gaps (e.g. concurrent enrollment)

src/components/student/StudentRow.vue, src/views/cohort/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1697
Corresponding qa PR is #1214
=> BOAC-1697, Joe cannot edit Jane's cohort; QA asked for ids

src/components/sidebar/SearchStudents.vue, src/components/sidebar/Sidebar.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1702
=> BOAC-1702 Student search includes courses only when requested

boac/merged/student.py, fixtures/loch_student_profile_11667051.json, src/components/student/StudentRow.vue, src/views/Student.vue, tests/test_externals/test_data_loch.py, tests/test_merged/test_student.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1328
=> BOAC-1328: surfaces min/max unit overrides when applied to a student

src/components/sidebar/SearchStudents.vue, src/components/sidebar/Sidebar.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1702
QA version of #1219.
=> [QA] BOAC-1702 Student search includes courses only when requested

src/components/student/SortBy.vue, src/views/cohort/Cohort.vue, src/views/group/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1701
Corresponding master PR is #1222
=> [QA] BOAC-1701, re-sort students if and only if sortBy was changed by user

src/components/cohort/ApplyAndSaveButtons.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1704
=> BOAC-1704, set page=1 before applying a new set of cohort filters

src/components/cohort/ApplyAndSaveButtons.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1704
Corresponding master PR is #1224
=> [QA] BOAC-1704, set page=1 before applying a new set of cohort filters

src/components/student/StudentRow.vue, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1328
=> BOAC-1328: tweaks enrolled/min/max units display

src/components/cohort/FilterRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1717
=> [QA] BOAC-1717, edit values of 'Last Name' filter

src/components/cohort/FilterRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1717
Corresponding qa PR is #1228
=> BOAC-1717, edit values of 'Last Name' filter

boac/api/cohort_controller.py, boac/models/cohort_filter.py, tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1721
=> BOAC-1721, set cohort.alert_count on cohort create/update

boac/api/cohort_controller.py, boac/models/cohort_filter.py, tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1721
QA dept judged this a worthy fix for qa branch.
master PR is #1234
=> [QA] BOAC-1721, set cohort.alert_count on cohort create/update

src/components/curated/StudentProfileCuratedGroups.vue, src/components/student/AcademicTimeline.vue, src/components/student/StudentAvatar.vue, src/components/student/StudentProfileGPA.vue, src/components/student/StudentRow.vue, src/views/Course.vue, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1711
Major demolition on student profile page. I want to get this PR in early cuz shared components are impacted (eg, StudentAvatar).
=> BOAC-1711, initial restructure of /student; make room for Academic Timeline

boac/api/auth_controller.py, boac/api/config_controller.py, boac/routes.py, config/default.py, config/development.py, config/test.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1681
=> BOAC-1681 Erase traces of Angular in routes, configs

src/components/matrix/Matrix.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1732
=> BOAC-1732 Do not seek to plot the unplottable

src/components/curated/CuratedGroupSelector.vue, src/components/student/StudentAvatar.vue, src/components/student/profile/StudentGroupSelector.vue, src/components/student/profile/StudentProfileHeader.vue, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1712
I reverted my recent work on `CuratedGroupSelector` cuz sharing that component, in this case, ain't gonna work.
=> BOAC-1712, custom curated-group component for /student page

src/components/student/profile/AcademicTimeline.vue, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1714
=> BOAC-1714, finishing touches on Academic Timeline tabs

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1715
=> BOAC-1715, hover style for Academic Timeline

src/components/student/profile/AcademicTimeline.vue, src/mixins/Util.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1716
=> BOAC-1724, expand/collapse Timeline entries; sr-only status; pill styling

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1597
Use `?w=1`. I moved `ids` from `<td>` to child `<div>` in order to `putFocus` when filter/showAll change.
=> BOAC-1597, Academic Timeline > accessibility tweaks

boac/models/alert.py, src/components/student/profile/AcademicTimeline.vue, src/components/student/profile/StudentProfileUnits.vue, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1748
=> BOAC-1748, StudentProfileUnits styles; /api/alerts now delivers updatedAt

src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1703
=> BOAC-1703: Hides pagination ellipsis

src/components/student/profile/StudentProfileGPA.vue, src/components/student/profile/StudentProfileUnits.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1713
The GPA component UX is not what you see in designs. We (Flint and others) agreed on some tweaks.
=> BOAC-1713, StudentProfileGPA component (expand/collapse, etc.)

src/components/student/profile/AcademicTimeline.vue, src/components/student/profile/StudentClasses.vue, src/components/student/profile/StudentProfileGPA.vue, src/components/student/profile/StudentProfileHeader.vue, src/components/student/profile/StudentProfileUnits.vue, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1753
Includes 'flex-wrap' on header, units and gpa blocks.
=> BOAC-1753, misc fixes on Academic Timeline (eg, h2 size, showHide)

boac/externals/data_loch.py, boac/merged/student.py, tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1718
For the record, I too disapprove of SQL shenanigans.
=> BOAC-1718 Do not restrict results when sorting cohort by team name

package-lock.json, package.json, src/api/cohort.ts, src/components/cohort/CohortPageHeader.vue, src/main.ts, src/store/modules/context.ts, src/store/modules/user.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-1755
I think we need to use https://github.com/MatteoGabriele/vue-analytics/blob/c774f50b7df683f1ee2ca9eab8fd257c6456d117/docs/fields.md
=> BOAC-1755, track userId with vue-analytics (GA)

src/store/modules/context.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-1758
=> BOAC-1758 Fix error before state.config initialized

src/components/admin/DevAuth.vue, src/components/sidebar/SearchStudents.vue, src/components/student/profile/StudentProfileGPA.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1756
https://jira.ets.berkeley.edu/jira/browse/BOAC-1753
Plus, get show/hide right per revised boolean def.
=> BOAC-1756, remove height 100% on expandable div (student profile GPA)

boac/merged/student.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1754
=> BOAC-1754 Ignore pagination when returning cohort SIDs for alert-count calculation

src/components/cohort/FilterRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1731
=> BOAC-1731 Screenreader labeling for filter option groups

src/assets/styles/bootstrap-overrides.css, src/components/util/Pagination.vue, src/views/Cohort.vue, src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1749
https://jira.ets.berkeley.edu/jira/browse/BOAC-1750
For example:
=> BOAC-1749, Pagination component to centralize 'Goto' overrides and more

src/layouts/StandardLayout.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1729
=> BOAC-1729: makes home and skip links keyboard-friendly

src/layouts/StandardLayout.vue, src/mixins/Util.vue, src/views/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1752
https://jira.ets.berkeley.edu/jira/browse/BOAC-1741
=> BOAC-1752, back to unsaved cohort; go to #content does not reload page

src/api/cohort.ts, src/api/curated.ts, src/components/cohort/ApplyAndSaveButtons.vue, src/components/cohort/CohortPageHeader.vue, src/components/cohort/FilterRow.vue, src/components/curated/CuratedGroupSelector.vue, src/components/home/HomeCohort.vue, src/components/home/HomeCuratedGroup.vue, src/components/sidebar/SearchStudents.vue, src/components/student/SortBy.vue, src/components/student/profile/StudentGroupSelector.vue, src/mixins/GoogleAnalytics.vue, src/mixins/Scrollable.vue, src/mixins/Util.vue, src/views/Cohort.vue, src/views/Course.vue, src/views/Search.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1761
We want to know what is most used on cohort page.
=> BOAC-1761, Google Analytics: track minor events on /cohort (eg, add/edit/remove filter)

src/components/cohort/FilterRow.vue, src/main.ts, src/store/modules/user.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-1765
How it looks in GA console:
Disagree with dept=ADMIN for admins?
=> BOAC-1765, tracked GA events include user's dept/college affiliation

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1766
=> BOAC-1766, isShowingAll fix for Academic Timelime; fa-caret per design

boac/api/notes_controller.py, boac/externals/data_loch.py, boac/merged/student.py, boac/routes.py, config/default.py, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1770
Simply scaffolding.
=> BOAC-1770, initial wiring for /api/notes with expected data_loch query

src/assets/styles/bootstrap-overrides.css, src/components/cohort/FilterRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1738
=> BOAC-1738: improves accessibility of cohort filters

src/api/config.ts, src/components/util/Status.vue, src/views/Admin.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1776
=> BOAC-1776, /admin love: configs, version, link to git commit

boac/externals/data_loch.py, boac/merged/student.py, boac/models/note_read.py, fixtures/loch.sql, scripts/db/drop_schema.sql, scripts/db/migrate/20190205-BOAC-1775/pre_deploy_01_create_notes_read_table.sql, scripts/db/schema.sql, src/api/notes.ts, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1775
Note that this PR includes a db migration.
=> BOAC-1775 Mark notes as read; more test coverage

src/layouts/StandardLayout.vue, src/views/Home.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1783
=> BOAC-1783, one and only one h1 per page

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1785
https://jira.ets.berkeley.edu/jira/browse/BOAC-1784
"Nulls last" puts degree-progress items at bottom, on "All" tab.
=> BOAC-1785, aria-labels, nulls last in message sort

src/store/modules/user.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-1792
=> BOAC-1792 Ignore Google Analytics code when no analytics id present

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1787
=> BOAC-1787 Academic timeline requirements: more awesomefont

boac/models/note_read.py, fixtures/loch.sql, scripts/db/migrate/20190205-BOAC-1775/pre_deploy_01_create_notes_read_table.sql, scripts/db/schema.sql, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1775
=> BOAC-1775 String is the thing for note ids

boac/__init__.py
=> NOJIRA, Falco is v2.14 on master branch

src/components/student/profile/StudentProfileGPA.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1794
QA version of #1286.
=> [QA] BOAC-1794 Consistent precision for cumulative GPA

src/components/student/profile/StudentProfileGPA.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1794
=> BOAC-1794 Consistent precision for cumulative GPA

boac/api/util.py, src/assets/styles/boac-global.css, src/components/student/profile/AcademicTimeline.vue, src/components/student/profile/StudentClasses.vue, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1798
Having `isOpen` on each message was thwarted by use of computed property: DOM does not re-render when props of objects in list are modified.
=> BOAC-1798, message show/hide fix; order of messages; fall back to createdAt

boac/api/util.py, src/assets/styles/boac-global.css, src/components/student/profile/AcademicTimeline.vue, src/components/student/profile/StudentClasses.vue, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1798
master PR is #1288
=> [QA] BOAC-1798, message show/hide fix; order of messages; fall back to createdAt

src/views/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1741
=> BOAC-1741, put skip-to-pagination under Apply/Save buttons

src/components/search/SortableStudents.vue, src/components/student/StudentRow.vue, src/components/student/profile/StudentProfileGPA.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1795
=> BOAC-1795 Let zeros be zeros and nulls be nulls

boac/api/notes_controller.py, boac/api/util.py, boac/externals/data_loch.py, boac/merged/student.py, fixtures/loch.sql, src/api/notes.ts, src/components/student/profile/AcademicTimeline.vue, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1774
The loch query will evolve.
=> BOAC-1774, add notes (read-only) to Academic Timeline

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1800
=> BOAC-1800 Let the ternary operator operate

src/components/student/StudentAvatar.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1801
QA version of #1293.
=> [QA] BOAC-1801 Reattach alert counts to heads

src/components/student/StudentAvatar.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1801
=> BOAC-1801 Reattach alert counts to heads

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1806
=> [QA] BOAC-1806, Academic Timeline: multiple messages can be open

src/mixins/CohortEditSession.vue, src/store/modules/cohort-edit-session.ts, src/views/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1803
QA version of #1297.
=> [QA] BOAC-1803 Disable sorting when selected filters differ from displayed results

src/mixins/CohortEditSession.vue, src/store/modules/cohort-edit-session.ts, src/views/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1803
=> BOAC-1803 Disable sorting when selected filters differ from displayed results

src/components/student/profile/AcademicTimeline.vue, src/mixins/Util.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1796
https://jira.ets.berkeley.edu/jira/browse/BOAC-1806
Tabs with zero are disabled. Open a one-line message and min-height style forces row to expand a bit.
=> BOAC-1806, Academic Timeline: tabs always present; notes as html with min-height

src/components/cohort/ApplyAndSaveButtons.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1810
=> BOAC-1810: Corrects errant ternary operation

src/components/cohort/ApplyAndSaveButtons.vue
QA version of #1301 
https://jira.ets.berkeley.edu/jira/browse/BOAC-1810
=> [QA] BOAC-1810: Corrects errant ternary operation

boac/models/alert.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1811
=> BOAC-1811 Infrequent activity is for sure infrequent if it hasn't happened during the academic session

boac/models/alert.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1811
QA version of #1303.
=> [QA] BOAC-1811 Infrequent activity is for sure infrequent if it hasn't happened during the academic session

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1812
=> BOAC-1812, Academic Timeline: proper padding in right column (dates)

boac/externals/data_loch.py, boac/merged/student.py, fixtures/loch.sql, tests/test_merged/test_student.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1793
=> BOAC-1793: Adds category, topics, attachments to note feed

src/components/search/SortableStudents.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1807
=> BOAC-1807 Treat nulls as zeros for front-end sorting purposes

src/components/search/SortableStudents.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1807
QA version of #1307.
=> [QA] BOAC-1807 Treat nulls as zeros for front-end sorting purposes

boac/merged/student.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1815
=> BOAC-1815, note_id does not always map to topic(s)

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1757
=> BOAC-1757, go ask Alice, one pill makes you small

src/store/modules/cohort-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-1818
=> BOAC-1818 Saved cohorts deserve Sort By too

src/store/modules/cohort-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-1818
QA version of #1312.
=> [QA] BOAC-1818 Saved cohorts deserve Sort By too

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1822
Fixing the goof made in PR #1310
=> BOAC-1822, tabs are not pills

.eslintrc.js, src/components/cohort/FilterRow.vue, src/components/curated/CuratedGroupHeader.vue, src/components/student/StudentRow.vue, src/components/student/profile/StudentClasses.vue, src/components/util/Pagination.vue, src/mixins/CohortEditSession.vue, src/mixins/Loading.vue, src/mixins/UserMetadata.vue, src/views/Course.vue, src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1705
Follow up to PR #1311
=> BOAC-1705, fix linting 'warns' per stricter linting

boac/api/user_controller.py, boac/api/util.py, boac/merged/calnet.py, boac/merged/student.py, src/api/user.ts, src/components/note/AdvisingNote.vue, src/components/student/profile/AcademicTimeline.vue, src/components/student/profile/TimelineDate.vue, src/mixins/UserMetadata.vue, src/mixins/Util.vue, src/store/modules/user.ts, src/views/Admin.vue, tests/test_api/test_curated_group_controller.py, tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1813
https://jira.ets.berkeley.edu/jira/browse/BOAC-1828
Notes come to us with `advisor_sid`. Sample UX:
=> BOAC-1813/BOAC-1828, AdvisingNote component; lazy-load advisor by csid

src/components/student/StudentRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1760
=> BOAC-1760: Adds expected grad term to student row

src/components/student/profile/StudentGroupSelector.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1790
=> BOAC-1790: Sorts out labels on student group selector

boac/externals/data_loch.py, boac/merged/student.py, fixtures/loch.sql, tests/test_api/test_notes_controller.py, tests/test_merged/test_student.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1829
A poor man's ElasticSearch serves as a scratch pad for getting the UX in place.
=> BOAC-1829 Prototype Redshift query for notes search on scoped population

boac/api/admin_controller.py, boac/merged/reporter.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1710
=> BOAC-1710 Report the state of assignment scores in the current term

boac/merged/student.py, boac/models/development_db.py, boac/models/note.py, scripts/db/drop_schema.sql, scripts/db/migrate/20190220-BOAC-1835/pre_deploy_01_create_notes_table.sql, scripts/db/schema.sql, tests/test_api/test_notes_controller.py, tests/test_merged/test_student.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1837
Keyword: simple. This should be enough to support UX in https://jira.ets.berkeley.edu/jira/browse/BOAC-1835.
=> BOAC-1837, basic notes table has authorId, sid, subject, body, and dates

src/components/admin/DevAuth.vue, src/components/cohort/FilterRow.vue, src/mixins/UserMetadata.vue, src/router.ts, src/store/modules/user.ts, src/views/Admin.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1845
Regression/bug caused by recent change to lazy-`loadUserGroups`.
And, `vue-bootstrap` [resolved our 'Goto' concern](https://github.com/bootstrap-vue/bootstrap-vue/issues/2508).
=> BOAC-1845, /admin redirect to 404 for non-admin; Teena fixes

src/components/student/profile/StudentClasses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1817
=> BOAC-1817: restores min/max unit overrides to Student page

src/components/student/StudentRow.vue, src/views/Cohort.vue, src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1844
Teena no like XPath.
=> BOAC-1844, StudentRow id elements with sid<->rowIndex translation for Teena

src/components/student/StudentRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1844
See @lyttam comment: https://github.com/ets-berkeley-edu/boac/pull/1331#discussion_r259517551
=> BOAC-1844, ensure unique ids on enrollment.displayName

boac/api/notes_controller.py, boac/api/user_controller.py, boac/merged/student.py, boac/models/note.py, package-lock.json, package.json, src/api/notes.ts, src/api/user.ts, src/components/note/AdvisingNote.vue, src/components/note/NewNoteModal.vue, src/components/student/profile/AcademicTimeline.vue, src/mixins/UserMetadata.vue, src/store/modules/user.ts, tests/test_api/test_notes_controller.py, tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1839
`AcademicTimeline.vue` changes are minor – review with `?w=1`. Not using Bootstrap modal – code is more manageable if we roll-our-own.
=> BOAC-1839, initial NewNoteModal with API support; db model fixes

src/components/note/NewNoteModal.vue, src/components/student/profile/AcademicTimeline.vue, src/main.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-1840
PR #1333 has functional bits. This is tidying up.
=> BOAC-1840, collapse/expand create-note widget with proper putFocus

src/assets/styles/boac-global.css, src/components/course/SortableCourseList.vue, src/components/curated/CuratedGroupSelector.vue, src/components/home/HomeCohort.vue, src/components/home/HomeCuratedGroup.vue, src/components/search/SortableStudents.vue, src/components/student/StudentRow.vue, src/components/util/Pagination.vue, src/views/Course.vue, src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1859
Fewer style overrides is a good thing. Includes extra CSS cleanup.
=> BOAC-1859, bootstrap-vue upgrade brought breakage, simpler CSS

boac/externals/data_loch.py, boac/merged/student.py, config/default.py, fixtures/loch.sql, requirements.txt, tests/test_merged/test_student.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1858
See tests for expected behavior.
=> BOAC-1858 Postgres index query for full-text advising notes search

src/views/Course.vue, src/views/Home.vue, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1834
=> BOAC-1834 More, more, more scroll-to-top

src/components/student/StudentRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1866
=> BOAC-1866 Fix cohort sortedBy formatting

src/components/student/StudentRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1867
=> BOAC-1867, SID and INACTIVE get personal space

boac/api/config_controller.py, boac/api/notes_controller.py, boac/api/util.py, config/default.py, config/development.py, config/test.py, src/components/student/profile/AcademicTimeline.vue, src/mixins/Context.vue, src/store/modules/context.ts, tests/test_api/test_config_controller.py, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1870
=> BOAC-1870, feature-flag on /api/notes/create

src/components/curated/CuratedGroupSelector.vue, src/components/student/profile/StudentGroupSelector.vue, src/store/modules/context.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-1791
Changes in `context.ts` are purely cosmetic, compacting.
=> BOAC-1791, curated-group checkboxes indicate state with aria-label

boac/externals/calnet.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1768
See Jira for details. Plus, code cleanup for readability.
=> BOAC-1768, CalNet queries: widen search_base; 'ou' restriction on filter

src/components/cohort/ApplyAndSaveButtons.vue, src/views/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1797
=> BOAC-1797 Keep cohort sort, pagination in sync on filter update

src/components/cohort/ApplyAndSaveButtons.vue, src/mixins/CohortEditSession.vue, src/store/modules/cohort-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-1692
Tricky because the nature of "resetting" depends on context. When you've made changes to filters but not applied them, presumably "Reset" should take you back to the last apply. But when you've applied changes but not saved them, presumably "Reset" should take you back to the last save point.
=> BOAC-1692 Buttons to reset filter edits to last apply or save

boac/api/notes_controller.py, boac/api/search_controller.py, boac/api/util.py, boac/merged/advising_note.py, boac/merged/student.py, tests/test_merged/test_advising_note.py, tests/test_merged/test_student.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1882
Before changing behavior, this is a good moment to organize the garage.
=> BOAC-1882 Move advising notes into their own merged model

src/components/note/AdvisingNote.vue, src/components/sidebar/SearchForm.vue, src/components/student/profile/AcademicTimeline.vue, src/mixins/GoogleAnalytics.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1872
=> BOAC-1872, Google Analytics for note read, create; d-flex on sidebar search options

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1872
On second thought, let's not push sid to GA.
=> BOAC-1872, remove sid from gaNoteEvent and this.gaStudentAlert

boac/api/notes_controller.py, src/components/student/profile/AcademicTimeline.vue, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1896
Plus, id tweaks for Teena
=> BOAC-1896, sorry Admin, no note creation for you

src/components/note/AdvisingNote.vue, src/components/student/profile/TimelineDate.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1899
https://jira.ets.berkeley.edu/jira/browse/BOAC-1892
=> BOAC-1892/BOAC-1899, minor UX fixes in AdvisingNote template

src/components/student/profile/TimelineDate.vue, src/views/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1903
Child components must follow their parents.
Includes fix to `sr-only` link to pagination https://jira.ets.berkeley.edu/jira/browse/BOAC-1741
=> BOAC-1903, AcademicTimeline dates must update when rows are resorted

boac/merged/advising_note.py, src/views/Search.vue, tests/test_merged/test_advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1905
=> BOAC-1905, on front-end, notes will have note.id

boac/api/student_controller.py, src/components/student/profile/StudentProfileHeader.vue, tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1886
=> BOAC-1886, link to CalCentral profile

.travis.yml, boac/api/notes_controller.py, boac/externals/data_loch.py, boac/externals/s3.py, boac/merged/advising_note.py, config/default.py, fixtures/loch.sql, requirements.txt, tests/test_api/test_notes_controller.py, tests/test_merged/test_advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1780
=> BOAC-1780 Note attachments download API

src/components/note/AdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1781
=> BOAC-1781 Enable attachment download links

src/components/search/AdvisingNoteSnippet.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1915
Needs to be applied in a couple of different places to catch all the elements.
=> BOAC-1915 Blur search results in demo mode

src/components/student/profile/StudentClasses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1902
=> BOAC-1902: Tweaks enrollment term display rules

boac/api/user_controller.py, src/components/HeaderMenu.vue, src/views/Admin.vue, tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1909
A good enhancement to have in the upcoming release, specifically in _boac-demo_ env. We don't want to rely on `boac-dev`.
=> BOAC-1909, if dev_auth=True then advisors can toggle demo_mode, too

src/components/note/AdvisingNote.vue, src/components/note/NewNoteModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1894
And button style: https://jira.ets.berkeley.edu/jira/browse/BOAC-1918
=> BOAC-1894, 'Advisor profile not found' when CalNet has zilch

src/components/note/AdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1904
=> BOAC-1904, pre-Fall 2016 attachments unavailable

src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1923
=> BOAC-1923, class page gets :id on student SID

src/components/note/AdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1904
Conditionals matter.
=> BOAC-1904, v-if isPreCsNote then 'unavailable' message

src/components/note/NewNoteModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1928
=> BOAC-1928, z-index:1 for new note modal to rise above the blur

boac/__init__.py
=> NOJIRA, BOA is now v2.15 on master

boac/api/notes_controller.py, src/components/note/EditAdvisingNote.vue, src/components/note/NewNoteModal.vue, src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1936
https://jira.ets.berkeley.edu/jira/browse/BOAC-1935
And https://jira.ets.berkeley.edu/jira/browse/BOAC-1940, "Only subject is required"
=> BOAC-1935/BOAC-1936, if editing note then disable new note button, and other such

src/components/curated/CuratedGroupSelector.vue, src/components/curated/CuratedStudentCheckbox.vue, src/components/search/SortableStudents.vue, src/components/student/StudentRow.vue, src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1736
=> BOAC-1920, Accessibility: add to curated group with keyboard

package-lock.json, package.json, src/components/note/EditAdvisingNote.vue, src/components/note/NewNoteModal.vue, src/components/student/profile/AcademicTimeline.vue, src/components/util/AreYouSureModal.vue, src/main.ts, src/mixins/Util.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1916
=> BOAC-1916, step 1 in the 'are you sure?' in cancel Note

boac/api/notes_controller.py, src/components/student/profile/AcademicTimeline.vue, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1934
See comment in https://jira.ets.berkeley.edu/jira/browse/BOAC-1949
=> BOAC-1934, if feature flag false then turn off create and edit notes

src/components/note/NewNoteModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1920
=> BOAC-1920, note creation accessibility: sr-only cancel behind primary (save) button

boac/api/notes_controller.py, boac/models/note.py, src/api/notes.ts, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1911
See Jira for biz rules.
=> BOAC-1911, backend support for advising note deletion (feature flagged)

src/components/note/AdvisingNote.vue, src/components/note/EditAdvisingNote.vue, src/components/note/NewNoteModal.vue, src/components/student/profile/AcademicTimeline.vue, src/components/util/AreYouSureModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1911
* use `?w=1` for clearer diff
* hidden delete-button for accessibility
* element `id` changes per pending Teena PR
=> BOAC-1911, delete note (available to admins), front-end support

src/components/course/SortableCourseList.vue, src/components/search/SortableStudents.vue, src/layouts/StandardLayout.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1734
=> BOAC-1734: Fixes screen reader alerts for table sorting

package-lock.json, package.json, src/components/note/EditAdvisingNote.vue, src/components/note/NewNoteModal.vue, src/main.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-1967
=> BOAC-1967, in form to edit note, only the cancel button causes exit

src/components/course/SortableCourseList.vue, src/components/curated/CuratedGroupHeader.vue, src/components/search/AdvisingNoteSnippet.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1908
https://jira.ets.berkeley.edu/jira/browse/BOAC-1906
=> BOAC-1906/BOAC-1980, no zero-padding for date in note result; wording in pluralize

src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1941
https://jira.ets.berkeley.edu/jira/browse/BOAC-1943
=> BOAC-1943, accessibility and validation on search input

src/components/student/StudentRow.vue, src/components/student/profile/AcademicTimeline.vue, src/components/student/profile/StudentClasses.vue, src/main.ts, src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1746
=> BOAC-1746, directive for screen-reader-friendly grade

boac/api/search_controller.py, boac/externals/data_loch.py, boac/merged/advising_note.py, boac/models/note.py, scripts/db/drop_schema.sql, scripts/db/migrate/20190322-BOAC-1873/add_fts_index_to_notes.sql, scripts/db/schema.sql, tests/test_merged/test_advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1873
=> BOAC-1873 Include locally created notes in search results

boac/__init__.py
=> NOJIRA, Boa master branch is now v2.16

src/views/Search.vue, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1913
And, screen reader alerts on https://jira.ets.berkeley.edu/jira/browse/BOAC-1967 work.
=> BOAC-1913, helpful hints for finding advising notes

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1875
=> BOAC-1875: adds SR alert for open/close timeline messages

boac/api/cohort_controller.py, boac/api/util.py, boac/lib/cohort_filter_definition.py, src/views/Admin.vue, src/views/AllCohorts.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2011
https://jira.ets.berkeley.edu/jira/browse/BOAC-1877
master PR is #1404
=> [QA] BOAC-2011, both /cohorts/all and /admin must handle empty advisor name

README.md
https://jira.ets.berkeley.edu/jira/browse/BOAC-2004
Bonus: testing new type of Travis integration.
=> BOAC-2004, Readme file goes BOA

boac/api/util.py, boac/merged/calnet.py, fixtures/calnet_search_entries.json
QA version of https://github.com/ets-berkeley-edu/boac/pull/1408
=> [QA] BOAC-1877 Do not include ex-advisors in Act As list

src/components/course/SortableCourseList.vue, src/views/Search.vue
=> NOJIRA, Teena wants ids on h1/h2 headers in search results

src/mixins/Loading.vue, src/router.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-2027
I also have a more focused, Search-only, version of the fix, but @johncrossman thought it might be nice to hook it into the router. What do you think, @lyttam & John C.?
=> BOAC-2027 Allow refresh when Vue needs a loaded user profile

boac/merged/advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2013
=> BOAC-2013: UTCifies note timestamps from RDS to match Redshift's

boac/merged/advising_note.py, tests/test_merged/test_advising_note.py, tests/util.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1989
=> BOAC-1989: Suppresses updated/created time on pre-CS notes

boac/merged/calnet.py, boac/models/development_db.py, boac/routes.py, tests/test_auth/test_dev_auth.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2053
=> BOAC-2053, users 'expired' per LDAP cannot log in, regardless of dept affiliation

boac/api/auth_controller.py, src/components/admin/DevAuth.vue, src/components/util/Status.vue, src/layouts/Login.vue, src/mixins/Util.vue, src/router.ts, src/views/Admin.vue, src/views/Home.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2005
Everything under the hood remains BOAC.
=> BOAC-2005, in eyes of customer, BOAC is now BOA

boac/externals/calnet.py, boac/merged/calnet.py, boac/routes.py, src/views/Admin.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2053
Final piece in forbidding 'expired people' access to BOA. And, on `/admin` page, a small 'is expired' alert in place of the 'become' button.
=> BOAC-2053, auth user_loader checks 'isExpiredPerLdap' at login time

src/components/note/EditAdvisingNote.vue, src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1971
=> BOAC-1971: Updates 'updatedAt' when note is edited

src/components/note/EditAdvisingNote.vue, src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2039
=> BOAC-2039: Restores edit note form to its former glory

boac/models/db_relationships.py, boac/models/development_db.py, boac/models/note.py, fixtures/mock_advising_note_attachment.txt, scripts/db/drop_schema.sql, scripts/db/migrate/20190409-BOAC-2043/pre_deploy_01_create_note_attachments_table.sql, scripts/db/schema.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2043
`deleted_at` column for soft-deletes (see https://jira.ets.berkeley.edu/jira/browse/BOAC-2063)
=> BOAC-2043, db modify: create table note_attachments w/ boac.model

boac/api/notes_controller.py, boac/models/db_relationships.py, boac/models/development_db.py, boac/models/note.py, scripts/db/migrate/20190409-BOAC-2043/pre_deploy_02_add_uploader_column_to_note_attachments_table.sql, scripts/db/schema.sql, tests/test_api/test_notes_controller.py, tests/test_merged/test_advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2069
=> BOAC-20169, API to delete note attachment, with proper auth checks

boac/api/notes_controller.py, boac/merged/advising_note.py, boac/models/note_read.py, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1983
=> BOAC-1983: Marks updated or newly created note as read by user who did the deed

src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1999
=> BOAC-1999: Resets edit mode when user navigates away from note edit

boac/models/note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2065
=> BOAC-2065: Refreshes search index on note update and delete

src/api/notes.ts, src/components/note/EditAdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2044
=> BOAC-2044, remove existing attachment with 'Are you sure?' modal

boac/externals/s3.py, src/components/note/EditAdvisingNote.vue, src/components/note/NewNoteModal.vue, src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2040
https://jira.ets.berkeley.edu/jira/browse/BOAC-1937
https://jira.ets.berkeley.edu/jira/browse/BOAC-2045
Tweak attachments, click cancel and note is reset.
=> BOAC-2044, fixes around s3 encryption, discarding changes, and accessibility

boac/api/notes_controller.py, src/components/note/NewNoteModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2094
=> BOAC-2094, delete attachments bug fix: multipart-form-data has stringified array

boac/models/note.py, src/components/note/EditAdvisingNote.vue, src/components/note/NewNoteModal.vue, tox.ini
https://jira.ets.berkeley.edu/jira/browse/BOAC-2091
https://jira.ets.berkeley.edu/jira/browse/BOAC-2098
* The s3 key/path has date info (and so does the db) so we don't need it in filename
* see BOAC-2098 for screenshot of new 'choose file' UX
=> BOAC-2098/BOAC-2091, filename in s3; change 'Choose file' input to drag-and-drop-with-button

boac/__init__.py
Who put the bump in the bump-da-bump-da-bump?!
=> NOJIRA, bump BOA master to v2.17

boac/merged/advising_note.py, boac/models/note.py, boac/models/note_attachment.py, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2103
... but avoid S3 name collisions internally: BOAC-2091
=> BOAC-2103 Show users their supplied attachment filenames

boac/merged/advising_note.py, boac/models/note.py, boac/models/note_attachment.py, tests/test_api/test_notes_controller.py
QA version of https://github.com/ets-berkeley-edu/boac/pull/1438
So far as testing is concerned, this is a QA-first PR. Attachment deletion is broken on the Master branch, and I'm looking into that at BOAC-2104.
=> [QA] BOAC-2103 BOAC-2091 Show users their supplied attachment filenames

src/components/note/EditAdvisingNote.vue, src/components/note/NewNoteModal.vue, src/components/note/NoteUtil.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2112
=> BOAC-2112 Resize note attachment dropzone; no drops outside zone

src/components/note/EditAdvisingNote.vue, src/components/note/NewNoteModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2107
No error, just notice text stating the limit.
=> BOAC-2107 Consistent UX for max attachments limit

src/components/note/EditAdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2076
=> BOAC-2076 Fix note edit cancellation verbiage

boac/api/notes_controller.py, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2099
=> BOAC-2099 Handle Unicode in note attachment filenames

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1983
=> BOAC-1983: Displays new notes in open state upon creation

src/components/note/EditAdvisingNote.vue, src/components/note/NewNoteModal.vue, src/components/note/NoteUtil.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2041
https://jira.ets.berkeley.edu/jira/browse/BOAC-2113
=> BOAC-2041 BOAC-2113 Attachment file size validation, messaging fix

boac/api/notes_controller.py, boac/models/note.py, src/api/notes.ts, src/components/note/AdvisingNote.vue, src/components/note/EditAdvisingNote.vue, src/components/note/NewNoteModal.vue, src/components/note/NoteUtil.vue, src/components/student/profile/AcademicTimeline.vue, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2104
=> BOAC-2104 Separate out attachment modification from note editing

src/components/util/AreYouSureModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2122
=> BOAC-2122 Not invocation of the function but the function itself

src/components/note/AdvisingNote.vue, src/components/note/NewNoteModal.vue, src/components/note/NoteUtil.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1966
=> BOAC-1966 Keyboard accessiblity for attachment file selector

src/components/note/AdvisingNote.vue, src/components/note/NewNoteModal.vue, src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2090
=> BOAC-2090 Spin a spinner during advising note creation

src/components/note/AdvisingNote.vue, src/components/note/EditAdvisingNote.vue, src/components/note/NewNoteModal.vue, src/components/note/NoteUtil.vue, src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2090
With a little ancillary refactoring to further disentangle creation and editing workflows.
=> BOAC-2090 Spinner while uploading attachments to existing note

boac/api/student_controller.py, boac/externals/data_loch.py, boac/merged/student.py, tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2071
Reqts are described in https://jira.ets.berkeley.edu/jira/browse/BOAC-2124
=> BOAC-2071, API endpoint to report on status per SID in list, per user privileges

boac/api/student_controller.py, src/api/student.ts, src/components/home/HomeCuratedGroup.vue, src/components/sidebar/CuratedGroups.vue, src/router.ts, src/views/CuratedGroupBulkAdd.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2072
Front-end route, api call and basic form.
=> BOAC-2072, begin front-end work on curated-group-bulk-add

boac/api/search_controller.py, boac/externals/data_loch.py, fixtures/loch.sql, tests/test_api/test_search_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1847
https://jira.ets.berkeley.edu/jira/browse/BOAC-1848
=> BOAC-1847 BOAC-1848 Course search by partial subject area or catalog id alone

src/mixins/Util.vue, src/views/CuratedGroupBulkAdd.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2072
Using bulk-add with an existing group is next.
=> BOAC-2072, finishing touches on group creation with bulk-add-SIDs

buildspec.yml
Diagnosis attempt on https://jira.ets.berkeley.edu/jira/browse/BOAC-2129.
=> BOAC-2129 List installed Node packages during build process

buildspec.yml, src/components/note/AdvisingNote.vue, src/components/note/EditAdvisingNote.vue, src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2129
Whoops, it wasn't a build problem at all, it was a conflict with #1456.
=> BOAC-2129 Separate CSS for attachment pills

boac/api/curated_group_controller.py, src/components/curated/CuratedGroupBulkAdd.vue, src/components/curated/CuratedGroupHeader.vue, src/components/sidebar/CuratedGroups.vue, src/router.ts, src/views/CreateCuratedGroup.vue, src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2131
* review with `?w=1`
* textarea + validation is moved to shared component
* `/api/curated_group/students/add` returns group with students so page can refresh properly
=> BOAC-2131, update existing curated-group with bulk add SIDs

src/components/curated/CuratedGroupBulkAdd.vue, src/components/curated/CuratedGroupHeader.vue, src/mixins/StudentMetadata.vue, src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2131
* strip line breaks and tabs from bulk-add textarea
* prepare for future use case: ASC advisor seeing students w/o athleticsProfile
* curated-group-header fix
=> BOAC-2131, fixes in 'add SIDs to existing curated-group'

src/components/curated/CuratedGroupBulkAdd.vue, src/views/CreateCuratedGroup.vue, src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2127
=> BOAC-2127, accessibility enhancements for curated group: bulk-add SIDs

boac/api/notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2119
=> BOAC-2119 Four is not five

src/components/note/AdvisingNote.vue, src/components/note/NewNoteModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2129
=> BOAC-2129 Note attachments: more CSS spacing tweaks

src/components/note/AdvisingNote.vue, src/components/note/NewNoteModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2114
=> BOAC-2118 Delete attachments button advertises itself to screenreader

boac/models/curated_group.py, boac/models/development_db.py, tests/test_api/test_cache_utils.py, tests/test_api/test_curated_group_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2130
=> BOAC-2130, omit the 'unavailable' SIDs when rendering curated-group view

boac/models/note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2115
=> BOAC-2115 Update note timestamps on attachment addition/deletion

scripts/db/drop_schema.sql, scripts/db/migrate/20190425-BOAC-2049/pre_deploy_02_create_note_topics_table.sql, scripts/db/schema.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2049
This is to lay the necessary groundwork for my next PR for BOAC-2051.
=> BOAC-2049: Adds id to note_topics table

src/components/note/AdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2128
=> BOAC-2128 Clear errors on note expand/collapse

boac/api/util.py, boac/models/curated_group.py, src/components/home/HomeCuratedGroup.vue, src/components/sidebar/CuratedGroups.vue, src/router.ts, src/views/CreateCuratedGroup.vue, src/views/CuratedGroup.vue, tests/test_api/test_curated_group_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2132
Includes more concise wording (eg, toss out "Bulk")
=> BOAC-2132, curated group student-count should not include the group's 'unavailable' SIDs

src/components/curated/CuratedGroupSelector.vue, src/components/student/profile/StudentGroupSelector.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2067
Subjectively, and depending on what else is happening in the browser, 1000ms feels a bit brief.
=> BOAC-2067 Increase message lifespan on curated group edits

src/components/curated/CuratedGroupBulkAdd.vue, src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2127
https://jira.ets.berkeley.edu/jira/browse/BOAC-2140
https://jira.ets.berkeley.edu/jira/browse/BOAC-2145
=> BOAC-2127 / BOAC-2140, accessibility fixes (eg, textarea focus on validation error); faster 'Cancel' op with use of v-show

boac/api/curated_group_controller.py, src/api/curated.ts, src/views/CuratedGroup.vue, tests/test_api/test_curated_group_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2146
See Jira description.
=> BOAC-2146, curated-group bulk-add SIDs > all student profile data

package-lock.json, package.json
https://jira.ets.berkeley.edu/jira/browse/BOAC-2147
=> BOAC-2147 Remove unused npm sass packages

src/components/search/AdvisingNoteSnippet.vue, src/components/student/profile/AcademicTimeline.vue, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1871
=> BOAC-1871 Note search results link directly to open note

src/components/curated/CuratedGroupSelector.vue, src/main.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-2152
I assume that `self` was missed during a refactor.
=> BOAC-2152, self.isSaving is useless if 'self' is undefined

boac/api/notes_controller.py, boac/merged/advising_note.py, boac/models/note.py, boac/models/note_topic.py, src/api/notes.ts, src/components/note/AdvisingNote.vue, src/components/note/EditAdvisingNote.vue, src/components/student/profile/AcademicTimeline.vue, tests/conftest.py, tests/test_api/test_notes_controller.py, tests/test_merged/test_advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2051
Will submit a subsequent PR for adding note topics during note creation.
=> BOAC-2051: Implements add/remove topic feature for note editing

src/api/config.ts, src/components/admin/EditServiceAnnouncement.vue, src/layouts/StandardLayout.vue, src/mixins/Context.vue, src/store/modules/context.ts, src/views/Admin.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2081
https://jira.ets.berkeley.edu/jira/browse/BOAC-2083
=> BOAC-2081, css for service-announcement and corresponding Admin component

src/components/admin/EditServiceAnnouncement.vue, src/layouts/StandardLayout.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2081
=> BOAC-2083, validation on service-alert input and aria on announcement text

boac/api/notes_controller.py, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1927
=> BOAC-1927 Polite, minimal HTML for missing attachments

src/components/curated/CuratedGroupBulkAdd.vue, src/views/CreateCuratedGroup.vue, src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2162
=> BOAC-2162, CuratedGroupBulkAdd component must know if create/save op was cancelled

boac/api/config_controller.py, src/api/config.ts, src/components/admin/EditServiceAnnouncement.vue, src/layouts/StandardLayout.vue, tests/test_api/test_config_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2158
* publish and update-text are now separate operations
* UX tweaked to reflect the point above
=> BOAC-2158, UX enhancements to update/publish service alert on Admin page

src/components/note/AdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2163
=> BOAC-2163 Disable edit controls for legacy advising notes

boac/api/notes_controller.py, boac/merged/advising_note.py, boac/models/note.py, boac/models/note_topic.py, src/api/notes.ts, src/components/note/AdvisingNoteTopics.vue, src/components/note/EditAdvisingNote.vue, src/components/note/NewNoteModal.vue, src/components/student/profile/AcademicTimeline.vue, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2051
Also fixes some apparent regressions that should have been included in the previous PR.
=> BOAC-2051: Implements add/remove topic feature for note creation

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2150
=> BOAC-2150 Permanent URL links for advising notes

src/assets/styles/boac-global.css, src/components/curated/CuratedGroupSelector.vue, src/components/student/profile/StudentGroupSelector.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2030
=> BOAC-2030, minor fix to curated group select on student page

boac/merged/student.py, boac/models/cohort_filter.py, tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2171
=> BOAC-2171 Cohort membership constrained by creator

boac/api/notes_controller.py, boac/lib/util.py, boac/models/note.py, boac/models/topic.py, config/default.py, requirements.txt, src/api/notes.ts, src/components/note/AdvisingNoteTopics.vue, src/components/note/EditAdvisingNote.vue, src/components/note/NewNoteModal.vue, src/components/student/profile/AcademicTimeline.vue, tests/test_api/test_notes_controller.py, tests/test_lib/test_util.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2050
=> BOAC-2050: Introduces suggestions for note topics

boac/lib/cohort_filter_definition.py, fixtures/loch.sql, fixtures/loch_student_coe_profile_11667051.json, fixtures/loch_student_coe_profile_7890123456.json, fixtures/loch_student_coe_profile_9000000000.json, fixtures/loch_student_coe_profile_9100000000.json, scripts/db/migrate/20190508-BOAC-2167/post_deploy_01_upcase_cohort_filter_gender.sql, tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2167
=> BOAC-2167 Adapt to new CoE gender field format

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2175
=> BOAC-2175 Type conversion when matching advising notes to permalinks

src/components/course/SortableCourseList.vue, src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2100
=> BOAC-2100, do not blur instructor names in demo-mode

boac/externals/data_loch.py, boac/models/note.py, src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2190
In the legacy note feed, the BOA note feed, and the front end, just for consistency.
=> BOAC-2190 Sort advising notes by id as tiebreaker

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2189
=> BOAC-2189 Not all Academic Timeline entries have ids

boac/externals/data_loch.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2188
=> BOAC-2188 Better SQL binding for course search on user input

boac/__init__.py
=> NOJIRA, BOA master branch is v2.18

boac/api/search_controller.py, boac/externals/data_loch.py, boac/merged/advising_note.py, boac/merged/calnet.py, boac/models/note.py, src/api/search.ts, src/assets/styles/bootstrap-overrides.css, src/components/sidebar/SearchForm.vue, src/views/Search.vue, tests/test_merged/test_advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1852
It's our very first Advanced Note Search Filter (designs in https://jira.ets.berkeley.edu/jira/browse/BOAC-1789).
=> BOAC-1852 Allow user to narrow search to their own notes

src/assets/styles/boac-global.css, src/components/note/AdvisingNote.vue, src/components/sidebar/Cohorts.vue, src/components/sidebar/CuratedGroups.vue, src/components/sidebar/SearchForm.vue, src/views/AllCohorts.vue, src/views/Cohort.vue, src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2186
Follows PR #1505
=> BOAC-2186, CSS cleanup after move to 'grid' in main template

boac/merged/advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2191
=> BOAC-2191 Remove HTML tags with a parser like a grown-up

src/assets/styles/boac-global.css, src/components/admin/EditServiceAnnouncement.vue, src/components/util/Status.vue, src/views/Admin.vue, src/views/Home.vue, src/views/Search.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2182
=> BOAC-2182, ids on Admin page; CSS adjustments on padding, margins

src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2197
I'm learning my lesson, painfully.
=> BOAC-2197 Ids for note author filters

src/components/note/AdvisingNoteTopics.vue, src/mixins/Util.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2193
I tried to make this as unobtrusive as possible. It would be great to have others test it and report their annoyance levels.
=> BOAC-2193: Autocompletes topic with match from suggested topics

src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2201
QA PR coming soon.
=> BOAC-2201, if demoMode then no student name in page title

src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2201
master PR is #1512
=> [QA] BOAC-2201, if demoMode then no student name in page title

src/components/note/AdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2202
QA PR is #1515
=> BOAC-2202, if text is truncated then Safari has full-text tooltip (a problem for demo-mode)

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2203
=> BOAC-2203: Prevents note/topics call when note editing is turned off

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2203
QA PR for #1518
=> [QA] BOAC-2203: Prevents note/topics call when note editing is turned off

src/components/curated/CreateCuratedGroupModal.vue, src/views/CreateCuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2162
And, if cancel, put focus back on textarea.
=> BOAC-2162, if cancel with escape key then invoke same cancel()

src/components/note/EditAdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2199
=> BOAC-2199: Restores topics after cancel note edit

boac/externals/data_loch.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2209
Testing out what effect this has on performance in dev.
=> BOAC-2209 Switch profile and term queries to RDS

src/components/curated/CuratedGroupHeader.vue, src/components/student/SortBy.vue, src/store/modules/user.ts, src/views/Cohort.vue, src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2204
Includes:
* slightly diff convention on sortBy event handling
* less CSS
=> BOAC-2204, bulk add SIDs and page/orderBy are reset

src/components/note/AdvisingNoteTopics.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2210
=> BOAC-2210: Fixes topics array indexing error

scripts/db/tools/add_admin_user.sql, scripts/db/tools/add_advisor_per_dept.sql, scripts/db/tools/copy_external_cache_from_file.sql, scripts/db/tools/copy_external_cache_to_file.sql, scripts/db/tools/create_university_dept.sql, scripts/db/tools/delete_authorized_user.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2208
=> BOAC-2208, SQL scripts: delete_authorized_user and add_admin_user;  moved such scripts to 'scripts/db/tools'

boac/api/search_controller.py, boac/externals/data_loch.py, boac/merged/advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2209
=> BOAC-2209 Refactor search for (perhaps) performance improvements

src/components/admin/EditServiceAnnouncement.vue, src/layouts/StandardLayout.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2182
Teena PR coming soon.
=> BOAC-2182, more ids for Teena > service announcement tests

src/router.ts, src/store/modules/context.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-2185
=> BOAC-2185, service announcements for dev-auth peeps, too

src/assets/styles/boac-global.css, src/components/Footer.vue, src/components/student/profile/AcademicTimeline.vue, src/components/student/profile/StudentProfileHeader.vue, src/layouts/StandardLayout.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2207
Less custom CSS, more responsiveness.
=> BOAC-2207, fixed sidebar height; responsive student profile header

src/assets/styles/boac-global.css, src/components/Footer.vue, src/components/cohort/CohortPageHeader.vue, src/components/cohort/FilterRow.vue, src/components/curated/CuratedGroupSelector.vue, src/components/student/SortBy.vue, src/components/student/StudentRow.vue, src/components/student/profile/StudentClasses.vue, src/components/student/profile/StudentGroupSelector.vue, src/layouts/StandardLayout.vue, src/views/Cohort.vue, src/views/Course.vue, src/views/Home.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1745
In addition to CSS trimming, I moved footer component to its own `b-row` in StandardLayout for consistent positioning.
I encourage you to review with `?w=1`.
=> BOAC-1745, accessibility fix to show/hide terms; reduce custom CSS + responsiveness

boac/lib/util.py, boac/merged/advising_note.py, boac/merged/student.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2209
Easy enough, I hope, to remove or disable these lines once we no longer need them.
=> BOAC-2209 Simple temporary benchmarking on searches

boac/api/user_controller.py, boac/externals/data_loch.py, boac/merged/advising_note.py, config/default.py, fixtures/loch.sql, src/components/note/AdvisingNote.vue, src/mixins/Util.vue, tests/test_api/test_notes_controller.py, tests/test_externals/test_data_loch.py, tests/test_merged/test_advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2110
=> BOAC-2110: Displays ASC note summaries in timeline

src/store/modules/cohort-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-2223
=> BOAC-2223 Short-circuit applyFilters when no filters to apply

src/components/course/SortableCourseList.vue, src/components/note/AdvisingNote.vue, src/components/note/AdvisingNoteTopics.vue, src/components/search/SortableStudents.vue, src/components/student/profile/AcademicTimeline.vue, src/store/modules/context.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-2052
=> BOAC-2052: Makes topics feature more screen reader friendly

boac/lib/util.py, boac/merged/advising_note.py, boac/merged/calnet.py, boac/models/json_cache.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2218
=> BOAC-2218 Incorporate JSON caching into bulk advisor lookup

src/components/Footer.vue, src/components/search/SortableStudents.vue, src/mixins/Util.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2220
See 'stacked' at https://bootstrap-vue.js.org/docs/components/table/
=> BOAC-2220, responsive SortableStudents render is 'stacked' on narrow viewport

src/components/note/AdvisingNoteTopics.vue, src/components/note/EditAdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2226
=> BOAC-2226 Note ids all over topic elements

boac/externals/data_loch.py, fixtures/loch.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2219
=> BOAC-2219 Index table for student search by name

boac/models/note.py, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2229
=> BOAC-2229 Allow wholesale gutting of advising note topics

boac/api/config_controller.py, src/components/admin/EditServiceAnnouncement.vue, src/components/util/Spinner.vue, src/layouts/StandardLayout.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2180
The corresponding Teena change is queued up.
=> BOAC-2180, basic HTML support in BOA service announcements

boac/api/notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2176
=> BOAC-2176 When modifying attachments, hold on to your topics

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2195
=> BOAC-2195 Set focus when following permalink

src/components/course/CourseStudents.vue, src/mixins/Util.vue, src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2237
=> BOAC-2237, responsive students table in /course view

src/components/note/AdvisingNoteTopics.vue, src/mixins/Util.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2234
https://jira.ets.berkeley.edu/jira/browse/BOAC-2233
Includes fix to disable 'Add' button when input is blank.
=> BOAC-2233, canned topic is unavailable if you've already added it

src/api/ga.ts, src/store/modules/user.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-2196
=> BOAC-2196, add 'src/api/ga.ts' and protect against undefined Vue.prototype.$ga

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2232
=> BOAC-2232, in edit mode, 'Permalink' is hidden

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1901
=> BOAC-1901 Remove duplicative SR text from open notes

boac/models/note_topic.py, scripts/db/migrate/20190521-BOAC-2231/pre_deploy_01_shorten_note_topics.sql, scripts/db/schema.sql, src/components/note/AdvisingNoteTopics.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2231
With arbitrary truncation of what's already in the db, since we haven't let real users near it.
=> BOAC-2231 Constrain topics to 50 characters

boac/lib/util.py, boac/models/note.py, boac/models/note_topic.py, scripts/db/migrate/20190521-BOAC-2230/pre_deploy_01_add_deleted_at_to_note_topics.sql, scripts/db/schema.sql, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2230
https://jira.ets.berkeley.edu/jira/browse/BOAC-2239
=> BOAC-2230 BOAC-2239 Note topics: soft delete, update note timestamp

src/components/cohort/ApplyAndSaveButtons.vue, src/components/cohort/CohortPageHeader.vue, src/components/student/profile/StudentClasses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1739
https://jira.ets.berkeley.edu/jira/browse/BOAC-1744
=> BOAC-1739 BOAC-1744 Accessibility fixes

src/components/note/AdvisingNoteTopics.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2228
=> BOAC-2228 Boring old dropdown select for advising note topics

boac/api/search_controller.py, boac/externals/data_loch.py, boac/merged/advising_note.py, boac/models/note.py, fixtures/loch.sql, src/components/sidebar/SearchForm.vue, src/views/Search.vue, tests/test_merged/test_advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1855
=> BOAC-1855 Filtered note search by topic

boac/externals/data_loch.py, fixtures/loch.sql, tests/test_merged/test_advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2243
=> BOAC-2243 Note search: translate to legacy topic formats as required

src/store/modules/curated.ts, src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2245
=> BOAC-2245, update studentCount properly when student is removed from curated group

src/store/modules/cohort.ts, src/store/modules/curated.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-2252
=> BOAC-2252, true lazy-load of myCohorts and myCuratedGroups

src/components/note/AdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2247
=> BOAC-2247 Keep "author" attached to individual notes

boac/models/alert.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2253
Summer terms have no "regular undergraduate session" and shouldn't try to query for one.
=> BOAC-2253 Avoid failing db query during summer terms

boac/externals/data_loch.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2255
=> BOAC-2255 An empty array of SIDs does not mean 'every conceivable SID'

src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2244
A `?w=1` review.
=> BOAC-2244 UX/style fixes for sidebar search

src/components/sidebar/SearchForm.vue, src/views/Cohort.vue, src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2251
=> BOAC-2251, ignore 'sortBy-user-preference-change' until view has loaded

boac/api/config_controller.py, package-lock.json, package.json, src/components/student/profile/TimelineDate.vue, src/main.ts, src/mixins/Context.vue, src/store/modules/context.ts, tests/test_api/test_config_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1995
=> BOAC-1995 Correct local time display for note timestamps

src/components/note/AdvisingNote.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2242
=> BOAC-2242, if note has neither subject nor body then give 'em a bland summary

package-lock.json, package.json
https://jira.ets.berkeley.edu/jira/browse/NS-551
=> NS-551 Upgrade axios to 0.19

boac/__init__.py
=> NOJIRA, BOA master branch bumped to v2.19

config/default.py, config/development.py, config/test.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2295
I'll add release instruction to have config removed from dev, qa and prod overrides.
=> BOAC-2295, FEATURE_FLAG_EDIT_NOTES default to True

boac/api/notes_controller.py, src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2294
=> [QA] BOAC-2294: Removes feature flag restriction from topics API

boac/api/notes_controller.py, src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2294
=> BOAC-2294: Removes feature flag restriction from topics API

src/views/Cohort.vue, src/views/CuratedGroup.vue
https://github.com/ets-berkeley-edu/boac/pull/1585
QA version of #1585.
=> [QA] BOAC-2300 Fix loading-aware conditional in cohort/group sort

src/mixins/Util.vue, src/views/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2302
master PR is #1587
=> [QA] BOAC-2302, 'continueEdit-if-back-button' logic in /cohort is fooled by clicking around sidebar

src/mixins/Util.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2303
The QA PR is #1590
=> BOAC-2303, fix sortable columns: if args _.isNumber then compare w/o type conversion

boac/api/search_controller.py, boac/externals/data_loch.py, boac/lib/util.py, boac/merged/advising_note.py, boac/models/note.py, src/components/sidebar/SearchForm.vue, src/views/Search.vue, tests/test_api/test_search_controller.py, tests/test_merged/test_advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1856
=> BOAC-1856 Date filter for notes search

src/components/home/HomeCohort.vue, src/components/home/HomeCuratedGroup.vue, src/components/search/SortableStudents.vue, src/views/Home.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2169
The qa PR is #1592
=> BOAC-2308, proper secondary, tertiary sort for sortableStudents component; css fix on pills

src/components/home/HomeCohort.vue, src/components/home/HomeCuratedGroup.vue, src/components/search/SortableStudents.vue, src/views/Home.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2169
Styles shared across home-view components moved to `Home.vue` with fix to `home-issues-pill`.
=> [QA] BOAC-2308, proper secondary, tertiary sort for sortableStudents component; css fix on pills

src/assets/styles/boac-global.css, src/components/course/CourseStudents.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2309
=> BOAC-2309: Fixes row spacing on class list course sites

src/assets/styles/bootstrap-overrides.css, src/components/home/HomeCohort.vue, src/components/home/HomeCuratedGroup.vue, src/components/search/SortableStudents.vue, src/views/Home.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2246
=> BOAC-2308, secondary, tertiary, etc sort is always ASC; rogue icons begone

src/assets/styles/bootstrap-overrides.css, src/components/home/HomeCohort.vue, src/components/home/HomeCuratedGroup.vue, src/components/search/SortableStudents.vue, src/views/Home.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2246
The master PR is #1596
=> [QA] BOAC-2308, secondary, tertiary, etc sort is always ASC; rogue icons begone

src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2311
=> BOAC-2311: Adds attr to identify checked radio

src/components/sidebar/SearchForm.vue, src/layouts/StandardLayout.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2236
Narrower sidebar with appropriate wrapping.
=> BOAC-2236, reduce percentage of sidebar and improved flex-wrap

src/components/sidebar/SearchForm.vue, src/layouts/StandardLayout.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2236
master PR: #1601
=> [QA] BOAC-2236, reduce percentage of sidebar and improved flex-wrap

src/views/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2165
QA version of #1602
=> [QA] BOAC-2165: Preserves cohort filters when returning via back button

src/views/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2165
=> BOAC-2165: Preserves cohort filters when returning via back button

boac/api/search_controller.py, boac/merged/advising_note.py, src/views/Search.vue, tests/test_api/test_search_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1879
=> BOAC-1879: Expands scope of note search

src/components/course/CourseStudents.vue, src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2319
=> [QA] BOAC-2319, border-bottom on each student row of class page

src/components/course/CourseStudents.vue, src/components/sidebar/Cohorts.vue, src/components/sidebar/CuratedGroups.vue, src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2319
QA PR is #1607
=> BOAC-2319, border-bottom on each student row of class page

src/assets/styles/bootstrap-overrides.css, src/components/search/SortableStudents.vue, src/mixins/Util.vue, src/views/Search.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2317
=> BOAC-2308, nil in column-type number is treated as zero during sort

src/components/sidebar/Cohorts.vue, src/components/sidebar/CuratedGroups.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2165
=> BOAC-2165: Fixes sidebar links with programmatic routing

src/components/student/StudentBoxplot.vue, src/components/student/profile/StudentClasses.vue
=> BOAC-1994: Shows assignments submitted as boxplot when possible

.ebextensions/00_ami.config
https://jira.ets.berkeley.edu/jira/browse/BOAC-2316
=> BOAC-2316, SSLCertificateArns in 00_ami.config for BOA SSL certificate

boac/api/notes_controller.py, boac/models/note.py, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2271
=> BOAC-2271, more test coverage batch note creation: cohort_ids and curated_group_ids

boac/api/notes_controller.py, boac/models/note.py, src/api/notes.ts, src/components/note/AdvisingNoteTopics.vue, src/components/note/CreateNoteCohortDropdown.vue, src/components/note/EditAdvisingNote.vue, src/components/note/NewNoteModal.vue, src/components/sidebar/Sidebar.vue, src/components/student/profile/AcademicTimeline.vue, src/mixins/NoteEditSession.vue, src/mixins/Util.vue, src/store/modules/note-edit-session.ts, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2278
=> BOAC-2278, front-end support for batch note creation (except for search students field)

src/components/admin/EditServiceAnnouncement.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2328
=> BOAC-2328, do not wrongly disable post/unpost

boac/api/cache_utils.py, boac/models/json_cache.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2326
G'bye, ol' hoss.
=> BOAC-2326 Allow retries of BOA refresh; drop old cache staging code

boac/routes.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2347
=> BOAC-2347, open index_html once per deployment, not on every front_end_route()

boac/api/util.py, boac/models/alert.py, boac/models/curated_group.py, tests/test_api/test_curated_group_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2349
This should lighten the load on the homepage a bit.
=> BOAC-2349 Eliminate unnecessary curated group feed generation on homepage load

.ebextensions/01_create_apache_conf.config
https://jira.ets.berkeley.edu/jira/browse/BOAC-2345
Informed by https://medium.com/@ali.dev/how-to-setup-caching-gzip-compression-in-apache-web-server-with-htaccess-292a0f689553
=> BOAC-2345, static assets compressed and cached at Apache layer

boac/externals/data_loch.py
https://jira.ets.berkeley.edu/jira/browse/NS-568
=> NS-568 Pull ASC, COE profiles from RDS

boac/api/cohort_controller.py, boac/api/curated_group_controller.py, boac/externals/data_loch.py, boac/models/alert.py, boac/models/cohort_filter.py, src/components/home/HomeCohort.vue, src/components/home/HomeCuratedGroup.vue, tests/test_api/test_curated_group_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2324
=> BOAC-2324 Cutoff for homepage student-with-alert lists

.ebextensions/03_create_mpm_worker_conf.config, .ebextensions/99_delayed_script.config
https://jira.ets.berkeley.edu/jira/browse/BOAC-2323
=> BOAC-2323 Post-deploy Apache restart to pick up changed configs

boac/api/cohort_controller.py, boac/api/curated_group_controller.py, boac/merged/advising_note.py, boac/merged/student.py, boac/models/cohort_filter.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2367
=> BOAC-2367 More benchmarking on high-traffic code paths

boac/externals/data_loch.py, boac/models/note.py, src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2335
=> BOAC-2335 Prefer updated_at for note date filters wherever possible

src/components/home/HomeCohort.vue, src/components/home/HomeCuratedGroup.vue, src/components/home/HomeUtil.vue, src/components/search/SortableStudents.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2368
=> BOAC-2368 Tweak messaging for homepage cohort/group list cutoff

boac/api/cohort_controller.py, boac/api/util.py, boac/merged/calnet.py, boac/models/authorized_user.py, boac/models/cohort_filter.py, src/views/AllCohorts.vue, tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2365
=> BOAC-2365, performance bump for /all/cohorts: bulk LDAP query, db.all_cohorts() is expensive

src/components/sidebar/Cohorts.vue, src/components/sidebar/CuratedGroups.vue, src/components/sidebar/SearchForm.vue, src/components/util/NavLink.vue, src/mixins/Util.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2375
=> BOAC-2375, render sidebar links with NavLink, simpler force-route-reload logic

src/components/curated/CuratedGroupSelector.vue, src/components/student/profile/StudentProfileHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2333
Flint approved location on page.
=> BOAC-2333, student profile says 'Transfer' if sisProfile.transfer

package-lock.json, package.json, src/components/sidebar/SearchForm.vue, src/main.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-2334
The out-of-the-box element didn't cut it and has to go back in the box.
=> BOAC-2334 Better cross-browser date input

boac/externals/data_loch.py, boac/merged/advising_note.py, fixtures/loch.sql, tests/test_api/test_notes_controller.py, tests/test_merged/test_advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1907
=> BOAC-1907 Note search: show category/subcategory as snippet if no body

boac/api/auth_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2377
This is one change that should have been in PR #1644
=> BOAC-2377, flush_cached() when logout_user()

src/App.vue, src/components/sidebar/SearchForm.vue, src/main.ts, src/router.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-2389
=> BOAC-2389, move 'vue-analytics' init out of main.ts

src/App.vue, src/api/auth.ts, src/components/admin/DevAuth.vue, src/mixins/Context.vue, src/store/modules/context.ts, src/store/modules/user.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-2389
In PR #1645, the `async` in App.vue worked fine locally but it broke boa-dev – this PR follows convention of other async uses. To verify this change I deployed this branch to boa-dev and it looks good. I'll reset pipeline if/when this is merged.
=> BOAC-2389, async init is best placed in context.ts actions

src/components/student/StudentBoxplot.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2363
On boa-dev, `/course/2192/21547` is sample busted-ness.
=> BOAC-2363, null tolerant boxplot render

boac/api/notes_controller.py, src/components/note/CreateNoteCohortDropdown.vue, src/components/note/NewNoteModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2278
=> BOAC-2278, more tweaks to front-end modal, batch note creation

boac/api/cohort_controller.py, boac/models/cohort_filter.py, src/components/sidebar/Sidebar.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2257
In `get_cohort_by_user_id` we don't want 'sids' column. So, avoid select-star query.
=> BOAC-2257, new-batch-note button is position-fixed; explicit 'select' SQL is faster

src/components/sidebar/SearchForm.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1942
Instead of punting all accessibility issues to future sprint, I fixed one and punted the rest.
=> BOAC-1942, accessibility: search options before input field

src/components/admin/DemoModeToggle.vue, src/components/course/CourseStudents.vue, src/components/curated/CuratedGroupSelector.vue, src/components/matrix/Matrix.vue, src/components/search/AdvisingNoteSnippet.vue, src/components/search/SortableStudents.vue, src/components/student/StudentRow.vue, src/components/student/profile/StudentClasses.vue, src/components/student/profile/StudentGroupSelector.vue, src/components/util/SectionSpinner.vue, src/components/util/Spinner.vue, src/layouts/StandardLayout.vue, src/mixins/Util.vue, src/views/Admin.vue, src/views/Course.vue, src/views/Search.vue, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2399
Includes:
* path to student profile page no longer exposes UID
* a few helpful fixes for Teena, including encoded UID concern above
* lastly, fix "best practice" errors reported by dev-tools audit 
Teena PR will follow.
=> BOAC-2399 / BOAC-2400, encoded UID in student profile path; Teena fix on waitlisted, etc.

src/components/note/CreateNoteCohortDropdown.vue, src/components/note/NewNoteModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2276
Create note for zero students? Me thinks not.
=> BOAC-2276, when batch-note mode, show student count and disable save btn appropriately

src/components/course/CourseStudents.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2405
Mon dieu!
=> BOAC-2405, import Util to use studentRoutePath()

src/components/note/NewNoteModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2272
UX: https://jira.ets.berkeley.edu/jira/browse/BOAC-2283
=> BOAC-2272, batch note alert: '...X student records. Are you sure?'

src/views/Course.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2407
=> BOAC-2407, proper d-flex and padding on checkbox + tabs

src/components/note/NewNoteModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2284
=> BOAC-2284, Batch note create: if cancel unsaved changes then '...you sure?'

src/components/note/NewNoteModal.vue, src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2415
A few forgotten snippets.
=> BOAC-2415, NewNoteModal > non-batch mode > targetStudentCount is one

boac/api/notes_controller.py, boac/models/note.py, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2417
You wrote it, you read it.
=> BOAC-2417, when batch note create, mark as read by author

src/components/student/StudentBoxplot.vue
=> BOAC-1994: Fixes boxplot regression

src/components/student/StudentBoxplot.vue
=> [QA] BOAC-1994: Fixes boxplot regression

src/components/student/profile/StudentClasses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2399
=> BOAC-2399, valid termId in element.id

src/components/student/profile/StudentClasses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2399
master PR is #1666
=> [QA] BOAC-2399, valid termId in element.id

src/components/course/CourseStudents.vue
Missed this in my previous PR. Also, I forgot to add the assignments boxplot on the course page in the first place, so making up for that here.
=> BOAC-1994: Fixes boxplots on course page

src/components/course/CourseStudents.vue
=> [QA] BOAC-1994: Fixes boxplots on course page

src/components/admin/DemoModeToggle.vue, src/components/admin/EditServiceAnnouncement.vue, src/components/matrix/Matrix.vue, src/components/student/StudentRow.vue, src/components/student/profile/StudentProfileGPA.vue, src/views/Admin.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2423
My original `grep` missed these.
=> [QA] BOAC-2423, font-awesome ref fixes incl. zoom buttons on /matrix

src/components/admin/DemoModeToggle.vue, src/components/admin/EditServiceAnnouncement.vue, src/components/matrix/Matrix.vue, src/components/student/StudentRow.vue, src/components/student/profile/StudentProfileGPA.vue, src/views/Admin.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2423
qa PR is #1671
=> BOAC-2423, font-awesome ref fixes incl. zoom buttons on /matrix

src/assets/styles/boac-global.css, src/components/cohort/FilterRow.vue, src/components/student/profile/StudentProfileUnits.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2413
https://jira.ets.berkeley.edu/jira/browse/BOAC-2422
* Disabled cohort filter options are clearly disabled
* Null units alignment
=> BOAC-2413 / BOAC-2422, style fixes on student profile, cohort filter dropdown

src/assets/styles/bootstrap-overrides.css
https://jira.ets.berkeley.edu/jira/browse/BOAC-2428
The qa PR is #1675
=> BOAC-2428, odd case of ::after in bootstrap-override requires generic unicode

src/api/auth.ts, src/api/cohort.ts, src/api/config.ts, src/api/course.ts, src/api/curated.ts, src/api/menu.ts, src/api/notes.ts, src/api/search.ts, src/api/student.ts, src/api/user.ts, src/components/home/HomeCohort.vue, src/components/home/HomeCuratedGroup.vue, src/components/sidebar/SearchForm.vue, src/mixins/UserMetadata.vue, src/store/modules/user.ts, src/views/Search.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2418
* consistency in use of `@/api/api-utils`
* smooth out edges of Google Analytics integration
=> BOAC-2418, more and consistent use of gaTrackEvent in src/api

src/components/matrix/Matrix.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2429
qa PR is #1680
=> BOAC-2429, 'demo-mode-blur' must be on router-link, not enclosing div

src/components/matrix/Matrix.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2429
=> [QA] BOAC-2429, 'demo-mode-blur' must be on router-link, not enclosing div

boac/api/notes_controller.py, boac/api/search_controller.py, boac/api/student_controller.py, boac/externals/data_loch.py, boac/merged/advising_note.py, src/api/notes.ts, src/api/search.ts, src/api/student.ts, src/components/sidebar/SearchForm.vue, src/components/util/Autocomplete.vue, src/views/Search.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-1853
https://jira.ets.berkeley.edu/jira/browse/BOAC-1854
Including a first-pass autocomplete component. The most obvious thing it's missing is browser-side caching of suggestions, which would make the whole experience less jittery; but in my local testing it seemed usable even so.
=> BOAC-1853 BOAC-1854 Filter search by individual advisor and/or student

src/App.vue, src/components/cohort/ApplyAndSaveButtons.vue, src/components/cohort/CohortPageHeader.vue, src/components/cohort/FilterRow.vue, src/components/curated/CuratedGroupSelector.vue, src/components/sidebar/SearchForm.vue, src/components/student/profile/AcademicTimeline.vue, src/components/student/profile/StudentClasses.vue, src/components/student/profile/StudentGroupSelector.vue, src/components/student/profile/StudentProfileUnits.vue, src/mixins/Berkeley.vue, src/mixins/Context.vue, src/mixins/UserMetadata.vue, src/mixins/Util.vue, src/store/modules/context.ts, src/store/modules/user.ts, src/views/Cohort.vue, src/views/CreateCuratedGroup.vue, src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2434
=> BOAC-2434, proper hash format for event summaries sent to Google Analytics

src/App.vue, src/components/note/CreateNoteAddStudent.vue, src/components/note/NewNoteModal.vue, src/components/util/Autocomplete.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2277
Minor override options in `Autocomplete` component.
=> BOAC-2277, add Student, by name or SID (with autosuggest), in 'New Note' form

src/components/note/CreateNoteAddStudent.vue, src/components/note/NewNoteModal.vue, src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2282
=> BOAC-2282, steps towards a more accessible (batch) note create form

src/store/modules/cohort-edit-session.ts, src/views/CuratedGroup.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2431
=> BOAC-2431, show sortBy if page > 1 and only one student in view

boac/lib/util.py, src/components/search/AdvisingNoteSnippet.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2435
=> BOAC-2435 Fix timezone adjustment in note search date filters

boac/lib/util.py, src/components/search/AdvisingNoteSnippet.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2435
QA version of #1688.
=> [QA] BOAC-2435 Fix timezone adjustment in note search date filters

src/store/modules/context.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-2440
What a difference an if-block makes.
=> BOAC-2440, loadConfig with or without authenticated user

.ebextensions/00_ami.config
https://jira.ets.berkeley.edu/jira/browse/BOAC-2442
=> BOAC-2442 Update SSHSourceRestriction

boac/externals/data_loch.py, fixtures/loch.sql, tests/test_api/test_notes_controller.py, tests/test_api/test_search_controller.py, tests/test_api/test_student_controller.py, tests/test_merged/test_advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-1853
https://jira.ets.berkeley.edu/jira/browse/BOAC-1854
Follow-up to #1682.
=> BOAC-1853 BOAC-1854 Tests for note search by advisor and student

boac/models/curated_group.py
This didn't cause BOAC-2430, but it's certainly distracting.
=> NOJIRA Fix erroneous ORM mapping of Integer ForeignKey to String

src/components/note/CreateNoteAddStudent.vue, src/components/note/NewNoteModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2289
And, put `id` on added-student info.
=> BOAC-2289, fix :id on 'New Note' button

src/components/note/CreateNoteCohortDropdown.vue
=> NOJIRA, element ids in batch-note cohort dropdown

src/components/student/StudentBoxplot.vue, src/components/student/profile/StudentClasses.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2443
=> BOAC-2443: Fixes boxplot tooltip bleed-through

src/components/sidebar/SearchForm.vue, src/components/util/Autocomplete.vue, tox.ini
https://jira.ets.berkeley.edu/jira/browse/BOAC-2433
=> BOAC-2433 Note search: resolve conflicts between advisor name/'Posted by you'

src/components/note/NewNoteModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2448
https://jira.ets.berkeley.edu/jira/browse/BOAC-2446
Includes syntax fix in 'will be added to X student records' message.
=> BOAC-2448, batch notes create: on reset, set sids to empty

src/components/util/Autocomplete.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2447
=> BOAC-2447 Autocomplete cleans up punctuation before querying

src/components/note/CreateNoteAddStudent.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2449
=> BOAC-2449, if student was added to batch-note then do not auto-suggest again

boac/api/notes_controller.py, boac/merged/advising_note.py, src/api/notes.ts, src/components/note/NewNoteModal.vue, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2449
=> BOAC-2449, recalculate student count (via api) when cohort/group is added/removed

src/components/util/Autocomplete.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2453
I got my dratted regex negatives confused.
=> BOAC-2453 Autocomplete: spaces matter, punctuation doesn't

src/api/notes.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-2456
=> BOAC-2456, fix typo in '/api/notes' app.route

src/assets/styles/bootstrap-overrides.css, src/components/note/NewNoteModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2455
Color math.
=> BOAC-2455 Disabled New Note buttons are pale and wan but not transparent

src/components/note/NewNoteModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2449
=> BOAC-2449, recalculateStudentCount() in batch-note, even for simple add/remove SID

src/components/curated/CuratedGroupSelector.vue, src/mixins/UserMetadata.vue, src/store/modules/user.ts, src/views/Cohort.vue, src/views/Course.vue, src/views/Search.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2434
=> BOAC-2434, configurable gaEventTracker for Curated Group widget

boac/externals/data_loch.py, boac/merged/advising_note.py, boac/models/note.py, tests/test_api/test_search_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2465
=> BOAC-2465 ASC advising notes need author search by UID

boac/api/user_controller.py, boac/lib/http.py, src/views/Admin.vue, tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2420
Download link appears as:
=> BOAC-2420, export list of BOA users as CSV from /admin

boac/__init__.py
=> NOJIRA, BOA master is now v2.21

boac/api/config_controller.py, boac/api/notes_controller.py, config/default.py, config/development.py, config/test.py, src/components/sidebar/Sidebar.vue, src/mixins/Context.vue, src/store/modules/context.ts, tests/test_api/test_config_controller.py, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2477
v2.21 release instructions have been updated.
=> BOAC-2477, remove FEATURE_FLAG_BATCH_NOTES from code + config

boac/api/cohort_controller.py, boac/api/curated_group_controller.py, boac/api/util.py, boac/models/cohort_filter.py, package-lock.json, package.json, src/api/cohort.ts, src/api/curated.ts, src/components/cohort/CohortPageHeader.vue, src/components/curated/CuratedGroupHeader.vue, src/mixins/CohortEditSession.vue, src/store/modules/cohort-edit-session.ts, tests/test_api/test_cohort_controller.py, tests/test_api/test_curated_group_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2310
UX: https://jira.ets.berkeley.edu/jira/browse/BOAC-2299
=> BOAC-2310, from /cohort and /curated, export students in CSV

src/components/cohort/CohortPageHeader.vue, src/components/curated/CuratedGroupHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2310
See latest comment in Jira.
=> BOAC-2310, disable 'Export List' with precarious bool expression

boac/api/cohort_controller.py, boac/externals/data_loch.py, boac/merged/calnet.py, boac/merged/cohort_filter_options.py, boac/merged/student.py, boac/merged/user_session.py, boac/models/cohort_filter.py, boac/models/development_db.py, config/default.py, fixtures/calnet_search_entries.json, fixtures/loch.sql, package-lock.json, src/api/cohort.ts, src/mixins/CohortEditSession.vue, src/store/modules/cohort-edit-session.ts, tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2383
A lot of the added code is adjusting to the fact that cohort filters are no longer the same for everyone in the universe, but will change depending on what academic plans the cohort owner has available.
=> BOAC-2383 "My Students" cohort filter with academic plan options

src/assets/styles/boac-global.css, src/components/note/CreateNoteAddStudent.vue, src/components/sidebar/SearchForm.vue, src/components/util/Autocomplete.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2480
QA PR coming soon.
=> BOAC-2480, optional blur in autosuggest; demo-mode blur for student pills

src/assets/styles/boac-global.css, src/components/note/CreateNoteAddStudent.vue, src/components/sidebar/SearchForm.vue, src/components/util/Autocomplete.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2480
master PR is #1726
=> [QA] BOAC-2480, optional blur in autosuggest; demo-mode blur for student pills

boac/api/util.py, boac/externals/data_loch.py, boac/merged/cohort_filter_options.py, boac/merged/student.py, boac/models/cohort_filter.py, boac/models/development_db.py, scripts/db/migrate/20190716-BOAC-2384/alter_advisor_uid_key_in_cohort_json.py, scripts/db/migrate/20190716-BOAC-2384/alter_advisor_uid_key_in_cohort_json.sh, tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2384
A rename up and down the stack to avoid confusion/collision with the general-purpose "My Students" filter.
=> BOAC-2384 Advisor filter and associated params are COE-only

src/components/note/NewNoteModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2482
=> [QA] BOAC-2482, if cancel note edit then properly preserve sid

src/components/note/NewNoteModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2482
The qa PR is #1729
=> BOAC-2482, if cancel note edit then properly preserve sid

boac/api/util.py, boac/externals/data_loch.py, boac/merged/cohort_filter_options.py, boac/merged/student.py, boac/models/cohort_filter.py, scripts/db/migrate/20190716-BOAC-2256/alter_ethnicities_key_in_cohort_json.py, scripts/db/migrate/20190716-BOAC-2256/alter_ethnicities_key_in_cohort_json.sh, tests/test_api/test_cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2256
Thank you @paulkerschen for providing script template in PR #1728
=> BOAC-2256, 'ethnicity' filter is now 'coeEthnicity' (incl. migration script)

package-lock.json, package.json
https://jira.ets.berkeley.edu/jira/browse/BOAC-2484
=> BOAC-2484: highcharts, but not too high

src/components/note/CreateNoteAddStudent.vue, src/components/note/CreateNoteCohortDropdown.vue
See latest comment in https://jira.ets.berkeley.edu/jira/browse/BOAC-2282  Good bug bashing by @lyttam
=> BOAC-2282, expect student.label in autosuggest, not student.name

scripts/db/migrate/20190716-BOAC-2487/post_deploy_01_insert_advising_note_topic.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2487
=> BOAC-2487, new advising note topic: Minors

boac/api/search_controller.py, boac/externals/data_loch.py, boac/merged/advising_note.py, boac/models/note.py, src/components/sidebar/SearchForm.vue, src/views/Search.vue, tests/test_api/test_search_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2249
=> BOAC-2249 Allow filtered notes search without phrase

.ebextensions/05_download_local_configuration.config, .gitignore, boac/api/config_controller.py, boac/api/util.py, boac/externals/google_calendar_client.py, config/default.py, requirements.txt, src/components/appointment/AdvisingAppointment.vue, src/components/student/profile/AcademicTimeline.vue, src/mixins/Context.vue, src/store/modules/context.ts, tests/test_api/test_config_controller.py, tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2488
Includes:
* feature flag
* new Vue component: AdvisingAppointments
* `boac/externals/google_calendar_client.py` (fault tolerant)
=> BOAC-2488, prototype Google calendar integration; all appointments from one calendar

package-lock.json, package.json
https://jira.ets.berkeley.edu/jira/browse/BOAC-2463
https://jira.ets.berkeley.edu/jira/browse/BOAC-2490
=> BOAC-2463 BOAC-2470 Update lodash dependencies

src/components/cohort/FilterRow.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2256
Prettier, methinks.
=> BOAC-2256, style fixes in cohort dropdown due to verbose menu options

boac/__init__.py
Corresponding Nessie PR: https://github.com/ets-berkeley-edu/nessie/pull/483
=> NOJIRA, BOA is now v3.0 on master branch

boac/lib/berkeley.py, boac/models/development_db.py, boac/models/university_dept.py, scripts/db/migrate/20190722-BOAC-2508/pre_deploy_01_alter_university_depts.sql, scripts/db/schema.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2508
=> BOAC-2508 Add new university departments, automate_memberships boolean

boac/api/user_controller.py, boac/merged/cohort_filter_options.py, boac/models/authorized_user.py, consoler.py, scripts/db/migrate/20190722-BOAC-2509/pre_deploy_02_alter_authorized_users.sql, scripts/db/schema.sql, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2509
=> BOAC-2509 Add soft delete logic to authorized_users

boac/api/cache_utils.py, boac/externals/data_loch.py, boac/lib/berkeley.py, boac/models/authorized_user.py, boac/models/university_dept.py, tests/conftest.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2353
Tests to come in a follow-up; I wanted to give the job itself an early opportunity to get kicked around.
=> BOAC-2353 Refresh authorized users from SIS advising tables

boac/api/notes_controller.py, boac/models/development_db.py, fixtures/calnet_search_entries.json, tests/test_api/test_notes_controller.py, tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2528
=> BOAC-2528 Prefer LDAP for note author department affiliations

boac/externals/data_loch.py, config/default.py, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2378
Eliminating some distractions before Nessie replaces the L&S schema with an all-active-undergraduates schema.
=> BOAC-2378 Remove unnecessary student siloing support

tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2531
=> BOAC-2531 Hush intermittent test failure

boac/api/util.py, tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2526
=> BOAC-2526: Uses bulk LDAP query to load user profiles

boac/api/cache_utils.py, boac/externals/data_loch.py, boac/lib/berkeley.py, boac/models/db_relationships.py, boac/models/university_dept.py, tests/test_api/test_cohort_controller.py, tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2523
=> BOAC-2523 Fixes to advisor-department mapping import

boac/api/notes_controller.py, boac/models/development_db.py, boac/models/topic.py, scripts/db/migrate/20190716-BOAC-2487/post_deploy_01_insert_advising_note_topic.sql, scripts/db/schema.sql, src/api/notes.ts, src/components/sidebar/SearchForm.vue, src/store/modules/student-edit-session.ts, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2436
New notes cannot have deleted topics. Search form includes all.
=> BOAC-2436, deleted_at column for topics; show all in search; db mod script

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2530
=> BOAC-2530 Backslash abatement

src/components/student/profile/StudentProfileHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2535
=> BOAC-2535 Rescue student profile header when level unavailable

boac/api/cache_utils.py, boac/models/authorized_user.py, boac/models/development_db.py, fixtures/loch.sql, requirements.txt, tests/test_api/test_cache_utils.py, tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2353
=> BOAC-2353 Test coverage for advisor membership refresh

boac/api/user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2527
=> BOAC-2527 BOA welcomes very special guests

boac/api/util.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2549
=> BOAC-2549 Skirt disaster on missing hold attributes

boac/api/config_controller.py, config/default.py, src/components/util/Status.vue, src/layouts/StandardLayout.vue, src/mixins/Context.vue, src/mixins/Session.vue, src/store/modules/context.ts, tests/test_api/test_config_controller.py, tests/test_api/test_status_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2452
=> BOAC-2452: Keeps session alive unless browser is closed

scripts/db/migrate/20190722-BOAC-2508/pre_deploy_01_alter_university_depts.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2527
=> BOAC-2527 Update database migration to include guest access 'department'

boac/lib/berkeley.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2552
=> BOAC-2552: Handles winter term IDs in student profile

src/views/Search.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2503
=> BOAC-2503 A stronger no results page

src/components/student/StudentUnitsChart.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2562
=> BOAC-2562 Zero is the least cumulative number that you'll ever do

src/components/cohort/CohortPageHeader.vue, src/components/curated/CuratedGroupHeader.vue, src/store/modules/cohort-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-2538
=> BOAC-2538: Disables export link until download has started

scripts/db/migrate/20190716-BOAC-2256/alter_ethnicities_key_in_cohort_json.py, scripts/db/migrate/20190716-BOAC-2256/alter_urm_key_in_cohort_json.py, scripts/db/migrate/20190716-BOAC-2384/alter_advisor_uid_key_in_cohort_json.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2256
A copy-paste error that just kept copy-pasting along.
=> BOAC-2256 Remove superfluous array wrappers in migration scripts

scripts/db/migrate/20190716-BOAC-2256/alter_ethnicities_key_in_cohort_json.py, scripts/db/migrate/20190716-BOAC-2256/alter_urm_key_in_cohort_json.py, scripts/db/migrate/20190716-BOAC-2384/alter_advisor_uid_key_in_cohort_json.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2256
QA version of #1771.
=> [QA] BOAC-2256 Remove superfluous array wrappers in migration scripts

boac/models/note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2464
QA version of #1773.
=> [QA] BOAC-2464 Keep deleted notes out of no-phrase search results

boac/models/note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2464
=> BOAC-2464 Keep deleted notes out of no-phrase search results

boac/models/development_db.py, tests/test_api/test_notes_controller.py, tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2524
=> BOAC-2524 Remove vestiges of PHYSI department from test code

boac/api/cache_utils.py, boac/externals/data_loch.py, boac/merged/user_session.py, boac/models/authorized_user.py, boac/models/development_db.py, fixtures/loch.sql, scripts/db/migrate/20190802_BOAC-2512/pre_deploy_01_alter_authorized_users_add_can_access_canvas_data.sql, scripts/db/schema.sql, tests/test_api/test_cache_utils.py, tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2512
Nessie PR to come will add non-advisor users to our source table.
=> BOAC-2512 Import non-advisors from advising tables without Canvas data permissions

boac/merged/student.py, src/components/student/profile/StudentClasses.vue, src/components/student/profile/StudentWithdrawalCancel.vue, src/mixins/Context.vue, src/store/modules/context.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-2564
Late in the Summer term, these UX bugs got a lot more obvious.
=>  BOAC-2564 Fix layout of withdrawn/canceled terms

boac/externals/data_loch.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2574
Master version of #1778.
=> BOAC-2574 Suppress null advising note topics from Redshift

boac/externals/data_loch.py, config/default.py, fixtures/loch.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2393
Follow-up to nessie PR https://github.com/ets-berkeley-edu/nessie/pull/501
I will run the appropriate Nessie jobs in dev as soon as this is merged to avoid breakage.
=> BOAC-2393: Updates to reorganized notes schema

boac/api/course_controller.py, boac/api/search_controller.py, boac/merged/student.py, boac/models/development_db.py, src/components/sidebar/SearchForm.vue, src/components/sidebar/Sidebar.vue, src/components/student/StudentRow.vue, src/components/student/profile/StudentClasses.vue, src/views/Student.vue, tests/test_api/test_cache_utils.py, tests/test_api/test_cohort_controller.py, tests/test_api/test_course_controller.py, tests/test_api/test_curated_group_controller.py, tests/test_api/test_search_controller.py, tests/test_api/test_student_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2513
https://jira.ets.berkeley.edu/jira/browse/BOAC-2514
=> BOAC-2513 BOAC-2514 Suppress Canvas data when user unauthorized

boac/api/cache_utils.py, boac/api/user_controller.py, tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2573
=> BOAC-2573 Separate list for notes-only users; omit obviously fake users

boac/externals/data_loch.py, fixtures/loch.sql
https://jira.ets.berkeley.edu/jira/browse/BOAC-2395
=> BOAC-2395: Makes E&I notes searchable

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2559
=> BOAC-2559 Expand/collapse all notes in one fell swoop

boac/api/auth_controller.py, boac/models/user_login.py, scripts/db/drop_schema.sql, scripts/db/migrate/20190808-BOAC-2356/pre_deploy_01_create_user_logins_table.sql, scripts/db/schema.sql, tests/test_api/test_auth_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2356
=> BOAC-2356: Records user logins

boac/api/alerts_controller.py, boac/models/cohort_filter.py, tests/test_api/test_alerts_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2568
=> BOAC-2568 Update cohort alert counts on alert dismissal

boac/externals/data_loch.py, boac/lib/berkeley.py, boac/merged/cohort_filter_options.py, tests/test_externals/test_data_loch.py, tests/test_lib/test_berkeley.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2421
=> BOAC-2421: Fills gaps in expected grad terms

boac/merged/user_session.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2577
See stacktrace in the Jira.
=> BOAC-2577, GUESTs are welcome in BOA

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2521
=> BOAC-2521 Search for notes from Academic Timeline

boac/api/user_controller.py, boac/lib/berkeley.py, boac/merged/advising_note.py, boac/merged/calnet.py, boac/merged/cohort_filter_options.py, boac/models/development_db.py, fixtures/loch.sql, tests/test_api/test_cohort_controller.py, tests/test_api/test_user_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2582
...with tests.
=> BOAC-2582, GUEST user gets /cohort filter options

boac/api/cache_utils.py, boac/models/db_relationships.py, boac/models/university_dept.py, scripts/db/migrate/20190813-BOAC-2540/pre_deploy_01_alter_university_dept_members_add_automate_membership.sql, scripts/db/schema.sql, tests/test_api/test_cache_utils.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2540
=> BOAC-2540 Disable membership automation per membership

src/mixins/CohortEditSession.vue, src/store/modules/cohort-edit-session.ts, src/views/Cohort.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2537
=> BOAC-2537, do not alter 'isModified' (cohort filters) when paginate

boac/api/note_templates_controller.py, boac/api/notes_controller.py, boac/api/util.py, boac/lib/util.py, boac/models/note.py, boac/models/note_attachment.py, boac/models/note_template.py, boac/models/note_template_attachment.py, boac/models/note_template_topic.py, tests/test_api/test_note_templates_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2542
=> BOAC-2542, note_template API endpoints: my_templates, create

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2521
Follow up to #1790.
=> BOAC-2521 Timeline search spinner: add element id, remove unused CSS

boac/api/cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2581
=> BOAC-2581 Some users in Everyone's Cohorts have no names, sad

boac/api/notes_controller.py, boac/models/development_db.py, fixtures/calnet_search_entries.json, tests/test_api/test_notes_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2586
=> BOAC-2586 Prefer Calnet-provided roles when creating new notes

boac/merged/calnet.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2601
=> BOAC-2601 Handle surprise arrays in LDAP attributes

boac/api/cache_utils.py, tests/test_api/test_cache_utils.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2594
=> BOAC-2594 Include CalNet attributes in daily refresh

boac/externals/data_loch.py
Per https://jira.ets.berkeley.edu/jira/browse/BOAC-2593, we need to consolidate our three-and-counting advising note indexes into a single source, but this ugly-SQL solution gets us around some serious slowdown in the interim.
=> BOAC-2593 Move search filters into subqueries for performance

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2606
There are limits to the power of `comupted` values in Vue. In this case (and IMO), a complex `v-for` is best. (PR includes fix to benign bug in how we remove id from `openMessages` list when note deletion is confirmed.)
QA PR will happen after this is reviewed.
=> BOAC-2606, complex computed value not updating when note deleted

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2606
QA version of PR #1807
=> [QA] BOAC-2606, complex computed value not updating when note deleted

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2612
QA version of PR #1809
=> [QA] BOAC-2612, allNotesExpanded = false when you click to a new tab

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2612
=> BOAC-2612, allNotesExpanded = false when you click to a new tab

boac/merged/advising_note.py, tests/test_merged/test_advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2600
=> BOAC-2600 Exclude students no longer in BOA from local notes search

boac/merged/advising_note.py, tests/test_merged/test_advising_note.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2600
QA version of #1812.
=> [QA] BOAC-2600 Exclude students no longer in BOA from local notes search

src/assets/styles/boac-global.css, src/components/note/AdvisingNoteAttachments.vue, src/components/note/CreateNoteAddStudent.vue, src/components/note/CreateNoteCohortDropdown.vue, src/components/note/CreateTemplateModal.vue, src/components/note/NewNoteModal.vue, src/mixins/StudentEditSession.vue, src/mixins/Util.vue, src/mixins/Validator.vue, src/store/modules/context.ts, src/store/modules/student-edit-session.ts
https://jira.ets.berkeley.edu/jira/browse/BOAC-2545
UX is unpolished and 'edit template' is far from done.  I broke off `AdvisingNoteAttachments` in order to tame the complexity of `NewNoteModal`.
=> BOAC-2545, load/save note template with modal and validation

boac/externals/data_loch.py, boac/merged/cohort_filter_options.py, src/components/cohort/FilterRow.vue, tests/test_api/test_cohort_controller.py, tests/test_externals/test_data_loch.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2608
QA version of #1814.
=> [QA] BOAC-2608 Fixes to expected graduation term filter options

src/components/note/NewNoteModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2548
=> BOAC-2548, delete template modal and API call

src/api/note-templates.ts, src/api/notes.ts, src/assets/styles/boac-global.css, src/components/note/AdvisingNote.vue, src/components/note/AdvisingNoteAttachments.vue, src/components/note/AdvisingNoteTopics.vue, src/components/note/CreateTemplateModal.vue, src/components/note/EditAdvisingNote.vue, src/components/note/NewNoteModal.vue, src/components/sidebar/Sidebar.vue, src/components/student/profile/AcademicTimeline.vue, src/mixins/Attachments.vue, src/mixins/Notes.vue, src/mixins/Validator.vue, src/store/index.ts, src/store/modules/context.ts, src/store/modules/notes.ts, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2575
Refactoring for readability.
=> BOAC-2575, rename api/store components associated with notes/templates

boac/externals/data_loch.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2618
QA version of #1819.
=> [QA] BOAC-2618 Add id ordering to note topic queries

src/components/course/CourseStudents.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2617
=> BOAC-2617 Hide "bCourses Activity" for classes in past terms

src/components/note/NewNoteModal.vue, src/components/sidebar/Sidebar.vue, src/components/student/profile/AcademicTimeline.vue, src/mixins/Notes.vue, src/store/modules/notes.ts, src/views/Student.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2575
Small steps toward template CRUD support. Plus, consistent var naming for modal-related.
=> BOAC-2575, discard template edit; consistent naming for modals

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2632
Bug introduced by PR #1821
=> BOAC-2632, take care when invoking 'transientId' on a transient object

boac/api/cohort_controller.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2633
Master PR. Since this is a QA blocker, I'll prepare a QA version too.
=> BOAC-2633 Fix permission checks on multiple department memberships

boac/api/cohort_controller.py
QA version of https://github.com/ets-berkeley-edu/boac/pull/1824
=> [QA] BOAC-2633 Fix permission checks on multiple department memberships

src/components/student/profile/AcademicTimeline.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2639
QA version of #1826.
=> [QA] BOAC-2639 Loosen match criteria for note ID permalinks

boac/api/status_controller.py, boac/externals/data_loch.py, config/default.py, config/test.py, fixtures/loch.sql, fixtures/loch_sis_enrollments_61889_2162.csv, fixtures/loch_sis_enrollments_61889_2172.csv, fixtures/loch_sis_enrollments_61889_2178.csv, fixtures/loch_sis_enrollments_98765_2172.csv, tests/conftest.py, tests/test_externals/test_data_loch.py
https://jira.ets.berkeley.edu/jira/browse/BOAC-2624
=> BOAC-2624 Switch remaining Redshift queries to RDS

boac/externals/data_loch.py, fixtures/loch.sql
https://jira.ets.berkeley.edu/jira/browse/NS-658
It's still not beautiful SQL, but at least there's less of it.
=> NS-658 Revise advising notes search query against consolidated index

src/components/note/AdvisingNoteTopics.vue, src/components/note/NewNoteModal.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2655
https://jira.ets.berkeley.edu/jira/browse/BOAC-2450
And, `putFocus` appropriately.
=> BOAC-2655, no more click-to-add on topics dropdown; options disable properly when load template

src/components/cohort/FilterRow.vue, src/components/note/NewNoteModal.vue, src/components/note/NewNoteModalButtons.vue, src/components/note/NewNotePageHeader.vue
https://jira.ets.berkeley.edu/jira/browse/BOAC-2649
=> BOAC-2649, 'Save [note]' button is available in narrow viewport

requirements.txt, tsconfig.json
https://jira.ets.berkeley.edu/jira/browse/BOAC-2643
The alert: https://github.com/ets-berkeley-edu/boac/network/alert/requirements.txt/nltk/open
I also removed unnecessary line from tsconfig cuz we have no ts files in `tests/` dir.
=> NOJIRA, one more security fix: upgrade nltk to v3.4.5
